### ISSUE TITLE
vNext: Could not load type RESTCommand on Mac OS X

### ISSUE THREAD

**Issue by hoetz** [Azure/azure-storage-net#100]
I created a new aspnet vNext web app (kvm rc1) and use the latest 4.3.2 preview nuget package to access table storage. On Windows with VS2015 CTP4, everything works fine. On Mac OS X (same kvm version) my integration test fails when creating a table:

 System.TypeLoadException : Could not load type 'Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1[Microsoft.WindowsAzure.Storage.Table.TableResult]' from assembly 'Microsoft.WindowsAzure.Storage, Version=4.3.2.0, Culture=neutral, PublicKeyToken=null'.
      Stack Trace:
           at Microsoft.WindowsAzure.Storage.Table.TableOperation.ExecuteAsync (Microsoft.WindowsAzure.Storage.Table.CloudTableClient client, System.String tableName, Microsoft.WindowsAzure.Storage.Table.TableRequestOptions requestOptions, Microsoft.WindowsAzure.Storage.OperationContext operationContext, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
           at Microsoft.WindowsAzure.Storage.Table.CloudTableClient.ExecuteAsync (System.String tableName, Microsoft.WindowsAzure.Storage.Table.TableOperation operation, Microsoft.WindowsAzure.Storage.Table.TableRequestOptions requestOptions, Microsoft.WindowsAzure.Storage.OperationContext operationContext, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
           at Microsoft.WindowsAzure.Storage.Table.CloudTable+<>c__DisplayClass4+<<ExistsAsync>b__5>d__0.MoveNext () [0x00000] in <filename unknown>:0

**Comment by Andorbal** [comment]
Not sure if you're still having this problem, but I solved it by adding System.Net.Http as a dependency:

`kpm install System.Net.Http`

**Comment by Alkasai** [comment]
I had the same problem. After installing the System.Net.Http I get another error:
NullReferenceException: Object reference not set to an instance of an object
Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpClientFactory.BuildHttpClient[TableResult] (Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1 cmd, System.Net.Http.HttpMessageHandler handler, Boolean useVersionHeader, Microsoft.WindowsAzure.Storage.OperationContext operationContext) [0x00000] in <filename unknown>, line 0

**Comment by Andorbal** [comment]
@Alkasai Unfortunately, I hit that same problem.  I built a custom version of azure-storage-net with null checks in it and had my application use it.  Doing that, instead of getting an error, I got nothing.  The application just exited with no error or error code.

**Comment by Alkasai** [comment]
@Andorbal any idea why this happens? What exactly throws that exception?

**Comment by Andorbal** [comment]
I haven't figured it out yet.  I wanted to try running through all the tests on Linux, but the version of XUnit that's referenced in the project doesn't seem to be available.  I'll keep on it and let you know if I find anything, but I guess this is the price we pay by staying bleeding edge.

**Comment by hoetz** [comment]
I added the System.Net.Http package but nothing changed.

**Comment by Andorbal** [comment]
Which version of System.Net.Http are you referencing?

**Comment by hoetz** [comment]
v1.0.0-beta4-10885 , I'm on the dev feed.

**Comment by Andorbal** [comment]
My project.json is referencing System.Net.Http v4.0.0-beta-22416

**Comment by hoetz** [comment]
Think I'll try this after the next stable CTP is out. Too much in flux at the moment.

**Comment by hoetz** [comment]
This issue still exists with

"dependencies": {
    "WindowsAzure.Storage": "4.3.2-preview",
    "System.Net.Http": "4.0.0-beta-22605"
  },

ASP.NET 5 beta 3 bits

**Comment by pemari-msft** [comment]
Hi, we now support the beta4 bits -- can you try using version 4.4.1-preview of our library and see if it is still reproducible?

**Comment by Andorbal** [comment]
I'll see if I can give that a shot later tonight.

**Comment by hoetz** [comment]
Just tried a simple query against one of my tables, seems to work!
