### ISSUE TITLE
Allow injecting HttpClient/SocketsHttpHandler

### ISSUE THREAD

**Issue by HansOlavS** [Azure/azure-storage-net#1003]
This concerns all services (blob, queue, table) and all versions and all platforms.
The problem I'm getting is SNAT port exhaustion on App Function consumption plan (which has only 600 TCP connections available). This happens even with moderate load. I've only recently started to get this error, but the simplest way to reproduce it would be to create a consumption plan App Function and let it hammer away at a blob, queue or table endpoint.

My workaround solution is to hack the DelegatingHandler and have it use my own SocketsHttpHandler and rolling my own implementation of authentication.

Why not simply allow to inject a HttpClient or a HttpMessageHandler? The problem with DelegatingHandler is that the inner-most handler is selected by the SDK and will always be ClientHttpHandler which is obsolete and lack the crucial properties PooledConnectionLifetime, PooledConnectionIdleTimeout, ConnectTimeout and MaxConnectionsPerServer.

**Comment by HansOlavS** [comment]
Any comment on this from Microsoft? Anyone?

**Comment by aheintz** [comment]
I second this, I'm having problems running on Azure App Services where I'm running out of SNAT ports. I.e. I have to rewrite to use rest  API  directly otherwise my app hangs every now and then and then  the App Service thinks the container is unhealthy  => restart and a lot of errors.

**Comment by ben-graffle** [comment]
+1 any updates on this?

**Comment by HansOlavS** [comment]
> +1 any updates on this?

The update on this is that you have to move on to the newer libraries. the new Azure.Data.Tables nuget package was this capability, for example.
