### ISSUE TITLE
Cannot insert nullable datetime with DynamicTableEntity

### ISSUE THREAD

**Issue by plea134** [Azure/azure-storage-net#101]
using 4.3.0

I want to be able to initialize a property with a new DateTime?() ( specifically with null value - if you define an actual date it's fine).  This also fails with new DateTimeOffset?().  

It won't throw an error, it will create the entity, but these properties will be missing.

entity.Properties.Add("ma_someDateProperty1", new EntityProperty(new DateTime?()));
entity.Properties.Add("ma_someDateProperty2", new EntityProperty(new DateTime?()));

Also, these properties aren't known at runtime (they're prefixed), so their existence is crucial.  I need to project them into a collection when I read them out.

**Comment by vinaysh-msft** [comment]
This is by design as Azure table service does not support storing null properties within entities. A workaround for you is to use a specific value to represent null in your application logic. As an example, this value can be DateTime.MaxValue or DateTime.MinValue

**Comment by plea134** [comment]
Okay thanks, I ended up using DateTime.MaxValue and MinValue where it was appropriate.

I guess when a normal TableEntity is resolved, if the property is not there it is cast to a nullable of the correct type, so this missing property behaviour is hidden.

**Comment by vinaysh-msft** [comment]
@plea134 you are correct. TableEntity properties take up default values when those properties are not defined on the entity in the service.
