### ISSUE TITLE
TimeoutStream doesn't check if a stream is readable/writable before attempting to set timeout values

### ISSUE THREAD

**Issue by stephenjust** [Azure/azure-storage-net#1014]
### Which service(blob, file, queue, table) does this issue concern?
Common

### Which version of the SDK was used?
11.1.5 (and latest as of current git)

### Which platform are you using? (ex: .NET Core 2.1)
.Net Framework 4.7.2

### What problem was encountered?
In the constructor for TimeoutStream, ReadTimeout and WriteTimeout are set on the internal stream.
For some stream implementations, this will throw if the stream is either not readable or not writable.
Example: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/StreamContent.cs#L138

### How can we reproduce the problem in the simplest way?
TimeoutStream created when reading a blob produces this, set a breakpoint in TimeoutStream's UpdateWriteTimeout.

### Have you found a mitigation/solution?
The `UpdateWriteTimeout` and `UpdateReadTimeout` methods in **TimeoutStream** could check that the stream is readable or writable first.

**Comment by kasobol-msft** [comment]
This has been fixed in 11.2.1
