### ISSUE TITLE
aspnet 5, starter or empty project, Connected services fails on MS.JSON.core.parser

### ISSUE THREAD

**Issue by bdelaney** [Azure/azure-storage-net#103]
Using VS 2015 CTP5, and have successfully implemented connected services in an MVC5 project. But when I created an Asp.net 5 project and tried to use connected services to Azure Storage (same exact creds and storage), it halts almost immediately with an error:
`
Adding <storage> to the project failed. Could not load type 'Microsoft.Json.Core.Parser.JsonDocument from assembly 'Microsoft.Json.Core, version=14.0.0.0 ...
`
The process does actually add "WindowsAzure.Storage": "4.3.2-preview" to the project.json though. That is as far as it gets.

**Comment by pemari-msft** [comment]
Thanks for reporting this. Unfortunately, WindowsAzure.Storage 4.3.2-preview does not yet support CTP5 or CTP6 due to a bug in the CoreCLR. We’re working to correct this. Using CTP4 would be a good workaround in the interim. Sorry for any inconvenience.

**Comment by pemari-msft** [comment]
Hi, we now support the beta4 (RC1) bits -- can you try using version 4.4.1-preview of our library and see if it is still reproducible?

**Comment by pemari-msft** [comment]
I can't repro this and we now support Beta5 bits. Please reopen if you are still having trouble. 

Thanks!
