### ISSUE TITLE
Missing blob property RehydrationPriority 

### ISSUE THREAD

**Issue by viskin** [Azure/azure-storage-net#1036]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
11.2.2.0

### Which platform are you using? (ex: .NET Core 2.1)
.Net 4.6.2

### What problem was encountered?
Missing API to check rehydration priority for a blob that started rehydrating.

### How can we reproduce the problem in the simplest way?
Try figuring out rehydration priority

### Have you found a mitigation/solution?
BlobProperties should have a property RehydrationPriority or something like that, and CloudBlob.FetchAttributes() should read it from x-ms-rehydrate-priority header.

**Comment by kasobol-msft** [comment]
V11 is deprecated. Please see [here](https://github.com/Azure/azure-storage-net#support-statement).
Support for this property is present in V12, see [here](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobproperties.rehydratepriority?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobProperties_RehydratePriority)
