### ISSUE TITLE
CloudQueue AddMessage initialVisibilityDelay should not equal timeToLive

### ISSUE THREAD

**Issue by liuhongbo** [Azure/azure-storage-net#104]
If you pass initialVisibilityDelay and timeToLive the same value, the service will return with a 400 bad request response

However, in the AddMessageImpl

           if (initialVisibilityDelay.HasValue)
            {
                CommonUtility.AssertInBounds("initialVisibilityDelay", initialVisibilityDelay.Value, TimeSpan.Zero, timeToLive ?? CloudQueueMessage.MaxTimeToLive);
                initialVisibilityDelayInSeconds = (int)initialVisibilityDelay.Value.TotalSeconds;
            }

the check will pass.  I think it should be like something this:

            if (initialVisibilityDelay.HasValue)
            {
                CommonUtility.AssertInBounds("initialVisibilityDelay", initialVisibilityDelay.Value, TimeSpan.Zero, timeToLive.HasValue ? timeToLive.Value.Subtract(TimeSpan.FromMilliseconds(1)) : CloudQueueMessage.MaxTimeToLive.Subtract(TimeSpan.FromMilliseconds(1)));
                initialVisibilityDelayInSeconds = (int)initialVisibilityDelay.Value.TotalSeconds;
            }

           Or write another utility method to check it without equal the upper bound value.

**Comment by pemari-msft** [comment]
Thanks for reporting this. We'll consider adding this in an upcoming release.

**Comment by ggirard07** [comment]
3 years later, nothing has changed.
What's the point of closing issues if they are not actually fixed?
