### ISSUE TITLE
Add max batch operations constant in TableConstants

### ISSUE THREAD

**Issue by lencharest** [Azure/azure-storage-net#106]
The `TableConstants` class in the `Microsoft.WindowsAzure.Storage.Table.Protocol` namespace should include a constant representing the maximum number of operations allowed in a `TableBatchOperation`.

**Comment by pemari-msft** [comment]
Thanks for the suggestion! We’ll look to add this in an upcoming release.

**Comment by pemari-msft** [comment]
We've included this in our 5.0 release which is now live on nuget. Thanks again for the feedback!
