### ISSUE TITLE
Two missing properties from StorageAccountProperties

### ISSUE THREAD

**Issue by dotnetpro** [Azure/azure-storage-net#108]
According to the MS Wiki for List Storage Accounts - https://msdn.microsoft.com/en-us/library/azure/ee460787.aspx#bk_extendedproperties - there should be two properties, one for Account Type, and one for Custom Domains - these both appear to be missing from the WindowsAzure.Storage 4.3.2-preview package on nuget.

**Comment by veena-udayabhanu** [comment]
This functionality is part of the service management API. We have moved this issue to the correct repo. Please track the resolution here - https://github.com/Azure/azure-sdk-for-net/issues/945.
