### ISSUE TITLE
Request: Expose specific TableOperation properties

### ISSUE THREAD

**Issue by scottkupec** [Azure/azure-storage-net#111]
I'm not sure if this is best requested here or in the forums, but could the following TableOperation properties be exposed (directly or via GetXxx() methods - I vaguely prefer the latter):

https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Table/TableOperation.Common.cs
74         internal string RetrievePartitionKey { get; set; } 
75 
76         internal string RetrieveRowKey { get; set; } 

103         internal ITableEntity ITableEntity { get; private set; } 

108         internal TableOperationType OperationType { get; private set; } 

These are very useful to be able to get back to.  Currently, the only way to do so is to track them separtely or using relfection. (Our current implementation has does the latter, but that doesn't leave us all warm and fuzzy).

Ideally, I had something like this in mind:

public ITableEntity GetEntity()
{
    return ITableEntity; // may be null. Caller must handle
}

public TableOperationType GetTableOperationType()
{
    return OperationType;
}

public String GetPartitionKey()
{
    if ( OperationType==TableOperationType.Retrieve)
   {
        return RetrievePartitionKey;
   } 
  else
  {
     return Entity.PartitionKey;
 }
}

public String GetRowKey()
{
    if ( OperationType==TableOperationType.Retrieve)
   {
        return RetrieveRowKey;
   } 
  else
  {
     return Entity.PartitionKey;
 }
}

I would be happy to submit a pull request, but this likely falls into DCR territory and wanted to start a discussion first.

Thanks!

**Comment by pemari-msft** [comment]
Hi Scott, thanks for suggesting this. We'll take it as a feature request for a future release.

**Comment by ohadschn** [comment]
Seconded!

**Comment by Oleg12** [comment]
Please implement this - the most useful are OperationType and TableEntity

**Comment by erezvani1529** [comment]
Hi @Oleg12, @ohadschn, @scottkupec ,

The requested change has been applied and included in the latest published package on nuget ([v8.0.0](https://www.nuget.org/packages/WindowsAzure.Storage/))

Thanks!

**Comment by ohadschn** [comment]
@erezvani1529 Thanks! However `RetrieveRowKey` and `RetrievePartitionKey` are still internal so as far as I can tell cannot be accessed.
