### ISSUE TITLE
Populate CloudQueueMessage.PopReceipt  property for AddMessage API.

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#113]
The CloudQueueMessage object currently exposes 'PopReceipt' property which is populated by the ReadMessage API, UpdateMessage and DeleteMessage APIs. The ask is to populate this property for AddMessage API as well.

REASONING:
For reliable asynchronous request processing, we use the following pattern (it ensures that we can guarantee processing even if some requests partially fail/timeout):
1.	Create a message in the queue with a 10 minute visibility delay.
2.	Save some state, this could be tables or blobs.
3.	Create a new message without a visibility delay.

If step #1 fails we return error and the caller should retry. 10 minute delay is chosen to be sufficiently larger to cover storage operations with some failures and retries. Step #3 is optional, as it helps with processing latency since we can start processing right away from our backend workers. 

This pattern works well, but it duplicates the number of messages in our queues (and doubles our COGs from backend workers). We would like to change step #3 of this pattern and instead of creation new message just change visibility of message created in step #1. 

Unfortunately, Azure storage library do not expose this API and do not support it via REST.

Azure storage team, I am asking to review this feature requests and strongly consider it for next Azure Storage API update and Azure storage library version.

**Comment by pemari-msft** [comment]
Thanks for raising this. I've communicated your input with the relevant teams, and they will consider this as a future feature request.

**Comment by pemari-msft** [comment]
As this is a request for the service, not the client library, and it is in our service feature backlog, I'm going to close this issue. Thanks again for your feedback!
