### ISSUE TITLE
Issue in Azure Storage emulator related to concurrent merge operations

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#114]
I would like to report an issue related to concurrent merge operations. Bug is only repro in Azure Storage emulator. 

Repro steps:
1.	I have entity with initial state (A0, B0). 
2.	I am sending two concurrent Merge request to storage (A1, null) and (null, B1). 
3.	Expected result is (A1, B1), but Azure storage emulator sometimes return (A1, B0) or (A0, B1), because request are not properly serialized.

Repro program:

    namespace ConsoleApplication
    {
        using System;
        using System.Threading.Tasks;
        using Microsoft.WindowsAzure.Storage;
        using Microsoft.WindowsAzure.Storage.Table;
    
        public static class Program
        {
            internal class Entity : TableEntity
            {
                public string PropertyA { get; set; }
                public string PropertyB { get; set; }
            }
    
            public static async Task Test()
            {
                var table = CloudStorageAccount.DevelopmentStorageAccount.CreateCloudTableClient().GetTableReference("testtable");
                await table.CreateIfNotExistsAsync();
    
                for (int i = 0; i < 100; i++)
                {
                    var key = Guid.NewGuid().ToString();
    
                    var entity = new Entity { PartitionKey = key, RowKey = key, PropertyA = "A0", PropertyB = "B0" };
                    await table.ExecuteAsync(TableOperation.Insert(entity));
    
                    var entityA = new Entity { PartitionKey = key, RowKey = key, PropertyA = "A1", ETag = "*" };
                    var entityB = new Entity { PartitionKey = key, RowKey = key, PropertyB = "B1", ETag = "*" };
    
                    await Task.WhenAll(
                        table.ExecuteAsync(TableOperation.Merge(entityA)),
                        table.ExecuteAsync(TableOperation.Merge(entityB)));
                     
                    entity = (Entity)(await table.ExecuteAsync(TableOperation.Retrieve<Entity>(key, key))).Result;
                    if (entity.PropertyA != "A1" || entity.PropertyB != "B1")
                    {
                        throw new InvalidOperationException("Properties values mismatch!");
                    }
                }
            }
    
            static void Main(string[] args)
            {
                Test().Wait();
            }
        }
    }

**Comment by pemari-msft** [comment]
Thanks for reporting this! We'll look to fix this in an upcoming release.
