### ISSUE TITLE
Include pdb files with "WindowsAzure.Storage" nuget package.

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#115]
Could you please include pdb files with "WindowsAzure.Storage" nuget package or make them available via one of public symbols services:

http://referencesource.microsoft.com/symbols
http://msdl.microsoft.com/download/symbols
http://srv.symbolsource.org/pdb/Public

This will help with performance, concurrency, memory allocation troubleshooting and potentially results in PR requests. 

Azure storage team, I am asking to review this feature requests and strongly consider it for next Azure storage library version.

**Comment by pemari-msft** [comment]
Thanks for the suggestion! We’ll take this request under advisement and try to include these in future releases.

**Comment by ahmetalpbalkan** [comment]
+1 for this request.

**Comment by pemari-msft** [comment]
Hi, as of 6.0.0 we're now including our *.pdb files as part of our nupkg. Thanks again for the suggestion!

**Comment by sergii-sakharov** [comment]
Here's a line from an included pdb file:
c:\Program Files (x86)\Jenkins\workspace\dotnet-nov17\Lib\Common\Shared\Protocol\StorageErrorCodeStrings.cs

Instead is should be pointing to the public server as mentioned in the original post.

As of now those pdb files just obstruct debugging - without them at least it's possible to use Reflector or dotPeek as a pdb generator.
