### ISSUE TITLE
Rename SyncMemoryStream to CloudBlobStream and make it public.

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#117]
Rename SyncMemoryStream to CloudBlobStream, make it public and add constructor with "int capacity". 

Azure storage lib is using SyncMemoryStream to improve performance. System.Net also has similar SyncMemoryStream implementation. Unfortunately, both this classes are internal. So in order to achieve maximum performance we have to decompile/copy/paste or do some other hacks.

I think it would be beneficial that Azure Storage library expose SyncMemoryStream as public, so we could use it as well.

**Comment by pemari-msft** [comment]
Thanks for the suggestion! We'll look to do this in an upcoming release.

**Comment by pemari-msft** [comment]
Hi Ilya, we included this change in our 5.0 release which is available on nuget. Thanks again for the feedback.
