### ISSUE TITLE
TableQuery.SelectColumns always includes PartitionKey, RowKey, Timestamp

### ISSUE THREAD

**Issue by suprak** [Azure/azure-storage-net#120]
I'm trying to reduce the amount of data that my app has to pull down.
In my case I don't care about the PartitionKey, RowKey and Timestamp properties.

However even if I don't specify those columns in the TableQuery.SelectColumns those properties are auto added to the REST query.

Seems like an unnecessary overhead?

https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Table/TableQuery.Common.cs#L336-L352

**Comment by pemari-msft** [comment]
Thanks for the suggestion, @suprak . Originally the thought was that entities would need these properties to make them useful in any scenario, but now we see how that would add overhead that may not always be desired. We'll look to add some sort of opt-out ability in a future release to keep these column values from being selected.

**Comment by djnicholson** [comment]
I also ran into this problem, and worked around it with a horrible hack...

        /// <summary>
        /// This is part of a horrible hack to stop the Azure storage library asking for a lot of columns that
        /// are not needed (partition key, row key, row timestamp).
        /// See: https://github.com/Azure/azure-storage-net/issues/120
        /// </summary>
        private static readonly string DoNotSelectUnnecessaryColumns = "HACK.InterceptedBySendingRequest.HACK";

...

            operationContext.SendingRequest += SendingRequest;

...

        private void SendingRequest(object sender, RequestEventArgs request)
        {
            Uri uriBeingRequested = request.Request.RequestUri;
            string uriBeingRequestedString = uriBeingRequested.ToString();

            if (uriBeingRequestedString.Contains(DoNotSelectUnnecessaryColumns))
            {
                Uri desiredUri = new Uri(
                    uriBeingRequestedString.Replace("%2CPartitionKey%2CRowKey%2CTimestamp", "").Replace(DoNotSelectUnnecessaryColumns, ""));

                uriBeingRequested
                    .GetType()
                    .GetMethod("CreateThisFromUri", BindingFlags.NonPublic | BindingFlags.Instance)
                    .Invoke(uriBeingRequested, new object[] { desiredUri }); // http://referencesource.microsoft.com/#System/net/System/UriExt.cs
            }
        }

Initially I was looking for encoding vulnerabilities in the Azure library, but could not find a usable one (they do forget to encode the parameter names, but I can't get anything other than a fixed string like "$select" or "$filter" passed in).  So I had to resort to reflection.  

It works for me, in this context with the specific CLR and Azure library I am using in this non-critical project.  Use at your own risk :)

@pemari-msft @azureopensource When will the functionality you mentioned way back in April be built?

**Comment by pemari-msft** [comment]
This has been fixed in version 7.0 of our library -- check out `TableRequestOptions.ProjectSystemProperties`. Thanks.
