### ISSUE TITLE
Copy files/directories with Azure Files

### ISSUE THREAD

**Issue by flipchart** [Azure/azure-storage-net#121]
Is it possible (or on the roadmap) to copy (as in something like System.IO.File.Copy) files/directories on Azure Files without mapping the share as a drive? I'm looking for a purely .net solution (and preferably cross platform), so mapping a drive is not really an option. Downloading/uploading appears to be the only way, but this is really wasteful and slow

**Comment by pemari-msft** [comment]
Async server side file copy is indeed on our roadmap for this quarter. We’ll be adding the functionality to our .NET client libraries by the time the service supports this feature.

**Comment by pemari-msft** [comment]
Async server side Azure File copy is indeed on our roadmap. We’ll be adding the functionality to our .NET client library by the time the service supports this feature. Thanks for your feedback!

**Comment by pemari-msft** [comment]
Hi @flipchart, this is now enabled using our 5.0 library which is live on nuget. Please give it a try and let us know if you have any feedback!
