### ISSUE TITLE
Table Queries with floats are not correctly formatted

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-storage-net#122]
The query ```TableQuery.GenerateFilterConditionForDouble("Score", "gt", 5.0)``` generates a query string of ```Score gt 5``` when it should be ```Score gt 5.0```. Without the trailing .0, the query does not correctly execute and you get no results back. This only occurs when the value is .0 rather than e.g. 5.1.

**Comment by pemari-msft** [comment]
Thanks for reporting this! We will try to repro and get back to you.

**Comment by pemari-msft** [comment]
We were able to confirm this bug. We'll fix it in an upcoming release. Thanks again for your feedback.

**Comment by isaacabraham** [comment]
Cheers, look forward to it.

**Comment by pemari-msft** [comment]
Fixed this as of 6.0.0. Thanks again for reporting it!

**Comment by Dorokhov** [comment]
@pemari-msft , Hi Peter.
Please, have a look at changes in TableQuery.Common.cs I sent you above. I'm not sure why my fix was not merged in 6.0.0, but current implementation contains bug.

Please, test following code with Azure SDK 6.0.0:
var query = TableQuery.GenerateFilterConditionForDouble("PartitionKey", QueryComparisons.Equal, double.NaN);
Console.WriteLine("Query={0}", query);
Result: Query=PartitionKey eq NaN.0

So I think bug still exists and would suggest to merge my pull request. Thanks.

**Comment by pemari-msft** [comment]
Thanks for the new bug report. We'll take a look.
