### ISSUE TITLE
NuGet documentation incorrect for v4.3.0

### ISSUE THREAD

**Issue by kwtangerine** [Azure/azure-storage-net#124]
In NuGet, the dependencies are listed below:
.NETFramework 4.0 Client
Microsoft.Data.OData (≥ 5.6.2)
Newtonsoft.Json (≥ 5.0.8)
Microsoft.Data.Services.Client (≥ 5.6.2)
Microsoft.WindowsAzure.ConfigurationManager (≥ 1.8.0.0)

But in reality, we tried to use 
Microsoft.Data.OData and Microsoft.Data.Services.Client v5.6.3 and it was throwing exception unable to find those two DLLs version 5.6.2

Further investigating using ILDASM reveal that it was specifically looking for v5.6.2 and not v5.6.2 or greater.

**Comment by pemari-msft** [comment]
Similar to the stackoverflow post here: http://stackoverflow.com/questions/24553176/could-not-load-assembly-microsoft-data-odata-when-accessing-azure-storage-duri , can you please try adding Binding Redirects to your config file to see if that fixes the issue? Thanks!

**Comment by pemari-msft** [comment]
As we discussed offline, I'm glad to hear binding redirects solved your issue.
