### ISSUE TITLE
Why is StorageException internal for ASPNET_K?

### ISSUE THREAD

**Issue by markrendle** [Azure/azure-storage-net#130]
Porting an application from MVC5/WebAPI2 to MVC6, and I discover that StorageException is marked `internal` for `ASPNET_K`. I'm guessing this is more to do with CoreCLR/CoreFx than ASP.NET 5; I'm currently targeting DNX Beta4 running under Mono 4.0.1, and I can't see any reason to make it `internal` on that setup.

I'll take a proper look tomorrow, grab a fork and see what happens with a Core build vs a DNX build.

**Comment by pemari-msft** [comment]
Actually, I believe this is a side effect of code reuse between DNX/Core and WinRT in our library. I don't think there's a blocker in making StorageException public. We can look to do this in our next release -- We are in the process of upgrading our library to use DNX beta4 as well.

**Comment by markrendle** [comment]
Cool, thanks. Any ETA on the DNX beta4 version?

**Comment by Cheesebaron** [comment]
Also for the Portable version, why is it internal all of the sudden?

**Comment by pemari-msft** [comment]
It's the same answer as above -- it's a side effect of code reuse. We'll change it in an upcoming release. Thanks!

**Comment by pemari-msft** [comment]
1) StorageException is now public in Portable/ASPNET_K libraries in the 4.4.1-preview version which you can find on nuget (https://www.nuget.org/packages/WindowsAzure.Storage/).
2) beta4 is now supported as of 4.4.1-preview version as well. 

Try it out and let us know if you have any further issues. Thanks!
