### ISSUE TITLE
CancellationToken on async methods

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#133]
Every time I want to provide my own `CancellationToken` in any of the async methods I need to provide the `AccessCondition`, `BlobRequestOptions` and `OperationContext` arguments, which really makes the code look messy just providing null values for them.

So instead of having to do something like:

    await block.PutBlockListAsync(blockList, null, null, null, cancellationToken).ConfigureAwait(false);

It would be much nicer to just do:

    await block.PutBlockListAsync(blockList, cancellationToken).ConfigureAwait(false);

So what I ask is to simply add `CancellationToken` overloads or add `CancellationToken cancellationToken = default(CancellationToken)` to all method signatures.

**Comment by pemari-msft** [comment]
Thanks for your suggestion. We usually try to keep one minimal and one maximal overload to keep our code as clean as possible, but we'll consider this as a feature request for an upcoming release.
