### ISSUE TITLE
PCL reference not added automatically via NuGet

### ISSUE THREAD

**Issue by ertay** [Azure/azure-storage-net#136]
Hello,

I just installed Azure Storage 4.4.1 - preview, which was released on NuGet on 13th May 2015. I installed the package to my PCL project (targetting Android/iOS/WP) and I noticed that the reference did not get added. Manually adding the reference via Add Reference -> Browse -> navigating to .../packages/WindowsAzure.Storage.4.4.1-preview/lib/portable-net45+netcore45+wpa81+MonoAndroid1+MonoTouch1/ and then adding Microsoft.WindowsAzure.Storage.dll seems to work fine.

Cheers

**Comment by pemari-msft** [comment]
Thanks for reporting this. We've noticed a similar issue which may have to do with the fact that we don't have full Windows Phone support for our PCL yet. Can you share which targets you've chosen for your PCL?

**Comment by ertay** [comment]
The targets are:
.NET Framework 4.5Windows 8Windows Phone 8.1Windows Phone Silverlight 8Xamarin.AndroidXamarin.iOSXamarin.iOS (Classic)

Date: Mon, 18 May 2015 10:58:24 -0700

**Comment by pemari-msft** [comment]
Thanks! 
Yes, I believe this is because you're using a different PCL target than us. We do not have WP Silverlight 8 support in this PCL yet. Looks like you're using PCL Profile 259 and for now we're supporting Profile 111.

**Comment by ertay** [comment]
Alright, thanks for the quick response :)
