### ISSUE TITLE
No method that downloads a Block Blob with a single HTTP request?

### ISSUE THREAD

**Issue by nathanaeljones** [Azure/azure-storage-net#139]
It appears that one must call `GetBlobReferenceFromServerAsync` before `DownloadToStreamAsync`. 

Surely we don't have to write our own wrapper to the REST API just to access a blob in a single trip? 

We really can't afford the extra latency.

**Comment by pemari-msft** [comment]
Hi Nathanael,

I’m not sure what you mean. You do not need to call GetBlobReferenceFromServerAsync() before you call DownloadToStreamAsync().

If you know the type of blob you’re accessing and you know what the name of the blob is, you can use the CloudBlockBlob() or CloudPageBlob() constructor with a full uri to that resource and then call DownloadToStreamAsync() from that object. Alternatively, you can also use the GetBlockBlobReference() or the GetPageBlobReference() methods located on the CloudBlobContainer object to get the reference locally without any calls to the service, and call DownloadToStreamAsync() on that reference object.

Example:
```
{
    CloudBlobContainer containerReference; // this is a container reference object you have from elsewhere

    CloudBlockBlob blobReference = container.GetBlockBlobReference("blobname"); // No call to service, just local reference
    blobReference.DownloadToStream(stream); // one call to service
}
```
GetBlobReferenceFromServer() is used primarily for when you are not sure what type of blob is being accessed.

We’re also working to make this even simpler – our current preview bits have a CloudBlob() object as well that can be created without knowing the type and DownloadToStreamAsync() can be called from that as well. This will move to our GA bits in the next release.

Does this help your scenario?

**Comment by benfoster** [comment]
@pemari-msft assuming we know that the blob is a `CloudBlockBlob` and therefore can use the constructor, is it possible to get the blob properties and stream in one request?

When requesting the blob contents via the REST API the blob properties are exposed as HTTP Headers. Using the storage client we'd have to make two separate calls (`DownloadToStream` and `FetchAttributes`).

**Comment by pemari-msft** [comment]
Hi Ben,

A ```DownloadToStream()``` will correctly parse Properties and Metadata from the headers without the need to do another ```FetchAttributes()```. ```FetchAttributes()``` is for when you want to get metadata/properties without the overhead of getting the blob’s contents.

**Comment by pemari-msft** [comment]
Hi Ben, seems like this solved your issue. Please feel free to reopen or open another if you have further questions.
