### ISSUE TITLE
TypeLoadException thrown

### ISSUE THREAD

**Issue by DanielChilcott** [Azure/azure-storage-net#14]
Seems that StorageException.GetObjectData needs to be marked [SecurityCritical]. 

Received this error:

A first chance exception of type 'System.TypeLoadException' occurred in Microsoft.WindowsAzure.Storage.dll

Additional information: Inheritance security rules violated while overriding member: 'Microsoft.WindowsAzure.Storage.StorageException.GetObjectData(System.Runtime.Serialization.SerializationInfo, 

   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobRequestOptions requestOptions, OperationContext operationContext)

Received the error on code running in an AppDomain with restricted permissions. .Net doesn't seem to perform this validation by default.

**Comment by DanielChilcott** [comment]
This is still an issue - are there any plans to address it?

**Comment by erezvani1529** [comment]
Hi @DanielChilcott ,

I believe this issue was closed by accident. I am re-opening it to investigate more and get back to you.

Thanks,
Elham

**Comment by DanielChilcott** [comment]
Awesome thank you - this would be super useful for us as we're an integration platform and the Azure Storage SDK forms part of a Connector (Adapter) which runs in a sandbox.

**Comment by DanielChilcott** [comment]
I resolved this issue by conditionally excluding StorageException.GetObjectData (based on a symbol 'SANDBOX').

This is not ideal and so probably not suitable for PR but that method simply cannot be included if the code needs to run under partial trust. This is because Exception.GetObjectData is marked SecurityCritical.

Commit at https://github.com/Flowgear/azure-storage-net/commit/86df0d363f33f9db870fdd637546e3b44259b86b
