### ISSUE TITLE
Bug: Filter condition for double looses precision

### ISSUE THREAD

**Issue by Dorokhov** [Azure/azure-storage-net#149]
Code to reproduce the bug (C#):
 
double d = 4.1000000000000005;
var filter = TableQuery.GenerateFilterConditionForDouble("Field",  QueryComparisons.LessThanOrEqual, d);

Result: filter = "Field le 4.1"
Expected: "Field le 4.1000000000000005"

**Comment by pemari-msft** [comment]
Hi @Dorokhov,

Thanks for reporting this. We will fix this in an upcoming release.

Best,
Peter

**Comment by pemari-msft** [comment]
This has been fixed as of our 6.0.0 release. Thanks again for reporting it.
