### ISSUE TITLE
Support for IQueryable

### ISSUE THREAD

**Issue by korzh** [Azure/azure-storage-net#151]
We are working on ASP.NET 5 app which uses WindowsAzure.Storage package version 4.3.2-preview.

As I can see for now it's not possible to get TableQuery as IQueryable anymore like it was in previous version of Azure Storage for NET library (e.g. var queryable = table.CreateQuery().AsQueryable() ).

Is it a temporal restriction (since this library is still in "preview" mode for DNX Core 5.0) or there is some other way to query CloudTable object via LINQ?

**Comment by pemari-msft** [comment]
Hi @korzh,

Yes, this has not yet been implemented in our preview library for CoreCLR and DNX 4.5.1. It is in our backlog to add support for IQueryable, but we don’t have a timeline yet. Thanks for using our preview library. Please let us know if you have any further questions/feedback on it.

Best,
Peter

**Comment by korzh** [comment]
Thank you for this comment. It's good to know that that was not our fault. :)
I think we can close this issue since you already have an item about IQueryable support in your backlog
