### ISSUE TITLE
ListTablesSegmentedAsync not accessible in PCL

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#152]
Why is `CloudTableClient.ListTablesSegmentedAsync()` not available in PCL? The only available method on `CloudTableClient` is `GetTableReference()` which isn't super useful, if you want to list your tables.

**Comment by pemari-msft** [comment]
Hi @Cheesebaron, 

For now, the PCL only supports access via Shared Access Signatures, and SAS tokens do not yet provide the ability for Table Listing service-side.

However, we are in the process of expanding our SAS support to include Account level SAS tokens, which will allow for table/container/queue listing and a myriad of other new features. We'll support this in the PCL as soon as the service supports it, which is on track for later this year. 

Thanks for trying out our preview PCL!

**Comment by pemari-msft** [comment]
This functionality has been added as of our 6.1.1-preview release. Please do note that Queue/Table Account SAS is not yet live on the Storage Service but will be enabled soon. Blob does work for now. Thanks again!
