### ISSUE TITLE
4.4.1-preview does not have CreateIfNotExistsAsync method for container and table?

### ISSUE THREAD

**Issue by chassq** [Azure/azure-storage-net#153]
I am using VS 2015 RTM and trying out the new ASP.NET vNext web app. Wanted test saving something to azure storage. Set a ref to "WindowsAzure.Storage": "4.4.1-preview" and began writing code. I used some of the demo code from the Azure "how to" web site. When I got to the line to create the container (e.g. "await _container.CreateIfNotExistsAsync();") I got an error:

Error	CS1061	'CloudBlobContainer' does not contain a definition for 'CreateIfNotExistsAsync' and no extension method 'CreateIfNotExistsAsync' accepting a first argument of type 'CloudBlobContainer' could be found (are you missing a using directive or an assembly reference?)

Has something changed or does preview not yet support the latest ASP NET vNext in VS 2015?

Any help is appreciated!

**Comment by pemari-msft** [comment]
Hi @chassq,

There's a few different things to talk about here:
1) I'm not sure exactly what you mean. The ASPNET vNext version of our library (DNX 4.5.1 and CoreCLR) both have support for CreateIfNotExistsAsync. Are you sure you're targeting the right platform? Is it the intellisense telling you it's not there or does it also have build errors if you try to compile anyway?

2) Our preview library currently has support up to CoreCLR beta4 bits. We're working to update the package for support with beta5. 

3) Are you perhaps using our PCL version of the library? The PCL currently only works with SAS tokens, so it can't create containers yet. However, we're currently expanding our SAS offerings and this will also soon be updated.

Hope this helps!

Best,
Peter

**Comment by chassq** [comment]
Hey @pemari-msft,

Thanks for the quick reply! Sorry I was not clear.

1)  We are trying to use the x86 CLR beta 5 (not core). This is what is used "out-of-the-box" in the VS 2015 RTM asp net vnext project templates.
2) We are using a package (dll) to house the code that we are writing to talk to Azure Storage.
3) I do not think we are using the PCL library. We are using the same library we used in the solution we built using VS 2015 RC CLR x86 beta 4, which works fine.
4) We get an intellisense warning and it breaks the compile.

Sounds like this may have to do with not having beta5 support yet?

I am happy to post our sample code someplace that you can see it or if you have time you can most likely see the issue by simply creating a new asp net vnext web app project in VS 2015 RTM. Just use the asp net vnext web app template provided. Create a class library project to be referenced by the web app project. Reference WindowsAzure.Storage": "4.4.1-preview" in the class library and drop in just some code to create the container and use the CreateIfNotExistsAsync method. We get an intellisense warning and it breaks the compile.

**Comment by pemari-msft** [comment]
Hi @chassq,

It's possible that it may be because of beta5 support, but I'm not convinced it would manifest as a compilation break -- my upgrade tests were only really failing on CoreCLR in small cases, and during execution rather than compilation.

I did in fact try to repro before I commented before using a simple console app -- but I redid it as you mentioned hoping to hit your issue. I created an ASP NET vNext Web App using CLR beta5 bits. I created a class library to be referenced by the web app. I referenced our 4.4.1-preview library in the library and created a container:
![dnxcontainerlib](https://cloud.githubusercontent.com/assets/6854498/8912417/a05e6fd4-3447-11e5-927d-33aa47537e92.png)

I also tried doing it from the web app directly, thinking maybe that was the issue:
![dnxcontainerapp](https://cloud.githubusercontent.com/assets/6854498/8912444/b251db0e-3447-11e5-8f26-9c8a2d0fbcb2.png)

But both appear in the intellisense and both compile. Maybe if you could post sample code I could take a look? Sorry I haven't been able to help so far.

**Comment by chassq** [comment]
By chance did you change your project.json frameworks section. When I use the template the frameworks section in project.json uses a moniker of "dotnet" and not "dnx451" for example. Maybe that is my problem as I need to use "dnx451"?

**Comment by pemari-msft** [comment]
I didn't make any edits. The default template has dnx451 for the project.json for me:
![projectjson](https://cloud.githubusercontent.com/assets/6854498/8939213/ee0edf54-3517-11e5-93b8-04d3bcc37298.png)

That seems to be the issue. Looks as if you're pulling in the PCL dll. Your monikers are "dotnet" by default?

**Comment by chassq** [comment]
I am using the default template provided in VS 2015 I think. See images. It is defaulting to "dotnet" in my class library. Maybe I have some not configured properly?

![capture1](https://cloud.githubusercontent.com/assets/4785384/8955785/d7ef041e-35bd-11e5-8812-1dc038cef0dc.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4785384/8955786/d7f412ba-35bd-11e5-827f-5d7b9e59e7ee.PNG)

**Comment by pemari-msft** [comment]
So it seems somehow the Library targeting 4.6 project.json is pulling in our PCL instead of our DNX dll. 

Not sure why the VS team made this the default. I'll do some more research and try to see if we can make any adjustments to make this a better story. 

Thanks for your help investigating!

**Comment by chassq** [comment]
Ok, sounds good. Your help is most appreciated! I have it working using DNX451.

Thanks Again!
