### ISSUE TITLE
Document that ITableEntity.{ReadEntity,WriteEntity} may alias the dictionary

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [Azure/azure-storage-net#154]
I was surprised to learn that DynamicTableEntity.ReadEntity returns the entity's own dictionary by reference and DynamicTableEntity.WriteEntity adopts the passed dictionary as the entity's own.  The description of the methods on ITableEntity as "serializing" and "deserializing" data strongly suggests that implementations of those methods copy all mutable data.

I'm writing an in-memory implementation of the table API for testing purposes that stores the entities internally as DynamicTableEntity.  It uses ReadEntity and WriteEntity to transfer data between the stored entities and the entities passed by the caller (for writes) and returned to the caller (for reads), which are of a caller-specified subclass of ITableEntity.  I need to copy the dictionary and the EntityProperty objects to prevent aliasing between the stored entities and the caller's entities in case the caller-specified class is also DynamicTableEntity.

I'm not sure I can expect you to change DynamicTableEntity.ReadEntity and DynamicTableEntity.WriteEntity to do a deep copy, since there would be some performance cost and it isn't needed for ordinary usage of the table client library, but only for fake implementations, and I've heard that the Azure storage team discourages the use of fake implementations.  I'd still ask for a clarification to the ITableEntity documentation.

**Comment by jehine-MSFT** [comment]
Hello @mattmccutchen-microsoft,

Thanks for the feedback! We think your request is reasonable and will include an update to the DynamicTableEntity documentation in our next bug release.
