### ISSUE TITLE
Bug with Queue Approximate Message Count Property in WindowsRT

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-net#155]
Ref: http://stackoverflow.com/questions/31788798/approximatemessagecount-always-null-after-calling-fetchattributesasync-in-a-univ

There's a bug in `GetApproximateMessageCount` method here: https://github.com/Azure/azure-storage-net/blob/master/Lib/WindowsRuntime/Queue/Protocol/QueueHttpResponseParsers.cs.

The correct code should be:

        public static string GetApproximateMessageCount(HttpResponseMessage response)
        {
            return response.Headers.GetHeaderSingleValueOrDefault(Constants.HeaderConstants.ApproximateMessagesCount);
        }

**Comment by pemari-msft** [comment]
Thanks Gaurav. We'll make this fix in an upcoming release.

Best,
Peter

**Comment by pemari-msft** [comment]
This is included in our 5.0.0 release. Thanks again Gaurav.

**Comment by mpiecyk** [comment]
Has this bug resurfaced? I get null again for the 9.1.0 release.

**Comment by mpiecyk** [comment]
Sorry, I see that the FetchAttributes() method must be called to populate the 
ApproximateMessageCount property. Now it works for me.

There is no mention in the current documentation that ApproximateMessageCount is only populated when FetchAttributes() is called or what FetchAttributes() actually populates on either page, so I recommend you update them.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.queue.cloudqueue.approximatemessagecount?view=azure-dotnet

https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.queue.cloudqueue.fetchattributes?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Queue_CloudQueue_FetchAttributes_Microsoft_WindowsAzure_Storage_Queue_QueueRequestOptions_Microsoft_WindowsAzure_Storage_OperationContext_
