### ISSUE TITLE
5.0.0 and 5.0.1-preview packages are missing portable files

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#162]
Both 5.0.0 and 5.0.1 packages are missing files for the portable version of this library.

Opening up the NuGet package shows only these folders available: net4.0, win8, wp8 and wpa. No portable folder.

Would be really nice if you fixed this.

![Imgur](http://i.imgur.com/s8UIu25.png)

**Comment by pemari-msft** [comment]
Yes, the PCL is still in preview so it does not exist in our GA 5.0.0 package. However, it does exist in the 5.0.1-preview package. I was able to install it from Nuget and found it at this location: 
![capture](https://cloud.githubusercontent.com/assets/6854498/9089189/bc88321e-3b48-11e5-8463-ee6d2762c13f.PNG)

Can you please try to confirm this on your end?

**Comment by Cheesebaron** [comment]
OK it installs fine, I think NuGet was confused about the WindowsAzure.Storage and WindowsAzure.Storage-Preview packages and I might have attempted to install the latter.
