### ISSUE TITLE
Request: Have an option to use the $select query option in TableOperation.Retrieve

### ISSUE THREAD

**Issue by hpityu** [Azure/azure-storage-net#163]
We are trying to reduce the amount of data that our application has to GET from the Table service. For most of the use cases it would be useful to be able to control the properties that are added to the REST query (just as we have this option for TableQuery.SelectColumns) by using the $select query option of:

https://myaccount.table.core.windows.net/mytable(PartitionKey='<partition-key>',RowKey='<row-key>')?$select=<comma-separated-property-names>

I know that there is a workaround of creating a TableQuery with the exact PartitionKey and RowKey filter, but I am not sure of the performance difference that that may cause on the table service side.

**Comment by mirobers** [comment]
Thank you for this feedback. We will look at providing this functionality in a future release. Meanwhile, the workaround you mention (using TableQuery) is a good way to do this currently. It incurs no performance cost on the service, as long as you filter to an exact PartitionKey and RowKey.

**Comment by jehine-MSFT** [comment]
As of the 6.1 release, we now support this feature request for column projection functionality on the Table.Retrieve operation in all platforms.
Thank you so much for the great feature request!
