### ISSUE TITLE
5.0.1-preview missing many methods

### ISSUE THREAD

**Issue by yellowsix** [Azure/azure-storage-net#170]
When trying to use the 5.0.1-preview package in a new asp.net 5 class library, many methods are missing, such as:

CloudTable.CreateIfNotExists
CloudBlobContainer.CreateIfNotExists
CloudBlobContainer.SetPermissions
CloudBlobClient.GetServiceProperties
CloudBlobClient.SetServiceProperties

To reproduce, using vs2015 and asp.net 5 beta6:

1. Create a new Class Library (Package)
2. Add WindowsAzure.Storage 5.0.1-preview via nuget
3. Try to use any of the above methods... not there!

**Comment by pemari-msft** [comment]
Hi @yellowsix,

Can you please take a look at issue 153: https://github.com/Azure/azure-storage-net/issues/153 ?

It looks like you're creating a portable class library and not an ASP.NET class library. Can you check your targets and let us know?

Thanks!

**Comment by yellowsix** [comment]
Ah -- reading through the post, the issue is that the Class Library (Package) template in vs2015 defaults the framework to "dotnet" in the project.json file.  If I edit that to be the same as the web application template:

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }

... then the Async versions of the above methods become available.

Seems that framework value was causing a lot of other problems for me as well... anyway, that fixed it, thanks for pointing me to that.
