### ISSUE TITLE
Consider setting up two Announcements repos for Azure Storage annoucements

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#173]
It would be very helpful if the Azure Storage Team had an "Announcements" repo just like the .NET 5 dev teams are using, where we can subscribe and be kept up-to-date with the latest issues in package releases.

If you're up for that though, I'd like to recommend a change from the way that the .NET 5 folks setup Announcements. Don't close discussions in Announcements and open them elsewhere for discussion to prevent spam for those that want announcements and no discussion. It's a pain in the keester to search Github for issues when the announcements are discussed outside of the Announcements issues.

Just setup one Announcements (Closed) that is locked for discussions, which would be for those who don't want to be spammed with announcement discussions, and setup an Announcements (Open) repo, which is open for discussions. Devs who subscribe to that one want to see all of the chatter. All you have to do at that point is post the announcement to each repo.

**Comment by pemari-msft** [comment]
Thanks for this feedback! This is a very interesting idea -- I know I also find the .NET 5 dev team's Announcements repo to be helpful.

**Comment by pemari-msft** [comment]
I'm actually going to leave this open for now while we discuss it internally, if you don't mind :)

**Comment by pemari-msft** [comment]
Unfortunately, we share this with the entirety of the Azure SDK. Therefore, an announcements repo would be rather confusing unless we had an announcements repo for each of the corresponding libraries here. Thanks for the suggestion though. We'll continue to try to make the information found in our changelog, readme, and breakingchanges more accessible.

**Comment by DovydasNavickas** [comment]
The solution here would be kind'a simple, you know...
The whole Azure SDK team (or all teams) could acquire a habit of announcing all of the changes in a common announcements repo.
