### ISSUE TITLE
The argument 'ParallelOperationThreadCount' is larger than maximum of '64'

### ISSUE THREAD

**Issue by vladkasianenko** [Azure/azure-storage-net#174]
When deploying to ARM device (Windows Phone 8.1 Store app), I'm unable to create CloudBlobClient ->
Exception thrown: 'System.ArgumentOutOfRangeException' in Microsoft.WindowsAzure.Storage.ni.DLL
System.ArgumentOutOfRangeException: The argument 'ParallelOperationThreadCount' is larger than maximum of '64'
Parameter name: ParallelOperationThreadCount
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertInBounds[T](String paramName, T val, T min, T max)
   at Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions.set_ParallelOperationThreadCount(Nullable`1 value)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient..ctor(StorageUri storageUri, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.CreateCloudBlobClient()
   at App7.MainPage.<>c.<<Button_Click>b__3_0>d.MoveNext()

CloudTableClient is OK.
x86 configuration is OK.
Only ARM.

**Comment by pemari-msft** [comment]
Hi @vladkasianenko ,

What value are you passing in for your paralleloperationthreadcount? Is it larger than 64?

**Comment by vladkasianenko** [comment]
I pass nothing. 

--
Sent from Windows 10 for Mobile

-----Original Message-----

**Comment by pemari-msft** [comment]
When creating a CloudBlobClient from a StorageAccount the default value that gets passed in is 1. 

I'll try to repro this myself but I'm not sure this is a storage issue. Can you try creating a CloudBlobClient directly as below?:

``CloudBlobClient client = new CloudBlobClient(account.BlobStorageUri, account.Credentials)``

Thanks!

**Comment by vladkasianenko** [comment]
I'm using this code, but I get Exception. In x86 Cobfiguration everything
is OK, but not in ARM.

**Comment by vladkasianenko** [comment]
CloudBlobClient blobClient = new CloudBlobClient(new
Uri(string.Format("https://{0}.blob.core.windows.net",
"storagename")), new StorageCredentials("storagename",
"DHpNuYG5MXhamfbKmFPClUlNi38QiM2uqIqz07pgvpv2gmXJRwxaMlcV05pFCYsrelGYKPed9QphyJ/YnUrh5w=="));

**Comment by pemari-msft** [comment]
Please don't post your public key in GitHub. We'll investigate this. Thanks!

**Comment by vladkasianenko** [comment]
I know about keys, but they don't matter, because I provide wrong storage
name, Don't worry. =)

**Comment by vladkasianenko** [comment]
Finally, I get solution.
I install VS2013 Community (I was using VS2015 Community). In VS13 I just
installed WindowsAzure.Storage without any problems with OData.
CloudBlobClient is now working!

**Comment by pemari-msft** [comment]
Great. Glad to hear it.
