### ISSUE TITLE
azure-storage-net not compatible with asp.net beta-7

### ISSUE THREAD

**Issue by sandorfr** [Azure/azure-storage-net#175]
When using beta7 and azure storage, we might face some compiling errors if we you use cryptographic methods because WindowsAzure.Storage still references old assemblies. https://github.com/dotnet/corefx/issues/2882 

The workaround is just to remove the old references and replace them by the new ones : https://github.com/Azure/azure-storage-net/compare/master...sandorfr:beta7-fix

**Comment by pemari-msft** [comment]
Hi @sandorfr. We don't yet support beta7 bits. We only support up through beta5 at this time. We're looking to update our code soon to support up through beta7 and will be sure to make this fix.
Thanks for the feedback!

**Comment by pemari-msft** [comment]
Hi, this should be fixed as of 6.0.1-preview. Thanks for the heads up!
