### ISSUE TITLE
Not working in Visual Studio 2015

### ISSUE THREAD

**Issue by ravimandal47** [Azure/azure-storage-net#179]
Azure Storage SDK is not capable of CRUD Blobs in Windows Store apps using C#. I tried it with VS 2013 everything is working but doesn't work in VS 2015.

**Comment by pemari-msft** [comment]
Hi, can you please clarify? Are you using UWP? Please see #171.

**Comment by ravimandal47** [comment]
No its Windows 8.1 Universal App.

**Comment by pemari-msft** [comment]
Can you clarify what isn't working? Perhaps provide repro code? I was able to upload and download blobs with no issue. Thanks in advance!

**Comment by WDMichael** [comment]
Not sure if my issue is new or the same ... when I try to use the REST for a getting a Blob, I receive an error:
 "The MAC signature found in the HTTP request 'xxxxxyyyyzzz' is not the same as any computed signature" .. 

The error also contains a "Server used following string to sign: "'GET






Mon, 21 Sep 2015 12:45:14 GMT

"0x8D2C2827F310779"


x-ms-date:Mon, 21 Sep 2015 21:16:26 GMT
x-ms-version:2015-02-21... etc ... 

and here is my observation. The server uses a "string to sign" which contains the file "last modified date" and the "ETag" ... 2 strings I dont have in my request-"string to sign" and which is not suppose to be there according to the REST API documentation... 

Is this the same issue?

**Comment by pemari-msft** [comment]
@WDMichael This is the same issue as #171 yes. This has to do with the target and not storage code. We're working on a fix for that.

**Comment by WDMichael** [comment]
Thank you for your response ... I call REST directly ... https://[blobname].blob.core.windows.net/[account]/container/blob ... 

my code was working fin last week, but not since sunday .... (I think) ...

**Comment by WDMichael** [comment]
Hi Peter,

Thank you for your response ... I call REST directly ... https://[blobname].blob.core.windows.net/[account]/container/blob ...

my code was working fin last week, but not since sunday .... (I think) ...

I am not using the Storage Client Library, since I am iOS developer and the Storage Library is not made for objective-C .. Yet – right?

I am trying to use the Blob for storage for an app for mine of my  customers

Med venlig hilsen / Best regards

WeDoMobility

Michael Gylling Hviid
Mobility Specialist
Ellekær 9,1 – 2730 Herlev.
Telefon: +45 20 94 35 54
Email: michael@wedomobility.com
Web: http://www.wedomobility.com

[cid:96BA0549-6229-4903-B4F2-0312BB4876CC]

From: Peter Marino
Reply-To: Azure/azure-storage-net
Date: Monday 21 September 2015 22:13
To: Azure/azure-storage-net
Cc: Michael Gylling Hviid
Subject: Re: [azure-storage-net] Not working in Visual Studio 2015 (#179)


@WDMichael<https://github.com/WDMichael> This is the same issue as #171<https://github.com/Azure/azure-storage-net/issues/171> yes. This has to do with the target and not storage code. We're working on a fix for that.

**Comment by pemari-msft** [comment]
Ah. We usually see this happen in the case of a proxy in between you and the service. If you're using HTTPS, can you share how you're building the REST requests? Are you building them on a UWP app or something similar in c#?

**Comment by WDMichael** [comment]
I am developing in Objective-C .... and the strange thing is ... if I delete all files (test count i 8 files) and upload again, my App is working fine on the first download ... on the second run, only two of my files are downloading  ... the other are failing with this error ... 

I do not have any proxy between me and my storage ... and the app is failing on both my ethernet in the emulator and on my phone on 4G ...???

**Comment by WDMichael** [comment]
This is my Code:

 msDate = [self msNow];
            
            NSString *urlString = [NSString stringWithFormat:@"%@/%@",currentContainer, [thisBlob stringByAddingPercentEscapesUsingEncoding:NSASCIIStringEncoding]];
            url = [NSURL URLWithString: [NSString stringWithFormat:@"https://%@.blob.core.windows.net/%@", blobUrl,urlString]];
            request = [NSMutableURLRequest requestWithURL:url];
            NSString *string2Sign = [NSString stringWithFormat:@"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:%@\nx-ms-version:%@\n/%@/%@",msDate, msversion, blobUrl, urlString];
            NSString *blobSignature = [blobSigner sign:string2Sign];
            NSLog(@"String2Sign:%@", string2Sign);
            NSLog(@"blobSignature:%@", blobSignature);
            
            [request setURL:url];
            [request setHTTPMethod:@"GET"];
            [request setValue:[NSString stringWithFormat:@"%@ %@:%@",msauth, blobUrl, blobSignature] forHTTPHeaderField:@"authorization"];
            [request setValue:msDate forHTTPHeaderField:@"x-ms-date"];
            [request setValue:msversion forHTTPHeaderField:@"x-ms-version"];
            [request setValue:blobSignature forHTTPHeaderField:blobUrl];
            
            NSData *blobDataStream = [NSURLConnection sendSynchronousRequest:request returningResponse:&response error:&error];

**Comment by pemari-msft** [comment]
Hi -- this is unrelated to the current issue. Objective C does have URL caching on by default. I know I've used the following before:

```     NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
        sessionConfiguration.URLCache = nil;
        sessionConfiguration.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData; ```

But either way if you're using REST it's an issue on your end and not to do with the service :) 

These issues are separate. Thanks!

**Comment by WDMichael** [comment]
Sorry - I was not aware of this ... I changed my request to: 

request = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:60.0];

And it helped ... Thank you so much for your help. Much appreciated.

**Comment by pemari-msft** [comment]
No problem, glad to help. @ravimandal47, sorry for the divergence. Bringing my questions back to the top: Can you clarify what isn't working? Perhaps provide repro code? I was able to upload and download blobs with no issue. Thanks in advance!

**Comment by jehine-MSFT** [comment]
Hi @ravimandal47,

Can you give us more specifics on what is not working for you? A repro would be helpful!

Thanks!

**Comment by pemari-msft** [comment]
Closing this for nonresponse. Please let us know if you have other information -- we are unable to repro.
