### ISSUE TITLE
Moving files

### ISSUE THREAD

**Issue by flipchart** [Azure/azure-storage-net#180]
Not sure if this is the correct place for this as there doesn't appear to be a REST operation to move files to a different directory, or change the file's name for that matter. I'd like to be able to change a file's path akin to what the `mv` command does in bash, etc.

**Comment by Cheesebaron** [comment]
Copy it and remove the old file?

**Comment by flipchart** [comment]
@Cheesebaron That was my first thought, but you have to suffer the time to copy (for larger files) and you lose the atomicity that a move operation gives you.

**Comment by pemari-msft** [comment]
Yes, as you mentioned, unfortunately this is not yet supported by the service. I will forward your request to the relevant team and add it to our feature request list. Thanks!

**Comment by pemari-msft** [comment]
For now, the copy and remove method is the best bet. I'm going to close this issue for now as it's been added to the relevant backlog. Thanks!
