### ISSUE TITLE
(400) Bad Request with Storage Emulator and v. 6.0.0

### ISSUE THREAD

**Issue by ChristianRygg** [Azure/azure-storage-net#183]
Is the newest release (6.0.0) compatible with the current Azure Storage Emulator (4.1)? 

After upgrading the NuGet package all requests result in "(400) Bad Request" in our project.

**Comment by mod6890325** [comment]
+1 for the error :( The only difference between working and broken project is upgrading WindowsAzure.Storage from 5.0.2 to 6.0.0 (with nuget).

**Comment by andrewcfrancis** [comment]
Here's sample code that breaks with version 6.0.0:

`var account = CloudStorageAccount.Parse("UseDevelopmentStorage=true");`
`var client = account.CreateCloudBlobClient();`
`var container = client.GetContainerReference("logos/");`
`container.Exists();`

The last line throws an exception.

**Comment by pemari-msft** [comment]
Hi all -- if you check the inner exception info of the bad request you're receiving, you should see a VersionNotSupportedByEmulator error. This indicates that the version of the storage services you're using is for features that aren't implemented in that version of the Emulator. 

Please download the newest version of the storage emulator found here: https://azure.microsoft.com/en-us/downloads/ in order to work with the new features. Thanks!

**Comment by mod6890325** [comment]
Tried the "VS 2015" link (on https://azure.microsoft.com/en-us/downloads/), which installed Azure SDK 2.7.1, and Storage Emulator 4.2 => Now everything works again!

However, the release notes for WindowsAzure.Storage 6.0.0 don't even mention dependency on Storage Emulator 4.2 -- could you add this please?

**Comment by pemari-msft** [comment]
Hi -- The storage client library does not depend on the Emulator, so we won't be able to add that verbiage. 
 
Azure Storage has a set of service versions that it allows. 
When it adds new features, you need to use the newest (x-ms-version) service version to use those features. 
If you want to use those features in the client library, you upgrade the client library to the newest version (in this case, 6.0.0).
If you want to test those features emulator, you need to upgrade your emulator to support those features, irrespective to how you make those requests. 

They are certainly related to each other, but they are independent. You could make requests on the older emulator with an older library, or make older requests with the newer emulator, or use the client library without the emulator at all. This is why we added the VersionNotSupportedByEmulator error code that you've received that instructs you to upgrade your emulator version when using an unsupported client library. 

Thanks!

**Comment by mod6890325** [comment]
Peter, there are a couple things to consider:
- in my case, VersionNotSupportedByEmulator was buried deep inside AggregateException, and I simply didn't see it when debugging. The exceptions that I saw were "(400) Bad Request" that could be anything.
- if my project breaks in local development environment - that's a show stopper. It doesn't matter if it works in cloud. I simply will roll back until it's sorted out.
- adding a sentence in release notes isn't all that hard you make it to be. It's not a compile-time dependency, but it is a run-time dependency at development time -- in all meanings of the word "depencency".

I appreciate the work you do, but you don't have to take a hard line on this. It doesn't help developers, who you serve, right?

**Comment by ChristianRygg** [comment]
I second the suggestions to more clearly communicate compatability changes with Storage Emulator. Even if the library doens't rely directly on the emulator, they are in reallity very tightly connected in daily use.

**Comment by mirobers** [comment]
@ashrafxcoder Please use this direct download link for [Storage Emulator 4.6](https://go.microsoft.com/fwlink/?LinkId=717179&clcid=0x409). We are actively working on adding it to latest SDK installation as well. Sorry for the inconvenience.

**Comment by mod6890325** [comment]
After installing 4.6 from above link, I get an error running my project in
VS2015:

Could not load file or assembly
'Microsoft.Azure.Storage.Emulator.Controller, Version=4.0.0.0..' or one of
its dependencies.

Tried reinstalling/repairing 4.6. This sucks.

**Comment by mirobers** [comment]
@mod6890325 Thank you for reporting this. I've investigated and it appears that some of the assemblies in Storage Emulator 4.6 are x64, but Visual Studio Cloud Tools requires AnyCpu.

I apologize for this. We are working on releasing a fix. In the meantime, you will need to use version 4.5 (and therefore Storage Client version 7.2.1).

If you are interested in trying a potential workaround, theses steps worked in my tests:

1) Copy Microsoft.Azure.Storage.Emulator.Controller.dll from emulator 4.5 and replace the same DLL in the install directory of emulator 4.6 (Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator).
2) Add the following binding redirects to AzureStorageEmulator.exe.config:

```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Storage.Emulator.Controller"
                          publicKeyToken="31bf3856ad364e35"
                          culture="neutral"/>
        <bindingRedirect oldVersion="4.6.16349.1343" newVersion="4.5.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.DevelopmentStorage.Services"
                          publicKeyToken="31bf3856ad364e35"
                          culture="neutral"/>
        <bindingRedirect oldVersion="4.5.0.0" newVersion="4.6.16349.1343"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.DevelopmentStorage.Storev4.0.2"
                          publicKeyToken="31bf3856ad364e35"
                          culture="neutral"/>
        <bindingRedirect oldVersion="4.5.0.0" newVersion="4.6.16349.1343"/>
      </dependentAssembly>
```
Then VS was able to start emulator 4.6 successfully.

**Comment by mirobers** [comment]
The fix has been released. Please uninstall and reinstall the storage emulator to get it.

**Comment by mod6890325** [comment]
Ok, downloaded from link above and reinstalled Azure Storage Emulator 4.6.16349.1347 - seems to work. Thanks!
