### ISSUE TITLE
IPAddressOrRange why string?

### ISSUE THREAD

**Issue by Peter-Juhasz** [Azure/azure-storage-net#186]
Why string if we have IPAddress for ages for representing an 'IP address'?

**Comment by pemari-msft** [comment]
While we do like the IPAddress class, unfortunately, it does not exist in the DNX, WinRT, or PCL target frameworks. We do some validation under the hood with the IPAddress class. But, we decided for clarity, maintenance, and uniformity over our API surface area, it was best to keep them represented as strings throughout the target frameworks.

**Comment by Peter-Juhasz** [comment]
Oh I see, thanks for the explanation.
