### ISSUE TITLE
Curious why CloudQueue CreateIfNotExists()/DeleteIfExists() methods do not exist in Portable library

### ISSUE THREAD

**Issue by samconn** [Azure/azure-storage-net#187]
Hello,

Currently, these two methods are only included when the compiler directive SYNC is defined and therefore are not available in the PCL version. 

Is there a workaround? If not, will these be included at some point?

Thanks.

Sam.

**Comment by pemari-msft** [comment]
Hi @samconn,

Yes, PCL only supports SAS token access. We'll be adding Account SAS support very soon to the PCL which will enable these scenarios. Thanks for trying out the preview PCL!

**Comment by SamBonavika** [comment]
Perfect! Thank you for the speedy response.

**Comment by pemari-msft** [comment]
This functionality has been added as of our 6.1.1-preview release. Please do note that Queue/Table Account SAS is not yet live on the Storage Service but will be enabled soon. Blob does work for now. Thanks again!

**Comment by billwert** [comment]
Looking at 6.2.2-preview, it looks like the method isn’t there on CloudBlobContainer. Any idea why @pemari-msft ?

**Comment by jehine-MSFT** [comment]
Hello @billwert ,

Are you talking about [this](https://github.com/Azure/azure-storage-net/blob/master/Lib/WindowsRuntime/Blob/CloudBlobContainer.cs#L135) API?

**Comment by billwert** [comment]
@jehine-MSFT nope, [this one](https://github.com/Azure/azure-storage-net/blob/40c04ce1dbbc0c569316da0e3fe47b9bff5d3042/Lib/ClassLibraryCommon/Blob/CloudBlobContainer.cs#L181).This is the pattern that [all](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-blobs/) [the](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-tables/) [walkthroughs](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-queues/) [use](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-files/), so it was surprising to not see it in the latest version of the library for .NET Core.

**Comment by pemari-msft** [comment]
Portable needs to be a subset of APIs that can work across the platforms in the Portable profile (which this issue is referring to). 
This is completely orthogonal to .NET Core. Please use the async paradigm for .NET Core as .NET Core is async only at this time.

**Comment by jehine-MSFT** [comment]
@billwert ,

This is the same API but for our CoreCLR library. We don't have a synchronous version of it for CoreCLR yet, but it provides the same functionality. All our walkthroughs are written with for the Desktop codebase, so that's why the examples will be slightly different than you'd use in the CoreCLR SDK.

Thanks!

**Comment by billwert** [comment]
Okay, thanks! Is there a doc issue somewhere to update the walkthroughs so they will work for ASP.NET Core/.NET Core?
