### ISSUE TITLE
Table properties of nullable enum type are not stored

### ISSUE THREAD

**Issue by pvones** [Azure/azure-storage-net#188]
Table properties of nullable enum type are not stored to table, using Storage Emulator 4.2 and library version 6.0.0. No error is returned. Releated issue in the past https://github.com/Azure/azure-sdk-for-net/issues/137

**Comment by pemari-msft** [comment]
Hi @pvones -- in order to help me try to repro this, can you confirm that this is an issue only in the emulator? Or does it happen when targeting the actual Storage Service as well?

**Comment by jehine-MSFT** [comment]
Hello @pvones,

The Azure Storage Table Service does not store properties with null values. It does not throw but silently ignores the values. Are you experiencing this problem with nullables that have **non-null** values or just **null** values?

Thanks!

**Comment by pemari-msft** [comment]
Closing this one for now as we are unable to get a repro. @pvones , please feel free to reopen if you can provide some more information!
