### ISSUE TITLE
Append to Azure Append Blob Using AppendTextAsync Results in Missing Data

### ISSUE THREAD

**Issue by matthewrenze** [Azure/azure-storage-net#190]
I'm attempting to create a logger for an application in Azure using the new Azure append blobs and the Azure Storage SDK 6.0.0. So I created a quick test application to get a better understanding of append blobs and their performance characteristics.

My test program simply loops 100 times and appends a line of text to the append blob. If I use the synchronous AppendText() method everything works fine, however, it appears to be limited to writing about 5-6 appends per second. So I attempted to use the asynchronous AppendTextAsync() method; however, when I use this method, the loop runs much faster (as expected) but the append blob is missing about 98% of the appended text without any exception being thrown.

If I add a Thread.Sleep and sleep for 100 milliseconds between each append operation, I end up with about 50% of the data. Sleep for 1 second and I get all of the data.

This seems similar to an issue that was discovered in v5.0.0 but was fixed in v5.0.2: https://github.com/Azure/azure-storage-net/releases/tag/v5.0.2

Here is my test code if you'd like to try to reproduce this issue:

	static void Main(string[] args)
	{
		var accountName = "<account-name>";

		var accountKey = "<account-key>;

		var credentials = new StorageCredentials(accountName, accountKey);

		var account = new CloudStorageAccount(credentials, true);

		var client = account.CreateCloudBlobClient();

		var container = client.GetContainerReference("<container-name>");

		container.CreateIfNotExists();

		var blob = container.GetAppendBlobReference("append-blob.txt");

		blob.CreateOrReplace();

		for (int i = 0; i < 100; i++)
			blob.AppendTextAsync(string.Format("Appending log number {0} to an append blob.\r\n", i));

		Console.WriteLine("Press any key to exit.");

		Console.ReadKey();
	}

In addition, I tried using `Task.WaitAll()` on the tasks to see if the tasks simply weren't completing.  However, when I do that, I receive an AggregateException with the following inner exception message:  "The remote server returned an error: (412) The append position condition specified was not met." 

Here's an example of the changed code: 

	var tasks = new Task[100];

	for (int i = 0; i < 100; i++)
		tasks[i] = blob.AppendTextAsync(string.Format("Appending log number {0} to an append blob.\r\n", i));

	Task.WaitAll(tasks);

However, if I attempt to perform the same set of tasks using the `AppendBlockAsync()` method, everything appears to work just fine.  Here's an example of a working solution:

	var tasks = new Task[100];
	
	for (int i = 0; i < 100; i++)
	{
		var message = string.Format("Appending log number {0} to an append blob.\r\n", i);

		var bytes = Encoding.UTF8.GetBytes(message);

		var stream = new MemoryStream(bytes);

		tasks[i] = blob.AppendBlockAsync(stream);          
	}

    Task.WaitAll(tasks);

_Note that I am not explicitly disposing the memory stream in this example as that solution would entail a using block with an async/await inside the using block in order to wait for the async append operation to finish before disposing the memory stream... but that causes a completely unrelated issue._

This makes me think that either there may a bug in the `AppendTextAsync()` method or I'm doing something incorrectly that I'm unaware of.  Any thoughts or suggestions would be greatly appreciated.

**Comment by galhag** [comment]
The same issue appears when using blob.AppendFromStreamAsync as well.

**Comment by jehine-MSFT** [comment]
Hello @matthewrenze & @galhag,

The issue is that you can't use methods such as AppendTextAsync in a multi-writer scenario since  they process data using the Append Position condition. This is why you see the second example failing with that condition not being met. As you're not waiting for the task to complete, you are not observing the same Append Position exceptions that you see when you use Task.WaitAll, but they are still occurring.

If you do need to support a multi-writer scenario such that ordering is not important, using AppendBlock(Async) is proper approach. Please refer our .Net lib documentation that gives guidance on how to use the AppendBlob APIs.

Link: https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.blob.cloudappendblob.aspx 

Hope this helps!
