### ISSUE TITLE
Issue with Microsoft.WindowsAzure.Configuration reference in encryption samples

### ISSUE THREAD

**Issue by davefellows** [Azure/azure-storage-net#200]
I've downloaded the encryption samples but when I open the GettingStartedSamples.sln, the nuget references to Microsoft.WindowsAzure.Configuration across all the projects are broken. 

I can see the nuget package has been downloaded and the supposedly missing dll is in packages (/net40) but it's not being picked up. If I uninstall the package and re-install it things work fine...

This is using VS2013.

**Comment by pemari-msft** [comment]
Thanks for reporting this, we'll get this fixed.

**Comment by pemari-msft** [comment]
Fixed in our 6.2 release. Thanks!
