### ISSUE TITLE
the dll file is not strongly signed

### ISSUE THREAD

**Issue by singlewind** [Azure/azure-storage-net#201]
I reference WindowsAzure.Storage 6.1.1-preview in one my project. And when I run xUnit test I got the error below.

Microsoft.WindowsAzure.Storage, Version=6.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by pemari-msft** [comment]
Hi @singlewind ,

Can you please let us know which platform you're targeting?

**Comment by jarroda** [comment]
I just hit the same issue.  It only popped up when migrating my Aspnet5 DNX app from beta7 to beta8.  The app targets dnx451

**Comment by pemari-msft** [comment]
Thanks for the extra details. My understanding was that this was a change in rc1, not beta8. Can you confirm that you're targeting beta8?

In any case, we'll correct this in the next release. Thanks so much for the report.

**Comment by singlewind** [comment]
@pemari-msft the referenced library is target to net46 and dotnet5.4. The xunit test library is target dnxcore50 (the xunit.runner.dnx doesn't support other target yet)

**Comment by kylesonaty** [comment]
I also ran into this issue. I am targeting `1.0.0-rc1-final` and using `6.1.1-preview'

**Comment by pemari-msft** [comment]
@singlewind  I think that the net46 change happened in 1.0.0-rc1 which is not yet supported by WindowsAzure.Storage. We will be updating our code soon to work with RC1.

@kylesonaty This makes sense for your scenario, as it is not yet supported.

Thanks for the reports!

**Comment by singlewind** [comment]
@pemari-msft  thanks for clarification. I will stay being patient. :+1: Too excited.

**Comment by mkarlsson** [comment]
Is there an ETA for RC1 support?
