### ISSUE TITLE
Support for DNXCore5 RC1

### ISSUE THREAD

**Issue by sescandell** [Azure/azure-storage-net#204]
Hi,

Do I missed something or the WindowsAzure.Storage package is not available for DNXCore5 (RC1 version).

Here is my project.json file:
```json
{
  "version": "1.0.0",
  "description": "UrlShortener.Core Class Library",
  "authors": [ "Stéphane" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.Extensions.Caching.Memory": "1.0.0-rc1-final",
    "Newtonsoft.Json": "7.0.1",
    "Microsoft.AspNet.WebUtilities": "1.0.0-rc1-final",
    "WindowsAzure.Storage": "6.1.0"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516",
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}
```

But dependency is not resolved for dnxcore50. Here is the message:
![image](https://cloud.githubusercontent.com/assets/1559970/11454346/e8e0ecd0-9628-11e5-953f-d6fe88d15f52.png)

In your Readme file you say this package support DNXCore5 beta8.
Do you have any information about DNXCore5-RC1 support date?

Many thanks,

**Comment by GuardRex** [comment]
You need ...
```
"WindowsAzure.Storage":  "6.1.1-preview"
```

**Comment by sescandell** [comment]
:+1: Going to try it.

Thank you

**Comment by sescandell** [comment]
Hi again,

"Sync" methods are not activated on 6.1.1-preview. Is it normal?

Will any coming version propose Sync methods too (`Execute` from `CloudTable` class for example)?

Thanks,

**Comment by GuardRex** [comment]
@sescandell That's the latest one for .NET 5 Core. If you mean synchronous methods vs. the async ones that are there, I very strongly suspect that its all async now going forward. You'll have to wrap the async stuff to make it synchronous for your app. I don't think the team is ever going to put the synchronous methods into the upcoming releases, but @pemari-msft will jump in and correct me if I'm wrong.

**Comment by GuardRex** [comment]
@sescandell Yeah, as I suspected. See his response here: https://github.com/Azure/azure-storage-net/issues/94

**Comment by sescandell** [comment]
Thanks for your help... I need to move all my call stack to async so :)

**Comment by GuardRex** [comment]
@sescandell Sure thing ... yeah ... I feel you on that. I had to do the same thing all the way back to my controllers, etc.

**Comment by pemari-msft** [comment]
To clarify, no -- we don't support rc1 yet. We'll be updating to support rc1 soon. For now, we support up to beta8 in preview support, which is contained in the Preview versions of our library. Please see our readme file at the root of this repo which explains all of this. Thanks!

**Comment by pemari-msft** [comment]
We are, however, evaluating adding sync methods for .NET Core at some point in the future. We've added it to our backlog, but it likely won't be supported while .NET Core support is still in preview. Hope this helps!
