### ISSUE TITLE
DNX Core

### ISSUE THREAD

**Issue by markrendle** [Azure/azure-storage-net#205]
From a quick scan of the code, it looks like everything in the `WindowsDesktop` build should now work with .NET Core, instead of using the `WindowsRT` bits. Is this something you're looking at now, or should I fork and fix and send you a PR?

**Comment by mirobers** [comment]
The WindowsDesktop code uses HttpWebRequest, which is not supported on .NET Core. Removing HttpWebRequest is a major refactor -- and it's work that we already did to create the WindowsRT codebase. So it makes more sense to evolve the WindowsRT code to achieve feature parity with WindowsDesktop. Is there a particular feature from WindowsDesktop that you are interested in seeing supported on the .NET Core platform?

**Comment by markrendle** [comment]
Right off the top of my head I can't remember what I was using that didn't work. I'll branch my project, switch to the DNX/ASPNET5 library and see what doesn't work, then I'll get back to you.

**Comment by pemari-msft** [comment]
Hi Mark, the DNX451 TFM doesn't exist anymore for class libraries. Therefore, our Desktop DNX library is now built from the `WindowsDesktop` codebase and like we said, HttpWebRequest isn't supported on CoreCLR as far as we're aware. So I think that is what you were looking for :) Please let us know/reopen if you have any further ideas about this one.
