### ISSUE TITLE
Table query not generating a proper request when no values are set

### ISSUE THREAD

**Issue by MeTitus** [Azure/azure-storage-net#206]
Given the following example:

            var tableQuery = table.CreateQuery<OffloadLapStat>();

            if (!string.IsNullOrEmpty(statType))
            {
                tableQuery = tableQuery.Where(x => x.StatisticType.Contains(statType)).AsTableQuery();
            }

            if (!string.IsNullOrEmpty(statName))
            {
                tableQuery = tableQuery.Where(x => x.ParameterName.Contains(statName)).AsTableQuery();
            }

            var entities = table.ExecuteQuery(tableQuery).ToList();

If the table query isn't change when issuing the request I get a 400 error. This is the workour which as you can see is not ideal:

            var tableQuery = table.CreateQuery<OffloadLapStat>();

            tableQuery = lapids.Aggregate(tableQuery, (current, lapId) => current.Where(x => x.PartitionKey == lapId.ToString()).AsTableQuery());

            if (!string.IsNullOrEmpty(statType) || !string.IsNullOrEmpty(statName))
            {
                if (!string.IsNullOrEmpty(statType))
                {
                    tableQuery = tableQuery.Where(x => x.StatisticType.Contains(statType)).AsTableQuery();
                }

                if (!string.IsNullOrEmpty(statName))
                {
                    tableQuery = tableQuery.Where(x => x.ParameterName.Contains(statName)).AsTableQuery();
                }
            }
            else
            {
                tableQuery = new TableQuery<OffloadLapStat>();
            }

            var entities = table.ExecuteQuery(tableQuery).ToList();

**Comment by jehine-MSFT** [comment]
Hello @MeTitus,

Could you please provide us with the Azure Storage Error message for the 400 request? The service may have returned a helpful error for debugging this issue.

Thanks!

**Comment by jehine-MSFT** [comment]
Hello again,

Any updates on your issue?

Thanks!

**Comment by MeTitus** [comment]
Hi, sorry I was on holidays and I was pushed to something else, but I'll try to give it a try during the week.

**Comment by pemari-msft** [comment]
Closing due to lack of info, please reopen if you find something more. Thanks!
