### ISSUE TITLE
does not work with asp.net 5 rc1

### ISSUE THREAD

**Issue by mkarlsson** [Azure/azure-storage-net#211]
Is there a time plan to be communicated so that I can know if I will be able to release my .net 4.6.1 dnx site? As of now it crashes because of strong name assembly binding.

**Comment by jehine-MSFT** [comment]
Hello @mkarlsson,

We are working on a release that will have the latest RC1 bits for CoreCLR. With this release, all of our dll's will be strong named signed.

We hope to get version 6.2 of our library out this week.

Thanks for reaching out to the storage team!

**Comment by pemari-msft** [comment]
As an aside, please note that the nuget TFMs for dnx have now changed, so the `dnx451` dll no longer exists. Taking a dependency on our `net40` dll in our GA package today should be the same for your purposes, unless you're also targeting CoreCLR. In that case, yes, we'll be supporting rc1 shortly.

**Comment by pemari-msft** [comment]
This has been fixed as of 6.2.1-preview. Thanks for your feedback.
