### ISSUE TITLE
Not compatible with Microsoft.Data.OData 5.7.0

### ISSUE THREAD

**Issue by wouterroos** [Azure/azure-storage-net#219]
Title says pretty much everything. The NuGet package definition says it should be compatible with Microsoft.Data.OData >= 5.6.4.

**Comment by pemari-msft** [comment]
Hi @wouterroos, can you clarify how it's not compatible? What error behavior are you seeing after using the binding redirect? Is it a runtime issue?

**Comment by wouterroos** [comment]
The issue can be reproduced by creating a console application, adding WindowsAzure.Storage as NuGet package, and updating the Microsoft.Data.OData package to 5.7.0. and trying to get any data from the table storage. Code used is similar to:

TableOperation tableOp = TableOperation.Retrieve<TableEntity>("TableEntity", "TableEntityName", new List<string> { "Column1", "Column2" });
            TableResult tableResult = table.Execute(tableOp);

**Comment by pemari-msft** [comment]
Hi @wouterroos,
I'm able to create a .NET Desktop console app, take a dependency on `WindowsAzure.Storage`, update my `Microsoft.Data.OData` dependency, then create a table and insert and retrieve entities. 
I'm not entirely sure where your case is different. Can you please provide the following?:
- The version of WindowsAzure.Storage you're using
- The platform of Console App you're using 
- The actual error returned when your app fails (you seem to implicate a runtime exception. Please provide the stack trace of that exception.)
- Optimally, your small repro app. For instance, in the code above there's no insert code. It looks like you're querying an existing table. Is this occurring for a specific type of data?

Thanks.

**Comment by axem** [comment]
@wouterroos Check your app.config or web.config for binding redirects for OData 5.7. Sample app.config
[app.zip](https://github.com/Azure/azure-storage-net/files/67296/app.zip)

**Comment by pemari-msft** [comment]
Yep, thanks @axem, I mentioend that in my comment above. 

@wouterroos, please let us know if you can provide us any viable repro information. Feel free to reopen this issue if you do -- for now I'll close as can't repro.
