### ISSUE TITLE
Consistent NuGet package naming with other Azure libraries

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-storage-net#22]
Service Management library packages and many other MS-originated packages start with `Microsoft.` namespace segment, but this one doesn't. Can we have consistency?

![msstor](https://f.cloud.github.com/assets/159209/2140904/9eca1066-9352-11e3-8772-27cea85ffd50.PNG)

**Comment by pemari-msft** [comment]
Thanks for the suggestion! We'll take this as a feature request.

**Comment by jehine-MSFT** [comment]
Hello @ahmetalpbalkan,

Thanks for the feedback! It's unfortunate that we didn't follow the Microsoft convention for our client when we first wrote the library. However, at this point changing the name has the potential to cause many issues for our customers while providing minimal value of consistency. Therefore, we have decided keep the name as is.

Thanks again!

**Comment by ahmetalpbalkan** [comment]
Thanks @jehine-MSFT.
