### ISSUE TITLE
Stream returned by CloudBlobBlock.OpenRead() does not respect AccessCondition

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-storage-net#223]
I am trying to read blobs from a known offset. I am doing this by "seeking" on the Stream returned by OpenRead, but I am frequently getting 412 errors because the resulting GET requests all contain `If-Match: "ETAG"`, even though I've specified the MatchCondition to be `"*"` when I call OpenRead.

    var buffer = new byte[100];
    var accessCondition =    Microsoft.WindowsAzure.Storage.AccessCondition.GenerateIfMatchCondition("*");
    var stream = blob.OpenRead(accessCondition,null,null); // Makes HEAD request with correct header,    If-Match: *
    stream.Position = 300;
    stream.Read(buffer, 0, buffer.length); // Fails very frequently with HTTP 412 errors. Resulting GET requests all have ETAGS in the If-Match header

I've tried using the OperationContext to set the `If-Match: "*"` header myself, but it's being overridden (requests still  have the wrong If-Match header)

The `DownloadToStream` and `DownloadToFile` methods all work as expected, but I cannot download the entire file.

**Comment by mirobers** [comment]
OpenRead is not a good fit for reading a blob while it is being concurrently modified. The calls to the service are abstracted away, so even a single read from the stream could contain inconsistent data and you would have no way of knowing whether the blob changed or how much of the returned data is from the modified blob. For these reasons, the stream locks to the blob's ETag for its lifetime. (The ETag access condition you provide to OpenRead is validated in addition to locking to the current ETag.)

I suggest using the DownloadRangeToStream API. This will let you select just the ranges you want, and each call will return a consistent view of the data range. Each call also refreshes the ETag so you will have the ability to detect when the blob was modified. Will this work for you?

**Comment by pemari-msft** [comment]
Please let us know if you have any other concerns about this behavior!
