### ISSUE TITLE
Package downgrade for WindowsAzure.Storage 6.2.2-preview

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#230]
RE: `WindowsAzure.Storage 6.2.2-preview`

It looks like there is a package downgrade occurring (`System.Xml.XmlSerializer`) for `dotnet cli` projects on the CI feed with your preview. Can you update the dependency? ... or will it be updated for whatever is coming next (`6.2.3-preview`?)?
```
warn : Detected package downgrade: System.Xml.XmlSerializer from 4.0.10-beta-23109 to 
4.0.0-beta-23109 myapp (>= 1.0.0) -> WindowsAzure.Storage (>= 6.2.2-preview) -> 
System.Runtime.Serialization.Xml (>= 4.0.10-beta-23109) -> 
System.Private.DataContractSerialization (>= 4.0.0-beta-23109) -> 
System.Xml.XmlSerializer (>= 4.0.10-beta-23109)  myapp (>= 1.0.0) -> 
WindowsAzure.Storage (>= 6.2.2-preview) -> System.Xml.XmlSerializer (>= 4.0.0-beta-23109)
```

**Comment by GuardRex** [comment]
`dotnet cli` is evolving rapidly ... the downgrade disappeared with the `netstandardapp1.5` framework. I assume this was just a temporary hiccup.

**Comment by GuardRex** [comment]
This is back again with latest packages. The app and storage library seem to work fine in spite of this, so is this an issue? We can close if the fix is pending a future version you'll release.

![capture](https://cloud.githubusercontent.com/assets/1622880/13093852/4085dd52-d4bc-11e5-9c4f-d5acc22e20ae.PNG)

**Comment by pemari-msft** [comment]
We've never used `System.Xml.XmlSerializer` `4.0.10-beta-23109`, always `4.0.0-beta-23109` and the packages have not changed in the past 6 days since you opened and then closed the issue. There's no fix from our perspective -- not sure what `paccharter` is, perhaps it's an interaction on your side? This is not a Storage issue however unfortunately.
