### ISSUE TITLE
Why can't I add this HTTP header to my blobs?

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#231]
I just learned that Googlebot-Image has been indexing images at my site, presumably because a `robots.txt` entry is only honored for LOCAL images ... those served from the site's domain. Images that are in Azure Storage (served by the Azure CDN) are on a different domain, thus Google indexes the images.

To stop this, Googlebot-Image needs to see this header on the blobs:
```
X-Robots-Tag: noindex
```
However, when I try to add this header (as a user-defined header) in CloudBerry Explorer for Azure Blob Storage, the header cannot be added.

So, what's up with this? Are you preventing me from adding the header? If so, why? If there is no good reason to stop me from adding the header, can you change your policy and allow its use? ... or do you have any other ideas?

**Comment by pemari-msft** [comment]
Hi @GuardRex,

You can add your own metadata headers [(user defined headers)](https://msdn.microsoft.com/en-us/library/azure/dd179404.aspx) as long as they're prefixed by `x-ms-meta-`. 

We're certainly not preventing you from sending a header (especially if you're using CloudBerry and not our library :) ) but the Storage Service will ignore any unsupported headers.

**Comment by GuardRex** [comment]
@pemari-msft Looks like I'm going to get stuck, but let's take a look. You imply that if I add:
```
x-ms-meta-X-Robots-Tag: noindex
```
... that servers (i.e., Googlebot-Image in this case) will see ...
```
X-Robots-Tag: noindex
```
... then you state ...

> the Storage Service will ignore any unsupported headers

... which refers to the standard blob headers and not the `x-ms-meta-` ones.

Besides, Azure apparently ...
* disallows dashes in the "name" (the part after `x-ms-meta-`), and
* the `x-ms-meta-` is not stripped off when the meta data header is sent the client, so this seems like it isn't going to work ...

Setup a test `x-ms-meta-mykey` header ...
![mykeytest](https://cloud.githubusercontent.com/assets/1622880/13087140/560e0058-d49b-11e5-9dad-50b47ea4aedf.PNG)

Fiddler response headers (`x-ms-meta-` is not stripped off) ...
![mykeytest2](https://cloud.githubusercontent.com/assets/1622880/13087144/58315574-d49b-11e5-8c08-37039fd79dd0.PNG)

Dashes are not allowed anyway (apparently) in the name part of `x-ms-meta` ...

![capture](https://cloud.githubusercontent.com/assets/1622880/13085821/fb85c432-d494-11e5-9be0-d03a7139fea7.PNG)

... it throws ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/13085834/06300b2c-d495-11e5-8006-56300e856682.PNG)

... so we're back to square one and the question remains ...

How can I set Azure Blob storage to serve image blobs such that the ...
```
X-Robots-Tag: noindex
```
... is plainly sent to the client? I think the simple answer is going to be, "You can't do that." Can you confirm?

Another way? @benaadams proposed that Googlebot-Image will look in the root of the domain for a `robots.txt` file for any image request it makes when indexing and caching external resources (specifically in this case to images referenced in the `src` attribute of an `img` element where the image is in a CDN). He suggested that I place a `robots.txt` file in the root of my blob storage account, which should also become available on the Azure CDN endpoints.

Personally, I have some doubt that this is going to work, but I can devise a test ...
1. Setup a handler in an app to keep an eye on requests (or just use standard IIS logging) ... looking for hits on `robots.txt` in that app
2. Serve a new image from that domain
3. Link the image into another website (`src` of an `<img>` tag).
4. Wait for (or trigger in Webmaster Tools) Google to index the site

See if ...
1. When the image is first requested by Google, does Google also even try to take a look at the `robots.txt` file in the site serving the image, and
2. Does the new image actually show up in Google Images, meaning they obviously ignored the `robots.txt` file the site serving the image.

This seems like an awful lot of crap to have to go through, but answers are difficult to find for this problem as it pertains to a CDN generally and with Azure specifically. Thoughts??

**Comment by pemari-msft** [comment]
Oh, I certainly in no way meant to imply that you could add `x-ms-meta-X-Robots-Tag: noindex`. I said you could add user defined headers in the way described, but that the Storage Service will ignore all unsupported headers (including, certainly, `X-Robots-Tag`).

**Comment by GuardRex** [comment]
@pemari-msft So as far as you know, that's all a dead end here (i.e., the Azure service helping me get that header out).

I should proceed with the test along the lines of the @benaadams proposed solution. I was just wondering if you had thoughts about what he's suggesting or any other ideas?

**Comment by benaadams** [comment]
@GuardRex don't forget items in the root directory of storage are served from a container called `$root` which you'll have to create.

Google Image bot does respect `robots.txt` https://support.google.com/webmasters/answer/35308?hl=en

**Comment by GuardRex** [comment]
@benaadams 

> Google Image bot does respect robots.txt

I know they respect it. What I don't know is if they even look for it under these circumstances. I think a test between two websites will show clearly what they're doing in these regards. It's worth a look for sure.

**Comment by GuardRex** [comment]
ah ... what the hell ... I'm gonna do it. I'll run the test. I'll report back the result of the test here, then I'll close the issue. We may as well have a firm answer on this. Stopping Google from indexing images served by Azure is an important piece of knowledge IMO. I think others will find this info useful.

**Comment by benaadams** [comment]
> What I don't know is if they even look for it under these circumstances

They do as its the premise for all links as they are linked from somewhere else; though they cache the `robots.txt` for 24 hours at least so make sure you get it right :)

**Comment by GuardRex** [comment]
@benaadams Should stop 'um dead :gun: in their tracks ...
```
User-agent: *
Disallow: /
```
`robots.txt` file saved in `$root` of Azure Storage blobs is successfully served at the storage endpoint and the CDN endpoint ...
```
http://my_storage_account.blob.core.windows.net/robots.txt
http://my_cdn_cname.vo.msecnd.net/robots.txt
```
... so far, so good.

**Comment by benaadams** [comment]
Check in webmaster tools that your image paths are disallowed; they have a section for it.

**Comment by GuardRex** [comment]
That's a little outside of the test though, isn't it?

I mean if you're correct, Googlebot-Image will scan site 1, see the `<img>` `src` point to an image in site 2 (it will be kept in site 2's `wwwroot` folder), but look (first) at `robots.txt` in site 2's `wwwroot` folder, see that it isn't supposed to index anything on site 2, and later I **should** see in logs that Googlebot-Image requested the `robots.txt` file in site 2 and **shouldn't** see this new image appear in Google Images for site 1. I'm trying to find out if they are looking and honoring the setup.

... and the bit above, of course, was just making sure that (as you correctly stated earlier) that `$root` is the root for even CDN endpoints. Geez! I bet you thought I trusted you more than that! :smile: I do. I do. I just like to see things working for myself ... remember my MS is in bio ... not comp sci ... well ... you've seen my code, so you prob guessed that already. :smile:

**Comment by benaadams** [comment]
Not sure `robots.txt` is a guarantee that all requests will always not be made; due to parallel requests etc; but it should discard the results rather than including in index.

**Comment by GuardRex** [comment]
@benaadams The table has been set ... the dinner has been served. Now, we just wait and see what happens when they index.

This might take a little while to get a definitive answer, b/c we don't know when Googlebot-Image will go looking, but my honeypot :smiling_imp: is ready for them.

Regardless of what is seen in logs, my custom 'don't index' asparagus image should not show up in Google Images and my 'do index' asparagus image (on a third domain) should show up on Google Images given this setup.

**Comment by pemari-msft** [comment]
As this has no update and is not related to the storage client library, I'm going to close this issue. Feel free to continue the discussion if you find anything useful.

**Comment by MackEdweise** [comment]
For people who are looking for a solution to the issue described by @guardrex in his[ comment ](https://github.com/Azure/azure-storage-net/issues/231#issuecomment-184840843) above, there is a way to set headers like `X-Robots-Tag` on Azure CDN profiles that are hosting storage blobs or the like.

The solution requires a premium CDN profile. With the premium profile, you can set headers on responses from your server with keys that contain dashes and are not C# identifiers. You will need to create the preium CDN profile, then access it in through the [Azure portal](https://portal.azure.com). You will be presented with a "manage" option that takes you to the Verizon Rules Engine.
![premium-prof](https://user-images.githubusercontent.com/10645577/51130999-6f6b2100-17fc-11e9-8ffb-e2e83c410fe2.png)

In the engine, you can set a rule to overwrite or append to the response headers with any header key / value.
![premium-header png](https://user-images.githubusercontent.com/10645577/51131081-a7726400-17fc-11e9-90cb-3777718a7792.PNG)

**Comment by penguinawesome** [comment]
@guardrex i'm also facing the same scenario. I want to add X-Robots-Tag = noindex in the blob storage http header. How did you resolve your issue?
