### ISSUE TITLE
CloudBlockBlob.AcquireLease leaseTime has invalid boundary check

### ISSUE THREAD

**Issue by dbelcham** [Azure/azure-storage-net#232]
The boundary check for the `leaseTime` parameter on `CloudBlockBlob.AcquireLease` isn't consistent with the valid values accepted by the REST endpoint. Calling `AcquireLease` with a value outside the valid range accepted by the REST endpoint will result in REST sending back an HTTP 400 error that surfaces with a `StorageException` exception thrown from the AzureStorage SDK that says "The value for one of the HTTP headers is not in the correct format."

The `leaseTime` range accepted by the REST endpoint is outlined as "...between 15 and 60 seconds" here: https://msdn.microsoft.com/en-us/library/azure/ee691972.aspx

**Comment by SeanFeldman** [comment]
:+1: 
Would it help if these values be part of a `BlockBlobConstants`? 
It would then remove the magical value from places like [this](https://github.com/Azure/azure-storage-net/blob/40c04ce1dbbc0c569316da0e3fe47b9bff5d3042/Test/ClassLibraryCommon/Blob/Protocol/BlobTests.cs#L900) or [this](https://github.com/Azure/azure-storage-net/blob/40c04ce1dbbc0c569316da0e3fe47b9bff5d3042/Test/ClassLibraryCommon/Blob/Protocol/BlobClientTests.cs#L364).

**Comment by mirobers** [comment]
Just wanted to post an update on this incident. We are working with @dbelcham to review the PR and get it committed. As this is a behavior change, we will be targeting the next major version release.

**Comment by erezvani1529** [comment]
@dbelcham,

/cc:@SeanFeldman,

The associated PR for the fix has been merged! Thanks again! ([v8.0.0)](https://www.nuget.org/packages/WindowsAzure.Storage/)
