### ISSUE TITLE
Remote Resolver

### ISSUE THREAD

**Issue by fabriziomorello** [Azure/azure-storage-net#235]
Is it possible to create a "Remote" Resolver? In the examples the Resolver is a simple Dictionary that lives as the application lives. I need to make the RsaKey instances persistent (in one or more blobs), but unfortunately RsaKey is not Serializable. How can I achieve this?

**Comment by mirobers** [comment]
You can create an RSACryptoServiceProvider object directly and call ToXmlString and FromXmlString to serialize and deserialize to storage. Pass the object to the constructor of RsaKey to produce a key usable by the storage client.

So basically, your key resolver can use the key ID to look up the correct stored XML, use FromXmlString to deserialize an RSACryptoServiceProvider and pass it to the constructor of RsaKey.
