### ISSUE TITLE
.gitignore should ignore TestConfiguration.xml

### ISSUE THREAD

**Issue by dbelcham** [Azure/azure-storage-net#237]
There should be no way to accidentally update this file with credentials when you setup your testing environment

**Comment by pemari-msft** [comment]
Thanks for your feedback. We'll look into making the TestConfiguration.xml file safer, however, it cannot be added to gitignore because we need to have the example file in the repo for public consumption.

**Comment by dbelcham** [comment]
The sample file is there, you don't need to delete it. You can add it to .gitignore now and prevent others from modifying it and commit it as part of their work. If you need to modify the structure of the file in the future you would then need to temporarily modify your local gitignore, commit the file changes and revert the change to your local .gitignore.

**Comment by pemari-msft** [comment]
As per the [gitignore man page](https://git-scm.com/docs/gitignore), "The purpose of gitignore files is to ensure that certain files not tracked by Git remain untracked." For files that are already tracked, adding that file to gitignore doesn't ignore future changes.

**Comment by dbelcham** [comment]
Try it. It works. I just verified it locally.

**Comment by jehine-MSFT** [comment]
Hello @dbelcham ,

You can see here (#243) that we have fixed this problem by removing the file from the repo and adding it to the .gitignore file. All you have to do is add it back to get the tests to work, and you won't need to worry about uploading your creds while testing with this file again.

Thanks for the feedback!
