### ISSUE TITLE
There should be a CONTRIBUTING.md

### ISSUE THREAD

**Issue by dbelcham** [Azure/azure-storage-net#238]
This file is pretty standard on OSS projects to outline the expectations that will be used when reviewing PRs. It is vitally important if the team is going to expect contributors to be responsible for updating the BreakingChanges.txt and changelog.txt files.

**Comment by pemari-msft** [comment]
Thanks for your feedback. We are indeed working on a file that details our process in order to make it clearer for customers who wish to submit PRs.

**Comment by dbelcham** [comment]
This file needs to include a list of all SDKs required to open all of the projects in the solution. It should also include a link to download each of the SDKs

**Comment by jehine-MSFT** [comment]
Hello @dbelcham ,

You can see here (#243) that we have added a [CONTRIBUTING.md](https://github.com/Azure/azure-storage-net/blob/master/CONTRIBUTING.md) file that gives guidelines on how to contribute to our SDK. Thank you for bringing this to our attention as we weren't aware having this file was a best practice. Please let us know if you still have problems after reading it.

Thanks again!
