### ISSUE TITLE
Undocumented overwrite behaviour of CloudFile.OpenWrite method

### ISSUE THREAD

**Issue by jnv** [Azure/azure-storage-net#240]
I would like to append data to existing file in the storage, however the documentation for the `CloudFile.OpenWrite` method is quite fuzzy regarding the file overwrite:

> Opens a stream for writing to the file. If the file already exists, then existing data in the file _may be overwritten_. [emphasis mine]

Now, if you take a look at [the code](https://github.com/Azure/azure-storage-net/blob/e2c5a2ac9a96a105e73eb379b6f516a6ce31f632/Lib/ClassLibraryCommon/File/CloudFile.cs#L187-L191) the new file is created if the `size` parameter is specified. However, the documentation for the parameter states:

> The size of the file, in bytes. If `null`, the file must already exist.

I suggest the overwrite behaviour should be explicitly documented, e.g. for the `size` parameter:

> The size of the new file, in bytes. If `null`, the file must already exist, otherwise a new file of the given size will be created.

**Comment by mirobers** [comment]
Thanks for the suggestion! We'll track this for a future release. If you prefer, you could submit a PR to the dev branch with this change as well.

This applies to the OpenWrite method of CloudFile and CloudPageBlob.
