### ISSUE TITLE
DownloadRangeToStreamAsync throws Exception: Microsoft.WindowsAzure.Storage.StorageException Message: Stream does not support writing

### ISSUE THREAD

**Issue by vigneshc** [Azure/azure-storage-net#246]
We use DownloadRangeToStreamAsync  on Cloud block blobs. Once in a while, it throws Stream not writable exception with below stack trace. The stream we pass is definitely writable, and also from the stack trace below. Based on the exception type and the stack trace, issue seems to be in the storage sdk library. Can you please take a look?

_Exception: Microsoft.WindowsAzure.Storage.StorageException
Message: Stream does not support writing. StackTrace:   
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)    
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)

InnerException
Exception: System.NotSupportedException
Message: Stream does not support writing.
StackTrace:   
at System.IO.Stream.BeginWriteInternal(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean serializeAsynchronously)    
at System.IO.Stream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)    
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.EndOperation(IAsyncResult res)    
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.EndOpWithCatch(IAsyncResult res) 
_

**Comment by pemari-msft** [comment]
Hi, we are unable to repro this with the information provided. Can you please specify what platform you are targeting, what version of the library you are using, and any other relevant repro details? Thanks.

**Comment by vigneshc** [comment]
We are using .Net SDK version 4.3.0 on a 64 bit windows server machine. We don't have a local repro, but we do see this in production often.

**Comment by pemari-msft** [comment]
Unfortunately, we aren't able to repro this still. Please enable client side logging or provide a repro for us to investigate this further.

**Comment by jod75** [comment]
I have the same issue too - Azure Storage v11.1.6.  WinDbg is filled with such first chance exceptions when downloading data from Azure block blob storage. My understanding is that you are setting up a timeout to a Readonly timeout stream.  I think the fix should be in TimeoutStream.cs as follows:

From:
private void UpdateWriteTimeout()
        {
            if (this.wrappedStream.CanTimeout)
            {
                try
                {
                    this.wrappedStream.WriteTimeout = (int)this.writeTimeout.TotalMilliseconds;
                }
                catch
                {
                    // ignore
                }
            }
        }

To (fix with bold):

private void UpdateWriteTimeout()
        {
            if (this.wrappedStream.CanTimeout **&& this.wrappedStream.CanWrite**)
            {
                try
                {
                    this.wrappedStream.WriteTimeout = (int)this.writeTimeout.TotalMilliseconds;
                }
                catch
                {
                    // ignore
                }
            }
        }



StackTrace below:

(5d3c.4fc0): CLR exception - code e0434352 (first chance)
Exception object: 0000024046aea548
Exception type:   System.NotSupportedException
Message:          The stream does not support writing.
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131515
OS Thread Id: 0x4fc0 (10)
        Child SP               IP Call Site
000000541bdfd428 00007ff97fffa799 [HelperMethodFrame: 000000541bdfd428] 
000000541bdfd510 00007ff91039763f System.Net.Http.StreamContent+ReadOnlyStream.set_WriteTimeout(Int32)
000000541bdfd540 00007ff9103975b7 Microsoft.Azure.Storage.Core.TimeoutStream.UpdateWriteTimeout() [C:\git\azure-storage-net\Lib\ClassLibraryCommon\Core\TimeoutStream.cs @ 290]
000000541bdfd590 00007ff910397406 Microsoft.Azure.Storage.Core.TimeoutStream..ctor(System.IO.Stream, System.TimeSpan, System.TimeSpan) [C:\git\azure-storage-net\Lib\ClassLibraryCommon\Core\TimeoutStream.cs @ 50]
000000541bdfd5d0 00007ff9103973ac Microsoft.Azure.Storage.Core.TimeoutStream..ctor(System.IO.Stream, System.TimeSpan) [C:\git\azure-storage-net\Lib\ClassLibraryCommon\Core\TimeoutStream.cs @ 38]
000000541bdfd600 00007ff910cd95d8 Microsoft.Azure.Storage.Core.Executor.Executor+d__1`1[[System.__Canon, mscorlib]].MoveNext() [C:\git\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs @ 147]
000000541bdfd850 00007ff96cdbdf12 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfd920 00007ff96cdbdd95 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfd950 00007ff96ce2d00f System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
000000541bdfd9a0 00007ff96ce32523 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
000000541bdfd9f0 00007ff96cd96f40 System.Threading.Tasks.Task.FinishContinuations()
000000541bdfda80 00007ff96cd96a88 System.Threading.Tasks.Task`1[[System.__Canon, mscorlib]].TrySetResult(System.__Canon)
000000541bdfdac0 00007ff96cd96a05 System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib]].TrySetResult(System.__Canon)
000000541bdfdb00 00007ff910391975 System.Net.Http.HttpClient.SetTaskCompleted(System.Net.Http.HttpRequestMessage, System.Threading.CancellationTokenSource, System.Threading.Tasks.TaskCompletionSource`1<System.Net.Http.HttpResponseMessage>, System.Net.Http.HttpResponseMessage)
000000541bdfdb70 00007ff9103917ad System.Net.Http.HttpClient+c__DisplayClass55_0.b__0(System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>)
000000541bdfdbe0 00007ff96ce2af27 System.Threading.Tasks.Task.Execute()
000000541bdfdc20 00007ff96cdbdf12 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfdcf0 00007ff96cdbdd95 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfdd20 00007ff96ce2b1e1 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
000000541bdfddd0 00007ff96ce2a8c1 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
000000541bdfde10 00007ff96ce2ee72 System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
000000541bdfde60 00007ff96ce2ed46 System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
000000541bdfdf00 00007ff96ce2e9e6 System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
000000541bdfdf90 00007ff96cd96c3e System.Threading.Tasks.Task.FinishContinuations()
000000541bdfe020 00007ff96cd96a88 System.Threading.Tasks.Task`1[[System.__Canon, mscorlib]].TrySetResult(System.__Canon)
000000541bdfe060 00007ff96cd96a05 System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib]].TrySetResult(System.__Canon)
000000541bdfe0a0 00007ff91038fa61 System.Net.Http.HttpClientHandler.GetResponseCallback(System.IAsyncResult)
000000541bdfe0f0 00007ff90fcf541f System.Net.LazyAsyncResult.Complete(IntPtr)
000000541bdfe140 00007ff96cdbdf12 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfe210 00007ff96cdbdd95 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfe240 00007ff96cdbdd65 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
000000541bdfe290 00007ff91037bbb9 System.Net.ContextAwareResult.Complete(IntPtr)
000000541bdfe2e0 00007ff90fcf52f6 System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
000000541bdfe320 00007ff91038d505 System.Net.HttpWebRequest.ProcessResponse()
000000541bdfe390 00007ff91038cf7d System.Net.HttpWebRequest.SetResponse(System.Net.CoreResponseData)
000000541bdfe430 00007ff91038760b System.Net.ConnectionReturnResult.SetResponses(System.Net.ConnectionReturnResult)
000000541bdfe490 00007ff910388071 System.Net.Connection.ReadComplete(Int32, System.Net.WebExceptionStatus)
000000541bdfe4f0 00007ff910387fac System.Net.Connection.ReadComplete(Int32, System.Net.WebExceptionStatus)
000000541bdfe570 00007ff90fcf541f System.Net.LazyAsyncResult.Complete(IntPtr)
000000541bdfe5c0 00007ff90fcf52f6 System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
000000541bdfe600 00007ff90f9a43d1 System.Net.Security._SslStream.ProcessFrameBody(Int32, Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
000000541bdfe680 00007ff90fcf518d System.Net.Security._SslStream.ReadFrameCallback(System.Net.AsyncProtocolRequest)
000000541bdfe6e0 00007ff90fcf4f8a System.Net.AsyncProtocolRequest.CompleteRequest(Int32)
000000541bdfe710 00007ff90fcf4ee5 System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32)
000000541bdfe740 00007ff90fcf4dbe System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult)
000000541bdfe790 00007ff90fcf541f System.Net.LazyAsyncResult.Complete(IntPtr)
000000541bdfe7e0 00007ff96cdbdf12 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfe8b0 00007ff96cdbdd95 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
000000541bdfe8e0 00007ff96cdbdd65 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
000000541bdfe930 00007ff91037bbb9 System.Net.ContextAwareResult.Complete(IntPtr)
000000541bdfe980 00007ff90fcf52f6 System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
000000541bdfe9c0 00007ff91037b5e5 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
000000541bdfea30 00007ff96ce2df74 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
000000541bdfebe0 00007ff96df96913 [GCFrame: 000000541bdfebe0] 
000000541bdfedf0 00007ff96df96913 [DebuggerU2MCatchHandlerFrame: 000000541bdfedf0] 
000000541bdfef58 00007ff96df96913 [ContextTransitionFrame: 000000541bdfef58] 
000000541bdff190 00007ff96df96913 [DebuggerU2MCatchHandlerFrame: 000000541bdff190]

Thanks!
