### ISSUE TITLE
DownloadToFile should decompress

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-storage-net#248]
When downloading a blob using a browser (Internet Explorer), the usable, decompressed version is saved to disk. The blob DownloadToFile method doesn't do the same - it saves a compressed version to disk (and does not store the fact that the content is compressed or how it is compressed, leaving the file on disk largely unusable).

**Comment by jehine-MSFT** [comment]
Hello @davidmatson ,

It appears you would like for our client to provide some convenience around compressing/decompressing data. Since data is just bytes to our service, we don't want to interpret or manipulate any user data on the client. If you would like to store whether the data is compressed or not metadata would be a great place for that. Simply put: we store exactly what is given and return exactly what is stored.

Thanks!

**Comment by davidmatson** [comment]
I'm referring to the blob.Properties.ContentEncoding (the standard HTTP Content-Encoding header). Other user agents, like IE, respect this header and act on the bytes accordingly to save the usable version of the bytes to a file.

**Comment by jehine-MSFT** [comment]
While we understand other software may make this convenience available for downloading compressed data, it would be very dangerous for us to start altering customer data. It all boils down to the fact that we treat all data as bytes and try not to do anything outside of storing and retrieve those bytes. We would advice our clients to store the data in a form that can later be read without relying on the client to take care of manipulating the data on their behalf.

Thanks!

**Comment by davidmatson** [comment]
>>It all boils down to the fact that we treat all data as bytes and try not to do anything outside of storing and retrieve those bytes.
I think that's the question I'm trying to raise here - should this API just save the raw bytes without understanding the content encoding? Today, I believe library today doesn't just save the response-body as raw bytes - it first performs some transformations (such as for chunked transfer encoding); also, it doesn't save the body to a file if the status code is 500. So I don't think it's solely retrieving raw bytes, it's understanding the HTTP contract and handling it accordingly to represent a .NET API call.

>>We would advice our clients to store the data in a form that can later be read without relying on the client to take care of manipulating the data on their behalf.
I don't think this statement fits with the contract the [Azure REST API](https://msdn.microsoft.com/en-us/library/azure/dd179451.aspx) provides:

Content-Encoding
Optional. Specifies which content encodings have been applied to the blob. This value is returned to the client when the Get Blob operation is performed on the blob resource. The client can use this value when returned to decode the blob content.

Content-Encoding is a valid, supported part of the Azure Blob service. Note how the contract necessitates having the client use this header appropriately to decode the content. Is the Azure storage library being a good client of the REST API if it ignores the Content-Enocding part of the contract?

**Comment by pemari-msft** [comment]
Hi David, 
Like we mentioned above, we do not modify client data. If you wish to adjust your data before or after the request, feel free to do so. The policy of the library is to not modify data, as we cannot understand the entirety of customer scenarios. Sorry for the inconvenience.
