### ISSUE TITLE
Request: Specific error code for features not supported by Storage Emulator

### ISSUE THREAD

**Issue by arangas** [Azure/azure-storage-net#249]
It can potentially be rather time consuming to verify whether an error is caused by a limitation in the Storage Emulator or is actually a bug.

Would it please be possible to add such an error in a similar style to [what's described here](https://github.com/Azure/azure-storage-net/issues/183#issuecomment-144481861) - something like NotSupportedByEmulator?

My apologies if something like this already exists! I read through ["Differences between the storage emulator and Azure Storage"](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/#differences-between-the-storage-emulator-and-azure-storage) and couldn't see anything.

**Comment by pemari-msft** [comment]
I'm not sure I quite understand the question. That error is returned by the storage emulator. Inspection of the error in the client library will show the NotSupportedByEmulator error code. Look especially at ``StorageException.RequestResult.StorageExtendedErrorInformation``.
