### ISSUE TITLE
UWP - CloudBlockBlob.UploadFromStreamAsync causes MissingMethodException

### ISSUE THREAD

**Issue by SamirHafez** [Azure/azure-storage-net#250]
The UWP App has the necessary nuget packages installed and uses a portable library that executes the call.

Creating a Test Library (`targetFramework="net45"`) and referencing the same nuget packages and portable library the call works as expected.

List of installed dependencies on the UWP app:

```
  "dependencies": {
    "Microsoft.Azure.Mobile.Client": "2.0.1",
    "Microsoft.Azure.Mobile.Client.Files": "1.0.0-beta-2",
    "Microsoft.Bcl": "1.1.10",
    "Microsoft.Bcl.Build": "1.0.21",
    "Microsoft.Data.Edm": "5.7.0",
    "Microsoft.Data.OData": "5.7.0",
    "Microsoft.Data.Services.Client": "5.7.0",
    "Microsoft.Net.Http": "2.2.29",
    "System.Spatial": "5.7.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "MvvmCross": "4.1.0",
    "Newtonsoft.Json": "8.0.3",
    "WindowsAzure.Storage": "6.2.2-preview"
  },
```
For what it's worth, I'm not directly calling the `UploadFromStreamAsync `method. I'm calling `IMobileServiceTable<>.AddFileAsync`

Is this a case of something that is not implemented for UWP?

EDIT:
Also, here is the warning from the .NET Native compilation of the UWP:

`2>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(887,5): warning : Method 'AzureBlobStorageProvider.<UploadFileAsync>d__2.MoveNext()' will always throw an exception due to the missing method 'CloudBlockBlob.UploadFromStreamAsync(Stream)'. There may have been a missing assembly.`

**Comment by FrancoisM** [comment]
I have the same issue with Download.
See https://github.com/Azure/azure-mobile-apps-net-files-client/issues/46
It's a signature issue. The UWP version of storage requires a IOutputStream whereas the MobileServiceClient calls the method with a System.IO.Stream.

However, I see that your post wasn't picked up in the last 10 days. Did you find a workaround? All the required fields are private so it's not straightforward to override DownloadToStreamSync (or Upload in your case).

**Comment by FrancoisM** [comment]
Actually I now have the same issue and it's more than a signature issue so I can't do what I did with Download.

**Comment by pemari-msft** [comment]
Please try using Version 7.0.1-preview of the library as we have made a fix for this issue in the latest version. Thanks!

**Comment by FrancoisM** [comment]
Can't install for MonoAndroid,Version=v6.0
