### ISSUE TITLE
CloudBlobClient.DefaultRequestOptions.RetryPolicy is always being recreated with default values due to call to IRetryPolicy.CreateInstance

### ISSUE THREAD

**Issue by husterk** [Azure/azure-storage-net#255]
I have setup a `CloudBlobClient` to use the custom retry policy class as shown below. However, each time a request is made using this `CloudBlobClient` the underlying `Microsoft.WindowsAzure.Storage.Core.Executor.ExecutionState<T>` class calls the `CreateInstance` method on my custom retry policy class which causes the request to revert to default values for the `DeltaBackoff` and `MaxAttempts` values. It seems to me that the requests should be using the retry policy object as supplied to the request instead of creating a new instance. Maybe I am just doing something wrong in defining my custom retry policy class but this seems to a bug in the `Microsoft.WindowsAzure.Storage.Core.Executor.ExecutionState<T>` class.

Note: I am using the Microsoft.Windows.Azure.Storage v6.2.0.0 Nuget Package.

**Custom Retry Policy Class**
```
public class CustomAzureBlobStorageRetryPolicy : IRetryPolicy
    {
        #region Constants
        private const int DefaultDelatBackoffInSeconds = 2;
        private const int DefaultMaxRetryAttempts = 5;
        #endregion

        #region Properties
        public TimeSpan DeltaBackoff { get; private set; }
        public int MaxAttempts { get; private set; }
        #endregion

        #region Constructors
        public CustomAzureBlobStorageRetryPolicy(
            int deltaBackoffInSeconds = DefaultDelatBackoffInSeconds,
            int maxAttempts = DefaultMaxRetryAttempts)
        {
            DeltaBackoff = TimeSpan.FromSeconds(deltaBackoffInSeconds);
            MaxAttempts = maxAttempts;
        }
        #endregion
        
        #region IRetryPolicy implementation
        public IRetryPolicy CreateInstance()
        {
            return new CustomAzureBlobStorageRetryPolicy();
        }

        public bool ShouldRetry(int currentRetryCount, int statusCode, Exception lastException, out TimeSpan retryInterval, OperationContext operationContext)
        {
            retryInterval = DeltaBackoff;

            if (currentRetryCount >= MaxAttempts)
            {
                return false;
            }

            if (statusCode != (int) HttpStatusCode.Conflict)
            {
                return false;
            }

            return lastException is StorageException;
        }
        #endregion
    }
```

**Configuring my CloudBlobClient**
```
this.AzureBlobClient.DefaultRequestOptions.RetryPolicy = new CustomAzureBlobStorageRetryPolicy(secondsBetweenRetries, maximumRetryCount);
```

**Execution State Code In Question**
```
public ExecutionState(StorageCommandBase<T> cmd, IRetryPolicy policy, OperationContext operationContext)
    {
      this.Cmd = cmd;
      this.RetryPolicy = policy != null ? policy.CreateInstance() : (IRetryPolicy) new NoRetry();
      this.OperationContext = operationContext ?? new OperationContext();
      this.InitializeLocation();
      if (!(this.OperationContext.StartTime == DateTime.MinValue))
        return;
      this.OperationContext.StartTime = DateTime.Now;
    }
```

**Comment by pemari-msft** [comment]
Hi -- your `CreateInstance()` method overwrites these values, right? Can you try using the following `CreateInstance` method?

        public IRetryPolicy CreateInstance()
        {
            return new CustomAzureBlobStorageRetryPolicy(this.DeltaBackoff, this.MaximumAttempts);
        }

**Comment by husterk** [comment]
I don't know what I was thinking... I guess I have been working in the functional programming paradigm for too long and I thought that the CreateInstance function was static and would not have the properties available to it. Oops... :+1:
