### ISSUE TITLE
Azure Storage Emulator 4.3 not found

### ISSUE THREAD

**Issue by evilpilaf** [Azure/azure-storage-net#258]
Hi, I've updated to Azure 2.9 SDK and downloaded the manual install msi for Azure Storage Emulator, but the latest version is still 4.2, I can't find 4.3 and I need to test the new libraries on my local machine before deploying to production

**Comment by jehine-MSFT** [comment]
Hello @evilpilaf,

Can you try using this link and seeing if it works for you? https://www.microsoft.com/en-us/download/details.aspx?id=51657

All you need to is select the Azure Storage Emulator from the list of downloadable packages.

**Comment by evilpilaf** [comment]
Hi @jehine-MSFT that did it, though I got a SmartScreen alert saying the publisher of the app wasn't recognized

**Comment by jehine-MSFT** [comment]
This is a known issue. We are working on addressing this issue.

Thanks!

**Comment by gaziqbal** [comment]
I was debugging locally against development storage after upgrading to the 7.0.0 libraries and the exception message directed me to download the latest emulator from https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/.
The link there is also pointing to the 4.2 and should be corrected.

**Comment by gaziqbal** [comment]
I'd recommend leaving the issue open for now so that it's easy to find information on where to download the latest emulator. Local development is broken with 7.0 otherwise.

**Comment by jehine-MSFT** [comment]
All the normal channel should be working now. Closing this issue. Please reopen (or comment) if you have nay more trouble with downloading the Azure Storage Emulator v4.3.

Thanks again everyone!
