### ISSUE TITLE
Unclear error message when using a SAS Token that already has `api-version` defined in it

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-net#259]
If I try to create an instance of `StorageCredentials` class with a SAS Token that already has `api-version` defined into it, I get following error:

> An item with the same key has already been added.

I believe this is because `UpdateQueryBuilder` method doesn't check if this parameter is already defined in the query string and tries to add it nonetheless.

```
    private void UpdateQueryBuilder()
    {
        SasQueryBuilder newQueryBuilder = new SasQueryBuilder(this.SASToken);

        newQueryBuilder.Add(Constants.QueryConstants.ApiVersion, Constants.HeaderConstants.TargetStorageVersion);

        this.queryBuilder = newQueryBuilder;
    }
```

Please see this thread on StackOverflow for more details: http://stackoverflow.com/questions/36579561/how-can-i-call-new-azurestoragecontext-using-sastoken-instead-of-storageaccoun.

**Comment by pemari-msft** [comment]
We should indeed update the error message to make it clearer, and we'll add that as a work item. However, the `api-version` parameter is owned by the component making the call, and so, we do intend to throw if that is present (the other option is to silently replace it with our own, which seems disingenuous).

**Comment by erezvani1529** [comment]
Hi @gmantri,

The error message has been improved to include relevant details for the above scenario in [8.0 release].(https://www.nuget.org/packages/WindowsAzure.Storage/8.0.0)

Thanks!
