### ISSUE TITLE
ExecuteBatchAsync and ExecuteAsync are giving out different exceptions for non-existing tables

### ISSUE THREAD

**Issue by AlvinStanescu** [Azure/azure-storage-net#261]
Hi everyone,

To check whether a table does not exist after an `ExecuteAsync` call, I'm using the code below:

````
try
{
    var insertOrMergeOperation = TableOperation.InsertOrMerge(entity);
    await this.CloudTable.ExecuteAsync(insertOrMergeOperation).ConfigureAwait(false);
}
catch (StorageException ex)
{
    var webException = ex.InnerException as WebException;
    var tableNotFound = webException != null && webException.Response != null && ((HttpWebResponse)webException.Response).StatusCode == HttpStatusCode.NotFound;
}
````

However, when using `ExecuteBatchAsync`, I have to parse the error message in order to figure out the same issue:

````
try
{
    var insertOrMergeOperation = TableOperation.InsertOrMerge(entity);
    await this.CloudTable.ExecuteAsync(insertOrMergeOperation).ConfigureAwait(false);
}
catch (StorageException ex)
{
    var tableNotFound = ex.Message.Contains("The table specified does not exist");
}
````

This is how the exception message looks like:

```
0:The table specified does not exist.
RequestId:[Guid]
Time:2016-04-14T09:28:10.0839691Z
```

In our scenarios we always want to create the table if it doesn't exist, and having to do it in two different ways definitely looks like an inconsistency to me.

Thanks,
Alvin

**Comment by pemari-msft** [comment]
This is accordance with the REST API spec of Table Storage. See the section entitled "[Sample Error Response](https://msdn.microsoft.com/en-us/library/azure/dd894038.aspx)":

> The following examples show responses from batch requests containing an operation that failed. Note that the batch response returns status code 202 (Accepted), but the individual operation that failed returns status code 400 (Bad Request). The additional error information is included in the response body for the failed operation. The code element specifies the storage service error code, whereas the message element begins with the index of the failed operation, followed by the error message string. To determine which operation failed, parse the index value from the message. Operations are indexed beginning at zero.
