### ISSUE TITLE
CloudTable method CreateIfNotExists not found in dnxcore50

### ISSUE THREAD

**Issue by pofallon** [Azure/azure-storage-net#262]
If I try to build my project under the `dnxcore50` framework, I get the following error:

`'CloudTable' does not contain a definition for 'CreateIfNotExists' and no extension method 'CreateIfNotExists' accepting a first argument of type 'CloudTable' could be found (are you missing a using directive or an assembly reference?) [dnxcore50]`

However, under `dnx451` it builds (and works) as expected.

Also, if I remove that one method call (and if the table already exists) the rest of my Azure Table Storage method calls work in `dnxcore50` as well.

**Comment by pemari-msft** [comment]
The 'dnxcore' platform only has an async paradigm. The 'dnx451' platform has both. Intellisense should show you this difference in Visual Studio. Please use the async paradigm if you want to use Core.
