### ISSUE TITLE
Update Azure storage packages to latest RC2 build of .NET Core

### ISSUE THREAD

**Issue by ericstj** [Azure/azure-storage-net#266]
The azure packages reference a very old build of .NET Core.  Would it be possible to update these to the latest RC2 packages?

**Comment by pemari-msft** [comment]
The latest stable version released on nuget [is a version of RC1](https://www.nuget.org/packages/dnx-clr-win-x86/). We can look to update to rc1-update2 in a coming release. Thanks!
