### ISSUE TITLE
Azure Storage - Append Blob very poor read performance

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-storage-net#267]
We switched from 'normal' Block Blobs to Append Blobs for parts of our implementation, because changes to blobs are appends to data only. To be more precise, we append an array of bytes every 15 minutes. Using Append Blobs and the SDK call `AppendFromByteArrayAsync`, updating of the blobs is now lightning fast.

But when we do a partial read of the data in the Append Blob using `DownloadRangeToByteArrayAsync`, we see response times that are some **2000% slower** compared to exact same operation performed against Block Blobs. Sometimes it takes more that 1.5 seconds to Get as little as 4 bytes from an Append Blob file, where this never exceeds 100ms when using Block Blobs. We tested this against Append Blobs and Block Blobs, both sitting in the same Storage Acount and holding same data in both blob types.

Any suggestions on how to amend these unexpected results?

**Comment by tedvanderveen** [comment]
A bit of additional testing reveals that if the `DownloadRangeToByteArrayAsync` requests a range of bytes that is part of the initial creation bytes of the Append Blob file, then performance is on par with Block Blobs. But when requesting bytes that were appended to the Append Blob later, then performance goes south. Is this expected behavior?

**Comment by pemari-msft** [comment]
Hi @tedvanderveen  --- I have a few followup questions that may help me solve this issue: 

-What size is your original byte array that you upload?
-What size are your additional writes? 
-Do you have a repro app?

If we can't figure it out from the above, we'll take a look at your account and debug why this is happening.

**Comment by tedvanderveen** [comment]
Hi @pemari-msft, in answer to your questions:
- Initial byte array size is approx. 200-300 kB
- Additional writes (appends) are usually 4 bytes
- We have no repro app
The scenario should be quite simply replicated. Please let me know if you need any additional information.

**Comment by pemari-msft** [comment]
Is there any reason you're appending in 4 byte increments? This means that each of your writes is going to be dominated by network latency. Further, you should expect your latency/performance to be directly related to the number of blocks you write, not to the overall size of the data. I'd recommend batching your writes to be as close to 4MB as possible to get the best performance. However, this would also be a limitation with 4byte block blobs. 

If you're also writing 4byte block blobs, would you mind sharing:
- The most recent repro time (preferably from today so it's easiest to find)
- The account name of the repro
- The request id of a slow read

and send that information privately to **ascl [at] microsoft [dot] com**? Thanks.

**Comment by tedvanderveen** [comment]
@pemari-msft: the 4 bytes of data is generated every 15 minutes, that is why we append the data in 4 byte increments. The write/read ratio would be some 1:10 so write performance is not very important. But these latency on reading the data is a problem. I will send you an email message now.

**Comment by tedvanderveen** [comment]
@pemari-msft: I recieve an error message when trying to send a mail to the address you provided above. Please contact me at ted@vanderveen.net

**Comment by pemari-msft** [comment]
I received your requests (and fixed the kickback issue, sorry about that) -- like I mentioned above, this is due to your extremely small block size. The fast request is because you're reading one piece of data that is written together, whereas your slow request requires reading data written in over 50 separate blocks. If you care about read latency and not write latency, you should design your application for optimal reads (that is, batch writes to be as near 4MB as possible, which will cause write requests to be slower but reads to be much faster). 

As this is expected and not a client issue, I'm going to close it. Please feel free to continue the design discussion with me via email.

**Comment by tedvanderveen** [comment]
@pemari-msft Thanks for this insight. It may be good to add this to the documentation somewhere. So for our scenario's where we have to add 4 bytes to a Blob every 15 minutes and still have good read performance, we should stick to the Block Blob way: read the full contents of the Block Blob, add the 4 bytes and replace the Block Blob and repeat that process every 15 minutes. This consumes quite a lot of data transfers between Azure Storage en the Webjob instance managing the Block Blob contents. But data traffic inside the same datacenter is free of charge, right?
