### ISSUE TITLE
Embrace github + open source

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-storage-net#268]
I get that your on GitHub and I also get that this library is open source. It just doesn't feel like you guys try to promote this project at all. The readme's and release notes say to check some blog that doesn't exist (use the release notes section of GitHub). The nuget project urls point to some azure website (but this is the actual project.... link here). Link people to this project. I shouldn't have to google to find it.

**Comment by jehine-MSFT** [comment]
Hello @niemyjski,

Thanks for the feedback! We are looking into getting the "Project Site" link updated to point to this GitHub repo.

We are always interested in improving our open source story as you can see by our commitment to working with the community to accept contributions and our publishing of a CONTRIBUTING.md file to help contributors get started.

If you think there are other ways we can embrace open source better, please let us know.

Thanks again!

**Comment by niemyjski** [comment]
Thanks! I think those things would really help. I see release notes now and a nuget link would help as well as adding a link to this github repo to the azure storage page would be a nice win as well.
