### ISSUE TITLE
Cache ability for table storage queries

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-storage-net#27]
Hi,

I am interested in designing an optional caching system for the table storage client so queries (that are explicitly marked "cachable") can use a local (possibly distributed) cache of Json responses instead of executing the query against the table storage endpoint.

Can the developers offer any insights as to where I should best look at implementing this feature?

**Comment by jehine-MSFT** [comment]
Hello @Plasma & @ahmetalpbalkan,

We are tracking the issue of caching content, but have decided to address it on the server-side as opposed to implementing a solution in each client library.

We are in the process of unsealing our classes for our next breaking release. Do you think that unsealing our classes and making all API calls virtual will help solve your issues?

Thanks!
