### ISSUE TITLE
CloudQueue and CloudQueueClient Recommended Life Cycle

### ISSUE THREAD

**Issue by aaronhoffman** [Azure/azure-storage-net#270]
Apologies if this is not the appropriate place for this type of question.

I am looking for the recommended guidance on the life cycle of a `CloudQueue` and `CloudQueueClient`.

In our current solution, we are adding messages to a `Queue` in parallel. Multiple threads are sharing the same `CloudQueueClient` and `CloudQueue`.

At times, messages have failed to queue, but the clients do not appear to throw any exception. We noticed that in the [getting started guide](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-queues/) and in the unit tests of this repository, a new client is made for each `AddMessage` call. Is this the recommended pattern, or can the `CloudQueueClient` and `CloudQueue` be reused? Can the `CloudQueueClient` and `CloudQueue` be used simultaneously on multiple threads?

**Comment by pemari-msft** [comment]
None of our objects are guaranteed to be threadsafe (I believe we write this in our [API reference](https://msdn.microsoft.com/en-us/library/azure/mt347887.aspx) as well). You should design your app around this fact.

**Comment by aaronhoffman** [comment]
That answers my question about threads.

What about reusing a `CloudQueueClient` and `CloudQueue` instance if messages are added sequentially on a single thread? Is the recommended practice to reuse these instances, or should a new `CloudQueueClient` and `CloudQueue` instance be created for each `AddMessage` request?

**Comment by pemari-msft** [comment]
You can reuse the CloudQueue instance.

**Comment by jstutson** [comment]
What about a loop on the Async versions of your add and delete messages methods?

I could begin calling the next insert before the first one responds.  Is this safe?  If it is, is there any way I would know for sure from documentation?  I think if it's stated the class is not threadsafe then this would imply that this is not safe.  The link provided doesn't make any mention of thread safety.

If not, then what is the recommended fastest way to write to or delete from the queue when we have thousands of items to process?  Is async even recommended in this scenario?
