### ISSUE TITLE
Portable *.dll must be referenced directly when using Xamarin targets

### ISSUE THREAD

**Issue by jiberan** [Azure/azure-storage-net#272]
It's not possible to install WindowsAzure.Storage version 7.0.0 and newer to project with Xamarin.Android target.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'System.Diagnostics.Tools 4.0.1-beta-23225'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
`

**Comment by pemari-msft** [comment]
Our Xamarin support is in preview. Can you try using the 7.0.1-preview package?

**Comment by jiberan** [comment]
Yes, in 7.0.1 preview it the same problem. If you take a look to nuget package there is dependency to
System.Diagnostics.Tools (>= 4.0.21-beta-23225). 

Problem is that this package is not compatible with xamarin.android target.

**Comment by pemari-msft** [comment]
Our PCL that supports xamarin only has these dependencies:
``Microsoft.Data.OData (>= 5.6.4)``
``Newtonsoft.Json (>= 6.0.8)``.

What type of project are you trying to create? Please use our PCL to work with Xamarin.

**Comment by jiberan** [comment]
It is Xamarin.Android type project. It looks like Nuget Manager is trying to restore dependecies from .NETPlatform 5.4

Install-Package WindowsAzure.Storage -Pre will show this error.

`Install-Package : Could not install package 'System.Diagnostics.Tools 4.0.1-beta-23225'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.`

**Comment by pemari-msft** [comment]
We'll take a look, but for now, please reference the PCL directly.

**Comment by jiberan** [comment]
ok, thanks!

**Comment by pemari-msft** [comment]
Can you check and see if this is still reproing? With our newest release (7.0.2-preview), I'm seeing nuget correctly add the PCL instead of the .NET5.4 dll. Thanks!

**Comment by jiberan** [comment]
it is still there. I just setup new clean VM with VS2015 Update2, install Xamarin and create Android app. (WebView template)

**Install-Package WindowsAzure.Storage -Pre**   is showing this error:

`

Attempting to gather dependency information for package 'WindowsAzure.Storage.7.0.2-preview' with respect to project 'App1', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'WindowsAzure.Storage.7.0.2-preview' with DependencyBehavior 'Lowest'
Resolving actions to install package 'WindowsAzure.Storage.7.0.2-preview'
Resolved actions to install package 'WindowsAzure.Storage.7.0.2-preview'
  GET https://api.nuget.org/packages/microsoft.data.edm.5.6.4.nupkg
  OK https://api.nuget.org/packages/microsoft.data.edm.5.6.4.nupkg 13ms
Installing Microsoft.Data.Edm 5.6.4.
Adding package 'Microsoft.Data.Edm.5.6.4' to folder 'c:\Users\jberan\documents\visual studio 2015\Projects\App1\packages'
Added package 'Microsoft.Data.Edm.5.6.4' to folder 'c:\Users\jberan\documents\visual studio 2015\Projects\App1\packages'
Added package 'Microsoft.Data.Edm.5.6.4' to 'packages.config'
Successfully installed 'Microsoft.Data.Edm 5.6.4' to App1
  GET https://api.nuget.org/packages/microsoft.netcore.runtime.native.1.0.2-rc2-24027.nupkg
  OK https://api.nuget.org/packages/microsoft.netcore.runtime.native.1.0.2-rc2-24027.nupkg 18ms
Installing Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027.
Install failed. Rolling back...
Package 'Microsoft.NETCore.Runtime.Native.1.0.2-rc2-24027' does not exist in project 'App1'
Removed package 'Microsoft.Data.Edm.5.6.4' from 'packages.config'
Package 'Microsoft.NETCore.Runtime.Native.1.0.2-rc2-24027' does not exist in folder 'c:\Users\jberan\documents\visual studio 2015\Projects\App1\packages'
Removing package 'Microsoft.Data.Edm.5.6.4' from folder 'c:\Users\jberan\documents\visual studio 2015\Projects\App1\packages'
Removed package 'Microsoft.Data.Edm.5.6.4' from folder 'c:\Users\jberan\documents\visual studio 2015\Projects\App1\packages'
Install-Package : Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package WindowsAzure.Storage -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

`

**Comment by tomcrusader** [comment]
7.0.2-preview tries to install .NetCore which will not fly for a standard Xamarin.Android project:

> Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by pemari-msft** [comment]
Hi all: as an update, yes, we've discussed with the Xamarin, CoreFx, and Nuget teams. This is actually a set of bugs owned by those teams. Currently, the "oreCLR on Xamarin" story is not yet complete which is why we see certain issues (and those teams are working to correct that problem). On top of that, Nuget is now bringing in .NetCore over portable projects which should not happen until the above story is fixed. 

For now, please reference the portable *.dll directly while we work with the other teams to correct this problem. We're really sorry for the inconvenience.

**Comment by pemari-msft** [comment]
As an update, we're still working with the Nuget team to try to fix this. It sounds like we'll have a workaround soon. Thanks for your patience.

**Comment by pemari-msft** [comment]
The nuget and Xamarin teams have come back with a plan for a fix. The ETA for the fix is in the next few weeks. Once that happens we'll release a new version of the library that works correctly. Thanks again for reporting this.
