### ISSUE TITLE
Newtonsoft.JSON Reference Update

### ISSUE THREAD

**Issue by goranzarkovic** [Azure/azure-storage-net#273]
In order to resolve many reference warnings on build, would it be feasible to update the Newtonsoft.JSON reference in this library to the latest available (8.0.3)?

**Comment by qin-nz** [comment]
Currently, it use >6.0.8
you can update to 8.0.3 by yourself

**Comment by pemari-msft** [comment]
We will take a look at doing this for everyone, but as mentioned, feel free to use binding redirects to do it yourself in the interim :)
