### ISSUE TITLE
Request for a new RC2-friendly package asap.

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-storage-net#274]
`WindowsAzure.Storage 7.0.1-preview` has been broken for .NET Core RC2-nightly builds for several weeks now. I'm somewhat blocked until a new RC2-friendly preview package is released, as developing further with the Azure Storage REST API doesn't make sense on the verge of getting a new library from you. Since RC2 is releasing next week, probably on Monday, can you commit to getting us a new preview package that works with RC2 as soon as possible?

**Comment by Bartmax** [comment]
PLEASEEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! BLOCKED

**Comment by mirobers** [comment]
We are working on it! RC2 was published just today and we will provide a preview version of our library with RC2 support soon.

**Comment by cwe1ss** [comment]
you need more than 2 hours for your update???? :D :D

**Comment by Bartmax** [comment]
If I ignore the restore errors, and publish to azure and ignore the fail publish message it magically works with 7.0.1-preview. This is weird, because yesterday wasn't working with the same package version.

**Comment by GuardRex** [comment]
@mirobers Thank you for jumping on it. Like @Bartmax I'm blocked and "roughing it" with Azure Storage REST API. I'm looking forward to the new preview. I'm going to close now ... just wanted to confirm to you that devs are hungry for this one! Yummy! :smile:

**Comment by stephanjohnson** [comment]
I would also like to see the next preview package include support for RC2

**Comment by Bartmax** [comment]
workaround: https://github.com/aspnet/Home/issues/1469

**Comment by stephanjohnson** [comment]
I've tried the workaround mentioned by @Bartmax and while that enables me to build, when I deploy I get a 500 internal server error on Azure Web Sites.

**Comment by Bartmax** [comment]
@stephanjohnson not sure what's going on. I deployed this successfully to azure. Maybe you want to try Remove additional files on destination

![image](https://cloud.githubusercontent.com/assets/3386797/15396078/d8975c96-1db0-11e6-8fad-ef84cc868d11.png)

**Comment by GuardRex** [comment]
@stephanjohnson If you have application logging enabled, you might get some additional info on the source of the exception.

Self-contained app:
```xml
<aspNetCore processPath=".\myapp.exe" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\myapp" />
```
Portable app:
```xml
<aspNetCore processPath="dotnet" arguments=".\myapp.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\myapp" />
```

**Comment by zygimantas** [comment]
As I tested, portable apps does not work on Azure right now because dotnet runtime is not installed yet.

**Comment by GuardRex** [comment]
Oh, right!!!! I forgot. :smile: I was just providing both for completeness. Well ... self-contained should work ok.

**Comment by Bartmax** [comment]
I tested it with both, portable is working.

**Comment by GuardRex** [comment]
They may have been rolling it out by-datacenter. The "end of the week" is almost here, so I would guess if it isn't in every datacenter yet it will be soon.

**Comment by zygimantas** [comment]
@Bartmax good news, I tested in Western Europe region. Have you created a new application or used the old one, which had no runtime installed previously?

**Comment by Bartmax** [comment]
@zygimantas used an old one without having the runtime.

**Comment by ovebastiansen** [comment]
Are there any ETA for a new package?

**Comment by erezvani1529** [comment]
Hi,

FYI, our preview package(7.0.2-preview) supporting RC2 release of .NetCore is now published to nuget.org.

Thanks!

**Comment by Bartmax** [comment]
:+1:

**Comment by zygimantas** [comment]
How long in your opinion it will take to support netcoreapp1.0?

**Comment by GuardRex** [comment]
This package does support `netcoreapp1.0`; however, there's a TFM of `netstandardapp1.5` present, so they put in a PR to fix that. https://github.com/Azure/azure-storage-net/pull/284 ... it might become `7.0.3-preview` when that gets merged (hard so say, since this is the least community-friendly part of Microsoft).

**Comment by erezvani1529** [comment]
@zygimantas: As mentioned in @GuardRex's comment, netappcore1.0 is supported. Also to clarify, the released package already includes the PR#284 to fix the TFM ( @GuardRex Thanks Luke! :) ) .

**Comment by GuardRex** [comment]
@erezvani1529 I feel u bro. We're just hoping for a little :heart: love ... it goes a long way. Keep on keep'in on. :smile:

**Comment by zygimantas** [comment]
@erezvani1529  I don't get it, how 7.0.2-preview is different than 7.0.1-preview which required to import:
```
"imports": [
 "dotnet5.6",
  "dnxcore50",
  "portable-net45+win8"
]
```

In other case, as previously, I get:

```
Package Microsoft.Data.OData 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.OData 5.6.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - sl4 (Silverlight,Version=v4.0)
Package Microsoft.Data.Services.Client 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Services.Client 5.6.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - sl4 (Silverlight,Version=v4.0)
Package System.Spatial 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Spatial 5.6.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - sl4 (Silverlight,Version=v4.0)
Package Microsoft.Data.Edm 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Edm 5.6.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - sl4 (Silverlight,Version=v4.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

I am missing something here?

**Comment by GuardRex** [comment]
These packages are not updated yet to explicitly support `netstandard1.5`. You can use this to force acceptance of the packages ...
```json
"imports": [ "portable-net40+sl5+win8+wp8+wpa81", "portable-net45+win8+wp8+wpa81" ]
```

**Comment by erezvani1529** [comment]
Thanks @GuardRex ! Confirming your response:

@zygimantas : Using  “imports” statement,  you will allow NuGet restore the required packages by specifying their supported target frameworks. Below imports statement should be sufficient to fix the problem for OData dependencies:

      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
