### ISSUE TITLE
Porting to .NET Core and the .NET Platform Standard

### ISSUE THREAD

**Issue by hoetz** [Azure/azure-storage-net#276]
@markrendle said it all in this blog post:
https://blog.rendle.io/net-core-a-call-to-action/

**Comment by qin-nz** [comment]
6.2.2-preview support asp.net 1.0.0-rc1.
And there is nothing to support 1.0.0-rc2 currently.

**Comment by GuardRex** [comment]
Duplicate: https://github.com/Azure/azure-storage-net/issues/274

TL;DR ... they're working on it now.
