### ISSUE TITLE
CloudQueue.DeleteMessageAsync(CloudQueueMessage) for message that became visible

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-storage-net#285]
## Scenario 1

1. msg1 (`CloudQueueMessage`) is received with visibility timeout set to 30 seconds.
1. processing is taking much longer than 30 seconds
  1. while processing of msg1 is happening, msg1 becomes visible on the queue
  1. another competing consumer received the message as msg2
1. msg1 is attempted to be deleted using `CloudQueue.DeleteMessageAsync(msg1)`. :boom: 

Exception is thrown `The remote server returned an error: (404) Not Found.`

## Scenario 2

1. msg1 (`CloudQueueMessage`) is received with visibility timeout set to 30 seconds.
1. processing takes 40 seconds
1. msg1 is kept around and later deleted using `CloudQueue.DeleteMessageAsync(msg1)`. 

Message is deleted.

## The question

Should the second scenario throw an exception? In the world of the competing consumers it sounds wrong that one can delete a message with an **expired** `PopReceipt`. 

Side note: This is also very inconsistent with ASB, where once message lock is expired, no operations can happen on the message.

**Comment by emgerner-msft** [comment]
Visibility timeouts are not intended to expire messages -- in fact they're for the very opposite. They're intended so that if one processor dies, another processor can pick up the message easily. 

I'm not sure I fully understand the question, but it seems like you're expecting visibility timeouts to work like time to live. Time to live is for message expiry and will actually delete the message when its time is up. Pop receipts don't expire and aren't intended for expiry. They're just a tag so that only one processor can access the message at a time. 

Scenario 2 makes perfect sense for this reason. The message is visible after 30 seconds (visibility timeout), but if nothing gets it, the original processor still has the tag for it and can delete and update it. If you'd like the message to get deleted after 30 seconds, you can use time to live.

**Comment by SeanFeldman** [comment]
@emgerner-msft nothing to do with TTL. 

Expectation is for `PopReceipt` to be connected to the visibilityTimeout. When a message is received, it's either default 30 seconds or whatever the `TimeSpan` (up to 7 days) specified. The receipt past the visibilityTimeout should not allow message deletion, regardless if there's another competing consumer or not. The receipt should be invalid once message has re-appeared on the queue. It's like getting a ticket movie for a show with a date/time. Just because no one purchased a ticket after I did, should not give me the right to be admitted. What this creates is inconsistent behaviour between a single and multiple consumers scenario.

### Single consumer

![image](https://cloud.githubusercontent.com/assets/1309622/15764700/47719e4e-28ea-11e6-9c10-34ac31ad9ec0.png)

## Multiple consumers

![image](https://cloud.githubusercontent.com/assets/1309622/15764711/5896b0e2-28ea-11e6-9063-38dfbf9bddf4.png)

As a result of the current behaviour, as long as there's a single consumer, visibilityTimeout *doesn't matter* and message will be processed in *whatever the custom processing time is*. 
The moment there's more than a single consumer, visibilityTimeout starts to play a significant role, since the 2nd consumer will pick the message up for processing the moment visibilityTimeout elapses, and the 1st consumer will not be able to delete the message. 

## Comparison to Azure Service Bus

With ASB when a message is received, it has a [`LockTonen`](BrokeredMessage.LockToken Property) and a [`LockDuration`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.queuedescription.lockduration.aspx) assigned by the queue to the message. During `LockDuration` time, no other consumer can touch the message. But, when `LockDuration` time elapses, an attempt to delete the message will not be allowed since `LockToken` will be considered *expired*. Doesn't matter if the message was or was not consumed by another competing consumer. So doesn't matter if there's 1 or many consumers, be behaviour is consistent.

Hopefully this makes more sense and you see what I'm after :smile: 
Thank you.

**Comment by mirobers** [comment]
The scenario as described is a bit broken, in that there is no good reason I can think of to process a message only to let it expire and then process it again. Consider using `UpdateMessage` to extend the lease on a long-running message.

Nevertheless, if this behavior is desired then there is a simple client-side solution: when you delete a message, first check the visibility time of the message. If it's in the past, throw an exception. This will prevent you from deleting visible messages.

**Comment by SeanFeldman** [comment]
The scenario has it's place. Here's an example:

```c#
var msg = ReceiveMessage();
ExecuteWorkBasedOnMessage(msg.Data);
RemoveMessage(msg);
```

You never know how long `ExecuteWorkBasedOnMessage`. Usually, an estimate is used to set visibility timeout, but once in a while processing time can exceed. Using `UpdateMessage` can lead to an infinite locking. Alternative, is let the message re-appear and allow other competing consumers handle it and remove if they are successful. In my scenario, a message that cannot be processed several times _should_ go to an error queue. Exceeding processing times is one of the criteria that would qualify message to end up in error queue.

The suggested workaround sounds good. Only concern if the client-side has a clock drift. Time issued by the server should be used to determine if the visibilityTimeout has elapsed or not (as you suggested, by looking at `ExecuteWorkBasedOnMessage`).

Thank you @mirobers

**Comment by SeanFeldman** [comment]
I still think this is a broken implementation that causes the issue. There should be no difference between one or many consumers.

**Comment by mirobers** [comment]
Could you describe your specific scenario? I can't quite come up with any good reason to intentionally fail in this case. The only time I want to fail to delete a message is when another consumer is already working on it. It doesn't matter how many consumers there are -- if someone else is already working on it then it is fine to fail.

**Comment by SeanFeldman** [comment]
When developing an application that literally uses ASQ as a transport an nothing else, one should not cater for edge scenarios. I have a customer that is currently building an application that processes a single message at a time (a single processing thread) and locking doesn't play any role since deletion can take place _any_ time after message becomes visible again. Unfortunately, the moment that customer will decide to dial up the number of consumers (i.e. have more than one processing threads), this is no longer a valid case. From an API standpoint, there shouldn't be a difference.

Yes, one could decide to lock all message for a longer time, but that means going by the worst common time it takes to perform work related to a message. It would also encourage a poor pattern of locking resources where a different approach is required.

**Comment by mirobers** [comment]
I think I see your point. You are saying that someone with a single queue consumer could be setting a visibility timeout that's too low for a given message, but not noticing it because everything just works. When they go to multiple consumers they might have messages that fail to be processed. (This assumes a small number of messages in the queue. If there's a backlog then everything still works smoothly with multiple consumers.)

On the other hand, if their queue consumer slows down on all messages for some reason then they would want the current behavior or else suddenly they would be facing a total outage for that consumer. If locking fails then optimistic concurrency is a lot better than nothing. :)

We'll take this as a feature request. As mentioned, there is a good client-side solution in this case. You can record the machine time when you dequeue the message to detect and handle clock skew.

**Comment by SeanFeldman** [comment]
>  If there's a backlog then everything still works smoothly with multiple consumers.
There's an issue as well, but that's a different one :)

Ideally, .NET client library would have what ASB has with [`AutoRenewTimeout`](https://msdn.microsoft.com/library/azure/microsoft.servicebus.messaging.onmessageoptions.autorenewtimeout.aspx). This way visibility timeout can be kept low, and at the same time specify for how long "lease" can be renewed.

Thank you @mirobers for taking this feature request.

**Comment by Scooletz** [comment]
It'd be great if we could have it. This behavior can have some serious consequences. Is there a way of upvoting it @mirobers other than this issue?

**Comment by mirobers** [comment]
@Scooletz Could you explain what the consequences are for your scenario?

If you want this behavior then I strongly recommend that you implement the simple client-side solution mentioned above. To summarize: you can measure the time it takes to process a message and decide whether you want to delete the message. Does that make sense?

**Comment by Scooletz** [comment]
The scenario is the same. Multiple consumers over a queue with possibly long processing time. 

I see the reasoning behind the client side time estimation, but still, if a client side measurement returns value equal to the visibility timeout, we go back to square one - one can't tell whether or not the message should be deleted. Having that said, I maintain my vote for this feature :)

**Comment by mirobers** [comment]
Please do use the feedback link above to register this request so others can vote on it as well. I'm closing the issue here as it doesn't relate to the client; we can track the request in the feedback forum instead. Thanks for your input!

**Comment by SeanFeldman** [comment]
Raised UserVoice issue [here](https://feedback.azure.com/forums/217298-storage/suggestions/14800320-invalidate-pop-receipt-when-message-becomes-visibl)

Please vote there as @mirobers has indicated. This is a storage queue server-side service issue.
