### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException while calling CloudTable.ExistsAsync().

### ISSUE THREAD

**Issue by vdangwal** [Azure/azure-storage-net#286]
Hi,

Not sure whats happening but when i call CloudTable.ExistsAsync(), getting Microsoft.WindowsAzure.Storage.StorageException exception with no informative details. 

`CloudStorageAccount storageAccount = CloudStorageAccount.Parse([Account Settings]);
            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();
            CloudTable table = tableClient.GetTableReference(tableName);
            var bExist = await table.ExistsAsync();`

**Comment by vdangwal** [comment]
I am using  "WindowsAzure.Storage": "7.0.2-preview"

**Comment by erezvani1529** [comment]
@vdangwal  Would you please share more details about the project type you are using?

**Comment by vdangwal** [comment]
Sure. It is a .Net Core RC2 project which is a console application. 

 "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },

**Comment by erezvani1529** [comment]
Thanks, also your complete project.json and stack trace of the failure would be helpful.

**Comment by vdangwal** [comment]
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Mdco.Framework": "1.0.0-*",
    "Microsoft.Extensions.Configuration": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "Newtonsoft.Json": "8.0.4-beta1",
    "OAuth": "1.0.3",
    "System.Runtime": "4.1.0-rc2-24027",
    "WindowsAzure.Storage": "7.0.2-preview"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "net40", "dotnet5.6" ]

    }
  }
}


Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.ni.dll

**Comment by vdangwal** [comment]
{"Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified."}   

at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableOperation[T](RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, Nullable`1 timeout, TableOperation operation, CloudTableClient client, HttpContent content, OperationContext ctx, TablePayloadFormat payloadFormat, ICanonicalizer canonicalizer, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass61_0.<RetrieveImpl>b__0(RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\TableOperation.cs:line 177
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 91

**Comment by erezvani1529** [comment]
The problem is with your project.json file importing dotnet5.6.
Please try using the below as your import statement:

        "imports": [
            "dnxcore50",
            "portable-net451+win8",
            "net40"
        ]

**Comment by vdangwal** [comment]
Thank you so much. It worked. Also, could you please redirect me to any good article about using these frameworks import?

**Comment by erezvani1529** [comment]
You can find good information here:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md
