### ISSUE TITLE
Separate Table Storage from the base package

### ISSUE THREAD

**Issue by vermorel** [Azure/azure-storage-net#287]
The `WindowsAzure.Storage` comes a _lot_ of dependencies. It would make the package leaner, easier to consume, and easier to maintain from client-app perspective by isolating the Table Storage into `WindowsAzure.Storage.Table`.

When installing the package on a fresh .NET project, the following dependent packages get dragged along: 

* `Microsoft.Azure.KeyVault.Core`
* `Newtonsoft.Json`
* `Microsoft.Data.Edm`
* `System.Spatial`
* `Microsoft.Data.OData`
* `Microsoft.Data.Services.Client`

Total packages account for 81MB.

 Of those 6 dependencies, the last 4 dependencies are only needed, if my understanding is correct, for the Table Storage. 

A quick look at StackOverflow indicates that there are about 3x more Blob Storage questions than Table Storage questions. Actually, as blobs are a lot simpler than tables, I would guess that the actual usage of tables on Azure is less than 1/10th of the blob usage - I don't have access to usage statistics, so I let you check my guess.

Extra dependencies don't come free:

* they are painful when combined with _serverless_ setup like Azure Functions (which are very cool). They also make Azure Webapp deployment fails on lower tier hosting scenarios
* each dependency represents extra surface area that need to be constantly monitored from a security perspective.
* each dependency represents extra upgrade overheads, multiplying the update frequency to benefit from the latest bugfixes (instigating _exactly_ what needs to be upgraded takes a lot of time).

Thus, it would be really _more secure_, _less consuming_ and _more productive_ to have the table storage put aside in its own package.

**Comment by GuardRex** [comment]
Dup: https://github.com/Azure/azure-storage-net/issues/97#issuecomment-191012939

> we do not plan to split up the different services into separate packages as this does not decrease the complexity

**Comment by vermorel** [comment]
Yes and the bulk of this complexity comes from Table Storage. In 2014, when #97 was opened, dominant usage patterns for the Azure Storage might not have been very clear. At present day, I would be inclined to think (not having access to usage data proving otherwise) that Table Storage is used only infrequently.

Isolating Table Storage would really drive the complexity down. Not for Table Storage itself - where the complexity would increase a little indeed - but for both Blob Storage and Queue Storage, complexity would be lowered, and quite a bit actually.

**Comment by mirobers** [comment]
Thanks for your feedback! First a minor nit: the package size of 81 MB seems to be quite high. A quick and dirty check shows this to be close to 11 MB total nupkg files for all six dependencies. (The size of the actual DLLs you need to ship is smaller still.)

I'd like to understand more about your request. Are you mainly interested in not having to ship Table Service DLL dependencies you don't happen to use? In other words, if it were a supported scenario to run blob-only workloads _without_ the last four DLLs being present then would this resolve the issue for you?

**Comment by vermorel** [comment]
Yes, a blob-only package would also work very nicely; and indeed, the primary concern is not shipping the Table Service DLL dependencies that are not used. Then, if I remember correctly, there is close to zero overhead in bundling blobs and queues because the two implementations are similar; so the thin package could indifferently be _blob only_ or _blob+queue only_.

**Comment by mirobers** [comment]
Sorry, my question was not clear. What I meant to ask is this: Suppose we keep the same package as we have now, but we guarantee (and test) that workloads that do not use the table service have no runtime dependency on the four OData/WCF DLLs. Then you can freely remove the table DLLs from your deployed code, although the NuGet package would still contains the dependencies. Would that resolve this for you?

**Comment by vermorel** [comment]
The point of my suggestion is to make things simpler, leaner, and more maintainable (hence more secure in practice) for the vast majority of the Azure Storage consumers - I would venture over 90% of the userbase, but again, I don't have the numbers. This is not a blocking issue so there is nothing to "resolve"; it's just one big chunk of unneeded complexity. Obviously, having no runtime dependency would already be a first step in reducing this complexity; but it would only yield a small fraction of the benefits brought by a wholly leaner package.

**Comment by mirobers** [comment]
Thanks. In the short term, we will remove the runtime dependency. Longer term, we would like to offer a package without the OData dependencies.

**Comment by vermorel** [comment]
Thanks a lot! This is a great perspective. I am looking forward to it.
