### ISSUE TITLE
StorageException on CloudBlockBlob.UploadFromFileAsync

### ISSUE THREAD

**Issue by georgechond94** [Azure/azure-storage-net#288]
StorageException is thrown **sometimes** when trying to upload a blob saying "A Task was canceled".
It seems that it is thrown when the file is around 10 MBs or more. My SAS expiry time is set to 1 hour.

Target: UWP Build 10586
Version: I tried with both latest stable (7.0.0) and latest preview (7.0.2-preview)

Here is the code where the exception is thrown.

                CloudBlockBlob blobFromSASCredentialvideo = container.GetBlockBlobReference(resourceName);
                blobFromSASCredentialvideo.Properties.ContentType = "video/mp4";
                
                await blobFromSASCredentialvideo.UploadFromFileAsync(file);
                await blobFromSASCredentialvideo.SetPropertiesAsync();`

Here is the Stack Trace

> "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__c`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass9.<<UploadFromStreamAsyncHelper>b__8>d__b.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass15.<<UploadFromFileAsync>b__14>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Eyeable.ViewModels.VideosViewModel.<UploadFile>d__56.MoveNext()"

And the Stack Trace of the Inner Exception

> "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__c`1.MoveNext()"

**Comment by mirobers** [comment]
Hi, what version of the library are you using and what platform does your project target?

**Comment by georgechond94** [comment]
@mirobers 
Hello Michael,
oops, I forgot to include them. I updated my comment.
Thanks for your reply.

**Comment by erezvani1529** [comment]
Hi @georgechond94,

Thanks for reporting this issue. I have a repro locally and have almost root caused the problem. Will update with more details upon further investigation.

**Comment by georgechond94** [comment]
Hello @erezvani1529,
yeah it seems that it is a timeout issue here. 
That's good to know, thanks!

**Comment by georgechond94** [comment]
UPDATE

I tried using a CloudAppendBlob and appended my chunked file to that blob, and it worked like a charm. So, probably it would be nice to split the file into chunks, if it is large enough, before uploading to a CloudBlockBlob or throw a useful exception when the operation times out.


Thanks for your answers,
George

**Comment by erezvani1529** [comment]
Hi @georgechond94, 

This problem is happening due to HttpClient timeout and we have a fix for it with next release(the fix includes throwing the correct timeout exception as well). 

As you have also tried, the best workaround is to try uploading smaller chunks to avoid client time out.

Thanks,
Elham

**Comment by georgechond94** [comment]
That's good to know @erezvani1529, thanks!

George
