### ISSUE TITLE
.NET Core TableEntity not mapping all properties of all derived classes

### ISSUE THREAD

**Issue by dlmelendez** [Azure/azure-storage-net#291]
Starting line 306 azure-storage-net/Lib/Common/Table/TableEntity.cs
` #elif ASPNET_K 
             IEnumerable<PropertyInfo> objectProperties = entity.GetType().GetTypeInfo().DeclaredProperties; 
`
Declared Properties only pulls in the properties of the last derived class in the inheritance chain which in inconsistent with the behavior of the full framework code path to return all properties.
In this scenario:
`public class TableClassA : TableEntity {
  public string PropertyA { get;set; }
} `
`public class TableClassB : TableClassA {
  public string PropertyB { get;set; }
} 
`
In the above code, when TableClassB is evaluated for writing table entity properties, only PropertyB will be found and added to the Azure Table while TableClassA-> PropertyA is ignored. The expected and historical action is that all properties from derived classes would be saved to the Azure Table.
Proposed fix:
` #elif ASPNET_K 
             IEnumerable<PropertyInfo> objectProperties = entity.GetType().GetTypeInfo().GetProperties(); 
`

**Comment by erezvani1529** [comment]
Hi @dlmelendez, Thanks for reporting this issue.
We will have the fix for it in public dev branch and our next release.

**Comment by pemari-msft** [comment]
We've released a fix for this. Please let us know if you have any other issues :)
