### ISSUE TITLE
DownloadToFile allows other readers to see bad data

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-storage-net#296]
CloudBlob.DownloadToFile is using a constructor of FileStream that uses FileShare.Read. This means that, while the file is being downloaded, other readers are permitted to access the (incomplete or even empty) file. It should use the same FileShare mode as File.OpenWrite does - FileShare.None (so that no other readers or writers will be allowed while the file is in the middle of being downloaded).

**Comment by esummers-msft** [comment]
Thank you for pointing this out. We will take it under consideration as a feature request.

**Comment by rambo-msft** [comment]
Hi @davidmatson, we will be including this fix in our 8.0 release. Thanks again for bringing this to our attention. :-)

**Comment by rambo-msft** [comment]
@davidmatson , We have fixed this in our new release with 6c37540f174ea99717053fda93686aab4d496997. Thanks again for your contribution.
