### ISSUE TITLE
.Net Core RTM

### ISSUE THREAD

**Issue by Eneuman** [Azure/azure-storage-net#307]
It looks like the 7.0.2 preview is not working with the RTM bits of .net Core.
When will the package be updated to support the RTM bits?

**Comment by asiffermann** [comment]
According to @mirobers's comment in #298:

> Meanwhile, we are updating our preview support for Core RTM. This will make it out within the preview flavor of the 7.1 release today. There is more to do before GA but we are almost there!

Today was 13 hours ago, so... update is coming! :)

**Comment by Eneuman** [comment]
Awsome news! 
Thanks for the information.

**Comment by asiffermann** [comment]
I think you should let the issue opened until the package is really released, so other people can view it :)

**Comment by Eneuman** [comment]
Reopened issue until preview is released.

**Comment by pemari-msft** [comment]
We promise, as soon as there's an update to .NET Core we're working to make sure we can get a build of our library that supports it for you :) 

Please try out [7.1.3-preview](https://www.nuget.org/packages/WindowsAzure.Storage/7.1.3-preview).

**Comment by niemyjski** [comment]
https://github.com/Azure/azure-storage-net/issues/311
