### ISSUE TITLE
Please add server task id to all modify operations response objects

### ISSUE THREAD

**Issue by yauhen** [Azure/azure-storage-net#31]
Hello
As far as I could see non of the operations that modify objects (crud excluding r letter :) )
returns job it/task id. For example in azure sdk for .net most responses have RequestId (for example OperationResponse) so we could track status. I could see two async versions: first that returns Task and second IAsyncResult. Theoretically they should solve this problem (if they send requests about progress to server to set completed, as far as I could see for example create snapshot returns x-ms-request-id). But anyway we will loose persistence: we could not save task to database so main process could just save task id and other periodically check. In addition for example for snapshots, Task become completed, Blob is available over api, but physically copying process is not finished. So I am not sure that storage client really checks job id (or may be this is api problem that returns completed before really copying).

Any ideas are welcome.

**Comment by jehine-MSFT** [comment]
Hello @yauhen,

Is your question about how to use client-request-id for validation? If so, here is a reference doc (search  'Client request ID'): 
https://azure.microsoft.com/en-us/documentation/articles/storage-monitoring-diagnosing-troubleshooting/

If you question is about the CopyBlob API sending a response before the blob is finished coping, in version 2012-02-12 and newer, the Copy Blob operation can complete asynchronously. This means you would need to ping the blob periodically and check it's copy state properties to see if the copy has succeeded. Copy Blob documentation here: https://msdn.microsoft.com/en-us/library/azure/dd894037.aspx

If I did not address your concerns, please clarify your question.
Thanks!
