### ISSUE TITLE
.NET Core support with lower .netstandard support + updated dependencies

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-storage-net#311]
#Yes, I get that .NET core support is out with https://www.nuget.org/packages/WindowsAzure.Storage/7.1.3-preview

But I get the feeling someone on the team doesn't understand how .netstandard works when it's targeting 1.6.... It's targeting .netstandard 1.6 which you could probably run on .net standard 1.3 with no issues other than just changing the framework section in project.json.. Also JSON.NET is still at 6.0.8 when 9.0 is out.. What's going on here?

**Comment by niemyjski** [comment]
Also, please don't just target NETStandard.Library (>= 1.6.0) and force others to bring in a kitchen sink when they reference your package.. Explicitly state the packages you use because there are probably fewer than 5 total you are using, but you are bringing in 50 by using `NETStandard.Library`

**Comment by niemyjski** [comment]
Looks like you could drop down to 1.3 after looking at your dependencies (all of which are out of date) and some of which say they support pcl but need to get updated to .netstandard. The OData team needs to get to work and also update their nuget package defs while there at it and explicitly state supported frameworks in the nuspec file.

**Comment by niemyjski** [comment]
Looks like OData and other libraries can target .net standard 1.0 which means there is nothing stopping you from lowering it to 1.0. However, may I suggest just dropping ODATA as this library should be broken out into multiple for those who do not need odata... Which would be great because I wish I didn't have to have a dependency on something that's rarely updated and something I don't use which is now holding us back.

https://github.com/OData/odata.net/issues/568

**Comment by pemari-msft** [comment]
Hi @niemyjski, I think you have some misunderstandings about what the "State of the Union" is right now here. Please take a look at some of the comments in the [odata thread you linked](https://github.com/OData/odata.net/issues/568#issuecomment-229848697) for more context. Of particular importance is that we are not the OData team and so we have no control over their release schedule 😄 

One of the big things for Azure Storage is that .NET Core and Xamarin aren't playing nice right now, so we're trying our hardest to support both without breaking either 😞 . Further, changing our dependencies also has other effects (like affecting the Azure SDK). We try not to move major version dependencies without a major version bump of our own to stay aligned with the principles of semver. 

Finally, please remember that this library is preview support. When we GA this library, we'll make sure that we have some of these 'housekeeping' items taken care of. Are any of the things you mentioned affecting your ability to use the client library on .NET Core? If so, please do open an issue on them. 

Your recommendation about removing the OData dependency has been heard in our other thread on it  and is unrelated to our .NET Core support. We'd always have to have the OData dependency updated to support Table Storage on .NET Core 😆
