### ISSUE TITLE
7.1.3-preview dependency problem

### ISSUE THREAD

**Issue by Eneuman** [Azure/azure-storage-net#312]
I'm trying to upgrade from 7.0.2-preview to 7.1.3-preview and the .Net Core release bits but I'm receving the following error after changing the version:

error: Package Microsoft.Data.OData 5.6.4 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Data.OData 5.6.4 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - sl4 (Silverlight,Version=v4.0)
error: Package Microsoft.Data.Services.Client 5.6.4 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Data.Services.Client 5.6.4 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - sl4 (Silverlight,Version=v4.0)
error: Package System.Spatial 5.6.4 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package System.Spatial 5.6.4 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - sl4 (Silverlight,Version=v4.0)
error: Package Microsoft.Data.Edm 5.6.4 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Data.Edm 5.6.4 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - sl4 (Silverlight,Version=v4.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.6.

**Comment by pemari-msft** [comment]
Hi @Eneuman, have you taken a look at this note?: https://github.com/Azure/azure-storage-net#odata
Can you please paste your project.json?

**Comment by Eneuman** [comment]
@pemari-msft Thanks!
Changing my import to:
```
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
```
solved the problem.

**Comment by rocifier** [comment]
Hi I'm having this same issue with dotnetcore1.1 - how can I configure imports now that project.json is gone?

**Comment by rocifier** [comment]
I figured it out. The following code must be in all .csproj files in the dependency chain, inside the first `<PropertyGroup>`

    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.6' ">dotnet5.6;portable-net451+win8</PackageTargetFallback>
