### ISSUE TITLE
Error when compiled with .Net Native UWP app

### ISSUE THREAD

**Issue by vinodshinde** [Azure/azure-storage-net#314]
I have a UWP app in Windows Store and I believe that windows store compiles app using .Net Native tool chain before delivering it to users device.

My Code inserts/updates/deletes an object from storage table and it gets following error.

    `System.NotSupportedException: NotSupported_UnreadableStream. 
    For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, Threading.CancellationToken cancellationToken)

    at Microsoft.WindowsAzure.Storage.Core.NonCloseableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, Threading.CancellationToken cancellationToken)`

Here is the code:

Delete Operation:

    `await AzureStorageTable.ExecuteAsync(TableOperation.Delete(myObject));`

Insert/Update Operation:

    `await DeletesStorageTable.ExecuteAsync(TableOperation.InsertOrReplace(myObject));`

Thanks for advance for the help.

**Comment by erezvani1529** [comment]
Hi @vinodshinde,

Would you please share the steps to repro along with your project.json as well? 

Thanks!

**Comment by vinodshinde** [comment]
Attached are the project.json files for the main app and library projects.
Library project has all the business logic and main app project has all UI code.

I have tried to reproduce it several times by compiling code in release mode but was not able to reproduce it.
But some of my users are reporting the errors and stack trace shows following. 

Most of the users who reported this issue are using Surface Pro 3. For the same users, app works perfectly on their desktop and Lumia mobiles. unfortunately I do not have Surface Pro 3.

`System.NotSupportedException: NotSupported_UnreadableStream. 
For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, Threading.CancellationToken cancellationToken)

at Microsoft.WindowsAzure.Storage.Core.NonCloseableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, Threading.CancellationToken cancellationToken)`
[project for app.json.txt](https://github.com/Azure/azure-storage-net/files/350953/project.for.app.json.txt)
[project for library.json.txt](https://github.com/Azure/azure-storage-net/files/350954/project.for.library.json.txt)

**Comment by erezvani1529** [comment]
Thanks for the information:

- In the project json file you are referring to a wrong version of the Nuget which does not target netstandard TFM(CoreCLR support). 

[Here](https://www.nuget.org/packages/WindowsAzure.Storage/7.1.3-preview) is our latest preview release. Please make sure you fix your reference.

- You mentioned "Most of the users who reported this issue", are there any other platforms with the same failure? would you please add details about those platforms as well.

**Comment by vinodshinde** [comment]
Hi @erezvani1529,
Thanks for quick response.
Is it safe to use preview release of SDK in production UWP app distributed through Windows Store?

This is a standard C# UWP app for Windows 10. Does it really need to be netstandard TFM (CoreCLR support)

I am little bit confused. It will be great if you can explain about netstandard TFM in UWP app.

Thanks,

**Comment by erezvani1529** [comment]
You should be able find useful information [here](https://msdn.microsoft.com/en-us/magazine/mt590967.aspx) or any other online documentation on UWP.

**Comment by vinodshinde** [comment]
Hi @erezvani1529,
I tried the preview 7.1.3 version with my UWP app but it gives lot of errors. I guess it will take time for you guys to add UWP support.

So, the only option for me at this point is to access Azure Table storage using REST API.

I use Shared Access Signature with permissions restricted at Partition Key level.
My server generates SAS Tokens and passes it to UWP app in encrypted format.

Are there any examples of how REST headers should be formed for REST API to work with Table Storage using Shared Access Signature.

I tried to search but all the examples pointed to using Azure Storage SDK. 
Is there any code in SDK that i can reuse to create the required headers for REST calls from UWP.

Thanks

**Comment by erezvani1529** [comment]
Hi  @vinodshinde,

We do support UWP apps with our preview package(7.1.3-preview). 

If any of the mentioned errors are library related, please open a separate issue tracking them, so we may acquire more detail for further investigation. 

Thanks!
