### ISSUE TITLE
Differences between assemblies in one package v7.1.3-preview

### ISSUE THREAD

**Issue by aquiladev** [Azure/azure-storage-net#315]
I wanna notice that there are huge differences between assemblies for different versions of runtimes in 7.1.3-preview version of nuget package. Big part of functionality is absent in assembly for .Net Framework  v4.5 and v4.6.1
I'm just curious how it works.
Is it good enough for you to put completely different assemblies into one package (I mean assemblies with types with different contracts)? Are you going to fix it or not?

Thanks

**Comment by kfarmer-msft** [comment]
Can you be more specific on the differences you're asking about?

**Comment by aquiladev** [comment]
package [7.1.3-preview](https://www.nuget.org/packages/WindowsAzure.Storage/7.1.3-preview)

<table><tr><td><b>net40 (.Net Framework v4.0 Client)</b></td><td><b>netstandard1.6 (.Net Framework v4.6.1)</b></td></tr>
<tr><td>PRESENT</td><td>ABSENT</td></tr>
<tr><td colspan="2"><div><b>Namespaces:</b></div>
<div>Microsoft.WindowsAzure.Storage.Analytics</div>
<div>Microsoft.WindowsAzure.Storage.Table.DataServices</div>
<div>Microsoft.WindowsAzure.Storage.Table.Queryable</div></td></tr>
<tr><td colspan="2"><div><b>Classes:</b></div>
<div>Microsoft.WindowsAzure.Storage.Table.EncryptPropertyAttribute</div>
<div>Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy</div>
<div>Microsoft.WindowsAzure.Storage.Auth.Protocol.NoOpAuthenticationHandler</div>
<div>Microsoft.WindowsAzure.Storage.Auth.Protocol.SharedKeyAuthenticationHandler</div>
<div>Microsoft.WindowsAzure.Storage.Auth.Protocol.SharedKeyLiteAuthenticationHandler</div>
<div>Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy</div>
</td></tr>
<tr><td colspan="2"><div><b>Interfases:</b></div>
<div>Microsoft.WindowsAzure.Storage.Auth.Protocol.IAuthenticationHandler</div>
</td></tr>
<tr><td colspan="2"><div><b>Methods:</b></div>
<div>Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateQuery()</div>
</td></tr>
</table>

I found some differences but I didn't check everything. I saw that a lot of Async methods were added and lot of methods were deleted (e.g. Microsoft.WindowsAzure.Storage.Table.TableQuery`1.BeginExecuteSegmented()) in CloudTable class.

I expect that assemblies for different runtimes should have one contract in single package.

**Comment by pemari-msft** [comment]
Our .NET Core support (NetStandard) is currently in preview. Why not use our GA version (7.1.2) if you just want to target .NET Desktop?

**Comment by aquiladev** [comment]
I've tried to move my package to **netstandard**, but I have a reference to your assembly.
I've asked about your plans related to **netstandard**. Are you going to provide new contract for using or the preview version has temporary contract?

**Comment by pemari-msft** [comment]
If you're moving to `netstandard`, you'll get the new CoreCLR dll. I would guess that when you're on .NET 4.0, you're being bait and switched back to our desktop dll by VS/nuget. We'll look into this more to see if there's anything we can do in packaging. However, if you're targeting .NETStandard, you should take a dependency on only the signatures found in that dll (in this case, you won't have access to Sync, APM, Analytics). We're continuing to add things to this dll, but you should not expect them in the immediate term. Thanks!

**Comment by pemari-msft** [comment]
Still looking into this -- when you say you moved your package to `netstandard`, did you mean you created a new project type? Or just changed your nuget `tfm`? Can you specify which netstandard you target? Can you provide your project.json file?

**Comment by aquiladev** [comment]
I have a project based on .Net Framework v4.5.1, but I want to use my package in different projects based on net451 or netstandard. That is why I created new project with same functionality based on dotnet core.

I've already changed the project.json, but it was like:
```
{
	"version": "2.0.0-preview",

	"dependencies": {
		"WindowsAzure.Storage": "7.1.3-preview"
	},

	"frameworks": {
		"netstandard1.6": {
			"imports": [
				"dnxcore50",
				"portable-net451+win8"
			],
			"dependencies": {
				"NETStandard.Library": "1.6.0"
			}
		},
		"net451": {
			"imports": [
				"portable-net451+win8"
			]
		}
	}
}
```
