### ISSUE TITLE
Tried 7.1.3-preview, cannot get CloudTable execute async to work.

### ISSUE THREAD

**Issue by gegana** [Azure/azure-storage-net#316]
Calling any CloudTable async methods result in the follow error:

`One or more errors occurred. (Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.)`

I have no control over this object, so I have no way of checking if it is disposed or creating a new response stream.

**Comment by kfarmer-msft** [comment]
Thank you for writing.  Could you verify for us what your target framework is?

**Comment by gegana** [comment]
Hi, I was targeting .net core 1.

**Comment by erezvani1529** [comment]
Hi @gegana,

Would you please provide details and steps to reproduce? (please include your project.json as well)

Thanks!

**Comment by pemari-msft** [comment]
We are still unable to repro this -- we do run tests on all of our code before we release and we are able to use CloudTable apis successfully :( Please do reopen if you can provide us more repro details.
