### ISSUE TITLE
Can't add Nuget (7.1.3-Preview) to .NetCore v1 (RTM) application

### ISSUE THREAD

**Issue by ry8806** [Azure/azure-storage-net#317]
I have the latest .NetCore tooling installed and I cannot install the 7.1.3-Preview package. On your GitHub Readme.md it says that this preview version should support .NetCore

The error I'm getting is with the dependencies of WindowsAzure.Storage.

Here's the Package Manager output:
[PackageManagerOutput.txt](https://github.com/Azure/azure-storage-net/files/378143/PackageManagerOutput.txt)

Project.json:
[project.json.txt](https://github.com/Azure/azure-storage-net/files/378149/project.json.txt)

Steps to Reproduce:
- Create new Console (.NetCore) application
- Try adding package "WindowsAzure.Storage" to project.json

**Comment by GuardRex** [comment]
Add the `portable-net45+win8` import ...
```c#
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
```

**Comment by pemari-msft** [comment]
Please see our [readme ](https://github.com/Azure/azure-storage-net/#dependencies) for more info.
