### ISSUE TITLE
Mocking CloudBlobContainer

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#318]
Several improvements were introduced in Azure storage SDK 7.0 to make classes easier to mock in unit testing (for instance: classes were unsealed, methods were marked as virtual, etc.). This is really great. However, I noticed that a few methods are still not marked as 'virtual' and therefore can't be mocked. One such example is the GetBlobReference method on the CloudBlobContainer class. There are other methods in the same situation, I'm just using this one to illustrate the issue.

I'm wondering if this was an oversight that I can expect to see fixed in an upcoming release of the SDK or if it was intentional. If it was intentional, can anyone suggest a strategy that would allow me to mock these methods? I'm using [Moq](https://www.nuget.org/packages/Moq).

**Comment by pemari-msft** [comment]
The only calls that were made virtual are ones that make network calls (service requests). Could you explain a bit more why there's a need to mock a call that only creates a local reference of an object? Thanks!

**Comment by Jericho** [comment]
The fact that I can't mock GetBlobReference means that I can't provide my own mocked CloudBlockBlob and therefore I can't mock UploadTextAsync. This results in my C# code (which I am unit testing) attempting to actually upload the text (which I'm obvisouly trying to avoid, it's not important for my unit testing purposes).

**Comment by Jericho** [comment]
To further illustrate my scenario, please consider the following C# class:
```
public class Foo
{
    private static readonly long MAX_CONTENT_SIZE = ((CloudQueueMessage.MaxMessageSize - 1) / 4 * 3);
    private readonly CloudBlobContainer _blobContainer;
    public Foo(CloudBlobContainer blobContainer)
    {
        _blobContainer = blobContainer;
    }
    public bool Bar(string content)
    {
        if (content.Length > MAX_CONTENT_SIZE)
        {
            var blobName = "abc123";
            var blob = _blobContainer.GetBlockBlobReference(blobName);
            await blob.UploadTextAsync(content).ConfigureAwait(false);
        }
        else
        {
            // Do something else
        }
    } 
}
```
I want to write a unit test to verify that the 'Bar' method will upload the content string when it exceeds the maximum size. For unit testing purposes, I don't want the text to be actually uploaded neither to Azure storage nor to emulator. I just want to verify that the 'UploadTextAsync' method is invoked.

**Comment by Jericho** [comment]
I would like to be able to write a unit test similar to this:

```
[TestMethod]
public void FooBar()
{
	// Arrange
	var mockBlobItem = new Mock<CloudBlockBlob>(MockBehavior.Strict);
	mockBlobItem
		.Setup(b => b.UploadTextAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
		.Returns(Task.FromResult(true))
		.Verifiable();

	var mockBlobUri = new Uri("http://bogus/myaccount/blob");
	var mockBlobContainer = new Mock<CloudBlobContainer>(MockBehavior.Strict, mockBlobUri);
	mockBlobContainer
		.Setup(c => c.GetBlockBlobReference(It.IsAny<string>(), It.IsAny<DateTimeOffset?>()))
		.Returns(mockBlobItem.Object)
		.Verifiable();

			
	// Act
	var content = "Hello World";
	var myFoo = new Foo(mockBlobContainer.Object);
	myFoo.Bar(content).Wait();


	// Assert
	mockBlobContainer.Verify();
	mockBlobItem.Verify();
}
```

but unfortunately, it doesn't work because. I get the following error:

```
Test method MyUnitTests.FooBar threw exception: 
System.NotSupportedException: Invalid setup on a non-virtual (overridable in VB) member: c => c.GetBlockBlobReference(It.IsAny<String>())

```

**Comment by pemari-msft** [comment]
I see. I think perhaps I was expecting a mocked `CloudBlob` object to be created via constructor (like you did with `CloudBlobContainer` instead of using the `GetContainerReference` method). We can make the Get*Reference methods virtual in the next breaking change release.

**Comment by Jericho** [comment]
Thank you for considering making these methods virtual.

**Comment by PureKrome** [comment]
Just to jump in here .. I'm having the exact same issue with `CloudQueueClient`. I end up getting a Queue and the want to `AddMessageAsync` but that needs to be a mock'd queue, so it really doesn't try to Add it...

eg..

```
var storageConnectionString = CloudConfigurationManager.GetSetting(connectionStringName);
var storageAccount = CloudStorageAccount.Parse(storageConnectionString);

var cloudQueueClient = storageAccount.CreateCloudQueueClient();
var queue = _cloudQueueClient.GetQueueReference("my-queue");

await queue.AddMessageAsync("some message");
```

So it's _very_ similar to @Jericho situation above ... including how I would like to mock out a `CloudQueueClient`, the `GetQueueReference` method and the `AddMessageAsync` method.

**Comment by erezvani1529** [comment]
Hi @Jericho, @PureKrome ,

The Get*Reference methods have been updated with "virtual" qualifier in [8.0.0](https://www.nuget.org/packages/WindowsAzure.Storage/8.0.0) release.

Thanks!

**Comment by Jericho** [comment]
This is excellent news! thank you very much

**Comment by PureKrome** [comment]
Thank you so much MS!

(lets now hope the `ctors` are easy/nice) :) it's been a while since i've checked :P
