### ISSUE TITLE
Roadmap for NetStandard Support

### ISSUE THREAD

**Issue by onovotny** [Azure/azure-storage-net#325]
The 7.1.x preview version has `netstandard1.6` support. That means the package has an extra output for netstandard 1.6 that does not work with UWP or other 1.4 based platforms.

Additionally, the package references the 6.x version of JSON.net requiring the need for imports statements.

Can we please clean this up?

Let's have a netstandard1.0/netstandard1.1 based façade (if it cannot all be implemented there), then an impl for wp8/win8/wpa81/net45 as needed, and then have a `netstandard1.4` version for the rest. Then the 1.4 version can be used in a `net461`, and `uap10.0` to ensure the same binary is used for those platforms.

Lastly, the `portable-` folder should be removed as nothing is using it now... NuGet 2.12 for VS 2012/2013 and 3.4 for 2014 won't use it. Xamarin Studio will also choose the `netstandard` version too.

Very happy to discuss this, and this will help keep the package neat.

**Comment by pemari-msft** [comment]
Firstly, netstandard did not support Xamarin correctly on the order of a few days ago, so portable was still necessary. Secondly, the support for netstandard is in preview. We are working to GA it which will come with a few changes (such as updating JSON and changing the netstandard version). At that point, we can look to unify and move forward in our roadmap of shipping only one dll. For now, we're focused on GAing the new platform 😄

**Comment by onovotny** [comment]
Xamarin does support .NET Standard in the stable channel as of today :) 
https://blog.xamarin.com/net-standard-library-support-for-Xamarin/

My main point here is that netstandard1.6 seems like way overkill and excludes most platforms. It also has issues with PCL's. Like what if I have a netstandard 1.0/1.1 class library with common logic? I cannot reference this library.

**Comment by pemari-msft** [comment]
Yes, as of today :) we have been closing working with the netstandard and Xamarin teams. We do need more than an hour to get a new packaged released 😃  We will change the netstandard version (at this point, it looks like to 1.3). We do have other considerations to take, but our roadmap is to keep expanding our Netstandard support until that dll can be used everywhere, and then we don't need to ship more than one.

**Comment by onovotny** [comment]
Cool- and to be clear, I am/was offering to help, if I can as the topic can be confusing :)

**Comment by fabiocav** [comment]
We, too (Azure Mobile Apps), would like to see that relaxed as 1.6 would be way too restrictive and have a direct impact on us. If you're planning on making this change and target 1.3, was this issue closed on accident? Can we reopen so we can continue to track this?

**Comment by pemari-msft** [comment]
This change is already implemented. We will work with Oren as well to discuss future changes we might be able to make. Then, we will post on this issue in order to track that work.

**Comment by pemari-msft** [comment]
See #338  :)

**Comment by fabiocav** [comment]
Great! Thanks for the update!
