### ISSUE TITLE
[Bug?/Feature request] Table storage request concurrency

### ISSUE THREAD

**Issue by MikaelGRA** [Azure/azure-storage-net#332]
Hello,

I have been working with your latest azure storage library (7.1.3-preview) in order to implement a library that supports both the full .NET and .NET Core.

Specifically I am working with Azure Table Storage and related APIs.

Previously, the recommended approach to get full performance out of the client library when you make a lot of small requests, was to increase the following property on the **ServicePointManager**:

``` C#
ServicePointManager.DefaultConnectionLimit = 100;
```

However, this class does not exist in .NET Core anymore and the new recommended approach is to use the **WinHttpHandler** class when you make your requests with an **HttpClient**, which now has a property called **MaxConnectionsPerServer**.

Now while I do find the change of API great (no longer needing to use a static class), it kinda leaves me wondering, how do I achieve the same thing with the WindowsAzure.Storage nuget package, which I can only assume uses the **HttpClient** under the hood, where I have no way of accessing it.

To point out the problem, as it stands right now, if I use my library in a full .NET application using the ServicePointManager, I am able to achieve about twice the performance compared with a .NET Core version.

Something to think about. Or maybe this is already available, and I simply don't know where/how?

**Comment by pemari-msft** [comment]
This is a great point. Thanks for bringing it to our attention! We'll look to correct this in our next release. WinHttpHandler is Windows specific which is something we'll need to consider as well.

**Comment by mirobers** [comment]
There is no limit to the number of concurrent connections. ([To be precise, it's int.MaxValue](https://msdn.microsoft.com/en-us/library/system.net.http.winhttphandler.maxconnectionsperserver(v=vs.105).aspx#P:System.Net.Http.WinHttpHandler.MaxConnectionsPerServer).) Have you directly observed concurrent connection throttling (e.g. in Fiddler)?

Another thing to consider is Nagle's algorithm, which will increase latency of small requests. Are you disabling Nagling when using ServicePointManager? We are currently investigating how to disable this in .NET Core, as we haven't seen a way to do this to date.

**Comment by MikaelGRA** [comment]
Interesting...

I actually also turned off Nagle algorithm in in the ServicePointManager for the full .NET application, so it could theoretically be related to that.

In my tests though, I was primarily doing batch operations and read operations involving 100/1000 entities.

I will see if it might be related to Nagle algorithm and report back.

Anyway, I did try running my tests with fiddler in the .NET Core app, and when I did this, the throughput actually increased to around the same speed of the full .NET application.

**Comment by MikaelGRA** [comment]
Hello again,

I have investigated the issues a bit further and I can say that:

Not using Nagle algorithm definitely makes the .NET application run faster, however, it still runs quite a bit faster than the .NET Core counterpart.

Is there a way to turn off nagling for .NET Core?

**Comment by rambo-msft** [comment]
Hey @MikaelGRA,

Not that we are aware of, but we have followed up with the .NET core team to investigate the matter for you. You can refer to this  [issue](https://github.com/dotnet/corefx/issues/10727) for more information. 

Thanks for reporting back, we will have to do some perf testing on our end to see if there are any issues outside of the Nagle algorithm that may cause this discrepancy.

**Comment by goncalo-oliveira** [comment]
Are there any news regarding this issue? The netcore team closed the issue without offering a solution, so I take it there's still no way to disable the nagle algorithm or any of the usual cases with Azure tables handling (such as expect 100 and connection limit)?

**Comment by MikaelGRA** [comment]
Not as far as I am aware, but I have not been looking at it for a while.

**Comment by erezvani1529** [comment]
Hi @goncalo-oliveira, @MikaelGRA,

Looks like the code for missing functionality has been ported [(see here)](https://github.com/dotnet/corefx/blob/master/src/System.Net.ServicePoint/src/System/Net/ServicePointManager.cs) in CoreFx repo, however we can not provide exact timelines about the public availability on all platforms. 

Based on our initial assessments with Netstandard2.0, we expect almost all of the missing features from Netstandard/NetCore to be added as well helping with our parity objective :) 

I will update this thread once we have more updates.

Thanks,
Elham

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
