### ISSUE TITLE
Multiple keys used in key rotation sample (as opposed to key versions) 

### ISSUE THREAD

**Issue by theMichaelB** [Azure/azure-storage-net#334]
Instead of using a single key, and using Key Vaults' versioning mechanism, the code provided in the key rotation sample uses multiple keys and swaps them around. 

Wouldn't versioning be more consistent with Key Vaults' architecture?

**Comment by mirobers** [comment]
Thanks for the feedback. We are working on improving the entire key rotation experience, and updating the sample to use Key Vault key versions is part of this effort.

**Comment by theMichaelB** [comment]
Good stuff :) 

There is a question here - http://stackoverflow.com/q/38958483/5255018 - that you could probably answer more authoritatively then
