### ISSUE TITLE
Mocking methods that return a sealed class

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#335]
Say I want to write a unit test for the `Bar` method:

```
public class Foo
{
    private readonly CloudBlobClient _blobClient
    public Foo(CloudBlobClient blobClient)
    {
        _blobClient = blobClient;
    }
    public async Task Bar()
    {
        var prefix = "/myfiles/";
        var result = await _blobClient.ListBlobsSegmentedAsync(prefix, null).ConfigureAwait(false);
        ... do something with the result ...
    } 
}
```

I can easily pass a mock blobClient to the constructor of the `Foo` class and I can also mock the `ListBlobsSegmentedAsync` method since it is marked as virtual. So far so good. However, how can my mock method return a `BlobResultSegment`? 

The problem I am facing is that `BlobResultSegment` is sealed, it does not have a public constructor and also its properties are read-only. 

Here's what I have attempted but it does not work because if the following errors:
- 'BlobResultSegment' does not contain a constructor that takes 0 arguments
- 'BlobResultSegment.ContinuationToken' cannot be assigned to -- it is read only
- 'BlobResultSegment.Results' cannot be assigned to -- it is read only  

```
[TestMethod]
public void ListBlobsSegmentedAsync()
{
    // Arrange
    var mockCloudBlobClient = new Mock<CloudBlobClient>(MockBehavior.Strict, new Uri("http://bogus/myaccount/blob"));
    var myBlobSegment = new BlobResultSegment
    {
        ContinuationToken = new BlobContinuationToken() { NextMarker = "abc123" },
        Results = new[]
        {
            new CloudBlockBlob(new Uri("http://bogus/myaccount/blob/myfiles/test1.txt")),
            new CloudBlockBlob(new Uri("http://bogus/myaccount/blob/myfiles/test2.txt")),
            new CloudBlockBlob(new Uri("http://bogus/myaccount/blob/myfiles/test3.txt"))
        }
    };

    mockCloudBlobClient
        .Setup(c => c.ListBlobsSegmentedAsync(It.IsAny<string>(), It.IsAny<BlobContinuationToken>()))
        .Returns(Task.FromResult(myBlobSegment))
        .Verifiable();

    // Act
    var myFoo = new Foo(mockCloudBlobClient.Object);
    var result = myFoo.Bar();
    result.Wait();

    // Assert
    mockCloudBlobClient.Verify();
}
```

**Comment by jofriedm-msft** [comment]
Hi @Jericho , you can create a BlobResultSegment object using System.Reflection

**Comment by erezvani1529** [comment]
Hi @Jericho,

Closing this issue as the Blob/Container/ShareResultSegment classes have been unsealed with latest release([8.0](https://www.nuget.org/packages/WindowsAzure.Storage/8.0.0)).

Thanks!

**Comment by Jericho** [comment]
Thank you
