### ISSUE TITLE
Roadmap to NetCore Transition: Changes in upcoming Azure Storage Client Library for .Net releases

### ISSUE THREAD

**Issue by erezvani1529** [Azure/azure-storage-net#338]
With the general availability of our support for .Net Core, we would like to share with you our plan in terms of future breaking changes and the roadmap to moving to .Net Core:

**Changes to be included in upcoming major version release (v. 8.0)**
- Adding support for Netstandard1.0: As the lowest TFM supported by all our implementations, 1.0 is selected to cover maximum platforms. Based on the great feedback from our users, we are planning to add a façade reference assembly targeting netstandard1.0 with no API implementations.
  The reference assembly, through the bait and switch technique, enables other portable class libraries to reference our library while the correct implementation assembly will be picked when the package is referenced by the application or the project.json file.
- Moving from .Net 4.0 to .Net 4.5.2: Microsoft is no longer supporting .NET 4.0 in favor of the more commonly used 4.5.2 and the newly released .NET Core. We have determined that the vast majority of our users are already targeting .NET 4.5.2 thus we will no longer support .NET 4.0 in our next major version release.

**Backlog changes as part of transition to .NetCore**
- Parity between .Net Core and Desktop Libraries: We will be working to ensure feature and performance parity between our Desktop and .Net Core libraries.
- Deprecating Windows Phone 8 in favor of Windows Phone 8.1 and UWP 10, which is supported through NetStandard.

**Comment by erezvani1529** [comment]
Using this issue to keep track of the parity items between Desktop and Netstandard support.

**Comment by niemyjski** [comment]
What's the status of this issue?

**Comment by erezvani1529** [comment]
Since the latest release of the [Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/9.4.0-preview), [Queue ](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/9.4.0-preview)and [File ](https://www.nuget.org/packages/Microsoft.Azure.Storage.File/9.4.0-preview) as our preview split packages, Desktop and Netstandard2.0 targets use the same code-base and have parity. Please make sure to review the BreakingChanges lists on the nuget packages before you use them.

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team. The CosmosDB team has planned support for Netstandard2.0.  Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information. between Netstandard and NetFx target.

Thanks!
