### ISSUE TITLE
Throwing exception if no permissions are provided when creating a SAS

### ISSUE THREAD

**Issue by dschenkelman** [Azure/azure-storage-net#34]
This is just an improvement proposal/question.

According to [this doc](http://msdn.microsoft.com/en-us/library/windowsazure/dn140255.aspx) the "sp" (signed permissions) query parameter is required in all valid signatures.

The code in `SharedAccessSignatureHelper::GetSignature` does not add the "sp" query parameter if the permissions string is empty (which could occur if the flags are incorrectly passed in, believe me :)), which generates what I understand is an invalid SAS.

```C#
string permissions = SharedAccessBlobPolicy.PermissionsToString(policy.Permissions);
if (!string.IsNullOrEmpty(permissions))
{
    AddEscapedIfNotNull(builder, Constants.QueryConstants.SignedPermissions, permissions);
}
```
Should an exception be thrown notifying that no permissions were specified?

**Comment by pemari-msft** [comment]
Thanks for the suggestion! However, while "sp" is required for all valid signatures, the permissions can also be stored on the container object via signed identifier (see here: https://msdn.microsoft.com/en-us/library/azure/dd179391.aspx). We will take this as a feature request to make this error case easier in the future.
