### ISSUE TITLE
Unable to Auth when using [ or ] character in resource name

### ISSUE THREAD

**Issue by dadagov125** [Azure/azure-storage-net#342]
I rewrite the project from aspnet mvc to asp core . When prompted in openwork returns 403 response: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by pemari-msft** [comment]
Hi @dadagov125 -- have you seen #329 ? Are you using the `.`, `[`, or `]` characters in your resource name?

**Comment by dadagov125** [comment]
the problem was [ or ]
[.NET CLR 4.0.30319.42000.txt](https://github.com/Azure/azure-storage-net/files/448172/default.NET.CLR.4.0.30319.42000.txt)
[.NET Core.txt](https://github.com/Azure/azure-storage-net/files/448180/default.NET.Core.txt)

**Comment by dadagov125** [comment]
problem here [14.11.46]

**Comment by pemari-msft** [comment]
Yep -- this is a CoreFx bug that they have fixed and will release a fix for in an upcoming CoreFx hotfix. Thanks!

**Comment by dadagov125** [comment]
there is some sort of a temporary bypass this problem? when released a corrected version?

**Comment by pemari-msft** [comment]
Nothing yet (besides using some other platform or blob name). We are considering how we might be able to work around this issue on our side. You'll have to discuss with them what their timelines are for a release.

**Comment by erezvani1529** [comment]
Closing this issue as it has been fixed already by CoreFx team.

Thanks!
