### ISSUE TITLE
ExtendedErrorInformation.ErrorMessage is not part of StorageException.ToString()

### ISSUE THREAD

**Issue by ryandle** [Azure/azure-storage-net#343]
StorageException.ToString() does log the ExtendedErrorInformation.ErrorCode but doesn't log ErrorMessage, which would have other valuable information. It seems like this should be added to help with debugging StorageExceptions.

**Comment by kfarmer-msft** [comment]
Thanks for the suggestion, @ryandle -- 

Have you encountered a case where the error message has useful information that isn't already in the HTTP status message?

**Comment by ryandle** [comment]
I haven't personally encoutered it. Because this property isn't part of the Exception.ToString() my service doesn't currently log it. 

I created this issue after reading [this StackOverflow thread](http://stackoverflow.com/a/25400612/75814) which seemed to indicate that it could contain more helpful information. Is that not the case? If not, it seems a little redundant to have that property in the first place.

**Comment by rambo-msft** [comment]
Thanks @ryandle, we have addressed this for our upcoming release.

**Comment by rambo-msft** [comment]
@ryandle We have resolved this with [6e6827](https://github.com/Azure/azure-storage-net/commit/6e68276b3de9091fb48f2544db7ad49ad4645783#diff-802e86e9fd2d207d391598051d4aa4af). Thanks again!
