### ISSUE TITLE
Scalability Testing - Requests Queueing?

### ISSUE THREAD

**Issue by dhakimTRX** [Azure/azure-storage-net#344]
I'm running some scalability tests against my Azure website.  We run a small REST api where each function goes off to table storage and comes back with the results of some query.  My server is using this library to connect to table storage.  

I'm seeing large delays reported when watching the OperationContext objects, I'm able to hit around 9ish seconds between the StartTime and EndTime reported (and RequestResults.Count is always 1) when I throw 100-200 requests at the server.  But checking the $MetricsHourPrimaryTransactionsTable for timings, I'm seeing table storage report a 0-100ms E2ELatency on all queries.  

That suggests to me that I'm queuing up requests somewhere in the library between when StartTime and EndTime are set.  

Are there a set of configuration parameters I should be setting somewhere to increase the number of queries I can have running?  Any kind of max thread pool, max outbound connection, max outbound connection to table storage, things like that?

**Comment by pemari-msft** [comment]
We don't queue requests ourselves, but you may be hitting .NET limits depending on your configuration. Please try setting the following:
`ThreadPool.SetMinThreads(100, 4);`
and
`System.Net.ServicePointManager.DefaultConnectionLimit = 100; `


This could also be caused by retries, or by network latency or client resource exhaustion. Please check on those and let us know if they fix your issue.

**Comment by dhakimTRX** [comment]
I've continued profiling for some time now, and I still don't really trust the results I'm getting.  As far as I can tell, I'm CPU bound somewhere within the OData library.  

This would indicate that I'm trying to parse too much data with too complex a schema?  

I've verified that <5% of the time is spent in the ReadEntity call of my TableEntity subclass, so I guess the expensive operations are elsewhere.  Unfortunately, my profiler and profiling abilities capped out trying to dive into async calls of libraries inside libraries, so I can't diagnose the issue any further.  

That is, assuming there is any issue at all.  I can solve my problems for now by scaling out the instances, and shifting back to SAS credentials client side to remove the bottleneck if required.  If there are any tips for reducing processing based on table schema or request flags, I'll be glad to have them.  If this is standard behavior of the library, please feel free to close.

**Comment by dhakimTRX** [comment]
In case it helps anyone to continue where I've left off, 

New Relic reports 61% of the time is in Microsoft.WindowsAzure.Storage.Core.util.APMWithTimeout.UnregisterWaitHandle(), compared with 2.4% in code serializing the returned entities to Json and sending them out of our server.  

ANTS reports ~60% of the time in various OData deserialization, ~10-20% in a cryptographic hash function.

**Comment by pemari-msft** [comment]
Sorry for the delayed response. We did find that Odata actually doesn't implement async processing. So what you see is valid, and an issue in the OData lib. We are already working to try to remove the odata dependency which would help with this issue.
