### ISSUE TITLE
Finding it hard to mock some of the Storage classes

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-storage-net#349]
Hi Team!

I'm finding it frustrating when mocking out some of the methods in the Storage SDK because a select number of them aren't `virtual`.

For example - i'm referencing the [code from the Getting Started docs](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-files/#develop-with-file-storage).

I'm assuming that the methods that are not `virtual` are defined like that because they don't need to hit the internet but just do some logic on the preset internal data?

Lets start with this:

REFERENCE: [Here's the full gist](https://gist.github.com/PureKrome/357e84b3554fff637432e64f7d50c050).

<details>
<summary>

(Click to expand) **Main method that does the code**</summary>

```
private static void DoSampleTest(CloudFileClient fileClient)
{
    if (fileClient == null)
    {
        throw new ArgumentNullException(nameof(fileClient));
    }

    // Get a reference to the file share we created previously.
    CloudFileShare share = fileClient.GetShareReference(ShareName);

    // Ensure that the share exists.
    if (share.Exists())
    {
        // Get a reference to the root directory for the share.
        CloudFileDirectory rootDir = share.GetRootDirectoryReference();

        // Get a reference to the directory we created previously.
        CloudFileDirectory sampleDir = rootDir.GetDirectoryReference(DirectoryName);

        // Ensure that the directory exists.
        if (sampleDir.Exists())
        {
            // Get a reference to the file we created previously.
            CloudFile file = sampleDir.GetFileReference(FileName);

            // Ensure that the file exists.
            if (file.Exists())
            {
                // Write the contents of the file to the console window.
                Console.WriteLine(file.DownloadTextAsync().Result);
            }
        }
    }
}
```

</details>

☝️ That is _literally_ a copy/paste of the MSDN sample docs code. The only exception is that the `CloudFileClient` instance is passed in. So we can pass in either:
- A real instance, that hit the interwebs.
- A mocked instance ✨ 💖 

<details>
<summary>

(Click to expand) **The real code that hits Azure for real, yo!**</summary>

```
[Fact]
public void IntegrationTest()
{
    // Parse the connection string and return a reference to the storage account.
    CloudStorageAccount storageAccount = CloudStorageAccount.Parse(...snipsnipsnipsnip....");

    // Create a CloudFileClient object for credentialed access to File storage.
    CloudFileClient fileClient = storageAccount.CreateCloudFileClient();
    DoSampleTest(fileClient);
}
```

</details>

<details>
<summary>

(Click to expand) **Finally - the mocked version**</summary>

```
[Fact]
public void Test2()
{
    var file = new Mock<CloudFile>();
    file.Setup(x => x.Exists(null, null))
        .Returns(true);
    file.Setup(x => x.DownloadTextAsync())
        .ReturnsAsync("some file content");

    var sampleDir = new Mock<CloudFileDirectory>();
    sampleDir.Setup(x => x.Exists(null, null))
                .Returns(true);
    sampleDir.Setup(x => x.GetFileReference(FileName))
                .Returns(file.Object);

    var rootDir = new Mock<CloudFileDirectory>();
    rootDir.Setup(x => x.GetDirectoryReference(DirectoryName))
            .Returns(sampleDir.Object);

    var share = new Mock<CloudFileShare>();
    share.Setup(x => x.Exists(null, null))
            .Returns(true);
    share.Setup(x => x.GetRootDirectoryReference())
            .Returns(rootDir.Object);

    var fileClient = new Mock<CloudFileClient>();
    fileClient.Setup(x => x.GetShareReference(ShareName))
                .Returns(share.Object);

    DoSampleTest(fileClient.Object);
}
```

</details>

So nothing crazy wazzy pants at all.

But because of the non-virtual methods, The mock code fails at run-time.

For example:

```
// Get a reference to the file share we created previously.
CloudFileShare share = fileClient.GetShareReference("logs");
```

The `GetShareReference` method on a `CloudFileClient` isn't virtual, so I can't mock that. So, is there some trick so it can return a fake reference without having to really go off an hit the internet?

Next is this one..

```
// Get a reference to the root directory for the share.
CloudFileDirectory rootDir = share.GetRootDirectoryReference();
```

So this is a reference to the root Share directory. Again, this method is not `virtual` :/ Again, is there some trick here that it doesn't need to be `virtual` BUT also shouldn't hit the interwebs...

So yeah .. any idea's folks?

Or am I just using the SDK incorrectly and failed to find the write samples/docs, about this?

**Comment by jofriedm-msft** [comment]
Hi @PureKrome, as mentioned in #318 we are planning on turning all Get*Reference methods to virtual. This should come in the 8.0 release.

**Comment by PureKrome** [comment]
hi @jofriedm-msft :) Thanks heaps for the prompt reply.

This is great news, indeed!!!

Question: If adding a `virtual` to those `Get*Reference` methods is going to occur in release `8.0` then does this mean that adding a `virtual` is considered a *breaking change*? I thought adding a `virtual` isn't a breaking change but an additive change. Things like API methods being removed/renamed/signatures modified are breaking (for example).

If this isn't a breaking change (and I'm also assuming you're following SEMVER) then could it be slipped into a minor change like a 7.3 instead ?

I'm not trying to be a meanie - just asking an honest question :)

**Comment by pemari-msft** [comment]
Hi @PureKrome !

2 things:
1) Perhaps it's not a breaking change, but changing signatures in such a way seems safer in a major version change from our vantage point. Perhaps it's overly cautious, but some of our customers need binary compatibility between versions and generally are sensitive to changes that might not be "breaking" by the letter of the law.
2) Luckily, 8.0 is our next scheduled release :) So hopefully this is okay?

**Comment by PureKrome** [comment]
1) Ah! binary - I didn't think of that (out of sight, out of mind, etc..) - gotcha
2) Oh totally dude! Totally ok!

Would love:
- Some tags added to some issues/PR's for M8. This helps me/us get some transparency over the next release 🙏 
- A *rough and conservative* date for M8 added to that milestone, plz?

and some token love ...

[](http://i.giphy.com/KvGkTDzBnY03m.gif)

**Comment by PureKrome** [comment]
Another question related to this...

I'm trying to do a simple MOVE of a file. So i'll COPY it then DELETE the original. Great! So this means I would do something like this..

`CloudFile sourceFile = sampleDir.GetFileReference("someFile.txt");`

That's ok - but now I need to access the `CloudFile` `Name` property .. but that's always `""`. But this is a mock, so who cares .. i can just mock that property ... but .. that property is not `virtual` :(

Reason: give a `CloudFile`, I need to make sure all the subdirectories exist _before_ I can move the file. I was using the `Name` field to get this data and then check/create each directory.

So could those properties on a `CloudFile` _also_ be considered to be made virtual, too?
