### ISSUE TITLE
CloudFileDirectory 404 on Creating of directory

### ISSUE THREAD

**Issue by boomtopper** [Azure/azure-storage-net#351]
``` vb
Sub Main()
        Dim storageAccount As CloudStorageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("StorageConnectionString"))
        Dim fileclient As CloudFileClient = storageAccount.CreateCloudFileClient()
        Dim share As CloudFileShare = fileclient.GetShareReference("vault")

        Dim rootdir As CloudFileDirectory = share.GetRootDirectoryReference()
        'Dim dir = rootdir.GetDirectoryReference("testing")
        Dim dir = rootdir.GetDirectoryReference("testing/spam1/spam2/spam3")

        dir.CreateIfNotExists()
    End Sub
```

I am using Azure File storage SDK and I am trying to create multiple levels of a directory in one step but it gives me a 404 error with the above code. If I just use "testing" it works but that would mean I would have to create each of the folder sections one by one?

Thanks

**Comment by rambo-msft** [comment]
Hi @boomtopper,
Yes. Initially, you have to create each directory individually. However, `GetDirectoryReference` does support references to multi-level directories so long as the parent directories exist.
i.e., calling `CreateIfNotExists` with `GetDirectoryReference("testing/spam1/spam2/spam3")` would succeed  if
`testing` / `spam1` / `spam2` were already created.

**Comment by pemari-msft** [comment]
Closing for nonresponse. Please let us know if you see further issues!

**Comment by sonlichao** [comment]
I have the same issue., when using CloudFileDirectory CreateIfNotExistsAsync.
If the fold is not exists, AppInsights will catch the 404 exception, but No any exception throws from  CreateIfNotExistsAsync.

**Comment by derekrivers** [comment]
Feels quite hacky and impractical to have to create folder structures this way.

**Comment by TheConservativeCoder** [comment]
@derekrivers  agreed would be really nice if they were able to fix this rather then work around it.

**Comment by afkhan517** [comment]
please help on this.cannot use foreach always for creating nested or sub directories

**Comment by salsolatragus** [comment]
It kinda defeats the purpose of `CreateIfNotExists()` if I have to check for `Parent.Exists()` (recusively) before I can call `CreateIfNotExists()`. If I have to check whether the folder exists anyways, I might as well just `Create()` it... or am I missing something?

**Comment by jnawk** [comment]
Even if the underlying API / back end can't do this atomically, that's no reason the SDK shouldn't be able to.  How about listening to your users?
