### ISSUE TITLE
GetServicePropertiesAsync call fails for Premium Storage Accounts

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-storage-net#354]
Returns a 400 Bad Request with ErrorCode 'InvalidQueryParameterValue' and ErrorMessage 'Value for one of the query parameters specified in the request URI is invalid.'

**Comment by pemari-msft** [comment]
GetServiceProperties is not supported on premium accounts. What service property are you trying to set?

**Comment by mamaso** [comment]
We use GetServiceProperties to validate that the storage account exists as well as enable blob logging (which I assume is not possible for premium account).

**Comment by mamaso** [comment]
Is it possible to get a more descriptive error message, or even better, an api along these lines? https://github.com/Azure/azure-storage-net/issues/355

**Comment by pemari-msft** [comment]
No, logging is not available for premium. Disk logging from the VM side is used for this case. But yes, as in the other response, we will look to make an API for that.
