### ISSUE TITLE
SDK method to determine storage account type

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-storage-net#355]
A method to determine whether an account is general purpose / blob only / premium storage would be useful, currently our account validation logic has to make sdk calls to the blob endpoint, queue endpoint, etc to determine what type of account we are using and what features it supports.

**Comment by pemari-msft** [comment]
This isn't a client library feature, but it would be a good new API for the service (which the client can then support). We have this in our backlog and it is something we will look to provide in the future. Thanks for your suggestion!
