### ISSUE TITLE
Feature request: Custom encryption implementation

### ISSUE THREAD

**Issue by thezero** [Azure/azure-storage-net#356]
Hi,
we'd like to encrypt some parts of our data, however internal SDK encryption doesn't meet our encryption policy (specifically: library doesn’t provide data integrity/authentication). We already have a library that does compliant encryption for us, so we just need to join those two together.

Unfortunately it's not very easy ATM - all the EncryptionPolicy objects ([1](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Blob/BlobEncryptionPolicy.cs), [2](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/QueueEncryptionPolicy.cs), [3](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Table/TableEncryptionPolicy.cs)) are referenced directly from *RequestOptions classes and have `internal` methods or are even `sealed`.

It would be great if we could simply specify `IEncryptionPolicy` (or at least `IQueueEncryptionPolicy` etc.) with simple methods `Encrypt` and `Decrypt`. This means also removing encryption logic from `TableOperationHttpResponseParsers` and moving it directly to the new implementation.

**Comment by thezero** [comment]
(I can start a PR, just wanted to avoid unnecessary work as per [Don't push your pull requests](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/))

**Comment by pemari-msft** [comment]
Hi @thezero ,

Can you clarify how our already existing encryption work doesn't fit your specifications? Can you explain more your scenario? We have pretty rigid guidelines when it comes to what we can allow in a Microsoft library re: encryption, so there would be some hurdles to jump here. Thanks!

**Comment by thezero** [comment]
Hi @pemari-msft ,
SDK now supports AES_CBC_256. I want to use AES-256-CBC-HMAC-SHA256 (or, you know, any algorithm that is in my requirement). HTTPS doesn't ensure data don't get modified inside the storage should someone get access to it.

**Comment by sdrapkin** [comment]
@pemari-msft MS approach to client-side encryption in Azure Storage is somewhere between ignorance and incompetence. @GrabYourPitchforks is probably your best MS resource, but let me explain the problem anyway.

Why is client-side encryption useful? What value does it provide, and what threats does it deter?

1. "encryption-at-rest", which is often a regulatory requirement (server-side encryption achieves it as well)
2. Defense against lack or lapses in confidentiality of Azure storage or/and Azure transit (HTTPS/TLS)
3. Defense against lack or lapses in **integrity** of Azure storage

Azure Storage [security guide](https://github.com/Azure/azure-content/blob/master/articles/storage/storage-security-guide.md) makes it clear that data **integrity** is of utmost concern, just like data confidentiality is. At the same time, client-side verification if data integrity is not "checking that the MD5 hash of the data matches its MD5 metadata" (which provides no integrity guarantees even with a non-broken hash alg), and it's not "relying on TLS to guarantee that the Azure-tampered data reaches the client with full in-transit integrity".

Saying "but isn't TLS enough?" when discussing client-side encryption is sheer ignorance of why client-side encryption is needed to begin with.

What really takes the cake, though, is that MS has shipped client-side encryption without client-side integrity validation. That shows incompetence, which no amount of "we have plans to implement AES-GCM [at some point in the future](https://github.com/Azure/azure-storage-net/issues/131)" can justify.

You don't need AES-GCM to provide client-side integrity validation &ndash; EtM with AES and HMAC-SHA2 will work on every platform.

It's not not a "custom" client-side encryption implementation that Azure Storage needs, but a **proper** and **secure** one.

**Comment by pemari-msft** [comment]
@sdrapkin, your comment has been removed for violating the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Please refrain from such attacks in the future.

**Comment by seanmcc-msft** [comment]
If this is a hard requirement, please consider encrypting your data before upload.
