### ISSUE TITLE
TableOperation expose Entity?

### ISSUE THREAD

**Issue by turowicz** [Azure/azure-storage-net#358]
Any reason we can't have Entity in a table operation available publicly? I'm writing an IndexTable that inherits CloudTable and the idea is that on each operation it will generate index entities and put them in extra tables (index table pattern). After that a ViewTable will extend the IndexTable to save full data (materialized view pattern).

**Comment by erezvani1529** [comment]
Hi @turowicz,

This change is part of our [8.0 release milestone ](https://github.com/Azure/azure-storage-net/milestone/1)which is our next planned release. We will update this thread along with other related feature requests once the 8.0 package is released.

Thanks :)

**Comment by erezvani1529** [comment]
Hi @turowicz,

Closing this issue with the change included in latest published package on nuget [v8.0.0](https://www.nuget.org/packages/WindowsAzure.Storage/) 

Thanks!
