### ISSUE TITLE
CloudBlockBlob.Uri returns an unescaped uri

### ISSUE THREAD

**Issue by lsarni** [Azure/azure-storage-net#359]
Version 7.0.0.0

If a blob name has spaces the Uri that this method returns is something like this:
https://g.blob.core.windows.net/mycontainer/image space.jpg

Instead of:
https://g.blob.core.windows.net/mycontainer/image%20space.jpg

The one made for [java](https://github.com/Azure/azure-storage-java) returns the second uri.

**Comment by pemari-msft** [comment]
The difference here is due to the System.Uri class in .NET having a different underlying implementation than the java.net.uri class.

Does the blob reference work correctly? Are you able to make a request to that blob?

**Comment by lsarni** [comment]
It works in some cases, but it gives me some problems in other but mostly because of what I'm going with it.
Since the difference is due to the NET class I could just encode it myself and close this issue.
Thanks!
