### ISSUE TITLE
Move DisablePropertyResolverCache to TableRequestOptions and make it non static

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#361]

**Comment by erezvani1529** [comment]
Hi @IlyaGrebnov,

Would you please share more information about your scenario to clarify what sort of improvement you are targeting with the proposed change?

Thanks!

**Comment by IlyaGrebnov** [comment]
I am working on client library, so disabling property resolver cache for entire process feels wrong, so I want to disable it for just types I expose. Note, I want to disable resolver cache for performance reasons since current version depends on concurrent dictionary and I could do better with just dictionary.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
