### ISSUE TITLE
AsyncStreamCopier should use IBufferManager

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#362]

**Comment by IlyaGrebnov** [comment]
Attaching image to illustrate the problem. Also opened #374 for second allocation as well.
![image](https://cloud.githubusercontent.com/assets/773346/21285003/2eecafa2-c3e1-11e6-95b5-3b2809f2f799.png)

**Comment by erezvani1529** [comment]
Hi @IlyaGrebnov ,

The latest v9.1 package includes enhancements to use IBufferManager in AsyncStreamCopier. Please do not hesitate to open a new issue if you see any other points of enhancements. Thanks!

Thanks!
