### ISSUE TITLE
Have an option to generate Service SAS and use it instead of per requst HMAC

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#365]
Storage now support service level SAS. Using this service level SAS is more performance since it could be computed once (and periodically refreshed) instead of per-request HMAC computations. 

My suggestion is to have an option when creating CloudClient{Table/Qeuue/..} reference to use this pattern.

**Comment by mirobers** [comment]
We have considered this enhancement, but we have decided against taking it. This would be some behind-the-scenes magic that is more straightforward to implement at the application layer. Better yet, the application could be written to not handle the account key at all -- this provides the best security and performance of all.
