### ISSUE TITLE
Cannot start the storage emulator

### ISSUE THREAD

**Issue by asipras** [Azure/azure-storage-net#370]
I am able to successfully initialize the storage emulator. However when I try to start the emulator it gives me the following exception,
Unhandled Exception: System.TimeoutException: Unable to open wait handle.
   at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.InternalWaitForStorageEmulator(Int32 timeoutInMilliseconds)
   at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.EnsureRunning(Int32 timeoutInMilliseconds)
   at Microsoft.WindowsAzure.Storage.Emulator.Commands.StartCommand.RunCommand()
   at Microsoft.WindowsAzure.Storage.Emulator.Program.Main(String[] args)

I tried to see the eventlogs on my machine and found the following Application Error

Faulting application name: AzureStorageEmulator.exe, version: 4.5.6891.0, time stamp: 0x57731cb1
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process id: 0x37fc
Faulting application start time: 0x01d2519669396619
Faulting application path: C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: eb0ec992-7b39-410e-a3a9-b43ad736a512
Faulting package full name: 
Faulting package-relative application ID: 

I also tried to start the emaulator with -inprocess parameter but i get this following message
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe start -inprocess
Windows Azure Storage Emulator 4.5.0.0 command line tool
Service Status: Blob http://127.0.0.1:10000/ False
The network location cannot be reached. For information about network troubleshooting, see Windows Help
Error: Unable to start the storage emulator.

I also turned on the logging for the storage emulator and found this message inside the log file

12/8/2016 2:31:02 PM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found
12/8/2016 2:31:02 PM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Hit Exception while reading Nephos.MaskClientIPAddressesInLogs setting from ACS: System.Exception: Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetConfigSetting[T](IServiceEntrySink serviceEntrySink, String configParam, String configDescription)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetIPAddressMaskSetting(IServiceEntrySink sink)
12/8/2016 2:31:02 PM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The network location cannot be reached. For information about network troubleshooting, see Windows Help
12/8/2016 2:31:02 PM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The network location cannot be reached. For information about network troubleshooting, see Windows Help

I have run the netstat to make sure none of the ports are being blocked.

Thanks,

**Comment by BellaCode** [comment]
+1 Exact same problem for me too.

**Comment by mirobers** [comment]
Sorry for the delay. It seems that the emulator can't listen on its ports. The error logs are expected except for the last two. Can you try resetting the loopback adapter? Does the issue persist across machine reboot?

**Comment by asipras** [comment]
Yes, the issue still exists even after restart @mirobers.  I tried installing and reinstalling the storage emulator but that did not help either. How do I reset the loopback adapter?

I can ping the the local host ip (127.0.0.1) successfully. I am attaching the list of network adapters on my machine. Let me know if you need more information.

![capture](https://cloud.githubusercontent.com/assets/16964799/21183696/bb725a90-c1ce-11e6-9f0c-bc53d0f4fe72.PNG)

**Comment by mirobers** [comment]
It has been reported that a firewall misconfiguration can cause this. Could you experiment by disabling the firewall and trying to launch the emulator again? In particular, rules preventing access to 127.0.0.1 would be an issue.

**Comment by asipras** [comment]
There is no firewall configured on my machine @mirobers. Like I said if I ping from command prompt i get reply
![capture](https://cloud.githubusercontent.com/assets/16964799/21407935/aa929ab8-c797-11e6-98a0-c9d0a7dd2e90.PNG)

It will be great if you can guide me through this.

Thanks

**Comment by asipras** [comment]
Hi,

I was able to resolve this issue. There was no firewall on my machine but I had IIS installed and running on my local computer. As soon as I stopped the IIS, the emulator started successfully.

Thanks for your help.

**Comment by mirobers** [comment]
Thanks for following up! @BellaCode does this resolve your issue as well?

**Comment by NichUK** [comment]
I'm currently getting this problem on a WIndows 10 machine. I've installed the Azure SDK and version 4.6 of the storage emulator. I've used netstat to ensure nothing has taken the ports, and my firewall and anti-virus softwares are both switched off, as is IIS (no inetinfo process running), but yet I get:

```
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>azurestorageemulator start
Windows Azure Storage Emulator 4.6.0.0 command line tool

Unhandled Exception: System.TimeoutException: Unable to open wait handle.
   at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.InternalWaitForStorageEmulator(Int32 timeoutInMilliseconds)
   at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.EnsureRunning(Int32 timeoutInMilliseconds)
   at Microsoft.WindowsAzure.Storage.Emulator.Commands.StartCommand.RunCommand()
   at Microsoft.WindowsAzure.Storage.Emulator.Program.Main(String[] args)

```

In the error log I get:
```
2/6/2017 3:48:53 AM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found
2/6/2017 3:48:53 AM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Hit Exception while reading Nephos.MaskClientIPAddressesInLogs setting from ACS: System.Exception: Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetConfigSetting[T](IServiceEntrySink serviceEntrySink, String configParam, String configDescription)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetIPAddressMaskSetting(IServiceEntrySink sink)
2/6/2017 3:48:53 AM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The network location cannot be reached. For information about network troubleshooting, see Windows Help
2/6/2017 3:48:53 AM [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The network location cannot be reached. For information about network troubleshooting, see Windows Help

```

interestingly, in the info_debug log I also get:

```
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] Loading config Param NephosAllowPathStyleUris (Allow path-style URIs) read: true
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] Successfully loaded NephosAllowPathStyleUris: True
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] Loading config Param NephosIncludeInternalDetailsInErrorResponses (Include internal details in error responses) read: false
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] Successfully loaded NephosIncludeInternalDetailsInErrorResponses: False
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] Loading config Param StampName (Stamp Name) read: StorageEmulator
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] BlockBlob: Load Interval failed. IsGC: True, Exception    at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlockBlobGarbageCollector.GetTimerIntervalOrDefault(Boolean isGC)
2/6/2017 3:48:53 AM [Info_debug] [ActivityId=00000000-0000-0000-0000-000000000000] BlockBlob: Load Interval failed. IsGC: False, Exception    at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlockBlobGarbageCollector.GetTimerIntervalOrDefault(Boolean isGC)

```

with two exceptions at the same time as the network errors. I cannot work out what's going on, and would be most grateful for any assistance anyone can offer.

**Comment by mirobers** [comment]
Something is preventing the emulator from listening on the ports. Have you tried listening on the ports yourself to see what goes wrong?

**Comment by NichUK** [comment]
What was interesting was I then tried changing the ports to 30000, 30001, 30002 (which netstat tells me are also free ports) and still got the same error. 
I've just used Netcat to set up a listener on port 10000
`nc -l -p 10000 -t -G 4 localhost`
and telnetted in to that with no problems. It echos chars to stdout no problem.
So there's obviously something that's stopping just AzureStorageEmulator from setting up the listener.
Also, I've tried running it as Administrator, just in case there was a strange permissions problem going on. Still no joy.

**Comment by athoscouto** [comment]
Just had the same problem, couldn't make Azure Storage Emulator start on any port.
I also noticed that I couldn't access some local servers using http://127.0.0.1:{port_number}. But I was able to access them with http://localhost:{port_number}.
**Making it short**: I solved my problem replacing 127.0.0.1 with localhost at AzureStorageEmulator.exe.config file.

**Comment by NichUK** [comment]
OK. I confess... I am absolutely flabbergasted. @athoscouto that totally did the trick! Weird, because I haven't noticed any other problems with local websites, although I suppose I normally use `localhost` rather than `127.0.0.1` anyway.
@mirobers My problem is sorted, but you may want to take that one on board for future reference,
Thanks Athos!

**Comment by athoscouto** [comment]
No problem at all. If you're having similar problems with other applications, you'd rather use the command:
`netsh http add iplisten 127.0.0.1`
As described [here](http://stackoverflow.com/questions/34543443/cant-access-127-0-0-1).

**Comment by NichUK** [comment]
Of course (for anyone finding this conversation afterwards) the corollary to this is that the standard shortcut `UseDevelopmentStorage=true` as a connection string value, won't work as it seems to use `127.0.0.1` internally, so I will have to use the full version:
`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;
AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
BlobEndpoint=http://localhost:10000/devstoreaccount1;
TableEndpoint=http://localhost:10002/devstoreaccount1;
QueueEndpoint=http://localhost:10001/devstoreaccount1;`

**Comment by mirobers** [comment]
Great investigation! @NichUK can you try the netsh command above? It seems a much simpler solution than modifying the endpoints to localhost. We'll look into making this automatic.

**Comment by NichUK** [comment]
@mirobers  I can confirm that running
`netsh http add iplisten 127.0.0.1`
from an elevated command prompt does the job!

**Comment by sanme98** [comment]
Please make sure you're not inside VPN also, inside certain VPN will cause the storage emulator unable to start, at least for my case.
