### ISSUE TITLE
Better error messages for debugging.

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [Azure/azure-storage-net#371]
When an exception is thrown due to success code outside the 2xx range, the exception has a generic message "The remote server returned an error: {StatusCode} {StatusMessage}".

However if we see the response payload there is some more information, for instance:

{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"One of the request inputs is not valid.\nRequestId:XXXXXXXXXX\nTime:XXXXXXXXXXXXXXXXXXXXXX"}}}.

I think it would be very useful to have these error messages in the exception, instead of relying in traffic interception to debug a problem.

**Comment by pemari-msft** [comment]
All of these things are contained within the StorageException.RequestInformation.ExtendedErrorInfo.

**Comment by rambo-msft** [comment]
@TiagoOliveiraMarques 
Also, for our upcoming release, we have included the `ExtendedErrorInfo` as part of the exception ToString() message  (so it will pop up organically).
