### ISSUE TITLE
Nuget package 8.0.0 and Storage emulator version 4.6

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#384]
I have upgraded the nuget package referenced in my solution to 8.0.0 but my code which runs against the local emulator is no longer working. I am getting the following exception: ``. This tells me that Storage nuget package requires a more recent version of the emulator.  I have confirmed that by taking the following steps:

1. using Fiddler, I was able to capture the http requests and noticed the `x-ms-version: 2016-05-31` header
2. I also confirmed that `2016-05-31` is the [version used by storage library 8.0.0](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/protocol-version-support-for-.net-client-library-versions)
3. Fiddler also allowed me to verify the error returned by the emulator: 
```
<Error><Code>VersionNotSupportedByEmulator</Code><Message>The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=392237
RequestId:551c3fe5-0cd4-4c50-a56c-1c9803f10390
Time:2016-12-28T21:22:12.2780775Z</Message><VersionAttempted>2016-05-31</VersionAttempted></Error>
```
4. I searched "Apps and Features" and found that Emulator version 4.5 is currently installed on my laptop
5. Finally, [this page on Microsoft's web site](https://docs.microsoft.com/en-us/azure/storage/storage-use-emulator) confirmed that Emulator 4.6 is necessary for `x-mx-version: 2016-05-31`

With this information, I ran the Web Platform Installer but it told me that I already have the latest SDK and therefore, there's nothing to upgrade. I went as far as uninstalling the emulator currently on my laptop and running the Web Platform Installer again; it detected the missing emulator and re-installed it but, once again, it installed 4.5

So my question is: is there a separate download for emulator 4.6 and ff so, where can I find it? Otherwise, how can I upgrade the emulator?

**Comment by Jericho** [comment]
Never mind: I found a link to [download the emulator](https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409).

**Comment by mirobers** [comment]
Thanks for reporting this. We're working on updating the Web Platform Installer with emulator 4.6 as well.
