### ISSUE TITLE
Storage Emulator in Container

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-storage-net#399]
Hello guys!

Now that we have (at least with the `import` hack) .Net Core support for Storage libs, many people from non-windows dev machines need to run Storage Emulator.

Is there any plans on getting the storage simulator to run xplat? It would be good if instead of a windows service, it run as a standalone exe so people can use it on Docker containers on either Windows or Linux.

Thanks!

**Comment by mirobers** [comment]
Hi, thanks for your interest. We'd definitely like to offer a cross-platform emulator and this is something we're currently evaluating. However, we have no timeline to share at the moment.

**Comment by xt0rted** [comment]
I'm on windows so this doesn't effect me too much, but I'd definitely like to see something similar for service bus. Moving from storage queues to service bus queues/topics for somethings has been painful when it comes to being fully offline.

**Comment by galvesribeiro** [comment]
I'm on windows too but even there, having to install tons of dev tooling is something annoying and hard to reproduce when some fail happen.

For example, since MS released SQL express in a container, even on windows, I dont want to install it anymore on my machine. All I do is docker run and thats all.

It also enhance the unit testingg and CI experience of all projects.

I think this could be a community-driven effort. The stora simulator code isnt that complicated if you look at it with ILSpy.

**Comment by xt0rted** [comment]
After thinking about this some more I was wondering if azure pack as a docker container could work? I tried setting that up for local development a couple times and ultimately failed and gave up. Having a preconfigured starting point with azure pack seems like it could be a great replacement for the emulators since you don't have to worry about feature parity.

**Comment by galvesribeiro** [comment]
@xt0rted Azure pack requires WAY too big infrastructure, RAM, etc... Would be an overkill IMHO...

A simple docker image running on Nanoserver (windows containers) or Alpine (linux containers) would have a very small footprint and low friction for people to use.

**Comment by grahamehorner** [comment]
Maybe it would be good to implement services using ServiceFabric that would scale and allow deployments on other cloud platform public, private or hybrid windows, Linux and/docker

**Comment by arafato** [comment]
Have a look at https://github.com/arafato/azurite which is a cross-platform storage emulator (blob storage only) written in NodeJS. Still early phase but already used by some companies.

**Comment by galvesribeiro** [comment]
WOW! THat looks great!

I was writing one myself @arafato but this time in .net core :)

**Comment by richardthombs** [comment]
I wrote this post on how to get the storage emulator to work in a stand-alone container. You'll need a Windows container for it though, obviously.

http://agilesnowball.com/azure/docker/2017/05/15/azure-storage-emulator-in-docker.html

**Comment by galvesribeiro** [comment]
Nice @richardthombs !

However, MSFT must provide a proper container for it. And be xplat. It is just a .Net app and a sql local for storage...

**Comment by alexsandro-xpt** [comment]
+1

**Comment by galvesribeiro** [comment]
One year past... Any word from MSFT?

**Comment by mirobers** [comment]
Please take a look at [Azurite](https://github.com/arafato/azurite) and let me know what you think. This is actually mentioned in the [official documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#get-the-storage-emulator).

**Comment by galvesribeiro** [comment]
@mirobers yeah, I follow that... But the progress is very slow. 1 year and still no Table API... I know it is a OSS project, but still not the same as the MSFT provided one. 

Anyway, thanks for the reply. If after one year this wasn't made a priority somehow, I guess we will never see it come from MSFT.

**Comment by arafato** [comment]
Author of Azurite here: we prioritize strictly depending on the feedback of our users. Support for Table API has never really been raised so far. Happy to prioritize, expect a working version within the next 5 weeks.


Von: Gutemberg Ribeiro
Gesendet: Samstag, 6. Januar, 01:30
Betreff: Re: [Azure/azure-storage-net] Storage Emulator in Container (#399)
An: Azure/azure-storage-net
Cc: Oliver Arafat, Mention


@<https://github.com/mirobers>mirobers<https://github.com/mirobers> yeah, I follow that... But the progress is very slow. 1 year and still no Table API... I know it is a OSS project, but still not the same as the MSFT provided one.
Anyway, thanks for the reply. If after one year this wasn't made a priority somehow, I guess we will never see it come from MSFT.
