### ISSUE TITLE
CloudBlockBlob.UploadFromStream reads file twice

### ISSUE THREAD

**Issue by vhe1** [Azure/azure-storage-net#400]
This happens whenever StoreBlobContentMD5 is not set to false.

Apparently the CloudBlockBlob object reads the whole file

- once  just for the checksum calculation
- and then again, for the upload.

I have a 230GB file to upload regularly and this consumes a non-trivial amount of time.

Theoretically it should not be necessary to read the file twice, since those hash calculations can be made with each block between when it's been read and when it's uploaded.

I've attached a code example that shows how that calculation can be done in parallel to a copy process.
[Program.cs.txt](https://github.com/Azure/azure-storage-net/files/736413/Program.cs.txt)

**Comment by pemari-msft** [comment]
What platform are you targeting?

**Comment by vhe1** [comment]
For now it's .net 4.6.1.

**Comment by pemari-msft** [comment]
What version of the library are you using? CoreCLR didn't have an implementation of IncrementalHash originally which is why this behavior was done. In Version 8.0 of our library, we do use IncrementalHash for CoreCLR. However, the Xamarin support for this is still not there, causing a regression for Xamarin customers. 

If you target version 8.0 of the library you should get the behavior you expect.

**Comment by vhe1** [comment]
I'm doing a windows desktop application (console app). (VS 2015)
The library is WindowsAzureStorage 8.0.1.

**Comment by vhe1** [comment]
Same behaviot with 8.0.0.

**Comment by vhe1** [comment]
(will to a small example solution to sow the problem and attach it as zip.)

**Comment by vhe1** [comment]
This is the example solution.
You will need to restore the packages.
[BlobUploadProblem.zip](https://github.com/Azure/azure-storage-net/files/736483/BlobUploadProblem.zip)
You can see that the number sequence shows up twice.

**Comment by pemari-msft** [comment]
So there is a bug in the small blob case (<128MB case) that we've found that causes the stream to be read twice instead of buffering. It's actually the case that large streams (230GB) and small streams (1<<19b) are vastly different codepaths. Are you sure you're seeing the same behavior on your large stream? 

What kind of stream are you passing into UploadFromStream? A 230GB filestream?

**Comment by vhe1** [comment]
I have seen it on a 28GB stream. I have not checked it on the 230 GB stream yet.

**Comment by vhe1** [comment]
(I'm uploading 3 database backups: 100MB, 28GB, 230GB. Saw the behavior on the first 2 files, didn't wait for the last one to finish.)

**Comment by pemari-msft** [comment]
Okay, we're running your test app on a bigger file to try to determine what's happening. Will update.

**Comment by vhe1** [comment]
:-)

**Comment by vhe1** [comment]
Btw, async/sync doesn't seem to make a difference.

**Comment by pemari-msft** [comment]
So we were only able to repro on the small blob case, even with your repro app :( I'm not sure what's causing the latency for large blobs (28GB++) but it doesn't seem to be reading the stream twice. Can you provide any more info to help us track it down?

**Comment by pemari-msft** [comment]
In the multi-part upload case (ie when the size of the data exceeds `BlobRequestOptions.SingleBlobUploadThresholdInBytes`, which is by default 128MB starting in version 8.0).

In the case of the one-shot upload (<128MB) we also revert back to buffering if the stream passed in is not seekable.

**Comment by vhe1** [comment]
Ok. I'll try again with the 128G upload. Will take a while, so I'll upload code and output tomorrow.

**Comment by vhe1** [comment]
Egg in my face...
Can't reproduce. It looks as if I got confused between the messages of all the files I uploaded in one go. :-(
On the other hand, I'm happy that the code works. :-)

Thank you a whole lot for your patience and for bothering!

**Comment by pemari-msft** [comment]
No problem at all! Glad to hear it's working as expected now.
