### ISSUE TITLE
SetMetadata Throws Exception if Blob has No Content

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-storage-net#401]
I have an application where I store metadata in the "virtual" directories I create within a blob storage account (and yes, I should probably be using the SMB/file storage system, but bear with me; this is a legacy situation, sort of).

I've discovered if I do this:

```
var _cloudMetadata = Container.GetBlockBlobReference( $"{Path}{FolderInfoBlobName}" );
// load stuff into metadata collection
_cloudMetadata.SetMetadata();
```
I get a StorageException complaining that the blob doesn't exist.

But if I do this:

```
var _cloudMetadata = Container.GetBlockBlobReference( $"{Path}{FolderInfoBlobName}" );
_cloudMetadata.UploadText("This is a placeholder blob, for storing metadata about the folder in which it exists");
// load stuff into metadata collection
_cloudMetadata.SetMetadata();
```

Everything's fine.

It's not a big deal to work around the issue by storing some dummy data in the blob. 

But, to me at least, it's counter-intuitive that I can't store metadata in a "valid" CloudBlockBlob until I fill it with something. It seems like the act of calling SetMetadata() ought to bring an empty blob into existence.

**Comment by pemari-msft** [comment]
It's not that the blob needs to have content, but the blob must exist on the back end storage service to save associated metadata to that location. This is a requirement of the service, which is why the client library works in the same way. If you did a put blob with empty content (replacing your text with String.Empty for instance), I would expect it to also work.

**Comment by markolbert** [comment]
Yes, I understand that...now. But my point is different: declaring metadata for an object ought to cause the back end storage service to do whatever it needs to to bring the object into existence so the metadata can be stored. Put another way, why should it matter whether I create an empty object or an object with content? Either way, I want to create an object.
