### ISSUE TITLE
Add option to create StorageCredentials with account name and sasToken

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#402]
We have telemetry code which traces account.Credentials.AccountName and we want to replace storage account shared keys with short-lived storage account SASes. This works fine except traces are now reporting null due to missing account name. And the problem is account name setter is private. So could you please ether add new constructor(problematic due to another (string, string) ctor) or make AccountName settable.

**Comment by pemari-msft** [comment]
This is used by us internally, so exposing it would cause bugs.
