### ISSUE TITLE
CloudQueue.CreateIfNotExistsAsync overload that takes a cancellation token was removed

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-storage-net#405]
We just upgraded to the latest version and it appears that the overload that took just a cancellation toke was removed. Can this be added back or was there a good reason it was removed?

**Comment by xclientdev-msft** [comment]
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L296

What platform are you targeting?

**Comment by pemari-msft** [comment]
https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Queue/CloudQueue.cs#L296

What platform are you targeting?

**Comment by niemyjski** [comment]
Looks like this also affects CloudBlob.DeleteIfExistsAsync

**Comment by pemari-msft** [comment]
Again, these are still present -- can you clarify if you changed your project type or at least how your project is created? It's possible you're interacting with our façade or something similar, but they weren't removed :)

**Comment by niemyjski** [comment]
I'm not seeing them in the source code, and I'm getting build errors when targeting net standard 1.5

**Comment by pemari-msft** [comment]
/cc @erezvani1529 .

These weren't removed. You're targeting a new dll it seems. Adding Elham to comment further.

**Comment by erezvani1529** [comment]
Hi @niemyjski,

Would you please share your upgrade story? were you targeting netstandard before or are you changing your target to netstandard from desktop? 

Thanks!

**Comment by niemyjski** [comment]
I'm upgrading foundatio (https://github.com/exceptionless/foundatio/tree/feature/dotnet) to use the new csproj on the .net branch and I'm not seeing any of these overloads when targeting .netstandard 1.5

**Comment by niemyjski** [comment]
I get compiler errors. I'm referencing 8.1

**Comment by niemyjski** [comment]
I'm live streaming (https://www.liveedu.tv/niemyjski/) you can see the issue if you look at the past hour or so.  We were targeting it before, and upgraded from I think 7.x to 8.0.1 Builds fine on 4.5 but not net standard

**Comment by erezvani1529** [comment]
Thanks for sharing the info @niemyjski,

The overload which only takes a cancellation token has never been available for RT/Netstandard targets. So I wonder if you are trying to build a code which was written against net45 as you mentioned with a new netstandard target? (building with net45 makes sense since this specific overload has only been supported in our desktop dll).

Even if this is the case, you can instead use [this overload ](https://github.com/Azure/azure-storage-net/blob/master/Lib/WindowsRuntime/Queue/CloudQueue.cs#L116) to build for netstandard successfully.
(Also in the livestream seems like you are not updating your TF to add the required imports for AzureStorage client OData dependencies?)

Please let us know if you need any more information.
Thanks!

**Comment by niemyjski** [comment]
Why not extend this support to net standard it's general useful and a simple overload to have? It's great to have consistency and an easy to use api. 

Yeah, I tried adding the imports for odata but there were errors. **RANT** I really wonder why none of the teams haven't started yelling at the odata team for not updating there packages. It's insane they treat this as a feature, they should be dog fooding and providing a great experience over a year past release of .net core. It's unacceptable and until they get there act together, I'm just not going to support any package that uses odata (which also means I'm not going to add .net core support for this integration even though you support it due to upstream bs....

**Comment by erezvani1529** [comment]
@niemyjski,

Glad that you solved the build issue.

Some good news regarding netstandard friendly OData package:

As a result of our collaboration with CoreFx team, soon (can not be exact about the milestone but most likely by our next 8.1 release in March) we will be using a new OData package to eliminate the need to import additional TFs. We will have more updates once this package is published.

Thanks!
