### ISSUE TITLE
Add support for DeleteMessages in batch in CloudQueue

### ISSUE THREAD

**Issue by tyrotoxin** [Azure/azure-storage-net#406]
The `CloudQueue` has 2 methods: `GetMessages` and `PeekMessages`.
But `DeleteMessages` is missing, what does not allow you to write IO-efficient code.

**Comment by pemari-msft** [comment]
Hi @tyrotoxin , This API is not available on the storage service. I will share the idea with them as a feature request. Thanks for the suggestion!
