### ISSUE TITLE
How to query entities in 8.x?

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-storage-net#407]
`CloudTable.ExecuteQuery` is no longer public in 8.x, and I haven't been able to find a single sample or piece of documentation that explains how to query entities.

Previously, I could do something like this:
```
var query = new TableQuery<MyEntity>();                
foreach (var entity in table.ExecuteQuery(query))
{
...
}
```

Must also queries use `ExecuteQuerySegmentedAsync` now?

```

**Comment by erezvani1529** [comment]
Hi @cocowalla,

Which platform are you targeting?

**Comment by cocowalla** [comment]
@erezvani1529 .NET Core 1.1 / Standard 1.6 and also .NET Framework 4.6.2 (but only because Azure Web Jobs don't work with .NET Core yet!)

**Comment by erezvani1529** [comment]
Thanks for the information @cocowalla,

Please note that we maintain 2 different code bases for our CoreFx and NetFx assemblies and basically Desktop codebase is a super set of Netstandard. For instance, sync methods which are provided in desktop are not yet supported in our netcore dll (we are working closely with CoreFx team on this btw). 

The ExecuteQuery sync is still available [here ](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Table/CloudTable.cs#L276) in Desktop version however for Netstandard as you mentioned please use ` ExecuteQuerySegmentedAsync ` instead.

Thanks,
Elham

**Comment by cocowalla** [comment]
@erezvani1529 thanks, that is useful to know. It would be great if these samples and the [getting started guide](https://docs.microsoft.com/en-us/azure/storage/storage-getting-started-guide) could be updated to show correct useage from .NET Core.

**Comment by erezvani1529** [comment]
@cocowalla,

Thanks for the suggestion. Yes, we do have a plan to add separate samples for NetCore applications(I will update this thread once they are out). Meanwhile we are working on parity between two code-bases 👍 !

**Comment by raRaRa** [comment]
Is there any particular reason why the .NET Standard version doesn't support `ExecuteQuery`? The code for fetching one record with specific row and partition key is getting quite complex, especially if you have to use `ExecuteQuerySegmentedAsync`.

Thanks.

**Comment by pemari-msft** [comment]
Because of the fact that no async enumerables exist, it's not feasible to have an executequery method in an async paradigm (see #94 ).
