### ISSUE TITLE
NullReferenceException in TableBatchOperationPostProcess

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#408]
Microsoft.WindowsAzure.Storage.StorageException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableBatchOperationPostProcess(IList`1 result, TableBatchOperation batch, RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx, TableRequestOptions options, String accountName) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpResponseParsers.cs:line 202
   at Microsoft.WindowsAzure.Storage.Table.TableBatchOperation.<>c__DisplayClassa.<BatchImpl>b__8(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableBatchOperation.cs:line 147
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessEndOfRequest[T](ExecutionState`1 executionState) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 898
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndOperation[T](ExecutionState`1 executionState) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 425
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndExecuteBatch(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 208
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 66

**Comment by IlyaGrebnov** [comment]
Request:

POST http://127.0.0.1:10002/devstoreaccount1/$batch?timeout=15 HTTP/1.1
User-Agent: Azure-Storage/8.0.1 (.NET CLR 4.0.30319.42000; Win32NT 6.3.9600.0)
x-ms-version: 2016-05-31
Accept-Charset: UTF-8
MaxDataServiceVersion: 3.0;NetFx
DataServiceVersion: 3.0;
Content-Type: multipart/mixed; boundary=batch_4fd50e81-c1c9-430a-8d87-92d1a9893fb7
x-ms-client-request-id: b3b1afab-9184-4719-89ef-a13379db6378
x-ms-date: Sat, 11 Feb 2017 17:11:33 GMT
Authorization: SharedKey devstoreaccount1:XLgaVf5sPO4fzkDLCqGnCu0UzPzZsuBlliKd14QaRS8=
Host: 127.0.0.1:10002
Content-Length: 3249

--batch_4fd50e81-c1c9-430a-8d87-92d1a9893fb7
Content-Type: multipart/mixed; boundary=changeset_ece23ff7-9d18-4fe3-ab22-ce40e73014d4

--changeset_ece23ff7-9d18-4fe3-ab22-ce40e73014d4
Content-Type: application/http
Content-Transfer-Encoding: binary

POST http://ipv4.fiddler:10002/devstoreaccount1/flowa606dc8d89a6447cae5464aad55b6c2e20170211t000000zvariables() HTTP/1.1
Accept: application/json;odata=minimalmetadata
Content-Type: application/json
Prefer: return-no-content
DataServiceVersion: 3.0;

{"PartitionKey":"9A471","RowKey":"A606DC8D89A6447CAE5464AAD55B6C2E-08587147737933601285397010592_OPERATION-08587147737933601285397010592-V1-0B41CB5D:2DAD1F:2D4606:2D9ADE:2D35D11CDF85F1","CreatedTime@odata.type":"Edm.DateTime","CreatedTime":"2017-02-11T17:11:33.4698934Z","ChangedTime@odata.type":"Edm.DateTime","ChangedTime":"2017-02-11T17:11:33.4703445Z","DeletedTime@odata.type":"Edm.DateTime","DeletedTime":"1970-01-01T00:00:00Z","PlatformOptions":"RunDistributionAcrossPartitions","FlowId":"a606dc8d89a6447cae5464aad55b6c2e","FlowRunSequenceId":"08587147737933601285397010592","VariableName":"v1","OperationId":"0b41cb5d-ad1f-4606-9ade-35d11cdf85f1"}
--changeset_ece23ff7-9d18-4fe3-ab22-ce40e73014d4
Content-Type: application/http
Content-Transfer-Encoding: binary

PUT http://ipv4.fiddler:10002/devstoreaccount1/flowa606dc8d89a6447cae5464aad55b6c2e20170211t000000zvariables(PartitionKey='9A471',RowKey='A606DC8D89A6447CAE5464AAD55B6C2E-08587147737933601285397010592_VARIABLENAME-08587147737933601285397010592-V1') HTTP/1.1
Accept: application/json;odata=minimalmetadata
Content-Type: application/json
If-Match: W/"datetime'2017-02-11T17%3A11%3A33.26Z'"
DataServiceVersion: 3.0;

{"CreatedTime@odata.type":"Edm.DateTime","CreatedTime":"2017-02-11T17:11:32.1496397Z","ChangedTime@odata.type":"Edm.DateTime","ChangedTime":"2017-02-11T17:11:33.4703445Z","DeletedTime@odata.type":"Edm.DateTime","DeletedTime":"1970-01-01T00:00:00Z","PlatformOptions":"RunDistributionAcrossPartitions","FlowId":"a606dc8d89a6447cae5464aad55b6c2e","SubscriptionId":"sub-18f25e24fbbe482884d62b1672d26580","ResourceGroupName":"f6532169d6164407889b03f8140ac62a","FlowName":"flow4dfef33dbd7340b0aac0eb9a113f52aa","FlowSequenceId":"08587147737933209084","FlowRunSequenceId":"08587147737933601285397010592","VariableName":"v1","DataType":"String","ValueLink@odata.type":"Edm.Binary","ValueLink":"MIICLgYJKoZIhvcNAQcDoIICHzCCAhsCAQAxggFUMIIBUAIBADA4MCQxIjAgBgNVBAMTGVNjaGVkdWxlciBFbmNyeXB0aW9uIFRlc3QCELqjXCb0JG6pTRshkRAVwZUwDQYJKoZIhvcNAQEHMAAEggEAZZa8c7Vs2lzSG1EpaLblu1UVWQbQnQOK9GW3a68pvG3V8jt4eVor3GYrXj0ZjMrOd5SP7drqEfFfzKUytGQIOp02Rw/uMJvQNmAkgm3AqeX8o0rUpO0kh6HsnabQ6Ig8IypbA8QgERnOcvZQS7UYIl6EAEUO2uwvihGNO+EK27EQSpGSJvtVGWkJc0GmnYq1ROguQsH2TFcHEiaidLnqoqQbSA6wuFnHQJNITne79htm3CXeT5Vi+jIw7e2E7+LSooFv4nCVw30jRhp+Xrg1zpqyG3vcbsVV6UX9KmCP2SsKpZYF99mAzsqx80+8BoNXdwlI3rwe2APaFr935IE8SDCBvQYJKoZIhvcNAQcBMB0GCWCGSAFlAwQBAgQQGhaoAbvVcv3+q43J2Jd2nYCBkBADatDUxlSNs4gSDrbyU3Gt4BB/JhnPiSbhPIn0FLpTFqqg027fKpnYOqB6ofe3dr1dPYnyj/spQ7jEWDO9pfLvy93tcYCqV0jdmeU92FNKhU3/VkzQZZazwwFCsELQ99iiQ1VLj0oYIEXoZ5KdAMI/u8n4ykALLFh/SHBxm0pWQZspo2Qbbc9EpXAQrBkjIA=="}
--changeset_ece23ff7-9d18-4fe3-ab22-ce40e73014d4--
--batch_4fd50e81-c1c9-430a-8d87-92d1a9893fb7--

Reponse:

HTTP/1.1 202 Accepted
Cache-Control: no-cache
Transfer-Encoding: chunked
Content-Type: multipart/mixed; boundary=batchresponse_64bcdd25-2ae0-4a97-995a-f1d2f2ff744d
Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 82471edb-ce2a-401c-bb1a-4be08f97f6a9
x-ms-version: 2016-05-31
X-Content-Type-Options: nosniff
DataServiceVersion: 1.0;
Date: Sat, 11 Feb 2017 17:11:33 GMT

31A
--batchresponse_64bcdd25-2ae0-4a97-995a-f1d2f2ff744d
Content-Type: multipart/mixed; boundary=changesetresponse_acb1b142-b74a-48ee-a1e2-aecff3d9ece0

--changesetresponse_acb1b142-b74a-48ee-a1e2-aecff3d9ece0
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 409 Conflict
X-Content-Type-Options: nosniff
Cache-Control: no-cache
DataServiceVersion: 3.0;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"0:The specified entity already exists.\nRequestId:82471edb-ce2a-401c-bb1a-4be08f97f6a9\nTime:2017-02-11T17:11:33.4947543Z"}}}
--changesetresponse_acb1b142-b74a-48ee-a1e2-aecff3d9ece0--
--batchresponse_64bcdd25-2ae0-4a97-995a-f1d2f2ff744d--

0

**Comment by IlyaGrebnov** [comment]
Exception is thrown on following line:
"if (!string.IsNullOrEmpty(cmd.CurrentResult.ExtendedErrorInformation.ErrorMessage))"
because ExtendedErrorInformation is null which is result of another hidden exception:
A supported MIME type could not be found that matches the content type of the response. 
None of the supported type(s) 'application/xml, application/json;odata=verbose, application/json' matches the content type 
'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'.

How I can fix this? It is currently blocking my release.

**Comment by IlyaGrebnov** [comment]
Note, I am using Microsoft.Data.OData.dll version 7.0

**Comment by IlyaGrebnov** [comment]
Same problem exists with Microsoft.Data.OData.dll version 5.6.4 and 5.8.2

**Comment by IlyaGrebnov** [comment]
Here is repro program: it prints "EntityAlreadyExists".
But after changing to PayloadFormat to TablePayloadFormat.Json it will throw.

            var account = CloudStorageAccount.DevelopmentStorageAccount;
            var tableClient = account.CreateCloudTableClient();

            tableClient.DefaultRequestOptions.PayloadFormat = TablePayloadFormat.AtomPub;
            var tableReference = tableClient.GetTableReference("test");

            tableReference.CreateIfNotExistsAsync().Wait();

            var pk = Guid.NewGuid().ToString("N");
            var rk1 = Guid.NewGuid().ToString("N");
            var rk2 = Guid.NewGuid().ToString("N");

            var batch1 = new TableBatchOperation();
            var entity = new DynamicTableEntity(pk, rk1);

            batch1.Add(TableOperation.Insert(entity));
            batch1.Add(TableOperation.Insert(new DynamicTableEntity(pk, rk2)));
            tableReference.ExecuteBatchAsync(batch1).GetAwaiter().GetResult();

            try
            {
                var batch2 = new TableBatchOperation();
                batch2.Add(TableOperation.Insert(new DynamicTableEntity(pk, rk2)));
                batch2.Add(TableOperation.Replace(new DynamicTableEntity(pk, rk1) { ETag = entity.ETag }));
                tableReference.ExecuteBatchAsync(batch2).GetAwaiter().GetResult();
            }
            catch (StorageException ex)
            {
                var errorInfo = ((StorageException)ex).RequestInformation.ExtendedErrorInformation;
                System.Console.WriteLine(errorInfo.ErrorCode);
            }

**Comment by erezvani1529** [comment]
Hi @IlyaGrebnov ,

Would you please let us know which version of Storage Client are you using? I am not able to repro with the repro code you have provided and 8.0.0.

Thanks,
Elham

**Comment by IlyaGrebnov** [comment]
-   "Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net46"
-   "Microsoft.Data.Edm" version="5.7.0" targetFramework="net46" 
-   "Microsoft.Data.OData" version="5.7.0" targetFramework="net46"
-   "Microsoft.Data.Services.Client" version="5.7.0" targetFramework="net46"
-   "Microsoft.WindowsAzure.ConfigurationManager" version="1.8.0.0" targetFramework="net46"
-   "Newtonsoft.Json" version="6.0.8" targetFramework="net46"
-   "System.Spatial" version="5.7.0" targetFramework="net46"
-   "WindowsAzure.Storage" version="8.0.1" targetFramework="net46"

**Comment by erezvani1529** [comment]
Thanks @IlyaGrebnov , 

As we discussed offline this is an emulator issue and we are following up internally to get it fixed. I will post updates on this thread.

Thanks!

**Comment by yevhen** [comment]
Experiencing the same issue with storage 8.1.1 and 4.6 emulator

**Comment by erezvani1529** [comment]
Hi @IlyaGrebnov, @yevhen,

We have released [Emulator  v5.1 ](https://go.microsoft.com/fwlink/?linkid=717179 ) to resolve this issue. Please give it a try to unblock. 

We have a fix on client side to handle the case as well and will use this issue to track it.

Thanks again for reporting,
Elham

**Comment by yevhen** [comment]
@erezvani1529 Just tried - it works! Thanks!
