### ISSUE TITLE
Problem installing 8.1 to a .NET Standard class library

### ISSUE THREAD

**Issue by raRaRa** [Azure/azure-storage-net#411]
I can't seem to install `WindowsAzure.Storage` 8.1 to a .NET Standard 1.6 class library. It complains that:
`Package System.Linq.Queryable 4.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). `

However, `System.Linq.Queryable` version 4.3.0 seems to support .NET Standard.

It works fine if I install `WindowsAzure.Storage` to a netcore class library since `System.Linq.Queryable` 4.0.0 supports it.

The `System.Linq.Queryable` dependency seems to be coming from the `Microsoft.Data.Services.Client` package.

https://www.nuget.org/packages/Microsoft.Data.Services.Client/
`System.Linq.Queryable (>= 4.0.0)`

I'm using the latest Visual Studo 2017 RC and started a new .NET Standard class library. I believe I have the latest tooling.

Thanks.

**Comment by TheRubble** [comment]
I'm working around this at the moment, but installing System.Linq.Queryable before installing windowsazure.storage.

**Comment by raRaRa** [comment]
@TheRubble Yeah that seems to do the trick for now. Thanks.

**Comment by GerFVersteegGitHub** [comment]
Hi Mister raRaRa,

I have installed the latest version of Visual Studio 2017 with ASP.Net Core

Now I have a big problem with azure table queries , all the 'EXECUTEQUERY'  did not exists any more.
('CloudTable'does not contain a definition for 'ExecuteQuery' and no extension method 'ExecuteQuery' accepting a first argument of type 'CloudTable' could be found)

Please do You know a solution for this?

Thanks Ger
![executequery](https://cloud.githubusercontent.com/assets/13047756/23157161/3bc48fa2-f81a-11e6-9174-90d40fa13a62.png)

**Comment by raRaRa** [comment]
Hey there @GerFVersteegGitHub 

I would check out this existing issue https://github.com/Azure/azure-storage-net/issues/407

But basically you need to use `ExecuteQuerySegmentedAsync` instead of `ExecuteQuery` for now.

Here's an example:

```csharp
    TableContinuationToken continuationToken = null;

    TableQuerySegment<CustomerEntity> tableQueryResult =
        await table.ExecuteQuerySegmentedAsync(query, resolver, continuationToken);

    return tableQueryResult.FirstOrDefault();
```

I've raised the question if there are plans to support `ExecuteQuery` in the future and if the code above could be simplified by passing null instead of a `TableContinuationToken`.

Hope this helps.

**Comment by GerFVersteegGitHub** [comment]
Hi Mister raRaRa,
Thank you for your help and I will changed my program this afternoon and I send my (hopefull) good result.
All the best from Holland, Ger

**Comment by erezvani1529** [comment]
Hi @raRaRa, @TheRubble,

Thanks for sharing your work-around and results. (Another workaround is the same old imports statement). 
What we are doing to fix the problem: we are going to work with ODataLib team to fix their dependency issue. However, since we do not want to block our users depending on another team, meanwhile we have verified that we can remove this dependency from our netstandard support and will be able to release a fix for this issue in next few days.
(versioned 8.1.1)

I will update once the package is ready and published.

Thanks again,
Elham

**Comment by raRaRa** [comment]
That's great news @erezvani1529 

Thank you for the quick update.

**Comment by TheRubble** [comment]
Just pulled this new version in 8.1.1 and there is a simliar issue around System.ComponentModel.EventBasedAsync

**Comment by erezvani1529** [comment]
Hi @TheRubble,

Are you trying to install on a Netstandard Library using VS2017  project template? I don't see any issues installing any more. Please share some more details about your project type and possibly your current dependency setting as well.

Thanks,
Elham

**Comment by TheRubble** [comment]
It's due to another reference, I'll give you an update later. Safe to close this.
