### ISSUE TITLE
HttpWebRequest.Abort() method is not called on ThreadAbortException and subsequent requests are waiting for an uncertain time.

### ISSUE THREAD

**Issue by egubenya** [Azure/azure-storage-net#419]
My program uses Azure Storage, and sometimes a thread fetching the data from storage is aborted. Afterward, it is often that subsequent requests cannot finish for an uncertain time (probably until an `HttpWebRequest` from the previously aborted thread is garbage-collected).

I looked in the source code of Azure Storage, particularly Executor.cs, and noticed that in a case of `ThreadAbortException` nobody calls `HttpWebRequest.Abort()` of `ExecutionState<T>.Req`. I'm talking about the code of `Executor.ExecuteSync<T>()` method. Once I fixed this, the problem was gone.

Could you please add the corresponding fix so it could be available in the release version? 

Please let me know if you need any other details.

**Comment by erezvani1529** [comment]
Hi @egubenya,

Thanks for sharing your investigation results. Can you share some more info regarding the underlying problem and the effects of it? Do you have any logs or exception messages to share? If you could share a sample repro code it would help us understand the issue better. Once we have a better understanding of the problem we can discuss the solution as well.

Thanks,
Elham

**Comment by seanmcc-msft** [comment]
We haven't heard back from you in a while, please reactive if you are still experiencing this issue.
