### ISSUE TITLE
CloudBlobContainer.CreateIfNotExists() fails with 404 error

### ISSUE THREAD

**Issue by Liphi** [Azure/azure-storage-net#425]
Hi, I have successfully created a SAS token by powershell for a container. Then my client application calls CloudBlobContainer.CreateIfNotExists(), but it fails with the '404 Not Found' error.

New-AzureStorageContainerSASToken -Permission rwdl -Name myNonExistingContainer -Context $ctx

I have verified that no matter whether the container actually exists or not, the CreateIfNotExists() call fails with the same 404 error.
My question is: is it actually supported to create a container from the client with a SAS token?

**Comment by pemari-msft** [comment]
Can you share the account name, timestamp, and failing request ID for the 404 error? Feel free to share this info to `ascl [at] Microsoft [dot] com` for privacy.

**Comment by pemari-msft** [comment]
Oh, now I see the issue. Yes, you're correct. You cannot create a container with a service SAS token. You can only create a container with an account SAS token.
