### ISSUE TITLE
TargetParameterCountException : Parameter count mismatch when using lists

### ISSUE THREAD

**Issue by cdmdotnet** [Azure/azure-storage-net#426]
If a property on your object to be flatterned is a list (the same is not true for an array, although I haven't tested a dictionary) you get an exception thrown at line 196 of EntityPropertyConverter.cs.

The issue come down the issue that the list property "item" cannot have it's value retrieved using `propertyInfo.GetValue(current, index: null)`.

Given generic lists are regularly used this and is a highly probable data type to deal with, can you guys find a solution to this. You could check if a type is an IList implementation, cast and serialise as an array, then on deserialisation, deserialise to an array and pass into a list constructor.

**Comment by erezvani1529** [comment]
Hi @cdmdotnet,

Given the property count and size limitations, Storage Client does not support List properties directly or through Flattener. However, you may want to consider using a private property of List type (which flattener does not attempt to flatten hence avoid the exception) and handle the serialization/deserialization logic in a public property of array type which is supported by flattener. 

Thanks,
Elham

**Comment by cdmdotnet** [comment]
I've gone one better and made a fork which I'll request a pull request for which will add support for IEnumerables by serialising them within the `EntityPropertyConverter` class. There's no need to force every developer to create their own differing form of serialisation... that's not interoperable development.

**Comment by mcinnes01** [comment]
@cdmdotnet can you sign the contributor agreement to get this merged?

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
