### ISSUE TITLE
Getting "Error occurred while decoding OAEP padding" while decrypting data from table storage

### ISSUE THREAD

**Issue by debasis-accn** [Azure/azure-storage-net#428]
Hi,
Reaching out to for your help / support. 
We have a requirement to Encrypt the data in table storage and Decrypt the data while pulling it from table storage. Tried with the sample application found in https://github.com/Azure/azure-storage-net.
In the sample application Encryption and Decyption is happening in same method. In my case it rasing error in "Decrypt" function and the error is **- "Error occurred while decoding OAEP padding"** But we need to two separate functions. Even we need to pull the data through Table Query.
Please find below is my code -

const string DemoTable = "demotable";

        static void Main(string[] args)
        {            
            RsaKey key = new RsaKey("mydemokey");
            string partitionid = "mydemoid123456";

            EncryptData(partitionid, key);

            DecryptData(partitionid, key);
        }

        public static void EncryptData(string partitionid,  RsaKey rsakey)
        {           
            CloudStorageAccount storageAccount = EncryptionShared.Utility.CreateStorageAccountFromConnectionString();
            CloudTableClient client = storageAccount.CreateCloudTableClient();
            CloudTable table = client.GetTableReference(DemoTable);

            try
            {
                table.Create();
                
                EncryptedEntity ent = new EncryptedEntity() { PartitionKey = partitionid, RowKey = "DemoKey1" };
                ent.Populate();

                TableRequestOptions insertOptions = new TableRequestOptions()
                {
                    EncryptionPolicy = new TableEncryptionPolicy(rsakey, null)
                };                                
                table.Execute(TableOperation.Insert(ent), insertOptions, null);
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
        }

        public static void DecryptData(string partitionid, RsaKey rsakey)
        {
            CloudStorageAccount storageAccount = EncryptionShared.Utility.CreateStorageAccountFromConnectionString();
            CloudTableClient client = storageAccount.CreateCloudTableClient();
            CloudTable table = client.GetTableReference(DemoTable);

            try
            {
                EncryptedEntity ent = new EncryptedEntity() { PartitionKey = partitionid, RowKey = "DemoKey1" };
                ent.Populate();
                LocalResolver resolver = new LocalResolver();
                resolver.Add(rsakey);
                TableRequestOptions retrieveOptions = new TableRequestOptions()
                {
                    EncryptionPolicy = new TableEncryptionPolicy(null, resolver)
                };
                TableOperation operation = TableOperation.Retrieve(ent.PartitionKey, ent.RowKey);
                TableResult result = table.Execute(operation, retrieveOptions, null);
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
        }

    }

Am I doing any mistake or any other option available to Encypt and Decrypt the data in Table Storage (including partitionkey).
![error_dec](https://cloud.githubusercontent.com/assets/26326530/23797812/a009e326-05c7-11e7-98c1-7145699505e9.png)

Thanks in advance for your help.

Best Regards,
Debasis

**Comment by erezvani1529** [comment]
Hi @debasis-accn,

Thanks for reporting your issue. Would you please share your stack trace as well? 

Also, there might be a confusion here:

> Am I doing any mistake or any other option available to Encypt and Decrypt the data in Table Storage (including partitionkey).

Please note that Encryption only applies to entity properties not the partition key or the row key.

**Comment by debasis-accn** [comment]
Hi erezvani,
Thank you very much for your information. Today I will debug the application and will share the details.

Best Regards,
Debasis

**Comment by aanttila** [comment]
Any update on this issue?

**Comment by debasis-accn** [comment]
Hi aanttila,

Apologize for delaying in repsonse. Please below the Stack trace -

`   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext)
   at TableGettingStartedUsingAttributes.Program.DecryptData(String partitionid) in C:\AZURE_AD_GROUP_CLAIM\azure-storage\azure-storage-net-master\Samples\GettingStarted\EncryptionSamples\TableGettingStartedUsingAttributes\Program.cs:line 90`

Exception ---

`Microsoft.WindowsAzure.Storage.StorageException: Decryption logic threw error. Please check the inner exception for more details. ---> System.AggregateException: One or more errors occurred. ---> System.Security.Cryptography.CryptographicException: Error occurred while decoding OAEP padding.
   at System.Security.Cryptography.RSACryptoServiceProvider.DecryptKey(SafeKeyHandle pKeyContext, Byte[] pbEncryptedKey, Int32 cbEncryptedKey, Boolean fOAEP, ObjectHandleOnStack ohRetDecryptedKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(Byte[] rgb, Boolean fOAEP)
   at Microsoft.Azure.KeyVault.Cryptography.Algorithms.RsaOaep.RsaOaepDecryptor.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Microsoft.Azure.KeyVault.RsaKey.<UnwrapKeyAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy.DecryptMetadataAndReturnCEK(String partitionKey, String rowKey, EntityProperty encryptionKeyProperty, EntityProperty propertyDetailsProperty, EncryptionData& encryptionData)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext)
   at TableGettingStartedUsingAttributes.Program.DecryptData(String partitionid) in C:\AZURE_AD_GROUP_CLAIM\azure-storage\azure-storage-net-master\Samples\GettingStarted\EncryptionSamples\TableGettingStartedUsingAttributes\Program.cs:line 90
`

Please ifnd below the entire code -

`public class Program
    {
        const string DemoTable = "demotable";

        static void Main(string[] args)
        {            
            
            string partitionid = "mydemoid123456";

            EncryptData(partitionid);

            DecryptData(partitionid);
        }

        public static void EncryptData(string partitionid)
        {           
            CloudStorageAccount storageAccount = EncryptionShared.Utility.CreateStorageAccountFromConnectionString();
            CloudTableClient client = storageAccount.CreateCloudTableClient();
            CloudTable table = client.GetTableReference(DemoTable);
            RsaKey rsakey = new RsaKey("mydemokey");
            try
            {
                table.Create();
                
                EncryptedEntity ent = new EncryptedEntity() { PartitionKey = partitionid, RowKey = "DemoKey1" };
                ent.Populate();

                TableRequestOptions insertOptions = new TableRequestOptions()
                {
                    EncryptionPolicy = new TableEncryptionPolicy(rsakey, null)
                };
                                
                table.Execute(TableOperation.Insert(ent), insertOptions, null);
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
        }

        public static void DecryptData(string partitionid)
        {
            CloudStorageAccount storageAccount = EncryptionShared.Utility.CreateStorageAccountFromConnectionString();
            CloudTableClient client = storageAccount.CreateCloudTableClient();
            CloudTable table = client.GetTableReference(DemoTable);
            RsaKey rsakey = new RsaKey("mydemokey");
            try
            {
                EncryptedEntity ent = new EncryptedEntity() { PartitionKey = partitionid, RowKey = "DemoKey1" };
                ent.Populate();

                LocalResolver resolver = new LocalResolver();
                resolver.Add(rsakey);

                TableRequestOptions retrieveOptions = new TableRequestOptions()
                {
                    EncryptionPolicy = new TableEncryptionPolicy(null, resolver)
                };

               
                TableOperation operation = TableOperation.Retrieve(ent.PartitionKey, ent.RowKey);
                TableResult result = table.Execute(operation, retrieveOptions, null);
            }
            catch (Exception ex)
            {
                string error = ex.ToString();
                string stackTrace = ex.StackTrace.ToString();
                Console.Write(ex.Message);
            }
        }

    }`

Kindly help us for the above issue.

Thanks.

Best Regards,
Debasis Ghosh

**Comment by erezvani1529** [comment]
Here is what is wrong with your code. The same Rsa key instance should be used to encrypt and decrypt(either directly or using the resolver). This is the actual reason you are getting the failure in decryption.

Also, if the Table is not created or Insert Operation with Encryption is not successful the decryption will fail so please make sure you are only decrypting if the previous set of operations are completed successfully.

Thanks,
Elham

**Comment by erezvani1529** [comment]
<closed by mistake> Please feel free to try the suggested fix and close if you don't have any related questions.

**Comment by debasis-accn** [comment]
Hi erezvani,
Thanks for your help / support. Apologize I did the mistake. Now encryption and decrytion is working as of now. 
Again facing a issue; it unables to encrypt "GUID", "Int" property, it supports only string property. Error is - 
Unsupported type : Guid encountered during encryption. Only string properties can be encrypted on the client side.
Should I need to change property type to "string" for all entitites?

Thanks for your help.

Best Regards,
Debasis Ghosh

**Comment by erezvani1529** [comment]
@debasis-accn,

Please take a look at our detailed [documentation on Encryption](https://docs.microsoft.com/en-us/azure/storage/storage-client-side-encryption) here. To answer your question quoting from the documentation:

`Note that only string properties can be encrypted. If other types of properties are to be encrypted, they must be converted to strings. The encrypted strings are stored on the service as binary properties, and they are converted back to strings after decryption.`

Thanks,
Elham

**Comment by debasis-accn** [comment]
Hi Elham,
Thank you very much for your help.
Best Regards,
Debasis Ghosh
