### ISSUE TITLE
Partition Keys or Row Keys that contain char.MaxValue fail

### ISSUE THREAD

**Issue by dontjee** [Azure/azure-storage-net#43]
With the switch to using Json as the default PayloadFormat, [a bug has been exposed in OData](https://odata.codeplex.com/workitem/15) that causes partition keys or row keys with char.MaxValue in the string to fail.

The workaround I've used is to set the PayloadFormat back to AtomPub but I'd like to use the Json format.

Feel free to close this bug if it's not useful, I just wasn't seeing any action on the issue I posted in the OData Codeplex repo.

**Comment by pemari-msft** [comment]
Thanks for reporting this to us and the OData team. This should be fixed in the latest versions of OData and this Library. Can you try updating your version of the Client Library to 4.3.0 or OData to version 4.6.1 or greater?

**Comment by dontjee** [comment]
Yup this is fixed. Thanks!
