### ISSUE TITLE
WebJobs Blob Trigger does not work correctly with Storage Emulator

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-storage-net#430]
Related to https://github.com/Azure/azure-webjobs-sdk/issues/53. 

Essentially it seems that the later versions of the emulator now do support blob triggers - great news. Unfortunately, if you copy multiple blobs into the local storage emulator at once e.g. 10 or so - you get an HTTP 500 error. This happens deep down so that the the web job does not trigger into application code (although you do see an exception in the webjob application occur).

**Comment by kfarmer-msft** [comment]
Hi, Isaac --

We'd be interested in viewing your emulator logs and Fiddler traces.

**Comment by isaacabraham** [comment]
@kfarmer-msft where can I can the logs from?

**Comment by kfarmer-msft** [comment]
Shut down the emulator, open the config file at \Users\<account>\AppData\Local\AzureStorageEmulator\ and change LoggingEnabled to true.

Restart, and the emulator should start logging to files in the Logs folder there.

**Comment by isaacabraham** [comment]
@kfarmer-msft OK, I've got them. What email address should I send them to?

**Comment by erezvani1529** [comment]
Hi @isaacabraham,

Please email to `ascl [at] Microsoft [dot] com` and we will take a look.

Thanks!

**Comment by isaacabraham** [comment]
Done :-)

**Comment by isaacabraham** [comment]
Ping. Any luck with this one?

**Comment by isaacabraham** [comment]
@erezvani1529 was my email with logs received?

**Comment by erezvani1529** [comment]
cc:/ @kfarmer-msft

Hi @isaacabraham ,

I just checked and yes we have received your email. Apologies for the delay in response. I have followed up internally and we will get back to you with more results soon.

Thanks,
Elham

**Comment by isaacabraham** [comment]
@erezvani1529 ping. it's been nearly two months now - any follow up?

**Comment by isaacabraham** [comment]
Four months now. Could you provide an update on this?

**Comment by isaacabraham** [comment]
It's been a year now. @erezvani1529 can you provide an update e.g. "won't fix" or something similar? It's hampering our adoption of more Azure services with a customer.

**Comment by kfarmer-msft** [comment]
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite

**Comment by isaacabraham** [comment]
@kfarmer-msft sorry - are you saying that azurerite is now the replacement for the official storage emulator?
