### ISSUE TITLE
EntityPropertyConverter.SetProperty can throw nulref if the target property is not found

### ISSUE THREAD

**Issue by StenPetrov** [Azure/azure-storage-net#432]
A more descriptive exception would be helpful when troubleshooting. 
Also `throw` replaces the stack in the exception if it's thrown in the same method, so the exception doesn't actually tell you where in the source code it was thrown but reports the `throw` line.

To troubleshoot my (edge case) problem I had to copy EntityPropertyConverter code in my project and call it directly

https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/Common/Table/EntityPropertyConverter.cs#L391

**Comment by erezvani1529** [comment]
Hi @StenPetrov,

Will [enabling Client Side Logging](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/client-side-logging-with-the-.net-storage-client-library) help with your investigation for future cases?

Thanks,
Elham

**Comment by StenPetrov** [comment]
I gave this a try, it didn't produce a log file so I moved on.

**Comment by erezvani1529** [comment]
Hi @StenPetrov,

In situations like this, enabling client side logging helps clarify the issue. Were you able to resolve you issue to view the logs?

Please feel free to re-open this issue to add more details in case you are still having problems.

Thanks!
