### ISSUE TITLE
Add sdk method `CloudStorageAccount.GetAccountProperties`

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-storage-net#434]
There's a large matrix of storage account types which support varying levels of blob, queue, and tables. 

- general purpose
- blob only (which includes ZRS)
- premium

Currently to detect this from a connection string you need to create the storage client and try to recover in the event of failure (creating a queue for a blob only account, for example). [Here's](https://github.com/Azure/azure-webjobs-sdk/blob/eeebd5ea4aa148a8c4455ee793e4cce4575afe81/src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs#L93) an ugly example of that in the webjobs sdk codebase.

It'd be a nice improvement if the storage sdk could handle this logic via a method or methods to indicate what type an accout is and what properties it has, i.e. support for:
- blobs?
    - page?
    - block?
- queues?
- tables?
- files?

Related to https://github.com/Azure/azure-webjobs-sdk/issues/1067

**Comment by erezvani1529** [comment]
Hi @mamaso, 

We have in our backlog to provide access to account properties on Storage Data-Plane level(and our SDK) but unfortunately I don't have any specific timelines to share for its availability.

However, in our release for one of our upcoming service versions we do have a change which will make it easier to distinguish the premium account types(apologies that I can not provide a certain date for this change either but it is alomost in final stages :) ).

Thanks for sharing your suggestion,
Elham

**Comment by mamaso** [comment]
Good to hear that it's on the radar, thanks 👍
