### ISSUE TITLE
File intermittently not released with UploadFromFileAsync

### ISSUE THREAD

**Issue by ajbeaven** [Azure/azure-storage-net#438]
I'm having an issue with `UploadFromFileAsync` in that it looks like the file is often not released before the Task completes.

```
var account = CloudStorageAccount.Parse(_settings.MicrosoftAzureStorage.AudioConnectionString);
var blobClient = account.CreateCloudBlobClient();
var container = blobClient.GetContainerReference("raw");

var blob = container.GetBlockBlobReference("myfile.webm");
await container.CreateIfNotExistsAsync();
await blob.UploadFromFileAsync(filePath);

// this line intermittently fails
System.IO.File.Delete(filePath);
```

I frequently (maybe 1 out of every 3 times it runs) receive the following exception when the file is deleted at the end of the snippet above:

> IOException: The process cannot access the file 'C:\MyApp\myfile.webm' because it is being used by another process.

I expected that UploadFromFileAsync would only return when the connection to the file had been disposed of?

**Comment by pemari-msft** [comment]
Can you please specify which platform you're targeting?

**Comment by ajbeaven** [comment]
ASP.NET Core 1.1.0, currently running on a 64 bit windows machine. Using WindowsAzure.Storage 8.1.1 nuget package.

**Comment by pemari-msft** [comment]
Looks like we're using a `using` statement in the [normal ](https://github.com/Azure/azure-storage-net/blob/master/Lib/WindowsRuntime/Blob/CloudBlockBlob.cs#L420) case. Are you using Large Block Blobs by any chance?

**Comment by ajbeaven** [comment]
Nah, nothing over 300kB. 

I create a temporary version of the file just before it's uploaded to Azure Storage, so I'm pretty sure nothing else would be using it. It doesn't happen if I comment out the code to upload to Azure Storage... weird.

```
var audioDataBytes = Convert.FromBase64String(upload.AudioData);

using (var memoryStream = new MemoryStream(audioDataBytes))
using (var fileStream = new FileStream(filePath, FileMode.Create))
{
	await memoryStream.CopyToAsync(fileStream);
}
```

**Comment by zezha-msft** [comment]
@ajbeaven Thanks for the info! I will look into this and give you an update soon.

**Comment by zezha-msft** [comment]
@ajbeaven I was not able to reproduce this problem under ASP.NET Core 1.1.0 and Storage 8.1.1, could you please provide some more information about your setup? Thank you

**Comment by ajbeaven** [comment]
I tried to create a sample console app that showed the problem but couldn't reproduce it myself. I'll close this for now and will provide further details later if I'm able to narrow it down. Thanks for looking in to this for me :)

**Comment by zezha-msft** [comment]
@ajbeaven Sounds good, thank you!
