### ISSUE TITLE
Add constructor parameters to TableBatchOperation

### ISSUE THREAD

**Issue by alexangas** [Azure/azure-storage-net#439]
Would it please be possible to add some constructors to improve the performance/memory usage of TableBatchOperation? That is, exposing some of the constructors from `List<>` to help improve management of the [private `operations` variable](https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/Common/Table/TableBatchOperation.Common.cs#L36).

Suggestions:

1. `new TableBatchOperation(int capacity)`
    1. Optionally with check for range of 0-100

2. `new TableBatchOperation(IEnumerable<TableOperation> collection)`
    1. Optimisation here is that the initial capacity could be set
    2. This would need to do a loop through and call `Add()` on each item

If option 1 and/or 2 would be beneficial, I'm happy to do a PR.

**Comment by pemari-msft** [comment]
This will be reevaluated once we have completed the library split. Thanks for the suggestion!
