### ISSUE TITLE
Azure Storage emulator performs case-insensitive comparisons

### ISSUE THREAD

**Issue by WillSullivan** [Azure/azure-storage-net#44]
The Azure Storage emulator (3.0.0.0) performs case-insensitive queries, although Azure Storage performs case-sensitive queries.  This can result in bugs where results are found where they should NOT be found.  

In my case, ASP.NET Identity expects a user be uniquely identifiable by user name (ugh, idiots).  Since AS performs case-sensitive searches (example later), you can end up with different users with the same user name that differ only by case.  This is not optimal, and should be avoided, for obvious reasons.

GIVEN the following table query (everything not shown is obvious)

    var userNameQuery = new TableQuery().Where(
        TableQuery.CombineFilters(
            TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, "derp"),
            TableOperators.And,
            TableQuery.GenerateFilterCondition("Name", QueryComparisons.Equal, userName)))
            .Take(1);
    return table.ExecuteQuery(userNameQuery).FirstOrDefault();

Azure Storage will perform a case-sensitive search on "Name".  However, if you perform the same exact query against the storage emulator, it will perform a case-insensitive search (e.g., search for "moe" you'll get "Moe"  back when it should return nothing).

**Comment by jezzsantos** [comment]
Yep, just got bitten by this one as well. Side-effects are extremely hard to find downstream bugs.

**Comment by pemari-msft** [comment]
Thanks for the feedback. While the emulator is not in this repo, we'll send this to the relevant people and we'll add it to their request backlog.

**Comment by mxa0079** [comment]
@pemari-msft I'd suggest not to close issues if they not resolved or if it is not clear that the issue is resolved and released to production.
