### ISSUE TITLE
CloudBlobContainer.CreateIfNotExists() fails to use "modifiedOptions" variable

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#440]
https://github.com/Azure/azure-storage-net/blob/ea2af9f78bbdf5a167bca1dd743e848ebae944b2/Lib/ClassLibraryCommon/Blob/CloudBlobContainer.cs

contains 

     public virtual bool CreateIfNotExists(BlobContainerPublicAccessType accessType,
          BlobRequestOptions requestOptions = null, OperationContext operationContext = null)

which does this:

        BlobRequestOptions modifiedOptions =
              BlobRequestOptions.ApplyDefaults(requestOptions, BlobType.Unspecified, this.ServiceClient);
            
but `modifiedOptions` is not used after that - instead `requestOptions` is used.

This is a CA1804 code analysis defect and it's likely a bug.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me, thanks for pointing this out. This is a bug and we fix this in our next release.

**Comment by erezvani1529** [comment]
Closing this issue with [8.2](https://www.nuget.org/packages/WindowsAzure.Storage) release.

Thanks again for reporting.
