### ISSUE TITLE
CloudBlockBlob.EndUploadFromFile() uses "is"-"as" instead of "as"

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#441]
https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs

contains 

       public virtual void EndUploadFromFile(IAsyncResult asyncResult)
       {
           if (asyncResult is CancellableAsyncResultTaskWrapper)
           {
                CancellableAsyncResultTaskWrapper cancellableAsyncResult = asyncResult as CancellableAsyncResultTaskWrapper;
                cancellableAsyncResult.Wait();
            }

which causes a CA1800 code analysis issue being reported - the reference is being cast twice to the same type. This code can be redesigned by moving `cancellableAsyncResult` variable out of `if` and just comparing it against `null`.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me, we can change this as well. Thanks!

**Comment by erezvani1529** [comment]
Closing with [8.2](https://www.nuget.org/packages/WindowsAzure.Storage) package.

Thanks for reporting
