### ISSUE TITLE
Performance issue with OpenReadAsync method

### ISSUE THREAD

**Issue by vishnuvg1984** [Azure/azure-storage-net#442]
We recently upgraded our Azure Storage Package from  v3.0.3.0 to v8.0.1. Identified that the "OpenReadAsync" method is facing major performance degradation. Our's is a asp.net webapi project configured to use AzureStorage nuget package. When  we tested after package upgraded and sent requests using apache jmeter tool at the rate of 15 req/sec. Within 5 minutes 2 requests were found in IIS active requests which aren't responding. 

On further analysis, we found that we getting slow response from the following webapi method. We tested again by changing the "OpenReadAsync" method to "OpenRead"(sync) and performance is good and working as before. Looks like the "OpenReadAsync" in the recent nuget versions, has performance issue. Normally the async methods would perform better , in this case its just the reverse.  Please find 
[OpenReadAsync Issue - WebApi Code.txt](https://github.com/Azure/azure-storage-net/files/957248/OpenReadAsync.Issue.-.WebApi.Code.txt)
the webapi controller code  for reference. Any help would be really appreciated

**Comment by erezvani1529** [comment]
Hi @vishnuvg1984,

Thanks for raising your issue. So just to make sure you are not seeing any delays in the actual read operation and only the OpenReadAsync operation? A few follow up questions for you as well:

> Within 5 minutes 2 requests were found in IIS active requests which aren't responding

Do you mean hanged requests?

> On further analysis, we found that we getting slow response from the following webapi method.

Would you please include some details on the analysis so that I can investigate more on a local repro?



Thanks,
Elham

**Comment by vishnuvg1984** [comment]
Elham, Thanks for the reply.

**To answer your questions**
Do you mean hanged requests - Yes hang we mean non-response. Ours is a WebApi Project using Azure Storage Nuget Package. We have a method which reads the blob content using OpenRead. To test the peformance of that method using Jmeter, we sent requests @ 15 req/sec. Code for method is attached in previous message. 

After 5 minutes the response from OpenReadAsync method seems slow and hanged. We checked the IIS logs and all those were in a waiting condition, preventing further processing. 

**More Analysis Details**
We further tested using Non-Async version of OpenReadAsync, ie OpenRead. The method worked fine for 1.5 hours, after that the requests got hanged(non-responsive). We then checked with DownloadtoStreamMethod and has the same issue. After 1.5 to 2hrs of continous requsts hits the OpenRead and DownloadToStream methods are underperforming

Our application has a lot of clients using the webapi at continous requests, so performance is a concern for us. Currently we fixed the issue by downgrading the Azure Storage package from 8.0.1 to 5.0.2 and now the performance is back as before and getting no hang requests even if its workign for more than 6+ hours. So now its quite stable. 

Please let me know for any further clarification.

**Comment by erezvani1529** [comment]
Hi @vishnuvg1984,

Thanks for the detailed explanation and apologies for the delay in response. Now that we know you are seeing hanged requests, would you please share a dump with us? (email to `ascl at microsoft dot com`). 

Thanks,
Elham

**Comment by vishnuvg1984** [comment]
Hi Elham,
I think I can. Will create a test standalone project and reproduce and then share. 

Regards
Vishnu VG

**Comment by vishnuvg1984** [comment]
Hi Elham,

I 've send an email from my account . Search Vishnu VG , Subject - azure-storage-net/issues/442

**Comment by vishnuvg1984** [comment]
Even after sending multiple emails the team is not responding, hence we are forced to use the older version 5.0.2.  I also pasted a questoin in msdn forums to find how long can i Use this particular version to connect to Azure Storage. https://social.msdn.microsoft.com/Forums/en-US/19ba17f4-85a9-4cc8-a0d0-67d31e0b78b2/azure-nuget-version-compatiblity?forum=windowsazuredata

**Comment by erezvani1529** [comment]
Hi @vishnuvg1984,

Thanks for following up on this issue and apologies if the required information were not made clear enough. I would appreciate it if you could generate and share the original process dumps and please check this [link ](https://blogs.msdn.microsoft.com/benjaminperkins/2017/02/01/create-a-memory-dump-for-your-slow-performing-web-app/) for some related instructions. I will prioritize investigating this issue once we have this information.

To answer your question: There will be 
at least a 1-year notice and deprecation announcement before an old service version is deprecated. Please checkout [this document](https://docs.microsoft.com/en-us/rest/api/storageservices/Azure-Storage-Services-Versions-2015-07-08-and-Earlier?redirectedfrom=MSDN) for more information about the oldest supported service versions.

Thanks again,
Elham
