### ISSUE TITLE
Adding a DateTime member to an existing table entity gets (400) Bad Request on first get

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-storage-net#443]
Mostly see here
http://stackoverflow.com/questions/14859405/azure-table-storage-returns-400-bad-request

But if you had

>   public class Build : TableEntity
>    {
>         public string foo { get; set} 
>    }
> 

And created a bunch of entities then added 

> public DateTimeOffset Birthday {get; set;}

 Then when you quried the exing entities you'll get a hard to understand error. Can make Birthday nullable to work around but beems like the best response would be to use the default(DateTimeOffset) value or at least give a better exception message  than

> 
> StatusMessage:Bad Request
> ErrorCode:OutOfRangeInput

**Comment by erezvani1529** [comment]
Hi @paulgmiller,

Thanks for bringing this issue to our attention. We will discuss and take a fix for it.

Just to clarify, the issue in the SO link is on inserts but you have mentioned querying the existing entities which might indicate another problem. 

Thanks,
Elham

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for support or more information. 

Thanks!
