### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout

### ISSUE THREAD

**Issue by esrpgith** [Azure/azure-storage-net#444]
I am using version 8.0.1 and trying to download a bob using DownloadRangeToByteArrayAsync(). The download range is 5 MB and getting timeout after 6 minutes. I am trying to download large files between 10 GB to 400 GB. But the timeouts are occurring after downloading 10 GB. Most of the time we see failures. But once or twice we see files getting downloaded successfully. Previously we were using 7.1.2.0 and we do not see this issue.

"Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult"1.End() in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\StorageAsyncResult.cs:line 77\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadRangeToByteArray(IAsyncResult asyncResult) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Blob\\CloudBlob.cs:line 1132\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1"1.<CreateCallback>b__0(IAsyncResult ar) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\AsyncExtensions.cs:line 66\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n

**Comment by pemari-msft** [comment]
Can you please look at your storage analytics logs and metrics to see if the latency is server or end to end latency? Please also change the value of your BlobRequestOptions.MaximumExecutionTime to be longer if you don't want it to time out as quickly. You should also rule out resource contention and network latency on your side using traces. Thanks!

**Comment by pemari-msft** [comment]
https://docs.microsoft.com/en-us/azure/storage/storage-monitoring-diagnosing-troubleshooting#troubleshooting-guidance

**Comment by erezvani1529** [comment]
Hi @esrpgith,

Please feel free to re-open this issue if you are still having issues after following the recommended changes.

Thanks,
Elham
