### ISSUE TITLE
EchoContent in batch operations

### ISSUE THREAD

**Issue by bragma** [Azure/azure-storage-net#446]
Hi,
after debugging some storage logs I found that my batch upsert response packets are very large and http status is 202 instead of 204. I suspect I a am getting echo back. Answer https://github.com/Azure/azure-storage-net/issues/65 seems to imply that upserts don't need EchoContent setting, but documentation for batch operations [here](https://docs.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions) seems to support Prefer header.
I think SDK is missing an optimization opportunity if batched upserts really support Prefer.

**Comment by erezvani1529** [comment]
Hi @bragma,

The Prefer header is only applied for insert operations and SDK seems to be working as expected (please see server docs for [Insert ](https://docs.microsoft.com/en-us/rest/api/storageservices/insert-entity) vs [Insert or Merge](https://docs.microsoft.com/en-us/rest/api/storageservices/insert-or-merge-entity)).

Please re-open if you have any other concerns with this regard.


Thanks,
Elham
