### ISSUE TITLE
Why Don't CloudQueueClient/CloudQueue Use BufferManager?

### ISSUE THREAD

**Issue by Yortw** [Azure/azure-storage-net#448]
Just wondering if there's a reason why the queuing classes (mostly) don't use the IBufferManager implementation provided via the CloudQueueClient.BufferManager property? 

The only place that seems to use it is CloudQueue.UpdateMessageImpl - everywhere else constructs MultiBufferMemoryStream with a null buffer manager and the reference to the buffer manager is commented out;

`
new MultiBufferMemoryStream(null /* bufferManager */, (int)(1 * Constants.KB));
`

I tried using annotate to see if there was a commit comment that explained this, but I didn't find one. Is this and oversight, or is there a reason not to use buffer manager?

**Comment by erezvani1529** [comment]
Hi @Yortw,

Thanks for bringing up this issue. We are tracking this item with issue #374 and our next release includes the changes to support IBufferManager for cases where it has not been added previously :).

Closing this issue to avoid duplicates and will update issue #374 once the change is out.

Thanks,
Elham

**Comment by Yortw** [comment]
Sorry about the duplicate, I *did* check first but somehow missed #374. Good to know it's coming in a newer build.

Thanks for the quick response.
