### ISSUE TITLE
CloudBlobClient.ListContainers() is not available in Net Core

### ISSUE THREAD

**Issue by tiagonmas** [Azure/azure-storage-net#449]
Trying to list all containers using .Net core but the ListContainers method is not there. ListContainersSegmentedAsync is there but not the other one !? is this the only way to list the containers in Net Core ? the ListContainersImpl method is private ...
Also, the documentation does not reflect what methods are part of .Net but not CoreCLR. How can this information be found ?

**Comment by pemari-msft** [comment]
.NET Core uses an Async-only paradigm. There is no way to have a non-segmented async version of this call, as there's no Lazy Enumeration support for Async calls in .NET.

**Comment by tiagonmas** [comment]
This should be reflected and explained in the API docs on MSDN. Currently there is no way to know what APIs are part of each framework. @polarapfel
