### ISSUE TITLE
Using WindowsAzure.Storage NugetPackage in Xamarin app causes immediate crash with NotImplementedException

### ISSUE THREAD

**Issue by leedjones** [Azure/azure-storage-net#450]
Following [this][1] article, I've created a blank Xamarin forms app, added the `WindowsStorage.Azure` package to the PCL and Android app (I've deleted iOS and UWP for now as its just a test app)  

      <package id="WindowsAzure.Storage" version="8.1.1" targetFramework="portable45-net45+win8+wp8+wpa81" />

And tried to interact with the library, but as soon as I do anything, the application crashes with an unhandled exception:

[![enter image description here][2]][2]

Whatever I do, be it create a new StorageCredentials object:

    var creds = new StorageCredentials("something", "other");

Or a new CloudStorageAccount:

    var storageAccount = CloudStorageAccount.Parse(storageConnectionString);

I get the same.
I can see from the debug window that its throwing a NotImplementedException:

    05-09 14:45:16.452 D/Mono    ( 3772): DllImport attempting to load: '/system/lib/liblog.so'.
    05-09 14:45:16.476 D/Mono    ( 3772): DllImport loaded library '/system/lib/liblog.so'.
    05-09 14:45:16.476 D/Mono    ( 3772): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
    05-09 14:45:16.476 D/Mono    ( 3772): Searching for '__android_log_print'.
    05-09 14:45:16.476 D/Mono    ( 3772): Probing '__android_log_print'.
    05-09 14:45:16.476 D/Mono    ( 3772): Found as '__android_log_print'.
    05-09 14:45:16.480 I/MonoDroid( 3772): UNHANDLED EXCEPTION:
    05-09 14:45:16.485 I/MonoDroid( 3772): System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: The method or operation is not implemented.
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor (System.String accountName, System.String keyValue, System.String keyName) [0x00006] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage.Facade\FacadeLib\Microsoft.WindowsAzure.Storage.Auth.StorageCredentials.cs:77 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor (System.String accountName, System.String keyValue) [0x00000] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage.Facade\FacadeLib\Microsoft.WindowsAzure.Storage.Auth.StorageCredentials.cs:71 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at TestApp.Droid.MainPage+<StartPolling>d__3.MoveNext () [0x0001d] in D:\XamarinAzureStorageTest\TestApp.Droid\TestApp.Droid\MainPage.xaml.cs:27 
    05-09 14:45:16.485 I/MonoDroid( 3772):    --- End of inner exception stack trace ---
    05-09 14:45:16.485 I/MonoDroid( 3772):   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at System.Threading.Tasks.Task.Wait () [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3054 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at TestApp.Droid.MainPage.StartPolling_Clicked (System.Object sender, System.EventArgs e) [0x0004e] in D:\XamarinAzureStorageTest\TestApp.Droid\TestApp.Droid\MainPage.xaml.cs:55 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () [0x00020] in C:\BuildAgent\work\ca3766cfc22354a1\Xamarin.Forms.Core\Button.cs:125 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer+ButtonClickListener.OnClick (Android.Views.View v) [0x0000b] in C:\BuildAgent\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs:298 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v) [0x00011] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.View.cs:1806 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at (wrapper dynamic-method) System.Object:0f149978-de2e-4679-a635-699ceeddec42 (intptr,intptr,intptr)
    05-09 14:45:16.485 I/MonoDroid( 3772): ---> (Inner Exception #0) System.NotImplementedException: The method or operation is not implemented.
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor (System.String accountName, System.String keyValue, System.String keyName) [0x00006] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage.Facade\FacadeLib\Microsoft.WindowsAzure.Storage.Auth.StorageCredentials.cs:77 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor (System.String accountName, System.String keyValue) [0x00000] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage.Facade\FacadeLib\Microsoft.WindowsAzure.Storage.Auth.StorageCredentials.cs:71 
    05-09 14:45:16.485 I/MonoDroid( 3772):   at TestApp.Droid.MainPage+<StartPolling>d__3.MoveNext () [0x0001d] in D:\XamarinAzureStorageTest\TestApp.Droid\TestApp.Droid\MainPage.xaml.cs:27 <---
    05-09 14:45:16.500 W/art     ( 3772): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
    05-09 14:45:16.604 D/Mono    ( 3772): DllImport searching in: '__Internal' ('(null)').
    05-09 14:45:16.604 D/Mono    ( 3772): Searching for 'java_interop_jnienv_throw'.
    05-09 14:45:16.604 D/Mono    ( 3772): Probing 'java_interop_jnienv_throw'.
    05-09 14:45:16.604 D/Mono    ( 3772): Found as 'java_interop_jnienv_throw'.
    Thread finished: <Thread Pool> #4
    The thread 'Unknown' (0x4) has exited with code 0 (0x0).
    Thread finished: <Thread Pool> #5
    05-09 14:45:57.900 D/Mono    ( 3772): [0x9b2de930] worker finishingThe thread 'Unknown' (0x5) has exited with code 0 (0x0).

Can anyone advise on the cause of this and what the resolution might be?

  [1]: https://docs.microsoft.com/en-us/azure/storage/storage-xamarin-blob-storage
  [2]: https://i.stack.imgur.com/mxWEn.png
  [3]: https://github.com/Azure/azure-storage-net

**Comment by erezvani1529** [comment]
Hi @leedjones,

Thanks for reporting your issue. 

Which version of Visual Studio are you using? 
This does not seem to be the right target(as our package supports PCL through NetStandard1.0):

>  <package id="WindowsAzure.Storage" version="8.1.1" targetFramework="portable45-net45+win8+wp8+wpa81" />

Would you please let us know how you are adding the packages to your projects?

Thanks,
Elham

**Comment by leedjones** [comment]
Hi @erezvani1529 
I'm using VS2017 Enterprise.
I created a new solution with two .net 4.5 console apps to test the queue sending and receiving. I then added a Xamarin Forms project to the solution, deleted the iOS and UWP and simply right-clicked on both the PCL and Android projects, did 'Manage Nuget Packages' and searched for "Azure Storage". WindowsAzure.Storage with the first result which I installed at v8.1.1.
I've also uninstalled it from both and installed 7.2.1 and get exactly the same behaviour.

Thanks

**Comment by erezvani1529** [comment]
@leedjones,

I am not observing any issues with the same setup as you described. So lets check to see whether your dependencies are being pulled correctly on each project:

Please check the References of the projects and verify that your PCL project is taking the storage client reference from the Netstandard1.0 path and the android project is taking its storage client dependency from Netstandard1.3 path. If that is not the case for you, would you please try with a new solution? 

Thanks,
Elham

**Comment by leedjones** [comment]
Hmmm..I created a brand new solution with just Xamarin apps and all is well, so I'm guessing its something to do with them being in a solution created using .net console apps first perhaps?

**Comment by erezvani1529** [comment]
Glad that it worked. In fact, I tried the exact setting as yours with no issues. So I believe some ordering of installation might be messing with the environment but eventually if you clean and redo everything it should work as well.

Thanks,
Elham
