### ISSUE TITLE
Update Microsoft.Azure.KeyVault.Core NuGet package to version 2.x

### ISSUE THREAD

**Issue by MJMMN** [Azure/azure-storage-net#452]
The latest (8.1.1) version of the WindowsAzure.Storage package targets Microsoft.Azure.KeyVault.Core 1.0 and is incompatible with the newer 2.0 version of KeyVault.Core.

Specifically, when attempting to use the BlobEncryptionPolicy with Microsoft.Azure.KeyVault.Core 2.0 a runtime exception is thrown:
Additional information: Method not found: 'Void Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy..ctor(Microsoft.Azure.KeyVault.Core.IKey, Microsoft.Azure.KeyVault.Core.IKeyResolver)'
More Detail: Argument 1: cannot convert from 'Microsoft.Azure.KeyVault.Core.IKey [Microsoft.Azure.KeyVault.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]' to 'Microsoft.Azure.KeyVault.Core.IKey [Microsoft.Azure.KeyVault.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]'

Downgrading my installed version of KeyVault.Core to 1.0 is not possible due to a number of interweaving dependencies including references to Microsoft.Azure.KeyVault (v2.0.6) and Microsoft.Azure.KeyVault.Extensions (for KeyVaultKeyResolver)

**Comment by erezvani1529** [comment]
Hi @MJMMN,

Have you tried using binding redirects?

**Comment by erezvani1529** [comment]
Hi @MJMMN,

Closing this issue assuming binding redirects work for you. Please re-open in case you still have more questions.

Thanks,
Elham

**Comment by Slettan** [comment]
This is still an issue.. Binding redirects are not supported in Azure functions and is therefore not a solution.

**Comment by TomasHubelbauer** [comment]
I have used a solution documented by @manfredlange in #834. In my case I wasn't able to install `Microsoft.Azure.Storage.Blob` at all.
