### ISSUE TITLE
Strugging to unit test code depending on CloudBlockBlob.GetSharedAccessSignature(...)

### ISSUE THREAD

**Issue by paulfleming2004** [Azure/azure-storage-net#453]
I noticed via #318 that many methods have been made virtual to allow for mocking. This has been immensely helpful in allowing unit testing of modules depending on this library. However, `CloudBlockBlob.GetSharedAccessSignature(...)` does not have the virtual qualifier and I'm having difficulty working around this.

I don't want to depend on the storage emulator for my unit tests, so in essence, anything that depends on a real connection could really do with being made virtual, starting with `CloudBlockBlob.GetSharedAccessSignature(...)`. :)

**Comment by pemari-msft** [comment]
This call doesn't make a network call, so it shouldn't need to be mocked, really. It can be called without the emulator or the service. Does this solve your issue?

**Comment by paulfleming2004** [comment]
@pemari-msft Thanks for the response. Ok, so I see it doesn't make network requests, yet it does break my testing code. I'm not trying to test CloudBlockBlob, but rather my module that depends on it. The error I'm getting is:
"Cannot create Shared Access Signature unless Account Key credentials are used."

The problem is that I'm not providing storage credentials to my Mock<CloudBlockBlob>. So while I can work around this, the problem still exists. I have to depend on correct configuration because I can't mock all functionality. I could abstract out code that depends on CloudBlockBlob to have a dependency on ICloudBlob but that still leaves me with two problems:
-It only gives me the superclass methods (which is ok in this example)
-It adds unnecessary complexity to my application, all for the sake of these methods being mockable.

I hope that all makes sense.

Thanks again for your help.

**Comment by paulfleming2004** [comment]
For reference my mock is now:

```
new Mock<CloudBlockBlob>(MockBehavior.Loose, 
	new Uri("http://refract.tv/container/file.ext"), 
	new StorageCredentials("fakeaccoutn", Convert.ToBase64String(Encoding.Unicode.GetBytes("fakekeyval")), "fakekeyname"));
```

My tests that depend on `GetSharedAccessSignature` now work.

**Comment by mwwhited** [comment]
I disagree with this solution.  If you add interfaces to the cloud storage objects these can be isolated and tested much cleaner.  Doing a loose mock doesn’t allow you to fully Verify your code.

**Comment by Fengyi-Li** [comment]
> For reference my mock is now:
> 
> ```
> new Mock<CloudBlockBlob>(MockBehavior.Loose, 
> 	new Uri("http://refract.tv/container/file.ext"), 
> 	new StorageCredentials("fakeaccoutn", Convert.ToBase64String(Encoding.Unicode.GetBytes("fakekeyval")), "fakekeyname"));
> ```
> 
> My tests that depend on `GetSharedAccessSignature` now work.

Hello, I know this is an old issue, but this solution did not work for me. I would get a NRE when mock CloudBlockBlob with GetSharedAccessSignature method. 

Here is the trace:
```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    CloudBlob.GetCanonicalName(Boolean ignoreSnapshotTime)
    CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy, SharedAccessBlobHeaders headers, String groupPolicyIdentifier, Nullable`1 protocols, IPAddressOrRange ipAddressOrRange)
    CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy, SharedAccessBlobHeaders headers, String groupPolicyIdentifier)
    CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy)
```
The package version is 9.3.3. It would be nice that we can find out a fix for this.

Thanks!

**Comment by blueThunder77** [comment]
> > For reference my mock is now:
> > ```
> > new Mock<CloudBlockBlob>(MockBehavior.Loose, 
> > 	new Uri("http://refract.tv/container/file.ext"), 
> > 	new StorageCredentials("fakeaccoutn", Convert.ToBase64String(Encoding.Unicode.GetBytes("fakekeyval")), "fakekeyname"));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My tests that depend on `GetSharedAccessSignature` now work.
> 
> Hello, I know this is an old issue, but this solution did not work for me. I would get a NRE when mock CloudBlockBlob with GetSharedAccessSignature method.
> 
> Here is the trace:
> 
> ```
> Message: 
>     System.NullReferenceException : Object reference not set to an instance of an object.
>   Stack Trace: 
>     CloudBlob.GetCanonicalName(Boolean ignoreSnapshotTime)
>     CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy, SharedAccessBlobHeaders headers, String groupPolicyIdentifier, Nullable`1 protocols, IPAddressOrRange ipAddressOrRange)
>     CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy, SharedAccessBlobHeaders headers, String groupPolicyIdentifier)
>     CloudBlob.GetSharedAccessSignature(SharedAccessBlobPolicy policy)
> ```
> 
> The package version is 9.3.3. It would be nice that we can find out a fix for this.
> 
> Thanks!

You're getting the NullReferenceException because your Mock<CloudBlockBlob> object's Name property is null. You can fix this using the SetupGet() method, like so:

mockCloudBlockBlob.SetupGet(_ => _.Name).Returns("testBlob");
