### ISSUE TITLE
Source code for the CosmosDB compatibility?

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-storage-net#454]
Are the updates to enable CosmosDB access going to be available in this repository? My team did a look earlier today through the branches and didn't find any recent commits.

There is a NuGet package that purports to be compatible but plus the changes; we're hoping to just see what the changes are instead of trying to reverse engineer the difference between this SDK.

The NuGet package is https://www.nuget.org/packages/WindowsAzure.Storage-PremiumTable/0.1.0-preview and is pointed to by the link https://aka.ms/premiumtablenuget and the article https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet

Thanks for any insight or making this code available!

**Comment by erezvani1529** [comment]
Hi @jeffwilcox,

As you already mentioned, this repository does not include the changes for CosmosDB/PremiumTable. The code changes for it are not yet made publicly available but as stated in the documents, the namespaces, class names and method signatures have remained the same.

We have contacted the team internally for the best place to post issues or questions and until there are official updates, here is my recommendation:

 If you see any lack of samples or documents to get you started quickly or generally any other issues, please post your issues as comments to the existing documentation or on the [DocumentDB client github repository](https://github.com/Azure/azure-documentdb-dotnet) for fastest responses.


Thanks,
Elham

**Comment by jeffwilcox** [comment]
Hi, it's been a month @erezvani1529 - does this mean that the storage SDK is no longer an open source project and this repo is being deprecated?

Or did the Cosmos team just do their own thing without a plan for actually reintegrating the changes?

Would love to help contribute to the storage Node.js and Java SDKs an implementation that works with Cosmos, and was hoping to be able to use the work done by the Cosmos team here to help contribute to the community... feels like a win-win, but not if it's a closed project.

**Comment by mirobers** [comment]
@jeffwilcox there seems to be a misunderstanding. CosmosDB is not part of storage and will not be included in the storage SDK. The code is maintained by the CosmosDB team and will make its way into the CosmosDB SDK. The best place for you to contribute to and give feedback on this effort is the repo linked above by @erezvani1529.

**Comment by erezvani1529** [comment]
@jeffwilcox ,

Here is the official alias for all CosmosDB related questions: `askcosmosdb at microsoft dot com`

Thanks,
Elham

**Comment by jeffwilcox** [comment]
Closing as it sounds like the forked SDK will remain forked.
