### ISSUE TITLE
Blob.OpenReadAsync calls HEAD before GET, doubling calls of small files

### ISSUE THREAD

**Issue by jerickmsft** [Azure/azure-storage-net#455]
Seems quite inefficient. Is there any way to avoid this with this library? We've changed our code to use a standard HttpClient because of this.

```
        public virtual Task<Stream> OpenReadAsync(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
        {
            return Task.Run<Stream>(async () =>
            {
                await this.FetchAttributesAsync(accessCondition, options, operationContext, cancellationToken);
                AccessCondition streamAccessCondition = AccessCondition.CloneConditionWithETag(accessCondition, this.Properties.ETag);
                BlobRequestOptions modifiedOptions = BlobRequestOptions.ApplyDefaults(options, this.BlobType, this.ServiceClient, false);
                return new BlobReadStream(this, streamAccessCondition, modifiedOptions, operationContext);
            }, cancellationToken);
        }
```

**Comment by pemari-msft** [comment]
It's very efficient in the case of a large upload, where the upload would only fail for the Etag after the whole blob has been uploaded.  If it's a small upload, any reason to call ``OpenRead`` instead of `UploadFromStream`?

**Comment by erezvani1529** [comment]
Hi @jerickmsft,

This call was initially added for a couple of reasons such as making sure the data hasn't changed after the stream is opened when the application starts to read from it, or, to fast fail in case the container/blob does not exist before opening the stream.
However, we are considering to remove this check in our next breaking change release and will use this issue to track this change.

Thanks,
Elham

**Comment by johnterickson** [comment]
If others want to pick up from here, I can tell you what my team's tool does.  Our tool downloads blobs as 8MB segment in parallel.  When it doesn't know the size of the blob, it first does a single GET call with Range:0-8MB.  The response will return:

1. whether the blob exists or not
2. the Etag of the blob
3. the size of the whole blob
4. the first and last byte indices of the content in the response
5. the whole blob contents if the blob is <= 8MB *or* the first segment if it is larger

With this one call, we're either done (blob is <= 8MB) or able to kick off the rest of the segment downloads in parallel.
