### ISSUE TITLE
Storage Exception on Blob.UploadTextAsync - InvalidBlockList

### ISSUE THREAD

**Issue by leroibeukes** [Azure/azure-storage-net#456]
Error returned :

`{
  "ErrorCode": "InvalidBlockList",
  "ErrorMessage": "The specified block list is invalid.\nRequestId:f31c101a-0001-0031-075e-d0c218000000\nTime:2017-05-19T05:15:53.0372722Z",
  "AdditionalDetails": {}
}`

StackTrace:
`[0]   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadFromStream(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 776
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at .....
`

My Code `
  await blob.UploadTextAsync(content, null, null, bro, null);
`

**Comment by mirobers** [comment]
This can happen when a concurrent upload commits after you have started to upload but before you commit. In that case, your upload fails. You can retry this error or attempt some other recovery action based on your scenario.

**Comment by leroibeukes** [comment]
Mmmm - Ok  - So then either the Storage Library should handle it , OR in this case we have to basically disable the parallel option in the blob request options and/or implement a custom retry mechanism... 

We've gone for the retry option ... Let's see how it holds up.

Incidentally found this article :  
[(https://azure.microsoft.com/en-us/blog/azure-storage-client-library-retry-policy-recommendations/)]

Buried as a 'throw away comment' is this little gem : 
>  Also, the retry policy classes do not retry on 4xx status codes. There are a few others as well (currently 306, 501 and 505).

It would be helpful if this was provided as a note on the retry policies :)

Thanks for the feedback.

**Comment by mirobers** [comment]
@leroibeukes, this is not caused by parallelism within an API. This would happen when you call two upload APIs concurrently on the same blob.

For my information, what is the size of your upload? The default retry policy does not make assumptions about how you want to handle write conflicts, but we'll take it as a feature request to give you a better error message in this case.

**Comment by leroibeukes** [comment]
Thanks for clearing that up Michael - It's about 50kb , very small.

The scenario you describe sounds familiar  ... we are uploading the content and updating the properties straight afterwards ... 

  await blob.UploadTextAsync(content, null, null, bro, null);
  await blob.SetPropertiesAsync(null, bro, null);

How would you suggest we handle this ?

Thanks for the help

**Comment by leroibeukes** [comment]
Ok - So turns out we were receiving concurrent requests and assumed optimistic concurrency would work for us ... it didn't. We've deployed a new version using leases (pessimistic concurrency) and this has helped us resolve the issue. Thanks for the help in pin-pointing the problem.
