### ISSUE TITLE
Deadlocks occur when querying table storage many times concurrently (.NET Core 1.1.0) 

### ISSUE THREAD

**Issue by benharden** [Azure/azure-storage-net#457]
I'm having trouble with some deadlocks when querying table storage many times simultaneously. This happens whether I call cloudTable.ExistsAsync() and cloudTable.ExecuteQuerySegmentedAsync().

Having downloaded the source code for 8.1.1, I can see that the root of the issue seems to be in [TableOperationHttpResponseParsers.cs](https://github.com/Azure/azure-storage-net/blob/v8.1.1/Lib/WindowsRuntime/Table/Protocol/TableOperationHttpResponseParsers.cs#L436). The problem is that instances of ODataReader are calling the Read() method when they should be taking advantage of the available ReadAsync() method.

Are these issues going to be fixed in the 8.2.0 release? My problem could be related to https://github.com/Azure/azure-storage-net/issues/431

The scenario can be reproduced with a simple Console Application (.NET Core 1.1.0) and using the following code sample:

```csharp
private const string connectionString = "...";
private const string tableName = "...";

public static void Main(string[] args)
{
    Task.Run(async () =>
    {
        await MainAsync(args);
    }).GetAwaiter().GetResult();
}

static async Task MainAsync(string[] args)
{
    Console.WriteLine("Hello World!");
            
    var cloudStorageAccount = CloudStorageAccount.Parse(connectionString);
            
    // run the query many times simultaneously to produce the thread lock issue
    await Task.WhenAll(Enumerable.Range(0, 100).Select(m =>
    {
        return Query(cloudStorageAccount);
    }));

    Console.WriteLine(string.Format("We never get here..."));

    Console.ReadLine();
}

private static async Task<bool> Query(CloudStorageAccount cloudStorageAccount)
{
    var cloudTableClient = cloudStorageAccount.CreateCloudTableClient();
    var cloudTable = cloudTableClient.GetTableReference(tableName);

    Console.WriteLine(string.Format("Exists query started"));

    // threadlock occurs here when calling table.ExistsAsync() or table.ExecuteQuerySegmentedAsync()
    var result = await cloudTable.ExistsAsync();

    Console.WriteLine(string.Format("Exists query finished"));

    return result;
}
```

**Comment by mirobers** [comment]
Unfortunately, ReadAsync in the OData lib is just a wrapper around a synchronous implementation so it won't help. We are working on fixing this, but it is a large change that will come with #372. For now, I suggest you increase your threadpool size to avoid thread exhaustion.

**Comment by ms-aprima** [comment]
We are running across this issue as well. We were running ExecuteQuerySegmentedAsync 100 at a time. We had to back it off to 25 (determined empirically) to prevent our async WebJob function from timing out.

**Comment by benharden** [comment]
I've tried increasing the threadpool size by adding the following to the my project's csproj:

<ThreadPoolMinThreads>4</ThreadPoolMinThreads>
<ThreadPoolMaxThreads>25</ThreadPoolMaxThreads>

This hasn't made any discernible difference and still threadlocks. Am I doing this correctly?

Is there any other way I can use the azure-storage-net table library and not have it lock up on me? This is causing us a real headache on our production system and it seems ridiculous that we can't make 100 calls to the server without it locking up.

**Comment by erezvani1529** [comment]
Hi @benharden . @ms-aprima ,

As mentioned in #372 we are tracking a work-item to remove our dependency to ODataLib and this issue is one of the main the main contributors to this decision (async APIs in ODataLib are wrappers over sync ones which lead to thread exhaustion eventually depending on the environment configuration.) 

The current workaround for this issue is to find the threshold up to which the increase in the ThreadPool size does not cause significant performance hit. Have you tried moving above the limit of 25 or even removing the limit on the max number of threads in the thread pool?

Thanks,
Elham

**Comment by raRaRa** [comment]
I'm also running into deadlocks because of the exact same reason. Over 700 threads waiting for something in OData to complete.

**Comment by flagbug** [comment]
Same problem here, this is super annoying and causes deadlocks at a high enough request throughput

**Comment by unaizorrilla** [comment]
+1 here.. any update about this issue

**Comment by erezvani1529** [comment]
Thank you for reporting your issue regarding the problematic OData references in the library and for your patience.

We have released the package([v9.0.0](https://www.nuget.org/packages/WindowsAzure.Storage/9.0.0)) in which these dependencies have been removed. We expect this issue to be resolved using v9.0.

Please let us know if you experience any other problems.

Thanks again!

**Comment by antonGritsenko** [comment]
@erezvani1529 looks like this is still the issue. We using 9.3.2 with .net 4.6.2 and it just locked when we try to query table from several threads:

```
private static async Task<CloudTable> GetOrCreateBlobTable(string tableName, string storageTableConnectionString)
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageTableConnectionString);
            // Create the table client.
            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            // Retrieve a reference to the table.
            CloudTable table = tableClient.GetTableReference(tableName);

            // Create the table if it doesn't exist.
            if(!await  table.ExistsAsync()) // <-- this never finished
                await table.CreateAsync();
            return table;
        }
```

**Comment by mishas2303** [comment]
> @erezvani1529 looks like this is still the issue. We using 9.3.2 with .net 4.6.2 and it just locked when we try to query table from several threads:
> 
> ```
> private static async Task<CloudTable> GetOrCreateBlobTable(string tableName, string storageTableConnectionString)
>         {
>             CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageTableConnectionString);
>             // Create the table client.
>             CloudTableClient tableClient = storageAccount.CreateCloudTableClient();
> 
>             // Retrieve a reference to the table.
>             CloudTable table = tableClient.GetTableReference(tableName);
> 
>             // Create the table if it doesn't exist.
>             if(!await  table.ExistsAsync()) // <-- this never finished
>                 await table.CreateAsync();
>             return table;
>         }
> ```
> 
> PS yes, I know about CreateIfNotExists() method. The code above just to ensure that it's not a problem with some specific method.

Agree with @antonGritsenko, we're also using 9.3.2 and experience major deadlock issue causing customer timeouts for a week until we rolledout the hotfix by skipping exists and create check.

**Comment by mishas2303** [comment]
@erezvani1529 Please help fix in newer sdk.
