### ISSUE TITLE
Regular unicode character 'č' not accepted in blob metadata value

### ISSUE THREAD

**Issue by jbinko** [Azure/azure-storage-net#458]
Try following code.
It will fail with the exception
Microsoft.WindowsAzure.Storage.StorageException: 'Specified value has invalid CRLF characters.
during call UploadFromFile. The problem is character 'č'. But it is frequent regular unicode character.

var blob = CloudBlobContainer.GetBlockBlobReference(blobUniqueName);
blob.Metadata.Clear();
blob.Metadata.Add("FileName", "Bezpečnost.msg");
blob.UploadFromFile(filePath);

It should work for all Czech specific characters. After fix I expect this line should work fine.
blob.Metadata.Add("FileName", "Příliš žluťoučký kůň úpěl ďábelské kódy. PŘÍLIŠ ŽLUŤOUČKÝ KŮŇ ÚPĚL ĎÁBELSKÉ KÓDY.");

**Comment by erezvani1529** [comment]
Hi @jbinko,

This behavior is expected as we do not support non-ASCII characters in headers(metadata being one of them). Please see the check within the [WebHeaderCollection ](http://referencesource.microsoft.com/#System/net/System/Net/WebHeaderCollection.cs,9d11c9ec2ddc1887) which is applying the restriction. A similar check is applied on server side as well. 

Please re-open the issue in case you need more details.

Thanks,
Elham

**Comment by jbinko** [comment]
Hi,
This is actually very unfortunate.
If I understand you correctly you are saying there is no way to store into metadata values in Unicode format. We can only store into values ASCII characters.
Correct?
This would be very weak capability.

Thanks
Jiri

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
