### ISSUE TITLE
CloudBlockBlob.DownloadText() handles UTF8 BOM incorrectly

### ISSUE THREAD

**Issue by rzio** [Azure/azure-storage-net#46]
CloudBlockBlob.DownloadText() behaves differently than File.ReadAllText in respect to UTF8 pre-amble/BOM

Repro:
Create an XML File in Visual Studio and upload it to a Cloud Blob container. The file will begin with a BOM (EF BB BF). Then download it using CloudBlockBlob.DownloadText() and pass the resulting string to XDocument.Parse. The parser will fail with XMLException - "Data at the root level is invalid. Line 1, position 1.".
Failing code:

    var storageAccount = CloudStorageAccount.Parse("connectionString");
    var blobClient = storageAccount.CreateCloudBlobClient();
    var container = blobClient.GetContainerReference("MyContainer");
    var blob = container.GetBlockBlobReference("my.xml");
    var s = blob.DownloadText();
    var x = XDocument.Parse(s);

A workaround suggested at http://stackoverflow.com/questions/2111586/parsing-xml-string-to-an-xml-document-fails-if-the-string-begins-with-xml by Dave Cluderay suggests passing the read string through StreamReader.
Working code

            var storageAccount = CloudStorageAccount.Parse("connectionString");
            var blobClient = storageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("MyContainer");
            var blob = container.GetBlockBlobReference("my.xml");
            var s = blob.DownloadText();
            using (var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(s)))
            {
                using (var streamReader = new StreamReader(memoryStream))
                {
                    var x = XDocument.Load(streamReader);
                }
            }

Moved from https://github.com/Azure/azure-sdk-for-net/issues/626#

**Comment by mirobers** [comment]
We have evaluated this issue. When a blob is downloaded using DownloadText(), we apply an encoding to construct a string (by default, we use .NET's UTF-8 implementation). Applying the encoding to the string does not strip out the BOM. We could detect and strip out the BOM ourselves, but this is a potentially surprising transformation of the blob's original data, especially given that the Content-Encoding header might also be specified on the blob with conflicting info.
 
See also that the same behavior exists in WebClient.DownloadString: http://stackoverflow.com/questions/1317700/strip-byte-order-mark-from-string-in-c-sharp
 
Note that you can pass your own Encoding implementation that strips out the BOM in the call to GetString() if this behavior is desired.
 
I am closing this old issue now; feel free to raise another issue if you have additional concerns related to encoding.

**Comment by GuardRex** [comment]
@joefeser :+1: I'm way late to the party, but ...

> We could detect and strip out the BOM ourselves, but this is a potentially surprising transformation of the blob's original data

It would have been nice though to have an overload `.DownloadText(bool stripByteOrderMark)`, so that the original method would just do the "unsurprising" thing and the overload would allow the dev to explicitly call for stripping the BOM.

**Comment by hermesramos** [comment]
Microsoft Famous' Crapware. I cannot believe it. I am uploading a text file using UploadFromFile and then downloading it later using DownloadText. If I compare the original file, with the downloaded string, c# tells me they are different.

**Comment by r-aghaei** [comment]
I created an extension method `DownloadString` for `CloudBlockBlob` and used the same code which is used in `WebClient.DownloadString`. Here you can find the code: [How to get rid of BOM when downloading text from azure blob](http://www.reza-aghaei.com/how-to-get-rid-of-bom-when-downloading-text-from-azure-blob/)

**Comment by freakydinde** [comment]
$content = $blob.ICloudBlob.DownloadText()

    $byteOrderMarkUtf8 = [Text.Encoding]::UTF8.GetString([Text.Encoding]::UTF8.GetPreamble())
    
    if ($content.StartsWith($byteOrderMarkUtf8))
    {
        $content = $content.Remove(0, $byteOrderMarkUtf8.Length)
    }
