### ISSUE TITLE
WindowsAzure.Storage 8.1.2 has broken strong name

### ISSUE THREAD

**Issue by Suchiman** [Azure/azure-storage-net#460]
After updating from 8.1.1 to 8.1.2 i now get the following exception at startup.
```
System.IO.FileLoadException: "Could not load file or assembly "Microsoft.WindowsAzure.Storage, Version=8.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)"
```

I've cleared the nuget cache and reproduced in a .NET 4.6.2 console application.

**Comment by rksvHackler** [comment]
on a clean project?
Otherwise check your app.config and specifically the version redirections in assemblyBindings.

```
 <dependentAssembly>
 			<assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
 			<bindingRedirect oldVersion="0.0.0.0-8.2.0.0" newVersion="8.2.0.0" />
 		</dependentAssembly>
```

just 2 cents.

**Comment by rksvHackler** [comment]
Sorry, maybe my 2 cents were just away from your real problem. Didn´t read the the strong name thing... 
sorry.

**Comment by jkonecki** [comment]
I can confirm 8.1.2 is not signed. Please sign the assembly and publish new package.

**Comment by erezvani1529** [comment]
Thank you for bringing this to our attention. We are publishing a new package immediately.

There seems to be a problem with our new build and signing environment.

**Comment by erezvani1529** [comment]
Please update to [version 8.1.3](https://www.nuget.org/packages/WindowsAzure.Storage/8.1.3) to resolve this issue. We apologize for the inconvenience once more.

Thanks,
Elham
