### ISSUE TITLE
Mock BlobResultSegment

### ISSUE THREAD

**Issue by tverboon** [Azure/azure-storage-net#463]
In #335 this class is not sealed anymore, but I still have a hard time mocking this class with Moq as the constructor is internal and results in an exception.

`System.NotSupportedException : Parent does not have a default constructor. The default constructor must be explicitly defined.`

I tried to go with reflection, but fieldInfo is always null.

```
var segment = System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof(BlobResultSegment));
var fieldInfo = typeof(BlobResultSegment).GetField(@"Results");
```

I even tried to GetFields with a lot BindingFlags, but then I only got the private backing fields and not the public fields.

```
BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic |
                         BindingFlags.Static | BindingFlags.Instance |
                         BindingFlags.DeclaredOnly;
```

The goal to unseal the class was to be able to mock it. What is the best solution to mock this class?

My not so pretty work around is as follows:

```
private BlobResultSegment CreateResultSegment(CloudBlockBlob blob)
        {
            BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic |
                         BindingFlags.Static | BindingFlags.Instance |
                         BindingFlags.DeclaredOnly;

            var segment = System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof(BlobResultSegment));
            var fields = segment.GetType().GetFields(flags);
            var fieldInfo = fields.First(f => f.Name.Contains(@"Results"));

            fieldInfo.SetValue(segment, new[] { blob });
            return (BlobResultSegment)segment;
        }
```

**Comment by PureKrome** [comment]
@tverboon out of interest, can you provide some code to how you use a `BobResultSegment` in some normal code (not mocks, etc)

I would like to see how it's used, to then understand how it could be mocked (regardless if the mocking doesn't work, currently). This way, we can help _show_ the MS Team how we are using their code and suggest how/what should be fixed.

Example reference to another Issue re: mocked => https://github.com/Azure/azure-storage-net/issues/465

**Comment by tverboon** [comment]
We have wrapped the Storage methods in a class and thanks to you, @PureKrome,  and the Storage team, I could test almost everything. The only method I had some difficulties was this one:

```csharp
public async Task<IEnumerable<BlobFile>> ListBlobsAsync(string containerName)
{
    var container = GetContainerReference(containerName);
    var result = await container.ListBlobsSegmentedAsync(null, true, BlobListingDetails.None, null, null, null, null);

    return result.Results.Select(blobItem =>
    {
        var blob = blobItem as CloudBlockBlob;
        return new BlobFile
        {
            Name = blob.Name.Substring(blob.Name.TrimEnd('/').LastIndexOf('/') + 1),
            RelativePath = blob.Name,
            Container = blob.Container.Name,
            ContentType = blob.Properties.ContentType,
            ContentMD5 = blob.Properties.ContentMD5,
            LastModified = blob.Properties.LastModified.HasValue ? blob.Properties.LastModified.Value.UtcDateTime : DateTime.UtcNow
        };
    });
}

private CloudBlobContainer GetContainerReference(string container)
{
    return GetContainerReference(_cloudBlobClientFactory.CreateCloudBlobClient(), container);
}

private CloudBlobContainer GetContainerReference(CloudBlobClient blobClient, string container)
{
    return blobClient.GetContainerReference(container);
}
```

The ICloudBlobClientFactory is injected in the constructor, to create a mocked CloudBobClient in our unit tests. It basically wraps CloudStorageAccount.

```csharp
public class CloudBlobClientFactory : ICloudBlobClientFactory
{
    private readonly CloudStorageAccount _storageAccount;

    public CloudBlobClientFactory(IOptions<StorageConnectionSetting> connectionSetting)
    {
        if (connectionSetting?.Value?.ConnectionString == null)
        {
            throw new ArgumentNullException(nameof(connectionSetting));
        }
        _storageAccount = CloudStorageAccount.Parse(connectionSetting.Value.ConnectionString);
    }

    public CloudBlobClient CreateCloudBlobClient()
    {
        return _storageAccount.CreateCloudBlobClient();
    }
}
```

The following line needs to return a mocked `BlobResultSegment`:

```csharp
var result = await container.ListBlobsSegmentedAsync(null, true, BlobListingDetails.None, null, null, null, null);
```

**Comment by erezvani1529** [comment]
Thanks @tverboon, @PureKrome 

Thanks for sharing the information and the workaround for the issue (which seems to be the only working one).

As mentioned in #465, we are discussing improvements to increase mock-ability of our library(by either virtualizing the properties and adding default constructors or adding interfaces for the types). These changes once pinned down, will be included in our next breaking change release(9.0) and we will announce the final decision on this. Shall we use #465 to track this task and close the related ones such as this issue?

Thanks,
Elham

**Comment by PureKrome** [comment]
Awesome stuff @erezvani1529 :)

Yep - lets use #465 to track this task, as you have suggestion.

**Comment by tverboon** [comment]
Sounds good to me @erezvani1529 👍

**Comment by pb-qs** [comment]
@tverboon Did you find a way to mock the call to `await container.ListBlobsSegmentedAsync` and get a mocked `BlobResultSegment` ?  - I had the issue creating the `BlobResultSegement` return value which brought me here.

I ended up with a bit of `Activator.CreateInstance` code in my xUnit tests....  copied below in case it helps anyone:

        private BlobResultSegment CreateTestBlobResultSegment(bool continuationToken, params CloudBlockBlob[] blobs)
        {
            const BindingFlags bindingFlags = BindingFlags.NonPublic | BindingFlags.Instance;
            BlobContinuationToken token = continuationToken ? new BlobContinuationToken() : null;
            object[] internalCtorArgs = { blobs, token };
            object obj = Activator.CreateInstance(typeof(BlobResultSegment), bindingFlags, null, internalCtorArgs, null);
            return obj as BlobResultSegment;
        }

**Comment by tverboon** [comment]
You need to mock your container an then some. I did something like this.

```csharp
var blob = new Mock<CloudBlockBlob>(new Uri("http://storageaccount/container/blob")).Object;
var cred = new StorageCredentials("account", Convert.ToBase64String(Encoding.Unicode.GetBytes("key")), "keyname");
var containerMock = new Mock<CloudBlobContainer>(new Uri("http://storageaccount/container"), cred);
containerMock.Setup(c => c.GetBlockBlobReference(It.IsAny<string>()))
                    .Returns(blob);

containerMock.Setup(c => c.ListBlobsSegmentedAsync(null, true, BlobListingDetails.None, null, null, null, null))
                    .ReturnsAsync(CreateResultSegment(blob));
```

**Comment by pb-qs** [comment]
@tverboon Yeah, thanks for that.  I'd got the rest working, but just wanted to make sure I'd shared the 'unusual' part, having come past this issue myself when digging.  Cheers
