### ISSUE TITLE
Service bus do not return number of deduped messages

### ISSUE THREAD

**Issue by vineetmangla** [Azure/azure-storage-net#466]
Service bus provide dedupe functionality but is there anyway by which we can get the number of messages it deduped for the respective deduped time window?

**Comment by erezvani1529** [comment]
Hi @vineetmangla,

I believe [this ](https://github.com/Azure/azure-service-bus-dotnet) is the right repository to ask Service Bus related questions. Please do not hesitate to re-open this issue if you have questions about details in Storage Client Library.

Thanks,
Elham
