### ISSUE TITLE
HttpStatusMessage get values that corresponds to other HttpStatusCodes

### ISSUE THREAD

**Issue by austvik** [Azure/azure-storage-net#467]
When we have high load on our servers, we sometimes see HttpStatusCode 408 with unexpected status messages, like "Accepted", "OK", "Created", or "No Content". We have seen it both for BLOBs and Queue messages.

We have (with ClientRequestId) checked with Azure Storage backend engineers that they are not returning this, so it is a client side issue.

Concurrency issue?

**Comment by mirobers** [comment]
When you see a 408 status code, the requests timed out on the client side. This is configured using the MaximumExecutionTime property in BlobRequestOptions. This is a limit on the total time for the API call, including retries. So it is expected that you could see a 408 along with the status message returned by the service. In this case, you hit a client-side timeout after receiving the HTTP headers from the service. Let me know if you have more questions about this behavior.
