### ISSUE TITLE
WindowsAzure.Storage <= 8.1.4 not mapping new LAD 3.0 TableEntity fields

### ISSUE THREAD

**Issue by AaronHofer** [Azure/azure-storage-net#474]
Linux Azure Diagnostic (LAD) version 3.0 was released recently which added some additional fields we needed (ident, pid among others), but it appears that the API is not picking them up.  I added the new fields to my derived class but the values are always empty strings even though I can see the real data with Azure Storage Explorer.

Example, i'm trying to grab the newly added "ident" and "pid" columns, and while it still grabs the legacy fields, ident and pid values for each record queried are empty strings.

public class LinuxLogEntity : TableEntity
    {
        public LinuxLogEntity() { }
        public string ident { get; set; }
        public string pid { get; set; }
        public DateTime TimeStamp { get; set; }
        public DateTime EventTime { get; set; }
        public string Facility { get; set; }
        public string Host { get; set; }
        ... etc....

Please advise, thanks.

**Comment by jasonzio** [comment]
Did you use a tool like Azure Cloud Explorer to confirm there was actually data in those columns in the time window you were querying?

**Comment by AaronHofer** [comment]
Correct.

**Comment by AaronHofer** [comment]
Tested with API 8.1.4, still having the same issue.

**Comment by erezvani1529** [comment]
Hi @AaronHofer,

Apologies for the delay in response. A few questions to help identify the issue:

- Which framework are you targeting?
- Would you please share the logic of how you are querying the data? I am specifically interested in whether or not an Entity Resolver is being used as a projection on the query results.
- Is there any logic in LinuxLogEntity which would override the WriteEntity method on the parent TableEntity class that might need an update?

Thanks,
Elham

**Comment by AaronHofer** [comment]
Hi @erezvani1529,

I'm using C#, VS 2017.  This code works, i.e. it captures all the fields it should, except for the new ones added by LAD 3.0.  

                     
```
   CloudStorageAccount storageAccount = new CloudStorageAccount(new Microsoft.WindowsAzure.Storage.Auth.StorageCredentials(currentName, currentKey), true);
                        CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

                        try
                        {
                            CloudTable table = tableClient.GetTableReference("LinuxsyslogVer2v0");

                            TableQuery<LinuxLogEntity> query = new TableQuery<LinuxLogEntity>().Where(
                                TableQuery.CombineFilters(
                                    TableQuery.GenerateFilterConditionForDate("EventTime", QueryComparisons.GreaterThanOrEqual, acct.StartingDateTime),
                                    TableOperators.And,
                                    TableQuery.GenerateFilterConditionForDate("EventTime", QueryComparisons.LessThan, acct.EndingDateTime)));
```


Here's my Linux Table Entity class:

` public class LinuxLogEntity : TableEntity
    {
        public LinuxLogEntity() { }

        public string ident { get; set; }
        public string pid { get; set; }
        public DateTime TimeStamp { get; set; }
        public DateTime EventTime { get; set; }
        public string Facility { get; set; }
        public string Host { get; set; }
        public string ignore { get; set; } 
        public string Msg { get; set; }
        public string N { get; set; } 
        public DateTime PreciseTimeStamp { get; set; }  
        public string RowIndex { get; set; }  
        public string SendingHost { get; set; }
        public int Severity { get; set; }
        public DateTime TIMESTAMP { get; set; }   
   }
`

**Comment by erezvani1529** [comment]
@AaronHofer ,

Would you please create a test partition and enter a few entities into it and try retrieving the entities within that partition only and share the fiddler trace here? Also just to make sure, are you running against the Emulator or a storage account?

Thanks,
Elham

**Comment by AaronHofer** [comment]
@erezvani1529 ,

It's a storage account.  This is C# on Windows desktop, not a web app.  This was with a brand new storage account, did you try my code?

**Comment by erezvani1529** [comment]
@AaronHofer,

I was not able to repro a similar issue. It would be great if you could share some fiddler trace with us so that we can investigate using information on what is being transferred over the wire. 

Thanks,
Elham

**Comment by AaronHofer** [comment]
I was able to get this to work.  I discovered that events generated by LAD 3.0 can't be queried by using the "EventTime" field, even though those values are populated I never get any results.  Once I switched to using "TimeStamp" instead, I got all the events plus the extra data I needed.  

`TableQuery<LinuxLogEntity> query = new TableQuery<LinuxLogEntity>().Where(
                                    TableQuery.CombineFilters(
                                        TableQuery.GenerateFilterConditionForDate("Timestamp", QueryComparisons.GreaterThanOrEqual, StartingDateTime), 
                                        TableOperators.And,
                                        TableQuery.GenerateFilterConditionForDate("Timestamp", QueryComparisons.LessThan, EndingDateTime)));  
`

**Comment by erezvani1529** [comment]
Thanks @AaronHofer for providing the information.
