### ISSUE TITLE
Cannot create database 'AzureStorageEmulatorDb51' : The database 'AzureStorageEmulatorDb51' does not exist. Supply a valid database name. To see available databases, use sys.databases..

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-storage-net#476]
Hi,

I have the last version of Azure Storage explorer, when i try to launch the service I have this error:
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe start
Windows Azure Storage Emulator 5.1.0.0 command line tool
Autodetect requested. Autodetecting SQL Instance to use.
Looking for a LocalDB Installation.
Probing SQL Instance: '(localdb)\MSSQLLocalDB'.
Found a LocalDB Installation.
Probing SQL Instance: '(localdb)\MSSQLLocalDB'.
Found SQL Instance (localdb)\MSSQLLocalDB.
Creating database AzureStorageEmulatorDb51 on SQL instance '(localdb)\MSSQLLocalDB'.
_Cannot create database 'AzureStorageEmulatorDb51' : The database 'AzureStorageEmulatorDb51' does not exist. Supply a valid database name. To see available databases, use sys.databases..
One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
Error: The storage emulator needs to be initialized. Please run the 'init' command._

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>cmd /K AzureStorageEmulator.exe help
Windows Azure Storage Emulator 5.1.0.0 command line tool
Usage:
    AzureStorageEmulator.exe init            : Initialize the emulator database and configuration.
    AzureStorageEmulator.exe start           : Start the emulator.
    AzureStorageEmulator.exe stop            : Stop the emulator.
    AzureStorageEmulator.exe status          : Get current emulator status.
    AzureStorageEmulator.exe clear           : Delete all data in the emulator.
    AzureStorageEmulator.exe help [command]  : Show general or command-specific help.

See the following URL for more command line help: http://go.microsoft.com/fwlink/?LinkId=392235

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>

It seems to be a known problem, but this fix didnt work for me:
http://www.hackered.co.uk/articles/azure-storage-emulator-init-cannot-create-database

**Comment by kfarmer-msft** [comment]
The link you point to misses a couple steps that could prove useful.  We suggest trying the procedure we've outlined here, which includes deleting the mdf and ldf files:  https://stackoverflow.com/questions/29239053/azure-storage-emulator-fails-after-adding-vs-2015-sdk/29239714#29239714

**Comment by ranouf** [comment]
I did the first 2 step but not delete the file, it s now working :)

Thanks @kfarmer-msft
