### ISSUE TITLE
Querying on blob metadata

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [Azure/azure-storage-net#478]
Hi Team,   do we have any option for querying blob Metadata. In my blob container I have 50000 blobs. I want to fetch blob querying Metadata.

**Comment by pemari-msft** [comment]
You can do a [list blobs with the Metadata details](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Blob/BlobListingDetails.cs#L41) or you can do a head request on the blobs to get the metadata (GetMetadata call).

**Comment by AbhishekAdusumilli** [comment]
I want to filter blob  using Metadata.

**Comment by pemari-msft** [comment]
You can filter on the client side after you've listed the blobs. There's no way to filter on the server side.

**Comment by vanillajonathan** [comment]
@pemari-msft Any example on how to do this?
