### ISSUE TITLE
ListBlobs method returns duplicate CloudBlobDirectory

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-storage-net#483]
We found this issue yesterday, it occurred in particular account and particular path. I found https://github.com/Azure/azure-storage-net/issues/396, but I can reproduce always in my test case.

**Comment by zhiweiv** [comment]
```
public static void HandleBlobs(CloudBlobContainer container, string prefix = null)
{
	var blobs = container.ListBlobs(prefix);
	foreach (var item in blobs)
	{
		if (item.GetType() == typeof(CloudBlobDirectory))
		{
			var dir = (CloudBlobDirectory)item;
			HandleBlobs(dir);
		}
	}
}

private static void HandleBlobs(CloudBlobDirectory dir)
{
	var blobs = dir.ListBlobs();
	foreach (var item in blobs)
	{
		if (item.GetType() == typeof(CloudBlobDirectory))
		{
			Console.WriteLine(item.Uri);
		}
	}
	foreach (var item in blobs)
	{
		if (item.GetType() == typeof(CloudBlobDirectory))
		{
			var subDir = (CloudBlobDirectory)item;
			HandleBlobs(subDir);
		}
	}
}
```

```
[TestMethod]
public void TestHandleBlobs()
{
	var conn = StorageUtil.GetBlobClient("AccountName", "AccessKey");
	var container = conn.GetContainerReference("ContainerName");
	StorageUtil.HandleBlobs(container, "data_granular/Remote Farm/PLAN20150819011259282723");
}
```
 I used the latest storage library 8.1.4.

The result
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170523131017980895/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170524131018185946/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170523131017980895/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170524131018185946/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170523131017980895/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170524131018185946/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/FB20170519131014800058/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170523131017980895/
/data_granular/Remote Farm/PLAN20150819011259282723/FB20170519131014800058/IB20170524131018185946/

**Comment by erezvani1529** [comment]
Hi @zhiweiv,

Thank you for bringing this issue to our attention. As mentioned in #396 this requires a fix on server side which is deployed already but disabled in some cases due to a misconfiguration. We have followed up internally and the configuration which has caused the fix NOT to be effective will be fixed very soon.

If this issue is blocking you, please share your account information with us emailing `ascl at microsoft dot com `  so that we prioritize accordingly.

Thanks,
Elham

**Comment by zhiweiv** [comment]
Thanks erezvani1529, I have sent an email to ascl with our storage account, please help to fix on it first, it is used in our production environment.

**Comment by erezvani1529** [comment]
Hi @zhiweiv,

The configuration issue should be fixed for your account now. Please let us know if you are seeing any more issues.

Thanks,
Elham

**Comment by zhiweiv** [comment]
The issue has gone, thanks very much.
