### ISSUE TITLE
Performance issue with ExecuteQuerySegmentedAsync

### ISSUE THREAD

**Issue by raRaRa** [Azure/azure-storage-net#489]
I've been running into a strange issue where my web app suddenly deadlocks with around 600-700 threads running. I managed to get memory dump when the issue occurred and it seems like 99% of the threads are waiting on `TableOperationHttpResponseParser`.

For Table queries I use `ExecuteQuerySegmentedAsync`. Everything is as async (with await of course) as it can be. Is there any particular reason why this could be happening?

I'm using WindowsAzure.Storage 8.1.4 (.NET Standard 1.4 class lib), the app itself is running on netcoreapp1.1.2.

Here's a screenshot of the `Parallel Stacks` from the memory dump.

![Image](https://camo.githubusercontent.com/0f7ad3d3c1cf839ee5f45ada5146540104434c81/687474703a2f2f692e696d6775722e636f6d2f5253434d4268692e706e67)

Thanks.

**Comment by raRaRa** [comment]
Seems to be related to https://github.com/Azure/azure-storage-net/issues/457

**Comment by pemari-msft** [comment]
Indeed, caused by 457. The work to remove OData is ongoing which will solve the issue.
