### ISSUE TITLE
Authorization header issue with Microsoft.ApplicationInsights.AspNetCore v2.1.0

### ISSUE THREAD

**Issue by Klipi** [Azure/azure-storage-net#490]
I'm trying to setup a simple Blob storage backend following the guide here: https://docs.microsoft.com/en-us/azure/storage/vs-storage-aspnet5-getting-started-blobs

Here's my current code:
```
cloudStorageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://ipv4.fiddler");
blobClient = cloudStorageAccount.CreateCloudBlobClient();
blobContainer = blobClient.GetContainerReference("data");
            
await blobContainer.CreateIfNotExistsAsync(); // StorageException here
```

Here's the request as captured by Fiddler:
```
PUT http://127.0.0.1:10000/devstoreaccount1/data?restype=container HTTP/1.1
Connection: Keep-Alive
Authorization: SharedKey devstoreaccount1:BUb0duyrg8SKj7MARfsml+G1yLQ+wIx0MMdpIi/zuKg=
User-Agent: Azure-Storage/8.1.4 (.NET Core)
x-ms-client-request-id: 929c480d-926c-493e-9455-671d52349983
x-ms-version: 2016-05-31
x-ms-date: Wed, 05 Jul 2017 17:03:59 GMT
x-ms-request-root-id: a827f7ed-479f851154b64889
x-ms-request-id: |a827f7ed-479f851154b64889.1.
Request-Id: |a827f7ed-479f851154b64889.1.
Content-Length: 0
Host: 127.0.0.1:10000
```

Response:
```
HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Content-Length: 839
Content-Type: application/xml
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 72d14368-94cb-4135-b7a1-329e99efabb6
Date: Wed, 05 Jul 2017 17:04:01 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:72d14368-94cb-4135-b7a1-329e99efabb6
Time:2017-07-05T17:04:01.4550192Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'BUb0duyrg8SKj7MARfsml+G1yLQ+wIx0MMdpIi/zuKg=' is not the same as any computed signature. Server used following string to sign: 'PUT











x-ms-client-request-id:929c480d-926c-493e-9455-671d52349983
x-ms-date:Wed, 05 Jul 2017 17:03:59 GMT
x-ms-request-id:|a827f7ed-479f851154b64889.1.
x-ms-request-root-id:a827f7ed-479f851154b64889
x-ms-version:2016-05-31
/devstoreaccount1/devstoreaccount1/data
restype:container'.</AuthenticationErrorDetail></Error>
```

Emulator status:
```
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe status
Windows Azure Storage Emulator 5.1.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/
```

I've been trying to look for a way to get the version of the string to sign used by the client library, but all the guides I've found are for .NET Framework (and not Core). (e.g. https://docs.microsoft.com/en-us/rest/api/storageservices/client-side-logging-with-the-.net-storage-client-library and "The TraceSource provider" at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging#built-in-logging-providers)

Any ideas on what to try next? Is logging available on a .NET Core project?

**Comment by Klipi** [comment]
Tried the same code in an empty .NET Core command line project. Everything works as expected:

Full code:
```
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Threading.Tasks;

namespace TestCoreBlobStorage
{
    class Program
    {
        static void Main(string[] args)
        {
            CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://ipv4.fiddler");
            CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();
            CloudBlobContainer blobContainer = blobClient.GetContainerReference("data");

            var t = Task.Run(() => blobContainer.CreateIfNotExistsAsync());
            t.Wait();
        }
    }
}

```

Request:
```
PUT http://127.0.0.1:10000/devstoreaccount1/data?restype=container HTTP/1.1
Connection: Keep-Alive
Authorization: SharedKey devstoreaccount1:fES8Gcq1iRZAPowOmh94ul1SYoxMPjX9mROIqKu4tMo=
User-Agent: Azure-Storage/8.1.4 (.NET Core)
x-ms-client-request-id: 1bdbf118-2b25-4063-948f-c573c9dc5fc3
x-ms-version: 2016-05-31
x-ms-date: Wed, 05 Jul 2017 18:17:50 GMT
Content-Length: 0
Host: 127.0.0.1:10000
```

Response:
```
HTTP/1.1 409 The specified container already exists.
Content-Length: 230
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: f43c35bc-513a-470e-8c85-476617161c5c
x-ms-version: 2016-05-31
Date: Wed, 05 Jul 2017 18:17:51 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.
RequestId:f43c35bc-513a-470e-8c85-476617161c5c
Time:2017-07-05T18:17:51.5465268Z</Message></Error>
```

What could affect the requests that are sent in my main project?

**Comment by Klipi** [comment]
I was able to isolate the issue into a reproducible project. Here are the steps:

1) Start a new .NET Core Web API project.
2) Replace the Get method in ValuesController.cs with the following:

```
// GET api/values
[HttpGet]
public IEnumerable<string> Get()
{
CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://ipv4.fiddler"); 
CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();
CloudBlobContainer blobContainer = blobClient.GetContainerReference("data");

Task.Run(() => blobContainer.CreateIfNotExistsAsync()).Wait();

return new string[] { "value1", "value2" };
}
```

**3) Update Microsoft.ApplicationInsights.AspNetCore package to version 2.1.0**
4) Run with Fiddler (the default navigation should take you to /api/values and you should get the auth error)

It appears that upgrading the ApplicationInsights package adds new headers to the request, which makes the signatures differ.

I'll downgrade ApplicationInsights for now, but this should now be reproducible for you guys to take a look at.

**Comment by Klipi** [comment]
I'm guessing this is the issue I ran into: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/488

**Comment by cijothomas** [comment]
Tracking it here https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/640 (for appinsights)

**Comment by contactsamie** [comment]
Having the same issue unfortunately. downgrading AI at the moment to get around it

**Comment by cijothomas** [comment]
@contactsamie This has been fixed in this release.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/releases/tag/v2.4.1

**Comment by contactsamie** [comment]
Thanks @cijothomas .  i tried again using Microsoft.ApplicationInsights.Web -Version 2.4.1 still having same issue in my app. In my case its not storage emulator, its just a class library used to access azure storage, so I downgraded back to version 2.2 , the latest working one for me that didn't give the "403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature." exception

**Comment by cijothomas** [comment]
@contactsamie Can you check applicationinsights.config file to verify that the following section exists?
<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
			<ExcludeComponentCorrelationHttpHeadersOnDomains>
				
				<Add>core.windows.net</Add>
				<Add>core.chinacloudapi.cn</Add>
				<Add>core.cloudapi.de</Add>
				<Add>core.usgovcloudapi.net</Add>
			</ExcludeComponentCorrelationHttpHeadersOnDomains>
		</Add>

**Comment by contactsamie** [comment]
Thank you @cijothomas 
i don't have those in my config
Mine looks like this , below
so i have to add those in to exclude headers from being modified?

![image](https://user-images.githubusercontent.com/2102748/30467926-e12dc4bc-999c-11e7-9ac2-8bfc0d11cd27.png)

**Comment by contactsamie** [comment]
@cijothomas  Yes it worked like a charm after i added those! Awesome,  thank you so much
