### ISSUE TITLE
AzureStorageEmulator.exe autoinstalled from VS doesnt work

### ISSUE THREAD

**Issue by pijemcolu** [Azure/azure-storage-net#492]
VS 2017 auto-installed AzureStorageEmulator when I tried to access Server Explorer -> Azure -> Storage -> Development tab. 

Now the UI tray icon neither the shortcut to the command line version from within windows start area doesn't work and on 
`$ AzureStorageEmulator.exe init`
`$ AzureStorageEmulator.exe start`
 returns the most descriptive message ever:
`Windows Azure Storage Emulator 5.1.0.0 command line tool
Error: Unable to start the storage emulator.`

The fix is to run it from command line with administrative privileges.

Feel free to close this or move it.

**Comment by erezvani1529** [comment]
Thanks @pijemcolu for reporting this issue and providing the workaround. I have created a task to update our documentation to avoid confusion.

Thanks,
Elham
