### ISSUE TITLE
How to work with Nuget in ASP.NET CORE, missing methods !!?

### ISSUE THREAD

**Issue by serhioV** [Azure/azure-storage-net#493]
In the ASP.NET Core project I have **only** **_...Async_** methods for the **Table** class... 

What is the point? How to use the Nuget for .NET Core projects?

See similar problem [here](https://stackoverflow.com/questions/30673266/missing-cloudtable-execute-and-all-non-async-methods-in-asp-net-5-projects)

**Comment by pemari-msft** [comment]
There is no synchronous httpclient in .Net Core, so our library also cannot be synchronous. Please use async methods as it is the correct and recommended paradigm for your code. Thanks!

**Comment by serhioV** [comment]
Please provide then some documentation on that usage of Async Methods. I am a beginner, any doc on how to use Azure Table Storage with ASP.NET Core... I would use them, no problem, but I don't know how.

**Comment by erezvani1529** [comment]
Hi @serhioV,

You are right and we are working on our documentations to include async operations as well. We are getting closer to getting the samples out and I will update as soon as I have an exact date. We will use this issue to track this task.

Thanks,
Elham
