### ISSUE TITLE
Storage emulator slow compared to Azure Storage for parallel IO

### ISSUE THREAD

**Issue by sarathys** [Azure/azure-storage-net#498]
We have some code that writes to storage in parallel, which works faster in Azure Storage, but very slow (20 to 30 times slower) when using Azure Storage Emulator.
Is this a known issue?

**Comment by pemari-msft** [comment]
Yes, depending on your usage pattern, the emulator can be slower. The emulator is designed to give an approximation of the storage service behavior. Thanks!

**Comment by jkonecki** [comment]
Please reopen this issue.
Storage emulator clearly needs a bit of love and attention with regards to performance.

Example:
I'm currently using AzCopy to transfer 1 table with 10k entities.

Export from Azure: 1m55sec
Import into emulator: 15mins and still running

Emulator uses 60-80% CPU and 3% disk - clearly there is a room for improvement there as bulk import should be really limited by IO and not CPU.

**Comment by fschmied** [comment]
@pemari-msft Any comment on @jkonecki 's request above (https://github.com/Azure/azure-storage-net/issues/498#issuecomment-361922388)?
