### ISSUE TITLE
Numerous summary comments with malformed XML - missing closing angle brackets

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#499]
Inside Lib/ClassLibraryCommon/Core/Util/TaskExtensions.cs there's 

    internal static class TaskExtensions

which has a lot of methods with malformed XML comments. For example:

    /// <summary>
    ///  WHATEVER
    /// </summary>
    /// <param name="cancellationToken" the cancellation token which will be used to cancel the combined task </param>
    /// <remarks>WHATEVER</remarks>
    internal static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)

Note the `<param name="whatever"` part - `>` must occur after the second quote but it's missing in actual code.

Each occurrence of this defect yields CS1570 warning

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.

**Comment by ctolkien** [comment]
This probably why no docs show up in Visual Studio with intellisense then....
