### ISSUE TITLE
BlobHttpResponseParsers.GetBlobTier XML comment lists wrong parameter name

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#500]
Here's how `BlobHttpResponseParsers.GetBlobTier` is declared:

    ///  WHATEVER
    /// <param name="pageBlobTier">WHATEVER</param>
    internal static void GetBlobTier(BlobType blobType, string blobTierString, out PremiumPageBlobTier? premiumPageBlobTier)

XML comment lists `pageBlobTier` parameter name but the method parameter name is `premiumPageBlobTier`

This yields a CS1573 warning.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.
