### ISSUE TITLE
CloudBlockBlob.EndUploadFromStream() uses "is"-"as" instead of "as"

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#501]
https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs

contains

    public virtual void EndUploadFromStream(IAsyncResult asyncResult)
    {
       if (asyncResult is CancellableAsyncResultTaskWrapper)
       {
            CancellableAsyncResultTaskWrapper cancellableAsyncResult = asyncResult as CancellableAsyncResultTaskWrapper;
            cancellableAsyncResult.Wait();
        }

which causes a CA1800 code analysis issue being reported - the reference is being cast twice to the same type. This code can be redesigned by moving cancellableAsyncResult variable out of if and just comparing it against null.

This is the same defect as in https://github.com/Azure/azure-storage-net/issues/441 and the two methods do exactly the same so their code should be reused.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.
