### ISSUE TITLE
Microsoft.WindowsAzure.Storage.Core.Util.TaskExtensions.WithCancellation<T>() misleading indentation

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#502]
This is how it's indented now:

            using (cancellationToken.Register(
                        taskCompletionSource => ((TaskCompletionSource<bool>)taskCompletionSource).TrySetResult(true), tcs))
                        if (task != await Task.WhenAny(task, tcs.Task))
                            throw new OperationCanceledException(cancellationToken);
            return await task;
 
It reads as if the if-block is part of the construct inside the `using()`. This is how it should be indented to reflect what's actually going on:

            using (cancellationToken.Register(
                        taskCompletionSource => ((TaskCompletionSource<bool>)taskCompletionSource).TrySetResult(true), tcs))
            {
                if (task != await Task.WhenAny(task, tcs.Task))
                    throw new OperationCanceledException(cancellationToken);
            }
            return await task;
        }

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.
