### ISSUE TITLE
CloudBlockBlob.GenerateExceptionForConflictFailure() missing closing tag in XML comment

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#503]
Here's the XML comment in the current code:

        /// <summary>
        /// Helper method to generate a 409 Conflict exception.
        /// <returns>Return a 409 error wrapped in StorageException </returns>
        private static StorageException GenerateExceptionForConflictFailure()

The closing tag `</summary>` is missing. This yields a CS1570 warning.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.

**Comment by Dmitry-Me** [comment]
@kfarmer-msft Why was this closed? Was it fixed?
