### ISSUE TITLE
ReadLengthLimitingStream.Seek() fails to pass parameter name into ArgumentOutOfRangeException constructor

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#506]
`ReadLengthLimitingStream.Seek()` goes like this:

             // Map offset to the specified SeekOrigin of the substream.
            switch (origin)
            {
                // WHATEVER, some case labels here, then...
                default:
                    throw new ArgumentOutOfRangeException();
            }

`ArgumentOutOfRangeException` is constructed without passing the parameter name. That's a CA2208 defect.

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.
