### ISSUE TITLE
SubStream/ReadLengthLimitingStream have Seek() method with seemingly unnecessary manipulations

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#507]
Both `SubStream.Seek()` and `ReadLengthLimitingStream.Seek()` end with setting `this.Position`. Their main goal would therefore be to compute the new position. Instead they compute some mysterious `startIndex` which is then summed up with the offset and that yields the new position. `ReadLengthLimitingStream.Seek()` even assigns the `offset` to zero in one of the switch-cases.

Here's how `ReadLengthLimitingStream.Seek()` could work:

        public override long Seek(long offset, SeekOrigin origin)
        {
            long newPosition;

            switch (origin)
            {
                case SeekOrigin.Begin:
                    newPosition = offset;
                    break;
                case SeekOrigin.Current:
                    newPostinion = this.Position + offset;
                    break;
                case SeekOrigin.End:
                    newPosition = this.length - offset;
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            this.Position = newPosition;
            return newPosition;
        }

Wouldn't something like this be more straightforward and easier to read?

**Comment by seanmcc-msft** [comment]
Thanks for your suggestion, we will consider implementing this change in a future release.
