### ISSUE TITLE
ReadLengthLimitingStream fails to use Math.Min for capping the number of bytes

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/azure-storage-net#508]
`ReadLengthLimitingStream` has methods `BeginRead()`, `ReadAsync()` and `Read()` and each has this code:

            if (this.Position + count > this.Length)
            {
                count = (int)(this.Length - this.Position);
            }

which is equivalent to

         count = (int)Math.Min(this.Length - this.Position, count);

which is what `MultiBufferMemoryStream.ReadInternal()` does

**Comment by jofriedm-msft** [comment]
Hi @Dmitry-Me , we have an internal item in our backlog to clean up these warnings. We also accept public contributions if you would like to send a PR request to our dev branch to get these fixes in sooner.

**Comment by seanmcc-msft** [comment]
Thank you for the suggestion.
