### ISSUE TITLE
bad request 400 - CreateIfNotExists(); 

### ISSUE THREAD

**Issue by stevearnoult** [Azure/azure-storage-net#509]
Hi

I am  trying to do my first unit test with 'Microsoft Azure Storage Emulator - v5.1'.

It fails at 'CreateIfNotExists()' with 400 error.

When I try to do [step by step mode] (F11), Visual Studio 2017 ask me to find 'CloudBlobContainer.cs'. (?)

It's a new MVC 5 project, with :

Install-Package WindowsAzure.Storage
Install-Package Microsoft.WindowsAzure.ConfigurationManager
Install-Package Microsoft.WindowsAzure.Management.Storage

And that MVC files : 

[Models.zip](https://github.com/Azure/azure-storage-net/files/1182802/Models.zip)
[Views.zip](https://github.com/Azure/azure-storage-net/files/1182799/Views.zip)
[Controllers.zip](https://github.com/Azure/azure-storage-net/files/1182805/Controllers.zip)
[Web.zip](https://github.com/Azure/azure-storage-net/files/1182807/Web.zip)

Can you help me ?

Thanks !

**Comment by stevearnoult** [comment]
My solution : 
- Stop trying to use 'Microsoft Azure Storage Emulator'
- Instead I use real Azure Storage (from my localhost app) 

My webconfig has the production key : 
<add key="StorageConnectionString" value="DefaultEndpointsProtocol=https;AccountName=MYACCOUNTNAME;AccountKey=MYACCOUNTKEY;EndpointSuffix=core.windows.net" />

**Comment by mirobers** [comment]
@stevearnoult The current version of the library requires version 5.2 of the emulator. You'll need to upgrade your storage emulator to the latest at the [Azure Download Page](https://azure.microsoft.com/en-us/downloads/). Please reopen this issue if you see the same problem using version 5.2.
