### ISSUE TITLE
WindowsAzure.Storage nuget brings 11 nuget package as dependancies.

### ISSUE THREAD

**Issue by RonakThakkar** [Azure/azure-storage-net#510]
Hi,

I created a blank console application and installed WindowsAzure.Storage and it tries to download 11 Nuget Packages as dependency. Having 11 nuget packages for just storing and retrieving blobs sounds scary.

I used some popular libraries like RestSharp, DocumentDb and MongoDb and those libraries are standalone or bring very few dependencies.

I think Microsoft team should look into and try to remove the dependencies which can be removed.

regards,
ronak thakkar

**Comment by erezvani1529** [comment]
Hi @RonakThakkar ,

Thanks for your feedback. We have been tracking this task with #372 and are in the process of removing ODataDependencies and splitting the library per service which is going to be announced with exact timelines here very soon. Please stay tuned. If you agree, we will close this issue and keep tracking the change on the original issue.

Thanks,
Elham
