### ISSUE TITLE
not compatible with ASP.NET Core 1.1

### ISSUE THREAD

**Issue by MovGP0** [Azure/azure-storage-net#513]
the System.IO.Stream library used in `WindowsAzure.Storage` v8.2.1 ist not working with .NET Core 1.1, since the `System.IO` library in .NET Core 1.1 is newer than the one used in `WindowsAzure.Storage`.

**Comment by erezvani1529** [comment]
Hi @MovGP0,

Would you please share the error you are getting? (Is it happening during package installation?  I am not seeing any incompatibility issues there).

Thanks,
Elham

**Comment by MovGP0** [comment]
`Argument type 'System.IO.Stream [System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]' is not assignable to parameter type 'System.IO.Stream [System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]'`

![image](https://user-images.githubusercontent.com/83339/29270997-9a742d56-80f9-11e7-8617-b45c537fcffc.png)

**Comment by erezvani1529** [comment]
Hi @MovGP0,

Would you please share the exact project type you are creating as well and you environment setting(the dotnet version)?  We are not able to repro this issue.

Thanks,
Elham

**Comment by kleinkauff** [comment]
im getting the message "The REST version of this request is not supported by this release of the Storage Emulator." after any of "UploadFromByteArrayAsync" or CreateIfNotExistsAsync(container). Someone can help me?

**Comment by erezvani1529** [comment]
Closing this issue as we were not able to repro.

@kleinkauff , you are probably using an older version of the emulator. If you are using v9.0 of the library, Emulator 5.3 should be installed.

Thanks!
