### ISSUE TITLE
CloudStorageAccount class is sealed and methods are not marked as virtual

### ISSUE THREAD

**Issue by Jericho** [Azure/azure-storage-net#514]
I found one additional class marked as sealed which prevents unit testing: `CloudStorageAccount`. Additionally, the  `Create*Client` methods in this class are not virtual which therefore prevent mocking.

Here's a contrived example where I am prevented from mocking the storage account and also mocking the blob client created by this storage account

```
public class Foo
{
    private readonly CloudStorageAccount _storageAccount;
    public Foo(CloudStorageAccount storageAccount)
    {
        _storageAccount = storageAccount;
    }
    public async Task DoSomething()
    {
        var blobClient = _storageAccount.CreateCloudBlobClient();
        ... do something useful with the blob client ...
    }
}
```

Can you please consider un-sealing the StorageAccount class in version 9.0?

**Comment by erezvani1529** [comment]
Thanks @Jericho,

We are using #465 to track this as well.

-Elham

**Comment by Jericho** [comment]
thanks @erezvani1529 . I opened this issue because #465 does not mention unsealing `CloudStorageAccount`  and virtualizing `Create*Client`. Your [comment on June 8](https://github.com/Azure/azure-storage-net/issues/465#issuecomment-307253223) specifically mentions that you are tracking virtualizing `Get*Reference` and properties, but I don't see anything regarding CloudStorageAccount.
