### ISSUE TITLE
Table columns in internal F# class ignored

### ISSUE THREAD

**Issue by jackfoxy** [Azure/azure-storage-net#523]
NET 4.6.1
FSharp.Core (4.2.3)
WindowsAzure.Storage (8.3)

Given the demo code to insert into an Azure Storage Table https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-on-azure/table-storage
Using local development storage "UseDevelopmentStorage=true".
Run from VS 2017 debugger.
The same code will work if there is no FSI file over the library function, but with an FSI file, only the partition and row keys are inserted into the table, not the rest of the data columns.

Demonstration of problem here https://github.com/jackfoxy/SignatureProblem

Work around is to not use F# signature file, which is inconvenient when authoring libraries.

**Comment by pemari-msft** [comment]
Unfortunately, F# is not supported today. We can try to consider adding support in the future. Thanks for the suggestion!

**Comment by jackfoxy** [comment]
@pemari-msft Strange, there are at least 2 popular F# Azure Storage projects on GitHub, one a type provider and the other a library.

http://fsprojects.github.io/AzureStorageTypeProvider/

https://github.com/fsprojects/FSharp.Azure.Storage

Other than this edge case, no real problems using Azure Table Storage natively that I am aware of.

**Comment by dsyme** [comment]
There's some disconnect going on here - the use if the .NET SDK from F# is common. Cc @cartermp

**Comment by cartermp** [comment]
@pemari-msft F# is most definitely supported with Table Storage (And Blob Storage, Queue Storage, File Storage, Disk Storage, DocumentDB, MongoDB, etc.).  It's a .NET language.

I'm not sure why the addition of a signature file should affect this, though.  Shouldn't consumption of the Storage SDK be no different than any other .NET librarY?

**Comment by dsyme** [comment]
Yes, saying "not supported" an odd reply. But your question is very F#-specific and you'll get better results with those of us doing F#+Azure, who can deep dive to work out what's going on. Perhaps the reply should have just said that.

**Comment by dsyme** [comment]
Adding the signature will make the types internal - that could be causing the problems

**Comment by jackfoxy** [comment]
@dsyme yes, I realized later that internal is exactly the problem. There are work arounds, of course, but they involve not using the signature file.

**Comment by ploeh** [comment]
@jackfoxy So, is F# supported, or isn't it?

**Comment by jackfoxy** [comment]
@ploeh  I would say it is, but that's just my opinion.

**Comment by ploeh** [comment]
@jackfoxy, in that case, may I suggest that this is a bug, and the issue should be reopened?

**Comment by jackfoxy** [comment]
@ploeh  Reviewing the problem (which I haven't thought about for a while), I agree this should be re-opened. This is a silent failure. I compiles, it runs, and it doesn't do what is expected.
cc @dsyme
