### ISSUE TITLE
Azure TableEntity Flatten method not working for “Byte” data type

### ISSUE THREAD

**Issue by Srav8** [Azure/azure-storage-net#526]
While trying to insert data object into azure-storage-table, TableEntity.Flatten is throwing below exception.

System.Runtime.Serialization.SerializationException: Unsupported type : System.Byte encountered during conversion to EntityProperty.

Data object contains byte property which is not supported. As I receive this data object from upstream, I am ending up with new class, copying all the properties while changing the byte property into int.
  [https://stackoverflow.com/q/45868286/1661861](stackoverflow)

**Comment by erezvani1529** [comment]
Hi @Srav8,

We will be adding this support as an enhancement in a future release. We will update this thread with the corresponding PR.

Thanks,
Elham

**Comment by erezvani1529** [comment]
Hi @Srav8,

Please update to Storage Client Library [v8.6.0](https://www.nuget.org/packages/WindowsAzure.Storage/8.6.0) which includes this enhancement.

Thanks,
Elham
