### ISSUE TITLE
Length property has "-1" if we upload a blob over 32 MB

### ISSUE THREAD

**Issue by yuimam** [Azure/azure-storage-net#527]
Length property is substituted by a negative value, "-1".
The implementation is here, and this is the same in the latests version.

https://github.com/Azure/azure-storage-net/blob/v7.2.0/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs#L2433

"-1" is inserted if we upload over 32 MB, because such a file over 32 MB is divided into multiple files and then this SDK calls multiple calls to upload all of them.

https://github.com/Azure/azure-storage-net/blob/v7.2.0/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs#L355

We have a trouble if we want to know the correct file size after uploaded in Blob Storage.
Do you have a plan to fix this?

**Comment by pemari-msft** [comment]
From the `PutBlockList`, there's no way to know the length of a blob. A simple `FetchAttributes` after will solve the issue.
