### ISSUE TITLE
Is there any spot to watch for announcements for when you need to update the emulator

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-storage-net#528]
We'll update our storage SDK's only for everything to all fall over in development.

We've just had to update to the 5.2 emulator, but couldn't see where this information was announced anywhere?

**Comment by PureKrome** [comment]
This _literally_ just happened to me at work 20 minutes ago!!

The good ole `400 bad request` exception.

The clue was when I drilled down into the inner exception and then into the Request property or something. That listed some nice link to go and d/l the next/most recent version.

But yes -> maybe we can use some `announcements` repo or one of the official blogs. Not many people subscribe to storage bits, vs the .net or asp.net blogs/announcements/etc...

**Comment by erezvani1529** [comment]
Hi @ctolkien , @PureKrome ,

Apologies for the delay in response. We always update the emulator requirements in [ReadMe ](https://github.com/Azure/azure-storage-net#use-with-the-azure-storage-emulator) and [ChangeLog ](https://github.com/Azure/azure-storage-net/blob/master/changelog.txt#L13)files, so please make sure to check these sections out before each update to the latest version.

Thanks,
Elham
