### ISSUE TITLE
Does Azure Storage API support multiple clouds?

### ISSUE THREAD

**Issue by JoyceLiang** [Azure/azure-storage-net#531]
Azure storage provider now (in 15.5) support multiple clouds, allow user to add a new storage service for say blackforest account. I am trying to get my container on blackforest by following [this instruction](https://docs.microsoft.com/en-us/azure/visual-studio/vs-storage-aspnet-getting-started-blobs).

I found when I call container.CreateIfNotExists(), my container name have been added a suffix as "blob.core.windows.net", whereas the expected suffix for blackforest is "blob.core.cloudapi.de".

**Comment by pemari-msft** [comment]
Hi @JoyceLiang -- if you're using that guide and creating a `CloudStorageAccount` object by parsing a connection string, please set the `EndpointSuffix` value in your connection string to [blob.core.cloudapi.de](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string). Thanks!

**Comment by JoyceLiang** [comment]
@pemari-msft
Just double confirm EndpointSuffix value in connection string is "core.cloudapi.de" not "**blob**.core.cloudapi.de". 

When I use the suffix with blob, the full uri  become xxx.blob.blob.cloudapi.de, which lead to exception.

**Comment by pemari-msft** [comment]
Indeed, my mistake. Thanks for pointing that out!
