### ISSUE TITLE
Package and namespace names should be updated to new Microsoft.Azure convention.

### ISSUE THREAD

**Issue by Jehoel** [Azure/azure-storage-net#532]
I know the name `WindowsAzure` comes from the first marketing name for Azure: "Microsoft Windows Azure" when they felt the need to piggy-back on the _Windows_ brand-recognition (which led to plenty of confusion), things became sane recently when Windows Azure was rebranded to Microsoft Azure - this includes the new Resource Management API client libraries that now have the package names `Microsoft.Azure.*` - however the Azure Storage client retains the old package name `WindowsAzure.Storage` and the old namespace `Microsoft.WindowsAzure.Storage`.

I'm aware the old Service Management API client libraries retained the old package and namespace names (I suppose keeping with the "old" theme...) but the Azure Storage API remains current, so it makes sense for the Storage Client library to have an updated package and namespace name too - i.e. the package name and namespace should both be `Microsoft.Azure.Storage`.

This would be a significant breaking change - I therefore propose it be combined with issue #372 or a potential future update that splits the Blob/File/Queue/Table clients into separate packages.

**Comment by erezvani1529** [comment]
Thanks @Jehoel,

This is exactly what we are working on to get out for our next preview release which will include the library split into multiple service packages in addition to the namespace update and removal of the OData dependencies as part of one breaking change. 
 
I will use this issue to update the namespace update status after release. Or we can use the issue #372 to track this change as well.

Thanks,
Elham
