### ISSUE TITLE
TableStorage>LINQ: forward slash for nested properies

### ISSUE THREAD

**Issue by VeselovAndrey** [Azure/azure-storage-net#533]
By default nested properties uses low dash to separate nested properties.
You can't change this separator to forward slash.

But when you trying to run LINQ with entity that have nested properties then LINQ generate names with forward slash.

E.g.
public class Class1  { public string Id  { get; set; } }
public class Class2 : ITableEntity  { public Class1 C1  { get; set; } ... }

If you will try to write Class2 to table storage you will get "C1_Id" column
But if you run LINQ like
CreateQuery< Class2 >.Where(...) you will get C1/Id in request. 

Need a way to set same valid separator to both cases.

**Comment by doguva-msft** [comment]
Hi,
you can change the seperator to whatever string you want, does not even need to be a single char.

You would need to use the overloaded version of TableEntity.Flattem method that takes the EntityPropertyConverterOptions parameter:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.tableentity.flatten?view=azurestorage-8.1.3

And specify the property name delimiter string using the EntityPropertyConverterOptions.PropertyNameDelimiter property. 

To read the complex object back, you would need to use the same delimiter specifying it similarly via the overloaded version of the ConvertBack method.

Like I mentioned, the delimiter can be a single char or a full string 

Let us know if this helps.

**Comment by VeselovAndrey** [comment]
Actually I tried that and it won't work.

LINQ generates forward slash. If you put forward slash into _EntityPropertyConverterOptions_ all requests to the table will fail. Because forward slash is the forbidden character for names in Table Storage.

**Comment by VeselovAndrey** [comment]
BTW: As I understand forward slash created when Azure Storage Library parses LINQ. So it's not LINQ problem but Azure Storage Library parser problem.

**Comment by erezvani1529** [comment]
Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information.
