### ISSUE TITLE
MD5 property always showing null

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-net#544]
I was trying to use the MD5 property on a Azure Storage File but it is always null

```
CloudFile file;
var md5 = file.Properties.ContentMD5;
```

I believe we are using `<package id="WindowsAzure.Storage" version="6.2.0" targetFramework="net45" />`

**Comment by erezvani1529** [comment]
Hi @crwilcox ,

Is the ContentMD5 property stored on the file? The Properties.ContentMD5 returns a value if it was stored with the File/Blob. Please refer to [this page](https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/) for more information.

Thanks,
Elham

**Comment by pemari-msft** [comment]
If it's stored, you'll also need to call FetchAttributes on the file in order to get the value stored on the service. Thanks!

**Comment by charmoniumQ** [comment]
> Please refer to [this page](https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/) for more information.

[Archived version](https://web.archive.org/web/20190118183153/https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/)
