### ISSUE TITLE
BlobEncryptionPolicy in .NET core?

### ISSUE THREAD

**Issue by mvaerum** [Azure/azure-storage-net#547]
Hi there,
I'm developing a dotnet core application and would like to make use of client side encryption.
I use the WindowsAzure.Storage.dll via NuGet (8.5.0)
However, I cannot seem to find the class BlobEncrytionPolicy ind WindowsAzure.Storage.Blob.
Is it possible to use this method in dotnet core?
Any idea what I could be doing wrong?
Thanks.

**Comment by pemari-msft** [comment]
Hi @mvaerum,
Client side encryption is not yet supported in .NET Core. We have it on our backlog as part of the .NETCore parity. Sorry for the inconvenience.

**Comment by mvaerum** [comment]
OK. Thanks for the quick reply. Any rough idea when this can be expected?

**Comment by pemari-msft** [comment]
tracked in #333
