### ISSUE TITLE
EntityProperty method names don't follow .NET Framework Design Guidelines

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-storage-net#549]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions

A few of EntityProperty methods don't follow these guidelines - for example:
* GeneratePropertyForBool
* GeneratePropertyForInt
* GeneratePropertyForLong

According to the design guidelines, these should instead be something like:
* GeneratePropertyForBoolean
* GeneratePropertyForInt32
* GeneratePropertyForInt64

(For an example of a class that does follow the guidelines, see:
https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqldatareader(v=vs.110).aspx)

**Comment by pemari-msft** [comment]
These were named long before the guidelines were published. The decision was made that the benefit did not warrant the breaking change. Moving forward we may make these changes. Thanks for the suggestion!

**Comment by davidmatson** [comment]
If I recall correctly, the framework design guidelines were first published in 2005 or earlier:
https://www.amazon.com/Framework-Design-Guidelines-Conventions-Libraries/dp/0321246756
