### ISSUE TITLE
EntityProperty.DateTime is named inconsistently

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-storage-net#551]
The property is named just "DateTime" rather than "DateTimeValue", unlike all the others (including DateTimeOffset).

I understanding fixing would be a breaking change (or require duplicates with both names). If you could change in the next major version, that would be appreciated. Thanks!

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
