### ISSUE TITLE
Server failed to Authenticate request. Connecting to storage emulator from android emulator

### ISSUE THREAD

**Issue by InquisitorJax** [Azure/azure-storage-net#556]
see [repo](https://github.com/InquisitorJax/Xamarin-Forms-Azure-Blob-Storage)

Trying to connect to local storage emulator from Xamarin Android client

In the repo: resolve LocalBlobStorageSettingsProvider as ICloudBlobStorageSettingsProvider
manually create the containers "image-container" and "document-container" in the development account using the Azure Storage Explorer
run the android client
=> Storage Exception

using connection string:
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://**10.0.2.2**:10000/devstoreaccount1

**Comment by erezvani1529** [comment]
Hi @InquisitorJax,

Would you please try using the local endpoint in your connection string?
"BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"

Please let us know if the issue persists.

Thanks,
Elham

**Comment by InquisitorJax** [comment]
Hi Elham,

That doesn't work because 127.0.0.1 (or localhost) from the android emulator points to the android device iteself, and not the host machine it's running on. The host machine is defaulted to 10.0.2.2, but using the 10.0.2.2:10000 endpoint doesn't seem to work either.

In the repo that I've linked, you can run the server project, and link to the api endpoint via 10.0.2.2 just fine from the device browser.

**Comment by erezvani1529** [comment]
@InquisitorJax ,

Have you tried changing the android emulator IP?

**Comment by InquisitorJax** [comment]
That wouldn't really make much sense, because 10.0.2.2 is that standard IP accepted to point to localhost (127.0.01) on the host machine. This IP is assumed for things like tests and team development. Changing an emulator IP for the sake of azure doesn't make a lot of sense.

When I query 10.0.2.2:10000/devstoreaccount1 from the emulator browser, it responds with the same response as entering 127.0.0.1:10000/devstoreaccount1 from my machine browser - so I don't think it's the IP that's the issue - more something else that's in the connection string mentioned above, or client protocol validation?

**Comment by erezvani1529** [comment]
Thank for the information @InquisitorJax,

It would be helpful if you could share your emulator logs with us. And one final check before that would be to use the proxy style connection string:
UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://myProxyUri

**Comment by InquisitorJax** [comment]
Eurika! :)

feel silly now that I didn't try the ProxyUri setting earlier.
This works as the connection string:
"UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://10.0.2.2"

thanks for the assist!
