### ISSUE TITLE
InsertOrReplace operation on TableStorage results in 409 Conflict being reported in AppInsights with Microsoft.WindowsAzure.Storage 8.1.4

### ISSUE THREAD

**Issue by SrividyaTR** [Azure/azure-storage-net#558]
I observe that while using Microsoft.WindowsAzure.Storage 8.1.4, when doing a InsertOrReplace on TableStorage, it results in 95% errors of 409 Conflict on AppInsights for table storage dependencies 

The same was reporting no errors when using Microsoft.WindowsAzure.Storage 7.2.1.0

I have verified that the same 409 conflict error is present even with the latest  Microsoft.WindowsAzure.Storage 8.5.0.0 version

Why is this being reported? Is this a known issue? How to prevent such false errors being reported in AppInsights?

**Comment by erezvani1529** [comment]
Hi @SrividyaTR ,

Replied to the [forum ](https://social.msdn.microsoft.com/Forums/en-US/a41f0e33-5c84-43ad-85d0-3a2e4ca67b7e/insertorreplace-operation-on-tablestorage-results-in-409-conflict-being-reported-in-appinsights-with?forum=windowsazuredata)thread as well.

AppInsight does not distinguish expected failures and reports them as-is even if the application receives an expected result. For instance attempting to create an existing table will be reported as failure. If the above scenario happens frequently in your case, you may need to update your logic to attempt and create the table only when it is needed. Could that be what is happening in your case?

Thanks,
Elham

**Comment by SrividyaTR** [comment]
The scenario here is not to create the table but to create a row in the table (if it does not exist, else update the row).

I am aware that AppInsights does not distinguish expected failures and real failures.

But with the older version of the Nuget (Microsoft.WindowsAzure.Storage 7.2.1.0), AppInsights does not report this expected failure. 

So it is clear that this behaviour is because of some change in the Nuget implementation. I wanted to understand what has changed and is there any alternate way to do a InsertOrReplace to table to avoid such perceived failures

**Comment by erezvani1529** [comment]
Thanks. What is your target platform?

**Comment by SrividyaTR** [comment]
Our application is targeting .NET 4.5.2.
We are using the nuget library from WindowsAzure.Storage.8.1.4\lib\net45

**Comment by erezvani1529** [comment]
There has been no relevant change in the corresponding code-path for desktop code-base since v7.2. Would you please share the piece of code which is leading to this issue? 

Thanks!

**Comment by SrividyaTR** [comment]
public void InsertOrReplace<T>(string partitionKey, string rowKey,
               T replacementData) where T : TableEntity
{
            Table.Execute(TableOperation.InsertOrReplace(replacementData));
}

This method is invoked with appropriate entity that is derived from
TableEntity

Let me know if you need more details.

**Comment by SrividyaTR** [comment]
Is there any update on this issue?

**Comment by jakobli** [comment]
would be interrested to know this too.

**Comment by erezvani1529** [comment]
@SrividyaTR , @jakobli 

As I mentioned there is no recent change in SDK that would cause this issue and looking at Fiddler traces, I don't see any unusual result. Can you try with a small app using old/new SDK with sample data and share your fiddler traces with us? (please email them to `ascl at microsoft dot com`)

Thanks,
Elham

**Comment by SrividyaTR** [comment]
Based on your suggestion, we created a small app using the old and new SDK and checked the fiddler traces. We see that it is not the InsertOrReplace method that gives the 409 but the call to 
Table.CreateIfNotExists(); results in 409 if the table already exists.

In the earlier SDK (7.2.1.0), Table.CreateIfNotExists() gives 200 even if the table already exists.

Do you have any suggestions to avoid this 409 error in this case?

**Comment by erezvani1529** [comment]
@SrividyaTR ,

This behavior an optimization in the library to avoid a service call to check whether the table/container already exists and ignore the 409 failure in case the Create was not successful (which means the table already exists).

Sure. Going back to my original response: if the majority of your calls to CreateIfNotExists return with 409, you can try applying the logic of a head call to make sure the table doesn't exist before you try to create it.

Thanks,
Elham
