### ISSUE TITLE
UploadFromStreamAsync with BlobRequestOptions?

### ISSUE THREAD

**Issue by robertbaker** [Azure/azure-storage-net#568]
I'm converted to .net core but this no longer works:

```
var requestOptions = new BlobRequestOptions { UseTransactionalMD5 = true, StoreBlobContentMD5 = true };
            blobRef.UploadFromStream(content, options: requestOptions);
```
So I'm trying to find an overload that works and I can't find one.

> await blobRef.UploadFromStreamAsync(content, options: requestOptions);

Should it be `await blobRef.UploadFromStreamAsync(content, AccessCondition.GenerateEmptyCondition(), requestOptions, null);`

How can I do the same thing with the Async method?

**Comment by erezvani1529** [comment]
Hi @robertbaker,

Apologies for the delay in response. If I understand the question correctly, the async method that you have referred to should work for you. Is that what you wanted to confirm?

Thanks,
Elham

**Comment by robertbaker** [comment]
Yes, it feels weird that a null is being passed in, I was worried that will throw an exception. Perhaps an overload could be added?

**Comment by erezvani1529** [comment]
@robertbaker , it should be ok to pass in Null for opContext. I can see that it may not be commonly used, however, as you see there are already many overloads and we would like to avoid adding more unless to avoid a break.

Please re-open if you have any related issues.

Thanks!

**Comment by robertbaker** [comment]
@erezvani1529 In my opinion without this overload, it's makes updating harder, because it's a breaking change if the goal is to have the same overloads as the old non-async method.

Other methods I was able to add Async at the end and it didn't break, except this one.
