### ISSUE TITLE
Authenticated applications cannot access storage

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-storage-net#573]
Most services, including Storage allow you to add application access to the resource.

Batch allows this to be utilized through this type: `BatchTokenCredentials`

In this fashion: 

```
BatchTokenCredentials batchTokenCredentials = new BatchTokenCredentials(this.BatchAccountUrl, 
authenticationManager.GetBatchAccessTokenAsync);var batchClient = BatchClient.Open(batchTokenCredentials);
```

Whilst Storage does allow the same access to be granted via the portal, there is no mechanism within `Microsoft.WindowsAzure.Storage` to facilitate access to storage with an Authority generated Access Token.

**Comment by zezha-msft** [comment]
Hi @wijays, this feature is coming soon!

**Comment by wijays** [comment]
@zezha-msft do we have a milestone release for this?

**Comment by zezha-msft** [comment]
Hi @wijays It is not confirmed at this point, I'll update this thread if I receive more info.

**Comment by kfarmer-msft** [comment]
@a-vishar -- We recently added OAuth support.  Let us know if this does not meet your needs.

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app
