### ISSUE TITLE
Allow configuring HttpClient creation

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-storage-net#580]
As part of our [performance guidelines](https://docs.particular.net/transports/azure-storage-queues/performance-tuning), we suggested to customers to tweak `ServicePointManager.DefaultConnectionLimit` to improve Storage operations. This relevant both for getting data as well as receiving data. With .NET Core the `ServicePointManager.DefaultConnectionLimit` is not taken into account with the `HttpClient` anymore. There is a new property called `MaxConnectionsPerServer` on the `HttpClientHandler` that needs to be set when the `HttpClient` is created. The default value of that property is `int.Max`. With massive concurrent storage operations, the async code running on .NET Core will create thousands of connections which makes the storage operation code slow on .NET Core. 

AWS SDK has a possibility to override certain settings of the `HttpClient `or `HttpClientHandler `when a client is created. For example `MaxConnectionsPerServer` can be set on the client configuration object with .NET Core. This allows tweaking the default behaviour of the HTTP client handler. 

```
new AmazonSQSClient(
            credentials,
            new AmazonSQSConfig
            {
                RegionEndpoint = region,
                MaxConnectionsPerServer = someValue,
            })
```

It would be really beneficial if the `HttpClient `creation can be somehow controlled or at least configuration like `MaxConnectionsPerServer ` can be set on the created `HttpClient` to be able to tweak performance if necessary.

**Comment by erezvani1529** [comment]
Thanks @danielmarbach ,

Fyi, we will take this as a feature request and I will update with more details soon.

Thanks,
Elham

**Comment by danielmarbach** [comment]
Any ideas when we'd be able to see these changes?

**Comment by SeanFeldman** [comment]
Also, would it be possilbe to update the issue with appropreate label(s)/milestone(s)?
Otherwise it looks like a long forgotten issue. Thanks.

**Comment by ryanerdmann** [comment]
As customers start taking advantage of  [`IHttpClientFactory`](https://github.com/aspnet/HttpClientFactory/blob/60a23380a354ebaf27c8cd3505e745bd8b7f1541/src/Microsoft.Extensions.Http/IHttpClientFactory.cs#L17) from `Microsoft.Extensions.Http`, there will be a desire to delegate control over creating `HttpClient` instances to the application.  For server applications, this is especially important so they can implement bulkheading, coordinate refreshing DNS changes, etc.

Can we enable the application to plug in some `HttpClient` factory when creating a `CloudBlobClient`?

**Comment by joshlang** [comment]
Could be related: https://github.com/Azure/azure-storage-net/issues/705

**Comment by brettsam** [comment]
Weighing in with another +1. In Azure WebJobs/Functions, we often need to interact at fairly high scale with Storage and have constrained number of connections that we can use in shared environments. In the .NET Framework, we'd set `ServicePointManager.DefaultConnectionLimit` to 50 in order to keep a cap on this. But that's not working for us in .NET Core as it doesn't appear this setting applies to HttpClient anymore.

**Comment by danielmarbach** [comment]
The setting is back in netcore 2.1.x if I'm not mistaken. Still support for http client factory would be great

**Comment by brettsam** [comment]
The `ServicePointManager` is back, but these comments indicate that it doesn't apply to HttpClient: https://github.com/dotnet/corefx/issues/29452#issuecomment-386030456

I just created a simple console app and if I set `DefaultConnectionLimit` to 2 explicitly and make a bunch of requests using HttpClient, I see many more than 2 connections. If I use `HttpClientHandler.MaxConnectionPerServer`, I get the behavior that I want.

**Comment by muratboduroglu** [comment]
Just to chip in, having the same issue while running our sample code in .Net Core in Azure Functions V2. 

Our own code is using the MaxConnectionPerServer setting for the httpclient but due to a high number of calls made by Azure Storage SDK, we are getting hit heavily by socket exceptions. (we also have the ServicePointManager.DefaultConnectionLimit set in static constructor of every function but as Brett mentioned above, it looks like it's ignored in .Net Core).

**Comment by mayoatbm** [comment]
Another +1.

The lack of connection management in the Azure Storage sdk causes so many problems when running in the Consumption Plan in Azure Functions. Try searching for "Host Thresholds Exceeded (Connections)" errors and there are tons of them across multiple repos (azure functions, azure functions host, azure durable functions etc). 

A lot of them lead right back to Azure Storage as the culprit.  The "transient" connections it uses stay around for  up to two minutes and count against sandbox thresholds. 

Please allow consumers to provide their own HttpClient or implement connection pooling. The current situation is crippling for Azure Functions. I've had to explain this to enterprise clients on three consecutive projects. Please, please,fix.

**Comment by kfarmer-msft** [comment]
9.4.1 includes the ability to pass in DelegatingHandler chains, which at runtime will have an HttpClientHandler instance assigned to the innermost InnerHandler property. This can be leveraged to set the Proxy (or any other property supported by HttpClientHandler). For example, see DelegatingHanlderImpl in TestBase.Common.cs, and the CloudBlobContainerVerifyProxyHit test in CloudBlobContainerTest.cs.

**Comment by tekking** [comment]
Hey there, 
We recently ran into this same problem with a v2 function that does a lot of inserting into an azure table storage. We would like to use the fix mentioned here, but as far as we can find table storage is not yet supported for .net standard2 or core in the >=9.4 libraries. Is there a suggested way to fix our issues with large amount of connections being created in .net standard2?
Thanks

**Comment by brettsam** [comment]
For those using Functions v2, can you give our latest release (anything >= [2.0.12210.0](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12210)) a try with your scenarios? At the time of this writing, this version is rolling out worldwide, so it may not quite be in all regions just yet.

We added a workaround that fixes a number of our test scenarios involving Storage connection limits. We'll be absorbing the new change made in Storage 9.4.1, but it will require a little bit of refactoring before that can happen. If you have functions-specific scenarios that still don't work, please file a separate issue over at https://github.com/Azure/azure-webjobs-sdk/issues, which the Functions team will look into.

**Comment by tekking** [comment]
Thanks for the quick response. We just restarted our functions to update to this new version, will be keeping an eye on them to see if this fixes our problem.

**Comment by brettsam** [comment]
@tekking -- I filed https://github.com/Azure/azure-webjobs-sdk/issues/2044 to follow up with you.

**Comment by mayoatbm** [comment]
@brettsam thanks for the quick response. We're gearing up for more load tests this month, we will let you know how it goes.
