### ISSUE TITLE
TableBatchOperation with SAS failing

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-storage-net#584]
I have pretty simple example of trying a TableBatchOperation operation using SAS that fails with: HTTP/1.1 415 Unsupported Media Type. Using standard authentication works fine.

I can repeat this error using the net, node, and native REST calls, so my assumption is that there is something wrong on the server side.

I attached the test class I used in c# and the raw output from fiddler.

This is a showstopper from a security perspective due to my inability to control batch updates to specific partitions and rows.

PS - using single row PUT works but when I have thousands of devices sending thousands of rows every minute, the processing costs explode...

[sasBatch.zip](https://github.com/Azure/azure-storage-net/files/1524911/sasBatch.zip)

**Comment by fuocor** [comment]
I walked though the issue with the azure team and the bug is in the client library.

when using SAS keys the library writes the wrapping POST as follows:
POST https://storage-account.table.core.windows.net/table-name/$batch?sas-token HTTP/1.1

it should not include the table-name in the uri

regards,
rich

**Comment by mirobers** [comment]
Hi, I just responded to Azure/azure-storage-java#249 with the following. If this does not help, please provide repro code and we will take a look.

> Hi, I believe the issue is that the URL passed to the constructor of CloudTableClient in the second line contains the name of the table. The CloudTableClient constructor takes the base URL of the table service, i.e. "https://myaccount.table.core.windows.net". Then you can use GetTableReference to work with a specific table in the account.
> 
> Is there an online example or tutorial you were following that has the wrong URL? If so, please let me know and I will make sure it is corrected.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
