### ISSUE TITLE
Problem No SetPermissions and ListBlobs methods appear in class CloudBlobContainer Windows.Azure.Storage 8.4.0

### ISSUE THREAD

**Issue by caycavani** [Azure/azure-storage-net#585]
I'm currently developing a test project with Net Core 2 in it I need to connect to a blogSorage and read an xml file, edifact in a container that I previously created up there all excellent I'm using Windows.Azure.Storage 8.4.0 The problem is When I invoke the SetPermissions method, this does not appear like the ListBlobs. In each case it shows me the respective async methods and therefore I will not be able to read the file. The strange thing is that if I add the same project with netFramework 4.6.1 it works correctly. Documentation is looked for and by no means it seems to be a problem by version of framework .net therefore I appeal to you.

// metodo para obtener conexion a contenedor y nombres de los blobs
        private List<string> GetBlobNames(string contenedor)
        {
            // Parse the connection string and return a reference to the storage account.
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=pricatstesting;AccountKey=syRVR84GQYrdWh+6jI4tqan9zTolnYiGUVI3Jbrb7ZdQYh3VW/+k0CIvzJhf80QGMhgiwNHTx7gZImsq6YZaBw==");

            //ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
            // Create the blob client.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            // Retrieve a reference to a container.
            container = blobClient.GetContainerReference(contenedor);
            // Set permissions for public access

            container.SetPermissionsAsync(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            //SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            BlobContinuationToken token = new BlobContinuationToken();

            // Lista los blobs dentro del container
            var list = container.ListBlobsSegmentedAsync(token);
            //container.ListBlobs();
            return null;
            //list.OfType<CloudBlockBlob>().Select(b => b.Name).ToList();

            //OfType<CloudBlockBlob>().Select(b => b.Name).ToList();
        }

Sincerely

Carlos A. Hernandez
Developer .NET

**Comment by erezvani1529** [comment]
HI @caycavani,

This is because our NetCore target only supports async method and this is expected. Please let us know if you observe any other issues.

Thanks!

**Comment by caycavani** [comment]
I could collaborate with an example to implement it
Thank you

**Comment by erezvani1529** [comment]
@caycavani, 

I noticed a wrong usage of ListBlobsSegmentedAsync in the code sample you have provided. Here is a sample on how to list blobs :

`
BlobContinuationToken continuationToken = null;
List<IListBlobItem> results = new List<IListBlobItem>();
do
 {
        var response = await container.ListBlobsSegmentedAsync(continuationToken);
        continuationToken = response.ContinuationToken;
        results.AddRange(response.Results);
 }
while (continuationToken != null);
return results;
`
Thanks,
Elham
