### ISSUE TITLE
Read the contents of an EDI file stored in an Azure Blog

### ISSUE THREAD

**Issue by caycavani** [Azure/azure-storage-net#588]
Good afternoon in a development I'm doing I'm connecting to a blog that contains a container with some EDI files that I read I'm using net core 2 with asynchronous methods, the connection and reading the file is already done correctly, however I have problems with the method that does the reading of the content of the file and I need this content mainly.

private async Task <List <string >> BlobReaderAsync (string blob)
        {
            List <string> records = new List <string> ();

            // Retrieve reference to blob.
            CloudBlockBlob blockBlob = container.GetBlockBlobReference (blob);
                
                 //// Blob reading process
            var stream = await blockBlob.OpenReadAsync ();
            // blockBlob.OpenRead ();

            // convert stream to List to verify format in rows
            using (StreamReader r = new StreamReader (stream))
            {
                string record;

                while ((record = r.ReadLine ())! = null)
                {
                    records.Add (record);
                }

            }

            return records;
        }

this is the method that connects and reads blob

// method to get connection to container and names of blobs
        private async Task <List <IListBlobItem >> GetBlobNamesAsync (container string)
        {
            // Parse the connection string and return to reference to the storage account.
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse ("DefaultEndpointsProtocol = https; AccountName = pricatstesting; AccountKey = **secret**");

                //ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
                // Create the blob client.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient ();
            // Retrieve a reference to a container.
            container = blobClient.GetContainerReference (container);
            // Set permissions for public access

            await container.SetPermissionsAsync (new BlobContainerPermissions {PublicAccess = BlobContainerPublicAccessType.Blob});

            // List the blobs inside the container

            BlobContinuationToken continuationToken = null;
            List <IListBlobItem> results = new List <IListBlobItem> ();
            do {
                var response = await container.ListBlobsSegmentedAsync (continuationToken);
               continuationToken = response.ContinuationToken;
               results.AddRange (response.Results);
                
            }
            while (continuationToken! = null);

            return results;

            // var list = container.ListBlobsSegmentedAsync (token); ;

            //// container.ListBlobs ();
            // return null;
            //list.OfType<CloudBlockBlob>().Select(b => b.Name) .ToList ();

            // OfType <CloudBlockBlob> (). Select (b => b.Name) .ToList ();
        }

I would appreciate a comment and if possible an example that would allow me to guide myself

Sincerely

Carlos Hernandez
Developer .NET

**Comment by erezvani1529** [comment]
Hi @caycavani,

Most importantly, please rotate your account keys immediately and make sure you never share them publicly :). 

What is the problem that you are encountering?

Thanks,
Elham

**Comment by caycavani** [comment]
Hi

 I'm doing I'm connecting to a blog that contains a container with some EDI files that I read I'm using net core 2 with asynchronous methods, the connection and reading the file is already done correctly, however I have problems with the method that does the reading of the content of the file and I need this content mainly.

private async Task <List > BlobReaderAsync (string blob)
        {
            List records = new List ();

            // Retrieve reference to blob.
            CloudBlockBlob blockBlob = container.GetBlockBlobReference (blob);
                
                 //// Blob reading process
            var stream = await blockBlob.OpenReadAsync ();
            // blockBlob.OpenRead ();

            // convert stream to List to verify format in rows
            using (StreamReader r = new StreamReader (stream))
            {
                string record;

                while ((record = r.ReadLine ())! = null)
                {
                    records.Add (record);
                }

            }

            return records;
        }

this is the method that connects and reads blob

// method to get connection to container and names of blobs
        private async Task <List > GetBlobNamesAsync (container string)
        {
            // Parse the connection string and return to reference to the storage account.
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse ("DefaultEndpointsProtocol = https; AccountName = pricatstesting; AccountKey = secret");

                //ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
                // Create the blob client.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient ();
            // Retrieve a reference to a container.
            container = blobClient.GetContainerReference (container);
            // Set permissions for public access

            await container.SetPermissionsAsync (new BlobContainerPermissions {PublicAccess = BlobContainerPublicAccessType.Blob});

            // List the blobs inside the container

            BlobContinuationToken continuationToken = null;
            List results = new List ();
            do {
                var response = await container.ListBlobsSegmentedAsync (continuationToken);
               continuationToken = response.ContinuationToken;
               results.AddRange (response.Results);
                
            }
            while (continuationToken! = null);

            return results;

            // var list = container.ListBlobsSegmentedAsync (token); ;

            //// container.ListBlobs ();
            // return null;
            //list.OfType().Select(b => b.Name) .ToList ();

            // OfType (). Select (b => b.Name) .ToList ();
        }

I would appreciate a comment and if possible an example that would allow me to guide myself

Sincerely

Carlos Hernandez
Developer .NET

**Comment by erezvani1529** [comment]
Hi Carlos,

Were you able to figure out your issue? Would you please be more specific about the question/issue?

Thanks,
Elham

**Comment by erezvani1529** [comment]
Please re-open if you have any related questions/issues.

Thanks!
