### ISSUE TITLE
Can you please add the Storage Emulator to this repo?

### ISSUE THREAD

**Issue by WillSullivan** [Azure/azure-storage-net#59]
It seems like every time you guys push out a new release (YAY!) it 400s the current version of the Storage Emulator (boo!).

It seems to me that if you rolled the emulator into this solution, not only would it simplify keeping the emulator up to date with the latest and greatest (by force of failed tests, yeah, but still...), **but it would also** allow us users easy and quick access to the updated emulator, making it super easy to get up and running after an update.

I'm writing this now prior to my tracking down the latest version of the storage emulator.  Experience has taught me that I may end up chucking my laptop across the room in frustration trying to track it down and install it correctly.

**Comment by nathanaeljones** [comment]
And... the storage emulator was renamed yet again. `WAStorageEmulator.exe` -> `AzureStorageEmulator.exe`

**Comment by mirobers** [comment]
You can get the latest storage emulator from the Azure SDK for .NET (http://azure.microsoft.com/en-us/downloads/). When a new version of the service is released, the emulator in the latest SDK is updated. You can install the SDK again when this happens – the Web Platform Installer will automatically only update the components with newer versions than you already have (i.e. the storage emulator). If you prefer not to go the SDK route, you can download the storage emulator installer individually from the latest SDK download page. Right now, the latest is here: http://www.microsoft.com/en-us/download/details.aspx?id=46892. Click download and choose MicrosoftAzureStorageEmulator.msi. There currently are no plans to distribute the storage emulator via NuGet or GitHub, although we will take it as a feature request to make it easier to find the latest storage emulator installer.

We do have plans in the next release to return a new error code from the storage emulator when it detects that it is out of date. This will make it easier to detect when the storage emulator needs to be upgraded.

**Comment by pemari-msft** [comment]
We've now released the latest version of the storage emulator which does have a new error code for out of date operations. We hope this will make it easier to use in the future and we apologize again that we are unable to host it on Github.
