### ISSUE TITLE
MissingMethodException after updating WindowsAzure.Storage

### ISSUE THREAD

**Issue by wkoeter** [Azure/azure-storage-net#593]
After updating our storage package from v8.0.0 to 8.7.0 we had to alter CloudFile.UploadFromFile because it no longer had an overload accepting only a string. However, after altering the call to the method to another overload the following exception keeps occurring:

System.MissingMethodException: 'Method not found: 'Void Microsoft.WindowsAzure.Storage.File.CloudFile.UploadFromFile(System.String, System.IO.FileMode, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.File.FileRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'.'

**Comment by erezvani1529** [comment]
Hi @wkoeter,

Apologies for the delay in response.  Have you updated your target framework as well? Would you please share your project type and TFM name/version?

Thanks,
Elham

**Comment by erezvani1529** [comment]
Closing this issue as no response was received. Please reopen if you still have any issues.

**Comment by dneu** [comment]
I was having the MissingMethodException problem with TableOperation.Retrieve, too. Here's a workaround I used:

`            string queryString =
                TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, partitionKey);
            string queryString2 =
                TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.Equal, rowKey);
            string finalQuery = TableQuery.CombineFilters(queryString, TableOperators.And, queryString2);`

            `var query = new TableQuery<GenericTableEntity>().Where(finalQuery);`

            `TableQuerySegment<GenericTableEntity> segment = Task.Factory
                .FromAsync<TableQuery<GenericTableEntity>, TableContinuationToken, TableQuerySegment<GenericTableEntity>>(
                    _table.BeginExecuteQuerySegmented,
                    _table.EndExecuteQuerySegmented<GenericTableEntity>, query, null, null).Result;
            var res = segment.Results.SingleOrDefault();`
