### ISSUE TITLE
Unable to load DLL 'fusion.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by nefcanto** [Azure/azure-storage-net#596]
Environment: 
VS 2017 Community edition 15.5.2
dotnet --version => 2.1.2
Windows 10 Enterprise

Steps to reproduce this bug:

1. Create a simple console application using default template
2. Add these Nuget packages:
```
  <ItemGroup>
    <PackageReference Include="WindowsAzure.Storage" Version="8.7.0" />
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
  </ItemGroup>
```
3. Write these lines of codes to get a container:
```
var accessKey = "your access key";
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting(accessKey));
CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
CloudBlobContainer container = blobClient.GetContainerReference("images");
```
4. Run the application

**Comment by sameedaris** [comment]
I was facing same issue . CloudConfigurationManager.GetSetting(accessKey)  method looking in configuration files and it takes AppSetting key name only  as  paramater. but ironically i was passing whole connection string in place of Key so it was giving error . i think they need to correct exception message

**Comment by user3301** [comment]
I had this issue before, when I try to load the configuration information using `CloudConfigurationManager.GetSettings(key)` this exception showed up, one workaround is put your exact value of you settings in `Parse(settings)` method.

**Comment by JoyceLiang** [comment]
I see the same issue when I try to use Microsoft.WindowsAzure.ConfigurationManager in ASP.NET Core Web Application. ASP.NET Web Application(.NET Framework) do not have this problem.

**Comment by erezvani1529** [comment]
Thanks for reporting this issue. However, this issue should be opened on [Azure Sdk repo](https://github.com/Azure/azure-sdk-for-net) as it is related to Microsoft.WindowsAzure.ConfigurationManager package. 

Thanks!

**Comment by JoyceLiang** [comment]
This issue was moved to Azure/azure-sdk-for-net#4010

**Comment by JoyceLiang** [comment]
Thank you @erezvani1529 . I've moved this issue to https://github.com/Azure/azure-sdk-for-net/issues/4010
