### ISSUE TITLE
Cannot bind CloudTable in Azure Function with WindowsAzure.Storage 8.x.x

### ISSUE THREAD

**Issue by bsokol** [Azure/azure-storage-net#599]
I have a simple azure function triggered via HTTP with default CloudTable binding:

run.csx:
```
public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, CloudTable players, TraceWriter log)
{
    ...
}
```
`
function.json:
```
{
  "bindings": [
    ...
    {
      "name": "players",
      "type": "table",
      "tableName": "players",
      "connection": "AzureWebJobsStorage",
      "direction": "in"
    }
  ]
}
```
project.json:
```
{
"frameworks": {
    "net46": {
        "dependencies": {
            "WindowsAzure.Storage": "8.7.0"
        }
    }
  }
}
```
With 8.7.0 setup I've got this error:

```
Error:
Function ($update_data) Error: 
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.update_data'. 
Microsoft.Azure.WebJobs.Host: Can't bind Table to type 
'Microsoft.WindowsAzure.Storage.Table.CloudTable'.

```
But with 7.2.1 version of storage library the same CloudTable binding works seamlessly.

The problem is that I cannot back to 7.2.1 version because in this method I want also to use the new Queue functionality introduced in 8.0.0 runtime:
https://azure.microsoft.com/en-us/blog/azure-storage-queues-new-feature-pop-receipt-on-add-message/

Any tips how to get this working?

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
