### ISSUE TITLE
Incorrect Edm.Double, Edm.Int32 and Edm.Boolean handling with JsonNoMetadata payload.

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#600]
class Program
    {
        static void Main(string[] args)
        {
            var account = CloudStorageAccount.DevelopmentStorageAccount;
            var client = account.CreateCloudTableClient();
            var table = client.GetTableReference("test");

            // Changing payload format to any other value will make program complete successfully.
            client.DefaultRequestOptions.PayloadFormat = TablePayloadFormat.JsonNoMetadata;

            table.CreateIfNotExists();

            // According to https://docs.microsoft.com/en-us/rest/api/storageservices/payload-format-for-table-service-operations
            // Edm.Double, Edm.Int32 and Edm.Boolean are non ambiguous and no odata.type annotation should be required.

            var originalEntity = new DynamicTableEntity("pk", "rk");
            originalEntity["MyInt32Value"] = new EntityProperty((int)0);
            originalEntity["MyBoolValue"] = new EntityProperty(true);
            originalEntity["MyDoubleValue"] = new EntityProperty((double)(1.0));

            table.Execute(TableOperation.InsertOrReplace(originalEntity));

            var persistedEntity = (DynamicTableEntity)table.Execute(TableOperation.Retrieve<DynamicTableEntity>("pk", "rk")).Result;

            if (originalEntity["MyInt32Value"].Int32Value != persistedEntity["MyInt32Value"].Int32Value ||
                originalEntity["MyBoolValue"].BooleanValue != persistedEntity["MyBoolValue"].BooleanValue ||
                originalEntity["MyDoubleValue"].DoubleValue != persistedEntity["MyDoubleValue"].DoubleValue)
            {
                throw new InvalidDataException();
            }
        }
    }

Note, the bug is not in Azure storage, but rather in incorrect response handling of storage library after which property type is lost and all value become string (not to mention this is a huge performance degradation).

![image](https://user-images.githubusercontent.com/773346/34448968-cc1604f0-eca7-11e7-9fbb-fc7907346754.png)

**Comment by erezvani1529** [comment]
Hi @IlyaGrebnov ,

In case of JsonNoMetadata, to avoid the default string assumption on EdmTypes, you can use a PropertyResolver and pass it via TableRequestOptions to your queries. Something like below:

```
                TableRequestOptions options = new TableRequestOptions()
                {
                    PropertyResolver = (partitionKey, rowKey, propName, propValue) =>
                    {
                        if (propName == "MyBoolValue")
                        {
                            return EdmType.Boolean;
                        }
                        else if (propName == "MyInt32Value")
                        {
                            return EdmType.Int32;
                        }
                        else if (propName == "MyDoubleValue")
                        {
                            return EdmType.Double;
                        }
                        else
                        {
                            return EdmType.String;
                        }
                    }
                };
```
Please do not hesitate to reopen if this approach is not what you were referring to.

Thanks!

**Comment by IlyaGrebnov** [comment]
Approach you recommended is a workaround and not a fix, because property resolved should not be necessary for Edm.Double, Edm.Int32 and Edm.Boolean types.

Looks like I unable to reactive this issue.  @erezvani1529 could you please reactive it?
