### ISSUE TITLE
Reading Metadata from CloudBlockBlob

### ISSUE THREAD

**Issue by MayankSri** [Azure/azure-storage-net#603]
I set some Metadata to the blob while writing it:
```
CloudBlockBlob blob = await GetBlockBlobReference(connectionString, containerName , filePath);
blob.Metadata["CorrelationId"] = Guid.NewGuid().ToString();
// using data movement library
await TransferManager.UploadAsync(fileStream, blob);
```
I can see the metadata in the Azure storage explorer in Blob Properties
![image](https://user-images.githubusercontent.com/89298/34738404-7a1fafee-f53e-11e7-9c71-7dc93d09c614.png)

But, when I read the blob the Metadata comes out to be and empty dictionary.
![image](https://user-images.githubusercontent.com/89298/34738723-8daa9ed8-f53f-11e7-85b0-a0b08058b70c.png)

What am I missing?

**Comment by erezvani1529** [comment]
Hi @MayankSri,

I wasnt able to repro this issue with the SDK. I noticed you are using TransferManager so would you mind opening this issue with [DMLib repo](https://github.com/Azure/azure-storage-net-data-movement) as there might be a problem there.

Thanks,
Elham

**Comment by Cj-muse** [comment]
Hi, having the same issue but not using TransferManager.

I set my metadata as follows.
`
cloudBlockBlob.Metadata.Add("Key1",value1);
cloudBlockBlob.Metadata.Add("Key2", value2);
cloudBlockBlob.SetMetadata();
`

I attempt to read the metadata as follows.
`
blob.Metadata.TryGetValue("Key1", out outputVariable)
`

however the blob object read has no metadata but other properties are populated correctly, such as name, content, and time created. 

![image](https://user-images.githubusercontent.com/5886515/65362639-fe66df00-dbbc-11e9-825a-1ed10cad2c28.png)

The blob has all properties and correct metadata in Azure explorer but when read programmatically there is no metadata.

Any ideas?

Thank you,
Conner
