### ISSUE TITLE
Error While Initializing Derived class of TableEntity type.

### ISSUE THREAD

**Issue by joshidp** [Azure/azure-storage-net#605]
Hi There,

I am getting below error while initializing a class which is derived from TableEntity type.

![image](https://user-images.githubusercontent.com/7415276/35046046-d82327f0-fbbb-11e7-8c67-fa1f53950fca.png)

Please provide a resolution.

**Comment by erezvani1529** [comment]
Hi @joshidp,

Would you please share your application's target framework?

**Comment by joshidp** [comment]
I found the issue, traget framework is netStandard.

WHy do we have ctor with NotImplemented exception in TableEntity Class?

**Comment by erezvani1529** [comment]
Which netstandard version are you targeting?

**Comment by joshidp** [comment]
netStandard1

**Comment by erezvani1529** [comment]
Thanks.

Unfortunately the lowest Netstandard target that we support is netstandard1.3. You will need to update your target to at least netstandard1.3 to resolve this issue.

The netstandard1.0 that you see in the package is a façade to provide PCL support for our win8,winRT and wpa targets. For more information please see our ReadMe [section ](https://github.com/Azure/azure-storage-net/blob/master/README.md#netstandard10-fa%C3%A7ade)about the façade and PCL support.
