### ISSUE TITLE
System.Net.WebException at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [Azure/azure-storage-net#606]
we are getting "System.Net.WebException at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException". due to this event hub is not working.what could be the possible reasons for this exception

**Comment by erezvani1529** [comment]
Hi Abhishek,

Would you please share the full stack trace with us? How are you using the library and which framework are you targeting?

Thanks!

**Comment by erezvani1529** [comment]
@AbhishekAdusumilli,

Closing this issue since we did not receive enough information to investigate. Please re-open if you are still experiencing issues.

Thanks,
Elham

**Comment by abdulrahaman7** [comment]
We are getting this error when we are creating EventProcessorHost object using Microsoft.Azure.ServiceBus.EventProcessorHost.3.1.5 NuGet package. Here is the full error log

{"name":"Microsoft.ApplicationInsights","time":"2018-02-12T20:05:15.0362521Z","data":{"baseType":"ExceptionData","baseData":{"ver":2,"exceptions":[{"id":7880838,"typeName":"System.AggregateException","message":"A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.","hasFullStack":true},{"id":35342034,"outerId":7880838,"typeName":"Microsoft.WindowsAzure.Storage.StorageException","message":"The remote server returned an error: (400) Bad Request.","hasFullStack":true,"parsedStack":[{"level":0,"method":"Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync","assembly":"Microsoft.WindowsAzure.Storage, Version=8.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Executor\\Executor.cs","line":50},{"level":1,"method":"Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass1`1.<CreateCallback>b__0","assembly":"Microsoft.WindowsAzure.Storage, Version=8.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\AsyncExtensions.cs","line":66},{"level":2,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":3,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":4,"method":"Microsoft.ServiceBus.Messaging.BlobLeaseManager+<GetEventHubInfoAsync>d__46.MoveNext","assembly":"Microsoft.ServiceBus.Messaging.EventProcessorHost, Version=0.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},{"level":5,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":6,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":7,"method":"Microsoft.ServiceBus.Messaging.BlobLeaseManager+<IsStaleLeaseStore>d__42.MoveNext","assembly":"Microsoft.ServiceBus.Messaging.EventProcessorHost, Version=0.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},{"level":8,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":9,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":10,"method":"Microsoft.ServiceBus.Messaging.EventProcessorHost+<InitializeAsync>d__b.MoveNext","assembly":"Microsoft.ServiceBus.Messaging.EventProcessorHost, Version=0.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},{"level":11,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":12,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":13,"method":"Microsoft.ServiceBus.Messaging.EventProcessorHost+<StartAsync>d__16.MoveNext","assembly":"Microsoft.ServiceBus.Messaging.EventProcessorHost, Version=0.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}]},{"id":56793269,"outerId":35342034,"typeName":"System.Net.WebException","message":"The remote server returned an error: (400) Bad Request.","hasFullStack":true,"parsedStack":[{"level":0,"method":"Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException","assembly":"Microsoft.WindowsAzure.Storage, Version=8.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\Common\\Shared\\Protocol\\HttpResponseParsers.Common.cs","line":50},{"level":1,"method":"Microsoft.WindowsAzure.Storage.Blob.CloudBlob+<>c__DisplayClass26.<ExistsImpl>b__25","assembly":"Microsoft.WindowsAzure.Storage, Version=8.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Blob\\CloudBlob.cs","line":3270},{"level":2,"method":"Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse","assembly":"Microsoft.WindowsAzure.Storage, Version=8.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Executor\\Executor.cs","line":299}]}],"severityLevel":"Critical"}}}

**Comment by abdulrahaman7** [comment]
Issue is related to storage connection, we are using DefaultEndpointsProtocol as http even after enabling secure transfer enabled configuration. After updating DefaultEndpointsProtocol to https it working fine.
