### ISSUE TITLE
ListBlobsSegmentedAsync keeps returning segments with empty results although there are blobs

### ISSUE THREAD

**Issue by Duber** [Azure/azure-storage-net#612]
Hello,

Often when using ListBlobsSegmentedAsync I get segments with empty list of results yet non-null continuation token (because there are more files).

Some times I'm retrieving maximum number of results (5000) consistently and suddenly I start getting empty results for hours.

Any idea what is going on here ? It's very frustrating

**Comment by erezvani1529** [comment]
Hi @Duber,

Thanks for reporting your issue. Are you receiving the same continuation token every time?
Would you please email the following information of the most recent occurrences, to  `ascl at Microsoft dot com`:

- Time Stamps
- Server Request IDs
- Account Name

Thanks!

**Comment by erezvani1529** [comment]
Hi @Duber,

Are you still having problems with listing? Please let us know if there is anything to look into here.

Thanks,
Elham

**Comment by Duber** [comment]
Hello again @erezvani1529,

Sorry for the silence, I have sent an email with some of the information you requested.
After updating the azure storage nuget to lastest version the issue now is not critical anymore. Some times I still get empty results but after a while it catches up.

**Comment by pemari-msft** [comment]
This is the expected behavior - if a continuation token exists, it should be followed to obtain the entire result set. Sorry for the delay.
