### ISSUE TITLE
DownloadToStreamAsync:  The range specified is invalid for the current size of the resource.

### ISSUE THREAD

**Issue by fredrik-annytab** [Azure/azure-storage-net#613]
Hi,

I get this error almost every time when downloading a file from Azure Blob Storage. I can not see that I do a Range request by just calling DownloadToStreamAsync.

Asp.Net Core 2.0
WindowsAzure.Storage v8.7.0

**Code**
<pre>/// &lt;summary&gt;&#10;/// Download a blob to a stream&#10;/// &lt;/summary&gt;&#10;public async Task DownloadToStream(string blob_name, Stream stream)&#10;{&#10;    // Get a container reference&#10;    CloudBlobContainer container = await GetContainerReference();&#10;&#10;    // Get a blob object&#10;    CloudBlockBlob blob = container.GetBlockBlobReference(blob_name);&#10;&#10;    // Download the blob to a stream&#10;    try&#10;    {&#10;        await blob.DownloadToStreamAsync(stream);&#10;    }&#10;    catch(Exception ex)&#10;    {&#10;        // Log the exception&#10;        logger.LogError(ex, $&#34;DownloadToStream: {blob_name}&#34;, null);&#10;    }&#10;           &#10;} // End of the DownloadToStream method</pre>

**Exception**
<pre>{&#10;  &#34;name&#34;: &#34;Microsoft.ApplicationInsights.Dev.aeb9447a93364b65b2d0428942396406.Exception&#34;,&#10;  &#34;time&#34;: &#34;2018-01-26T17:09:20.9823747Z&#34;,&#10;  &#34;iKey&#34;: &#34;aeb9447a-9336-4b65-b2d0-428942396406&#34;,&#10;  &#34;tags&#34;: {&#10;    &#34;ai.internal.nodeName&#34;: &#34;Annytab&#34;,&#10;    &#34;ai.location.ip&#34;: &#34;127.0.0.1&#34;,&#10;    &#34;ai.operation.name&#34;: &#34;GET member/file [id]&#34;,&#10;    &#34;ai.session.id&#34;: &#34;C9vHv&#34;,&#10;    &#34;ai.operation.parentId&#34;: &#34;|5515837b-4a234b1029d672a5.&#34;,&#10;    &#34;ai.internal.sdkVersion&#34;: &#34;aspnet5c:2.1.1&#34;,&#10;    &#34;ai.user.id&#34;: &#34;0GWEm&#34;,&#10;    &#34;ai.cloud.roleInstance&#34;: &#34;Annytab&#34;,&#10;    &#34;ai.application.ver&#34;: &#34;1.0.0.0&#34;,&#10;    &#34;ai.operation.id&#34;: &#34;5515837b-4a234b1029d672a5&#34;&#10;  },&#10;  &#34;data&#34;: {&#10;    &#34;baseType&#34;: &#34;ExceptionData&#34;,&#10;    &#34;baseData&#34;: {&#10;      &#34;ver&#34;: 2,&#10;      &#34;properties&#34;: {&#10;        &#34;Exception&#34;: &#34;Microsoft.WindowsAzure.Storage.StorageException: The range specified is invalid for the current size of the resource.\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.&lt;ExecuteAsyncInternal&gt;d__4`1.MoveNext() in C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\WindowsRuntime\\Core\\Executor\\Executor.cs:line 315\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.&lt;&gt;c__DisplayClass72_0.&lt;&lt;DownloadRangeToStreamAsync&gt;b__0&gt;d.MoveNext() in C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\WindowsRuntime\\Blob\\CloudBlob.cs:line 448\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Annytab.Repositories.BlobStorageRepository.&lt;DownloadToStream&gt;d__5.MoveNext() in D:\\ASP-hemsidor\\NetCoreApplications\\DoxServer\\DoxServer\\Repositories\\BlobStorageRepository.cs:line 128\r\nRequest Information\r\nRequestID:32aaf714-001e-003b-63c8-967327000000\r\nRequestDate:Fri, 26 Jan 2018 18:09:20 GMT\r\nStatusMessage:The range specified is invalid for the current size of the resource.\r\nErrorCode:InvalidRange\r\nErrorMessage:The range specified is invalid for the current size of the resource.\nRequestId:32aaf714-001e-003b-63c8-967327000000\nTime:2018-01-26T17:09:18.1748760Z&#34;,&#10;        &#34;AspNetCoreEnvironment&#34;: &#34;Development&#34;,&#10;        &#34;{OriginalFormat}&#34;: &#34;DownloadToStream: 0c682b45-731c-44b8-b723-541b7ca914f0.dox&#34;,&#10;        &#34;CategoryName&#34;: &#34;Annytab.Repositories.BlobStorageRepository&#34;,&#10;        &#34;DeveloperMode&#34;: &#34;true&#34;&#10;      },&#10;      &#34;exceptions&#34;: [&#10;        {&#10;          &#34;id&#34;: 58786665,&#10;          &#34;typeName&#34;: &#34;Microsoft.WindowsAzure.Storage.StorageException&#34;,&#10;          &#34;message&#34;: &#34;DownloadToStream: 0c682b45-731c-44b8-b723-541b7ca914f0.dox&#34;,&#10;          &#34;hasFullStack&#34;: true,&#10;          &#34;parsedStack&#34;: [&#10;            {&#10;              &#34;level&#34;: 0,&#10;              &#34;method&#34;: &#34;Microsoft.WindowsAzure.Storage.Core.Executor.Executor+&lt;ExecuteAsyncInternal&gt;d__4`1.MoveNext&#34;,&#10;              &#34;assembly&#34;: &#34;Microsoft.WindowsAzure.Storage, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&#34;,&#10;              &#34;fileName&#34;: &#34;C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\WindowsRuntime\\Core\\Executor\\Executor.cs&#34;,&#10;              &#34;line&#34;: 315&#10;            },&#10;            {&#10;              &#34;level&#34;: 1,&#10;              &#34;method&#34;: &#34;System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw&#34;,&#10;              &#34;assembly&#34;: &#34;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&#34;&#10;            },&#10;            {&#10;              &#34;level&#34;: 2,&#10;              &#34;method&#34;: &#34;System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification&#34;,&#10;              &#34;assembly&#34;: &#34;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&#34;&#10;            },&#10;            {&#10;              &#34;level&#34;: 3,&#10;              &#34;method&#34;: &#34;Microsoft.WindowsAzure.Storage.Blob.CloudBlob+&lt;&gt;c__DisplayClass72_0+&lt;&lt;DownloadRangeToStreamAsync&gt;b__0&gt;d.MoveNext&#34;,&#10;              &#34;assembly&#34;: &#34;Microsoft.WindowsAzure.Storage, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&#34;,&#10;              &#34;fileName&#34;: &#34;C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\WindowsRuntime\\Blob\\CloudBlob.cs&#34;,&#10;              &#34;line&#34;: 448&#10;            },&#10;            {&#10;              &#34;level&#34;: 4,&#10;              &#34;method&#34;: &#34;System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw&#34;,&#10;              &#34;assembly&#34;: &#34;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&#34;&#10;            },&#10;            {&#10;              &#34;level&#34;: 5,&#10;              &#34;method&#34;: &#34;System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification&#34;,&#10;              &#34;assembly&#34;: &#34;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&#34;&#10;            },&#10;            {&#10;              &#34;level&#34;: 6,&#10;              &#34;method&#34;: &#34;Annytab.Repositories.BlobStorageRepository+&lt;DownloadToStream&gt;d__5.MoveNext&#34;,&#10;              &#34;assembly&#34;: &#34;DoxServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&#34;,&#10;              &#34;fileName&#34;: &#34;D:\\ASP-hemsidor\\NetCoreApplications\\DoxServer\\DoxServer\\Repositories\\BlobStorageRepository.cs&#34;,&#10;              &#34;line&#34;: 128&#10;            }&#10;          ]&#10;        }&#10;      ],&#10;      &#34;severityLevel&#34;: &#34;Error&#34;&#10;    }&#10;  }&#10;}</pre>

**Comment by erezvani1529** [comment]
Hi @fredrik-annytab ,

The DownloadToStream internally fetches the data via range gets. Would you please email the below information about the most recent repro of the issue to `ascl at Microsoft dot com`:

- TimeStamps 
- AccountName
- Server Request ID

Thanks,
Elham

**Comment by fredrik-annytab** [comment]
Ok, thank you.

**Comment by RealPasso** [comment]
Hello, 

We have the same problem with v8.7 because ProgressIncrementingStream is calling stream.get_position we are not able to call DownloadToStreamAsync with a  Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream stream anymore because it does not support get position (=> in short blob.downloadtostreamasync(response.body) does not work anymore).

In my case, the blob length is 1024 bytes which are correctly written into the stream then ProgressIncrementingStream.FlushAsync() calls get position which throws then the command is retried with a range: length-* where length == 1024 which fails with "The range specified is invalid".

Hope that helps.

Pascal

**Comment by erezvani1529** [comment]
Yes. This is very helpful. We have identified two issues here: First the retry after the flush operation throws and second, wrapping all streams in ProgressIncrementingStream(which assumes seekable true).

We will fix the above issues with our next release v9.1 and update.

Thanks again @fredrik-annytab and @RealPasso .

**Comment by erezvani1529** [comment]
@fredrik-annytab , @RealPasso , please try the latest [v9.1 package](https://www.nuget.org/packages/WindowsAzure.Storage/9.1.0) and let us know if you are still experiencing any issues.

Thanks!

**Comment by fredrik-annytab** [comment]
Hi!

I have tested with v9.1 and the error/exception does not appear anymore.

Thank you @erezvani1529.
