### ISSUE TITLE
always remote server Error as 404 for the directory which has UniCOde Charaters.

### ISSUE THREAD

**Issue by allinagaraju** [Azure/azure-storage-net#614]
Hi Team,

I am using the DLL, to read from Azure File Storage.
In Azure File Storage , files are moving from ONPREM and those files are moving successfully.
Issue: I need to read all the files and move to BLOB storage.
I am able to move all the files except files which resides in folder with Unicode characters like AAAA BBB NOTÃCIAS DE(11111) in the directory.
Issue occurs as 404 remote server error.

Azure FIle Storage sampe:
https://filestorage.net/abc/AAAA BBB NOTÃCIAS DE(11111)/AAAA BBB NOTÃCIAS DE(11111).txt

BUT when I find as https://filestorage.net/abc/AAAA BBB NOTÃCIAS DE(11111) as directory and fetch the list of Files using below code error occurs.

Note: It is loop and ignore in exception, but I need those files to move to BLOB and issue in loop in for Unicode characters.
Its a company name in Japan or Any Unicode language which I cannot rename as Able to create directory in ON PREM and can move to File Storage.
Its occurs in the loop for Unicode only. below is the example.

  var directory = item as CloudFileDirectory;
directory.ListFilesAndDirectories() fails only for Unicode for above sample. Please help to fix it.

DO let me know for any additional info needed.

Thanks,
Nagaraju.a

**Comment by mirobers** [comment]
Could you share the exception.ToString output?

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
