### ISSUE TITLE
Emulator won't start when running as different user than who installed it

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-storage-net#615]
I set up my machine when I was away from work and didn't have access to the domain, so I used a personal account to set up my machine and install VS 2017, including the Azure workload. Once I got to work, I connected to the domain and started using my domain account. However, I am not able to launch the emulator:

```
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe start
Windows Azure Storage Emulator 5.2.0.0 command line tool
Error: Unable to start the storage emulator.

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>cmd /K AzureStorageEmulator.exe help
Windows Azure Storage Emulator 5.2.0.0 command line tool
Usage:
    AzureStorageEmulator.exe init            : Initialize the emulator database and configuration.
    AzureStorageEmulator.exe start           : Start the emulator.
    AzureStorageEmulator.exe stop            : Stop the emulator.
    AzureStorageEmulator.exe status          : Get current emulator status.
    AzureStorageEmulator.exe clear           : Delete all data in the emulator.
    AzureStorageEmulator.exe help [command]  : Show general or command-specific help.

See the following URL for more command line help: http://go.microsoft.com/fwlink/?LinkId=392235
```

I tried clearing, initializing, starting, and stopping and nothing seemed to work. However, if I launch `cmd` as my original user, I am able to run the emulator. Is there a way to either:

1) Support multiple users using the emulator
2) Reset the emulator completely so I can use it from my domain account

The first option would be ideal, but the second would fix the issue I'm hitting (since I'm the only one on my machine).

**Comment by mirobers** [comment]
@twsouthwick Could you add the -inprocess parameter and paste in the response?
`AzureStorageEmulator.exe start -inprocess`

If the emulator has not been initialized for the current user, it attempts to automatically initialize for the current user. You can also manually initialize it using the `init` command, but it sounds like you already tried that -- did it successfully initialize?

**Comment by twsouthwick** [comment]
The emulator seems to work now that I have upgraded to RS4. Thanks!
