### ISSUE TITLE
Azure Storage Emulator won't init if username has an apostrophe in it

### ISSUE THREAD

**Issue by elmalakai** [Azure/azure-storage-net#617]
Looks like during the init for Azure Storage Emulator, it's not properly escaping that apostrophe for the SQL grant.

My Win10 development machine uses AzureAD and my user profile path contains an apostrophe, eg:"c:\users\MartyO'Malley" . This doesn't play nice when people use UserName or homePath/UserProfile in SQL statements, or even some power-shell commands where you pass in a path unescaped.

```
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe init
Windows Azure Storage Emulator 5.2.0.0 command line tool
Found SQL Instance (localdb)\MSSQLLocalDB.
Creating database AzureStorageEmulatorDb52 on SQL instance '(localdb)\MSSQLLocalDB'.

**Granting database access to user AzureAD\MartyO'Malley.**
**Cannot create database 'AzureStorageEmulatorDb52' : Incorrect syntax near 'Malley'.
Unclosed quotation mark after the character string ''..**
One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
Error: Cannot create database 'AzureStorageEmulatorDb52' : Incorrect syntax near 'Malley'.
Unclosed quotation mark after the character string ''..

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>

```

Can someone add in code to properly escape the single quote.

**Comment by mirobers** [comment]
Thanks for reporting this. We will track it for a future release.

**Comment by kfarmer-msft** [comment]
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite
