### ISSUE TITLE
cannot mock TableQuerySegment

### ISSUE THREAD

**Issue by juniwang** [Azure/azure-storage-net#619]
I'm writing unit tests for my codes where I need to fake Azure storage. Inside my test codes, I need to mock `cloudTable.ExecuteQuerySegmentedAsync(query, continuationToken, cancellationToken)`  which returns `TableQuerySegment<TElement>`. However `TableQuerySegment` has no public contructors so I'm unable to mock it or consturct its instance. What can be done so that I don't have to call azure actually but get a fake data to continue my tests?

**Comment by juniwang** [comment]
FYI
```
var entities= new List<MyEntity>()
                {
                    new MyEntity(),
                    new MyEntity(),
                };
            var segment = new Mock<TableQuerySegment<MyEntity>>();
            FakeTable.ShimTableQuerySegment<MyEntity>.AllInstances.ContinuationTokenGet = (a) => null;
            FakeTable.ShimTableQuerySegment<MyEntity>.AllInstances.ResultsGet = (a) => entities;
```
The line `new Mock<TableQuerySegment<MyEntity>>()` fails with "System.NotSupportedException : Parent does not have a default constructor. The default constructor must be explicitly defined.
". And if I try ` FakeTable.ShimCloudTable.AllInstances.ExecuteQuerySegmentedAsyncOf1TableQueryOfM0TableContinuationTokenCancellationToken<MyEntity>(
                (table, tq, tct, ct) => Task.FromResult(new TableQuerySegment<MyEntity>()));`, I cannot find any possible way to construct an instance of `TableQuerySegment<TElement>`.

**Comment by erezvani1529** [comment]
Since Azure Storage Table is now supported by CosmosDB and we do not want to diverge, adding Garrett(
@ausfeldt) to consider adding to CosmosDB package future releases.

Thanks,
Elham

**Comment by pdl5p** [comment]
I've worked around this issue by using reflection to create a mock instance of TableQuerySegment like so:-

`            var ctor = typeof(TableQuerySegment<MyEntity>)
                .GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic)
                .FirstOrDefault(c => c.GetParameters().Count() == 1);

            var mockQuerySegment = ctor.Invoke(new object[] { new List<MyEntity>() }) as TableQuerySegment<MyEntity>;
`

**Comment by juniwang** [comment]
@pdl5p Thanks, that's a great idea. It works for me

**Comment by wilofice** [comment]
@pdl5p You saved my day.

**Comment by kannannet** [comment]
Sorry I am a newbie here .. 
I tried faking this 

var ShimCloudTable = new ShimCloudTable
ShimCloudTable.ExecuteQuerySegmentedAsyncOf1TableQueryOfM0TableContinuationTokenCancellationToken<MyEntity>( (table, tq, tct, ct) => Task.FromResult(mockQuerySegment);

but still I get Object reference error when i call the  

cloudTable.ExecuteQuerySegmentedAsync(query, continuationToken, cancellationToken)

**Comment by rabrahamOpti** [comment]
@juniwang could you consider reopening this ticket? pdl5p's work-around is great, but it's still a work-around, and we should be able to Mock TableQuerySegment normally

**Comment by jklaus** [comment]
I second this being addressed.  To be honest the whole library could use a one over.  Higher level components don't have or implement interfaces, but at least their methods are virtual.  Lower level components do have interfaces but they go unused by the classes that leverage them.  The lower level classes have non-virtual methods making it difficult to mock around the fact that the higher level components implement directly to the classes.  Its nearly as bad as the original brokered message libraries that had everything implementing to sealed classes.

**Comment by ljsg** [comment]
> I've worked around this issue by using reflection to create a mock (well actually a real) instance of TableQuerySegment like so:-
> 
> ```
> var ctor = typeof(TableQuerySegment<MyEntity>)
>                 .GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic)
>                 .FirstOrDefault(c => c.GetParameters().Count() == 1);
> 
> var mockQuerySegment = ctor.Invoke(new object[] { new List<MyEntity>() }) as TableQuerySegment<MyEntity>;
> ```

If like me you also need to use the ContinuationToken in your tests you can expand @pdl5p 's code like so:
```
MethodInfo setTokenMethod = typeof(TableQuerySegment<MyEntity>).GetMethod("set_ContinuationToken", BindingFlags.NonPublic | BindingFlags.Instance);

var continuationToken = new TableContinuationToken();
setTokenMethod.Invoke(mockQuerySegment , new object[] { continuationToken });

cloudTable.Setup(t => t.ExecuteQuerySegmentedAsync(It.IsAny<TableQuery<MyEntity>>(), It.IsAny<TableContinuationToken>()))
                    .Returns(Task.FromResult(mockQuerySegment ))
```
This can be used to test when ExecuteQuerySegmentedAsync returns a continuation token meaning more results are available from the table

**Comment by wislon** [comment]
@ljsg your ContinuationToken 'setter' code couldn't have been better timed! Thanks so much for this! :)
