### ISSUE TITLE
V9.0.0 Queue Message Infinite TTL

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-storage-net#626]
This may be the wrong place for this, but reading through the change logs, it says there is now infinite TTL on storage queue message. Does this mean that the 7 day restriction on the queue message life time is removed? 

I could not find any reference to the 2017-07-29 version of the REST APIs or any news on the Azure Storage blog. Can you confirm my speculation and or point me to the documentation on the new REST API version?

![image](https://user-images.githubusercontent.com/8879065/35961565-c04a03cc-0cb6-11e8-84b3-c8e52621b821.png)

**Comment by mirobers** [comment]
Yes, you are correct in your interpretation. You can specify infinite TTL using the value `-1`.

The REST docs are live now. You can find them [here](https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services).

**Comment by gorillapower** [comment]
Awesome thank you!

**Comment by digitalgym** [comment]
SDK 9.3.3  Still does not support TTL > 7 days, I am unable to create a message with a TTL over 7 days with the latest version of the Storage SDK. Can you confirm the limitation has been removed?
