### ISSUE TITLE
Why is TableConstants not public for .Net core?

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-storage-net#627]
I've got some code that I've just updated to all be .Net core and found that `TableConstants.TableServiceBatchMaximumOperations` was causing an error due to it being inaccessible. 

It turned out that this was due to the following `#ifdef` that made it public for desktop, and internal for everything else.
 
https://github.com/Azure/azure-storage-net/blob/c1966e1cd64d5eb8e40733ebd6b07b6b8e8fb136/Lib/Common/Table/Protocol/TableConstants.cs#L26-L32

Can this be changed to make it public always?

**Comment by erezvani1529** [comment]
Hi @nrandell,

Adding Garrett from COSMOSDB team to consider this change for their **Table** NetCore support:  @austfeldt .
We are already making the protocol layer public in our future release of Blob/Queue/File split packages.

Thanks,
Elham

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for support or more information. 

Thanks!
