### ISSUE TITLE
Azure Storage Emulator attempts to create LocalDB files in c:\Users

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-storage-net#635]
When I run this command:

>AzureStorageEmulator.exe init -forcecreate 

I'm getting this error:

>Windows Azure Storage Emulator 5.3.0.0 command line tool
Found SQL Instance (localdb)\MSSQLLocalDB.
Creating database AzureStorageEmulatorDb53 on SQL instance '(localdb)\MSSQLLocalDB'.
Cannot create database 'AzureStorageEmulatorDb53' : The database 'AzureStorageEmulatorDb53' does not exist. Supply a valid database name. To see available databases, use sys.databases..
One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
Error: Cannot create database 'AzureStorageEmulatorDb53' : The database 'AzureStorageEmulatorDb53' does not exist. Supply a valid database name. To see available databases, use sys.databases..

In the log file I see this error:

>2018-02-20 13:59:03.21 spid53      CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\alexbat.REDMONDAzureStorageEmulatorDb53.mdf'.

So it attempts to create `C:\Users\alexbat.REDMONDAzureStorageEmulatorDb53.mdf` rather than `C:\Users\alexbat.REDMOND\AzureStorageEmulatorDb53.mdf` (note the slash before the file name).

Do you know why? How can this be fixed? I was getting the same error with ASE 5.2.

**Comment by abatishchev** [comment]
Can anyone take a look, please? Our route me to the appropriate team/contact?

**Comment by erezvani1529** [comment]
Hi @abatishchev,

Please follow the steps that we have outline [here](https://stackoverflow.com/questions/29239053/azure-storage-emulator-fails-after-adding-vs-2015-sdk/29239714#29239714) and let us know if you still see any issues.

Thanks!

**Comment by abatishchev** [comment]
As I said on the last paragraph,  the issue is that it tries to create `%USERPROFILE%AzureStorageEmulatorDb54.mdf` instead of `%USERPROFILE%\AzureStorageEmulatorDb54.mdf`.

**Comment by mirobers** [comment]
I see, the final backslash in the path is just missing. We'll take a look. @kfarmer-msft

**Comment by abatishchev** [comment]
hi @mirobers, I talked to @kfarmer-msft and we concluded that this issues is likely related to LocalDB/SQL Server rather than to Azure Storage Emulator. Do you have by chance any point of contact there? Here's a [public bug report](https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files) which I'm basically facing too.

**Comment by ranouf** [comment]
I Have the same error, any solution?

**Comment by abatishchev** [comment]
@ranouf see my answer on DBA.SE

**Comment by ndroussi-xo** [comment]
I tried to clean up localdb but didn't work, so anyone has an issue running storage emulator with local db can benefit from this command to run it on SqlExpress.

Command: `AzureStorageEmulator.exe init -server . -sqlinstance SQLEXPRESS -forcecreate`

**Comment by scottywakefield** [comment]
same problem again upgrading from 5.6 to 5.7...

**Comment by neoandeson** [comment]
This solution is **not recommend** in generally, but you can try it.
I think AzureStorageEmulator by somehow can not full access the localDB whitch setup in directory has limited the permission.  
1. You can go to folder propertiy > sercurity > edit to full permission ( with me directory is user > Appdata).
2. Restart the emulator
![inkeduntitled3_li](https://user-images.githubusercontent.com/28818096/51436669-17cd2980-1cc4-11e9-8f43-55e6f12415b4.jpg)
Now it worked. You must consider it's **unsercurity** later

**Comment by HeHeHunter** [comment]
If you are using LocalDB for SQL Server 2017 and hit the above issue, you may want to try install CU6 for SQL Server 2017 here: https://support.microsoft.com/en-sg/help/4101464

The fixes includes the following:
FIX: "Access is denied" error when you try to create a database in SQL Server 2017 Express LocalDB.
Reference: https://support.microsoft.com/en-us/help/4096875/fix-access-is-denied-error-when-you-try-to-create-a-database-in-sql-se

**Comment by davemichel** [comment]
I tried the latest CU yesterday to no avail. I was able to install Emulator with "AzureStorageEmulator init /forcecreate /sqlinstance MSSQLLocalDB". I could not use (localdb)\MSSQLLocalDB for some reason, but you can still connect to .\MSSQLLocalDB in SSMS if you want to see the Emulator data sausage.

It sure would be nice if Microsoft would fix this problem with SQL 2017.

**Comment by douglashm** [comment]
> If you are using LocalDB for SQL Server 2017 and hit the above issue, you may want to try install CU6 for SQL Server 2017 here: https://support.microsoft.com/en-sg/help/4101464
> 
> The fixes includes the following:
> FIX: "Access is denied" error when you try to create a database in SQL Server 2017 Express LocalDB.
> Reference: https://support.microsoft.com/en-us/help/4096875/fix-access-is-denied-error-when-you-try-to-create-a-database-in-sql-se

it worked for me 👍
