### ISSUE TITLE
Stop making beeps

### ISSUE THREAD

**Issue by 2moveit** [Azure/azure-storage-net#636]
Sounds funny but after a time it is really annoying.
When inserting the marker for listings • (0x00b7) into the table storage (DevelopmentStorageAccount!) you will get a beep on every symbol. You can reproduce it via API or with the Storage Explorer. Just edit a string property in the Storage Explorer (0.9.5), insert the symbol • (not the hex value) and press update. I'm a little bit worried if has performance impacts. It should't as it is on another thread but don't know if it blocks the thread.
Unfortunately you cannot make any rythm but can someone check if the cloud servers beep, too ;-)

**Comment by kfarmer-msft** [comment]
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite
