### ISSUE TITLE
Releases should sync up with version installed by VS 2017

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-storage-net#637]
Currently VS 2017 installs Storage emulator 5.2, but the minimum version thats compatible with the latest *stable* version of the WindowsAzure.Storage is 5.3, meaning if you're just using the latest stable VS 2017 and latest stable WindowsAzure.Storage, your application won't work.

**Comment by kfarmer-msft** [comment]
Unfortunately, VS releases will always lag behind Azure releases, which are tied to Azure server releases.
