### ISSUE TITLE
Latest version 9.0.0 is not compatible with tables 

### ISSUE THREAD

**Issue by xtellurian** [Azure/azure-storage-net#640]
Latest version of Nuget package does not work with Azure Tables!
The error occurs when using Emulator.

Attempting to write to a table, or create a table, will throw an exception with a remote server 400 response.

**Steps to reproduce:**
git clone https://github.com/Azure/azure-storage-net
update WindowsAzure.Storage to 9.0.0 using Nuget
run the sample for "Tables" (with local storage emulator) 
`azure-storage-net/Samples/GettingStarted/VisualStudioQuickStarts/DataTableStorage/`

Throws an error, reported as 400 response from remote server

Suggested fix:
Give the user a better error, not just "Remote server

**Comment by erezvani1529** [comment]
Hi @xtellurian ,

Which version of the emulator are you using? Please upgrade to latest v5.3 and let us know if you still have any issues.

Thanks

**Comment by xtellurian** [comment]
I was using 5.2, which must have come installed with Azure Tools
Upgrading to 5.3 seems to have resolved the issue.

Thanks!
