### ISSUE TITLE
HTTP 400 when executing CloudTable.CreateIfNotExists()

### ISSUE THREAD

**Issue by MovGP0** [Azure/azure-storage-net#642]
Given I want to check if the table users already exists
When I execute
```
CloudTable.CreateIfNotExists()
```
Then the following HTTP Request will be executed: 
```
POST /Tables() HTTP/1.1
{"tableName":"users"}
```

Then I get an HTTP 400 error. 

----
When executing
```
POST /Tables() HTTP/1.1
{"TableName":"users"}
```
manually, it works fine. I am unsure what causes the misspelling.

**Comment by MovGP0** [comment]
The problem is with Version 9.0.0 of the `WindowsAzure.Storage` NuGet. Version 8.7.0 works fine.

**Comment by MovGP0** [comment]
column names are now also in `cameCase` instead of `PascalCase`, such that existing table data cannot be read properly.

**Comment by erezvani1529** [comment]
Hi @MovGP0 ,

Thanks for reporting your issue. What is your project target/type? This issue doesn't appear in netfx, netcore, uwp or xamarin targets.

**Comment by MovGP0** [comment]
the target is .NET 4.6.2

**Comment by erezvani1529** [comment]
Thanks @MovGP0 ,

Do you have a global setting for your Json Serializer? That seems to be overwriting the default setting used by the library.

We will be publishing a fix for this issue in our[ 9.2 release.](https://github.com/Azure/azure-storage-net/milestone/8)

**Comment by MovGP0** [comment]
there are two requirements that come to my mind: 

- the global `JsonSerializerSettings` should not affect data access libraries that require specific settings 
- it must be possible to change the `JsonSerializerSettings` in order to support the serialization of custom datatypes (ie. [NodaTime Serialization](https://nodatime.org/2.2.x/userguide/serialization))

To answer the question, the configuration looks like this: 

```csharp
   public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            config.Formatters.JsonFormatter.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
            config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            config.Formatters.JsonFormatter.SerializerSettings.Formatting = Formatting.Indented;
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                Formatting = Formatting.Indented,
                NullValueHandling = NullValueHandling.Ignore
            };

        // ...
        }
    }
```

**Comment by porschiey** [comment]
We're running into the same **casing** issue. No matter what we set in global serializer settings, all properties (apart from Pkey, rkey, timestamp) get saved as camelCase. Caused a temporary outage for us.

**Comment by nheinbaugh** [comment]
Do we have an ETA for 9.2?

**Comment by erezvani1529** [comment]
Thanks for reporting this issue . Please upgrade to [v9.1.1](https://www.nuget.org/packages/WindowsAzure.Storage/9.1.1) to get the fix.
