### ISSUE TITLE
Make Acquire(Change)Lease's proposedLeaseId Nullable<System.Guid> instead of string

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-storage-net#643]
The call to `Acquire(Change)Lease`/`Async` simply fails with a 400 BAD REQUEST if you try to use anything other than a GUID. It's not intuitive to have this as a `string` parameter, then, and leads users to believe they can ask for a `proposedLeaseId` of "foo" which will simply throw them a 400 w/ no reasoning.

We should either make this a System.Guid parameter, or allow *any* string as the value for `proposedLeaseId`

**Comment by erezvani1529** [comment]
Thanks @brandonh-msft . We will consider taking this suggestion for our split package release (currently in preview).
