### ISSUE TITLE
Retrieving entity with double.NaN fails

### ISSUE THREAD

**Issue by VDBorovikov** [Azure/azure-storage-net#644]
We have several services that work with `Windows Azure.Storage` version `8.7`. They are recording rows in Tables, which can contain `double.NaN` in some fields. 
After upgrading from `Windows Azure.Storage` in our API prior to version `9.1`, requesting such rows results in an exception. Also, if you try to write `double.NaN` in version `9.1`, in fact, 0 is written to the table. Zero is not NaN.
Summarize steps reproducing error:
1. Create entity in Table wich holds `double.Nan` in any field with `WindowsAzure.Storage 8.7`
2. Update current project with `WindowsAzure.Storage 9.1` or `9.0` and try to retreive created entity in step 1 (or do it in another project with `WindowsAzure.Storage 9.0/9.1`).
3. Reaplace or create entity with `double.Nan` with `WindowsAzure.Storge 9.1 or 9.0`.
4. Retreive entity from step 3.

**Comment by erezvani1529** [comment]
Thanks @VDBorovikov for reporting this issue.

We will look into this and most likely provide a fix very soon. I will update with more details after investigation.

**Comment by kfarmer-msft** [comment]
Thanks again, @VDBorovikov.

This was a result of our work to remove the dependency on the OData library.  Basically, the SDK fails to consider the possibility of NaN, PositiveInfinity, and Negative infinity, and (notably) doesn't transmit appropriate metadata marking them as doubles.

We've made changes to restore support, and have expanded out the entity testing to avoid losing these cases in the future.  We apologize for the oversight, and will get these changes out as soon as we can.

**Comment by erezvani1529** [comment]
Please upgrade to [v9.1.1](https://www.nuget.org/packages/WindowsAzure.Storage/9.1.1) for the fix.

Thanks!

**Comment by mguntli** [comment]
FYI: due to this bug you could end up with an inconsistent database (which does not match to your entity objects) if you have stored entities with 9.1, and read them back with 9.1.1.

```
class MyTestEntity : TableEntity {
    public double TestValue { get; set; }
}
```
Allthough you have defined your entity objects with double properties, it could have been saved as Edm.String (in case of NaN, Infinity). Reading the entity back in such scenarios fails.

A **possible workaround is to overwrite the _ReadEntity_ method** and attempt safely parse the value in case it has been erroneously stored as string.

```
class MyTestEntity : TableEntity {
    public double TestValue { get; set; }
    public override void ReadEntity(IDictionary<string, EntityProperty> properties, OperationContext operationContext) {
        TestValue = TryReadDouble(properties["TestValue"]);
    }

    static double TryReadDouble(EntityProperty entity) {
        if (entity.PropertyType == EdmType.Double) {
            return entity.DoubleValue.Value;
        }
        else if (entity.PropertyType == EdmType.String) {
            // Due to a bug in Azure storage NaN, PositiveInfinity and NegativeInfinity has been stored as string (https://github.com/Azure/azure-storage-net/issues/644)
            return Double.Parse(entity.StringValue, CultureInfo.InvariantCulture);
        }
        else {
            throw new InvalidOperationException();
        }
    }
}
```
