### ISSUE TITLE
Calling DownloadBlockListAsync method without getting exception

### ISSUE THREAD

**Issue by laukotomi** [Azure/azure-storage-net#649]
Hi,

I made an application which tries to upload big files in smaller blocks to the blob storage. Before starting to upload the blocks I would like to check if there are any blocks of the file already uploaded, so I call the DownloadBlockListAsync method of CloudBlockBlob class. If there are already uploaded blocks then I will skip those and continue from where the previous process failed. But when I am uploading a brand new file to the storage this call will throw an exception because the blob doesn't exist.

Is there a way to avoid this exception? Or can I request for a method change or a method that checks whether a blob has any uploaded blocks or returns an empty array if there aren't? Having a small try-catch block, because of the behave of this method and throwing an exception when a new file is being uploaded looks really bad right now. ExistsAsync method returns true only if a file is uploaded completely.

**Comment by zezha-msft** [comment]
Hi @laukotomi, according to the [.NET Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing), all methods should throw when they are unable to perform what their method name indicates:
> Execution failure occurs whenever a member cannot do what it was designed to do (what the member name implies). For example, if the OpenFile method cannot return an opened file handle to the caller, it would be considered an execution failure.

Therefore, the method `DownloadBlockListAsync` should throw, as it does.
