### ISSUE TITLE
Inline documentation: CloudQueue.PeekMessages(int) and similar don't tell max number to request

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-storage-net#650]
This is a reference doc issue that requires a change to the underlying `///` comments.

From @chaselal (https://github.com/Azure/azure-docs-sdk-dotnet/issues/396):

> The max number of messages to request from a queue is 32, according to the [REST API documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/peek-messages). This number (32) is not documented in the .NET SDK.
> 
> E.g.
> [PeekMessages](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.queue.cloudqueue.peekmessages?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Queue_CloudQueue_PeekMessages_System_Int32_Microsoft_WindowsAzure_Storage_Queue_QueueRequestOptions_Microsoft_WindowsAzure_Storage_OperationContext_)
> [GetMessages](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.queue.cloudqueue.getmessages?view=azure-dotnet)

cc: @tamram

**Comment by tamram** [comment]
@mirobers - Can you take care of this one in the SDK comments?

**Comment by erezvani1529** [comment]
This should be fixed in v9.1.1.

Thanks!
