### ISSUE TITLE
Data from TableClient is accessible after deleting the table.

### ISSUE THREAD

**Issue by macchmie3** [Azure/azure-storage-net#652]
From [microsoft docs:](https://docs.microsoft.com/en-us/cli/azure/storage/table?view=azure-cli-latest#az_storage_table_delete)

> When a table is successfully deleted, it is immediately marked for deletion and is no longer accessible to clients. The table is later removed from the Table service during garbage collection. Note that deleting a table is likely to take at least 40 seconds to complete. If an operation is attempted against the table while it was being deleted, an AzureConflictHttpError will be thrown.

After deleting a table, it's content is still accessible via CreateQuery<>. Is this intentional or not?

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
