### ISSUE TITLE
Blobs deleted with DeleteRetentionPolicy do not delete blobs after alloted time.

### ISSUE THREAD

**Issue by macchmie3** [Azure/azure-storage-net#653]
I wanted to test out the new Soft Delete mechanism. I found out that the results where unexpected in one of the testing case. What I did was as follows:

1. Set DeleteRetentionPolicy to enabled and Retention Days to 1.
2. Get reference to a new, non-existent blob in an empty container.
3. Upload data to the blob three times in a row (each time different data) using UploadFromByteArray.
4. Call Delete on the blob.

**My observations:**

Just after Step 3, what I got from the container after calling: _ListBlobs(useFlatBlobListing: true, blobListingDetails: BlobListingDetails.All)_ was just a single CloudBlockBlob with the last version I uploaded.

After Step 4, after calling the same ListBlobs method I got 3 blobs - all with _IsDeleted_ set to _true_. First two were snapshots of two initial versions of data that I uploaded, and the last one was the blob I uploaded as the third version (that one was not a snapshot)

After that I looked again to the storage after about a week. What I noticed in general was that the snapshots were gone, but the "third blob" is still visible.

**Questions:**
- Why were the snapshots visible only after deleting the blob?
- Why the "third blob" is not deleted?

**Comment by mirobers** [comment]
I just tried this by overwriting a blob a few times (and not deleting the blob), and I see all deleted snapshots in the listing as expected. This is with version 9.1. What client version are you using?

For the second question, the blob cleanup could be delayed (it's best effort) but typically not by a week. Are you still seeing this behavior?
