### ISSUE TITLE
UploadFromByteArrayAsync

### ISSUE THREAD

**Issue by mail19** [Azure/azure-storage-net#655]
I'm creating an archived file (zip file) in the cloud using CloudFile. If I'm debugging with break points, archive file is being created as expected. No break points, archive file entries except first file are corrupted. The corrupted files are created but empty.

**Comment by kfarmer-msft** [comment]
Thanks, @mail19. I've forwarded this to the team for investigation.

What version of the SDK are you using?

**Comment by mirobers** [comment]
Closing due to lack of information. If you are still seeing an issue please reopen with SDK version and code sample included.
