### ISSUE TITLE
UploadFromFile method not found

### ISSUE THREAD

**Issue by adriapa5** [Azure/azure-storage-net#657]
System.MissingMethodException: Method not found: 'Void Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromFile(System.String, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'.

When using Storage 9.1.0

**Comment by kfarmer-msft** [comment]
Hi, @adriapa5 --

We've seen a situation like this before with NuGet picking a lower-level release than intended, when there's a mix of platforms going on.  The workaround is that case is to directly reference the assembly. 

Do you mind describing the references going on in your project?

**Comment by rabrahamOpti** [comment]
@kfarmer-msft I'm running into a similar error in an Azure Function I'm writing. I'm using an #r statement to reference Microsoft.WindowsAzure.Storage at the head of my run.csx file. The error looks like this:

**Method not found: 'Void Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromFile(System.String, System.IO.FileMode, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'**

**Comment by seanmcc-msft** [comment]
We are looking at improving our cross-platform strategy in a future version of the library.
