### ISSUE TITLE
Use SecureString whenever possible to avoid exposing secrets

### ISSUE THREAD

**Issue by giggio** [Azure/azure-storage-net#663]
Right now you are using a regular string in classes like `StorageCredentials`, exposing secure information, like storage keys. For example:

https://github.com/Azure/azure-storage-net/blob/e01de1b34c316255f1ffe8f5e80917150325b088/Lib/Common/Auth/StorageCredentials.cs#L138

To avoid that you should stop using string and use `SecureString`, which is [now available on .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netstandard-2.0).

This way, if a memory dump is taken, or the memory is saved to disk, etc, the secret is not compromised.

And uses of `string` to store secrets should be marked as obsolete. The above constructor, for example.

**Comment by seanmcc-msft** [comment]
Thanks for your suggestion, we will are considering using SecureString in our next major release.

**Comment by amishra-dev** [comment]
based on https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md we decided to not pursue this further.
