### ISSUE TITLE
[v. 9.1.0] double values parsed differently depending on the running thread's culture

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-storage-net#664]
In version 8.7.0 when parsing an entity with a double value, it was parsed the same way without taking into account the running thread's culture, after updating to v. 9.1.0 that parsing is not always the same and it's dependent on the running thread's culture.

Is that an intended change? I did not find any commit related to this specifically or a breaking change in the release notes.

**Comment by pizerg** [comment]
The same issue also happens with the new version 9.1.1 released a few hours ago

**Comment by erezvani1529** [comment]
Hi @pizerg,

What is your target framework? Would you please share a simple repro code if possible?

Thanks!

**Comment by pizerg** [comment]
Hi @erezvani1529,

Target framework is 4.6.1.

To repro the issue:

* Create some table and insert some double data
* Create a CloudTableClient
* Set the desired thread culture 
```
var ci = new CultureInfo(YOUR_CULTURE_HERE);
System.Threading.Thread.CurrentThread.CurrentUICulture = ci;
System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(ci.Name);
```
* Just retrieve the data using CloudTable.ExecuteQueryAsync(...) method
* Repeat for a different culture

Two cultures that throw different results are "en-US" and "es-ES"

**Comment by pizerg** [comment]
Hi,

Are there any news about this issue? 
Is it considered as expected behaviour from now on or it will be reverted?

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
