### ISSUE TITLE
Invalid blob list item returned in 4.0 but not 3.0

### ISSUE THREAD

**Issue by s093294** [Azure/azure-storage-net#67]
https://gist.github.com/s093294/bc37a83fc93995b8dbbe

In the gist I listed my test program that shows how things worked in 3.x but not in 4.x with ListBlobs.

Due to the amount of files its hard to find out which file causes the issue.

**Comment by jehine-MSFT** [comment]
Hello @s093294,

Did you ever get this upgrade issue figured out? If not, we can definitely take a look.

Thanks!

**Comment by jehine-MSFT** [comment]
We weren’t able to repro this issue. Please feel free to reopen the issue if you’re able to provide more information.
