### ISSUE TITLE
Get exception when set properties on existing blob

### ISSUE THREAD

**Issue by BH4EHN** [Azure/azure-storage-net#674]
I'm trying to set property on existing blob
``` C#
var storageAccount = CloudStorageAccount.Parse(connectionString);
var cloudBlobClient = storageAccount.CreateCloudBlobClient();
var cloudBlobContainer = cloudBlobClient.GetContainerReference("mycontainer");
var blockBlobReference = await cloudBlobContainer.GetBlobReferenceFromServerAsync("myblobname");
blockBlobReference.Properties.ContentDisposition = $"attachment; filename=\"filename.ext\"";
await blockBlobReference.SetPropertiesAsync();
```
After `SetPropertiesAsync()`, I got a exception saying `Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

This is very wired, I have similar codes in other function, `StartCopyAsync()` and then `SetPropertiesAsync()` runs without any problem.

Environment:
Host on AppService on Azure
.NET Core SDK 2.1.104
.NET Core 2.0.0
ASP.NET Core 2.0.6
WindowsAzure.Storage 9.1.1

---
Update 16 hours later

I tried a lot method about the authentication to solve this problem but failed.
After I tried do the same thing use NodeJS, I finally realize the filename in  `ContentDisposition` contains Chinese characters can cause this problem (this also occoured as well as on NodeJS Azure Storage SDK).
Then I change the content of `ContentDisposition` to `$"attachment; filename*=''{utf8EncodedFileName}"`, everything works fine.

But I still think this is a problem, because the exception message is leading to a totally wrong way.

**Comment by seanmcc-msft** [comment]
Thanks for your suggestion, we are considering improving our exception messaging in the future.
