### ISSUE TITLE
Ref docs /// issue: RecordSetsOperationsExtensions.Delete behavior unclear

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-storage-net#676]
@tster123 commented on [Thu Apr 12 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/582) regarding [RecordSetsOperationsExtensions.Delete(IRecordSetsOperations, String, String, String, RecordType, String) Method (Microsoft.Azure.Management.Dns)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.dns.recordsetsoperationsextensions.delete?view=azure-dotnet#Microsoft_Azure_Management_Dns_RecordSetsOperationsExtensions_Delete_Microsoft_Azure_Management_Dns_IRecordSetsOperations_System_String_System_String_System_String_Microsoft_Azure_Management_Dns_Models_RecordType_System_String_)

What happens if the record set doesn't exist?  What kind of exceptions can be thrown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee169ce3-d3a1-4023-2fd0-e5fcc8833b0f
* Version Independent ID: 0171f512-8cd2-6bc6-7ba5-e851ea235de3
* Content: [RecordSetsOperationsExtensions.Delete(IRecordSetsOperations, String, String, String, RecordType, String) Method (Microsoft.Azure.Management.Dns)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.dns.recordsetsoperationsextensions.delete?view=azure-dotnet#Microsoft_Azure_Management_Dns_RecordSetsOperationsExtensions_Delete_Microsoft_Azure_Management_Dns_IRecordSetsOperations_System_String_System_String_System_String_Microsoft_Azure_Management_Dns_Models_RecordType_System_String_)
* Content Source: [xml/Microsoft.Azure.Management.Dns/RecordSetsOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Dns/RecordSetsOperationsExtensions.xml)
* Service: **dns**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mirobers** [comment]
Please move this issue to the DNS management repo.

**Comment by CamSoper** [comment]
@mirobers I'm not quite sure how it ended up here. Sorry about that, my bad!
