### ISSUE TITLE
Ref doc /// issue: CloudBlobClient.GetContainerReference doc not useful

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-storage-net#677]
@skofman1 commented on [Tue Apr 03 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/566)

I'm trying to understand what's the behavior of this method if the container doesn't exist, but it's not readily available in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e14fce0-457a-49b9-5591-53885864e6e9
* Version Independent ID: 6377895a-8fba-2fea-2066-9db4eead9566
* Content: [CloudBlobClient.GetContainerReference(String) Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobclient.getcontainerreference?view=azure-dotnet#applies-to)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mirobers** [comment]
GetContainerReference is independent of existence of objects in storage. You can get a reference to any container, whether it exists or not. For detailed information on the behavior of storage APIs, please check the [REST docs](https://docs.microsoft.com/en-us/rest/api/storageservices/).

**Comment by CamSoper** [comment]
Right, but maybe that should be in the inline `///` docs? I'm not familiar with your source code.  Please point me to the location in your repo and I'll be happy to make the change. :)
