### ISSUE TITLE
Calling ListQueues on a Blob-only storage account never returns.

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-storage-net#678]
If you have a blob-only storage account, get a Queue Client and call List Queues, the method appears to never return. This is unlike List Tables on Table Client, which returns a 501 immediately.

**Comment by mirobers** [comment]
I just tried this, and got the expected error due to hostname resolution:

> Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: 'myaccount.queue.core.windows.net'

The reason table gives a different error is that a blob storage account actually does have a table endpoint associated with it to expose metrics. But there is no queue endpoint, so the hostname fails to resolve.

**Comment by isaacabraham** [comment]
@mirobers is there a way to programmatically check is a storage account is "blob-only"?

**Comment by isaacabraham** [comment]
I'm asking because I'm (finally) retesting this and still seeing the same behaviour with 9.3.3:

Here's a trivial F# application that exhibits the issue I'm seeing:

```fsharp
[<EntryPoint>]
let main argv =
    let client = CloudStorageAccount.Parse(ConnectionString).CreateCloudQueueClient()
    printfn "Working!"
    let r = client.ListQueuesSegmentedAsync(null).Result // Never returns
    printfn "%A" r
```

**Comment by mirobers** [comment]
The simplest way to detect this would be to do a DNS lookup on the queue endpoint. If the endpoint doesn't exist then you can avoid trying to access it.

**Comment by isaacabraham** [comment]
@mirobers ok, thanks. In your first message regarding the storage exception that you received - how were you able to get that?

**Comment by mirobers** [comment]
That's essentially the same as your repro code on a standard BlobStorage account. It's not clear why you are not seeing the same thing. Maybe DNS resolution is having some problem. It would be interesting to see what happens when you try to resolve it yourself.
