### ISSUE TITLE
Support for IWebProxy

### ISSUE THREAD

**Issue by DanBovenzi** [Azure/azure-storage-net#679]
I have a. Net Core 2.0 client that runs behind a corporate firewall.  I need to route requests to blob storage via a proxy to get out of the firewall.
I need to be able to set proxy settings for the CloudStorageAccount.  This seems to be possible in the java version of this library but not the .Net version.
Is there any way to implement set the proxy using IWebProxy injection, similar to the way HttpClient implements it?

**Comment by kfarmer-msft** [comment]
9.4.1 includes the ability to pass in DelegatingHandler chains, which at runtime will have an HttpClientHandler instance assigned to the innermost InnerHandler property. This can be leveraged to set the Proxy (or any other property supported by HttpClientHandler). For example, see DelegatingHanlderImpl in TestBase.Common.cs, and the CloudBlobContainerVerifyProxyHit test in CloudBlobContainerTest.cs.
