### ISSUE TITLE
Suggestion: ListBlobsAsync/ListContainersAsync

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-storage-net#68]
Right now, async equivalents of ListBlobs/ListContainers are ListBlobsSegmentedAsync/ListContainersSegmentedAsync. These segmented methods needs to be used in a while loop to pass ContinuationToken between HTTP requests to get *all* blobs (just like in ListBlobs method). 

Many people get caught into this pitfall and think segmented methods are direct equivalents of those sync methods and therefore they only get first e.g. 5000 results from the REST API –which mostly introduces a bug later on. I have seen many people using it improperly like this.

Therefore adding helper methods ListBlobsAsync/ListContainersAsync would certainly help people to find async equivalent of those sync methods and they wouldn't need to go back and forth between MSDN docs & VS.

**Comment by ahmetalpbalkan** [comment]
@pemari-msft this is an open suggestion. please reopen.

**Comment by pemari-msft** [comment]
Apologies -- meant to link the similar issue in the repo here: Azure/azure-storage-net/issues/94. As per my response there or the response in the link Cheesebaron provided, this is not considered best practice to list everything in a greedy fashion. .NET does not at the moment include built-in support for async lazy iteration; we will consider this feature when the framework supports it.

**Comment by ahmetalpbalkan** [comment]
Sounds good then.
