### ISSUE TITLE
Option to not throw exceptions for conflicts in table storage

### ISSUE THREAD

**Issue by mikenorgate** [Azure/azure-storage-net#686]
I have a piece of code (see below) that is sending a lot of data to table storage, as part of this in high thoughput scenarios we get a number of conflicts (which is expected). 

We have been seeing a real performance issue because every conflict throws an exception. Is it possible to not throw the exception and just have access to the status codes in `TableResult`

Here is my code

    do
    {
        ++version;
        retry = false;

        var batch = new TableBatchOperation();
        if (!string.IsNullOrWhiteSpace(evt.IdempotentMarker))
        {
            batch.Add(TableOperation.Insert(new IdempotentRow(appliedEvent.Name, appliedEvent.Id, evt.IdempotentMarker)));
        }
        batch.Add(TableOperation.Insert(new EventRow(appliedEvent.Name, appliedEvent.Id, evt.GetType(), JsonConvert.SerializeObject(evt, evt.GetType(), _jsonSerializerSettings), version)));
        batch.Add(TableOperation.InsertOrReplace(new VersionRow(appliedEvent.Name, appliedEvent.Id, version)));

        try
        {
            results = await _tableRef.ExecuteBatchAsync(batch);
            //Instead of needing to catch exception can the failure just been a value in results?
        }
        catch (StorageException ex)
        {
            if (ex.RequestInformation.HttpStatusCode == 409)
            {
                // If there is an idempotent row, and it conflicts, ignore the exception and continue 
                if (!string.IsNullOrWhiteSpace(evt.IdempotentMarker) && ex.RequestInformation.HttpStatusMessage.StartsWith("0:"))
                {
                    continue;
                }

                retry = true;
                continue;
            }

            throw;
        }
    } while (retry);

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
