### ISSUE TITLE
Azure blob storage create snapshot with metadata data returns 400

### ISSUE THREAD

**Issue by hengjiaqi** [Azure/azure-storage-net#687]
Hi,

The code snippet below returns 400 error msg at the last line. Not sure if I missed anything?
I'm using this document as my reference: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-snapshots

```
            var blobClient = CloudStorageAccount.Parse("connection-string").CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("test");
            var cloudBlockBlob = container.GetBlockBlobReference("dummy.ttl");
            var metadata = new Dictionary<string, string>();
            metadata.Add("time-created", DateTime.UtcNow.Ticks.ToString());
            /*cloudBlockBlob.CreateSnapshot() works fine*/
            cloudBlockBlob.CreateSnapshot(metadata, null,null,null);
```

Microsoft.WindowsAzure.Storage.StorageException: 'The remote server returned an error: (400) Bad Request.'

**Comment by benederke** [comment]
The - is an illegal character; try replacing it with an underscore.

You can test for illegal chars at Microsoft Azure Storage Explorer: "The metadata specified is invalid. It has characters that are not permitted."
