### ISSUE TITLE
[v. 9.1.1] double values parsed differently depending on PayloadFormat

### ISSUE THREAD

**Issue by hodzanassredin** [Azure/azure-storage-net#690]
I have a double field in azure table. 
In case of TableRequestOptions.PayloadFormat = TablePayloadFormat.JsonNoMetadata this double xxx.yyyy returned as xxxyyy.
In case of TableRequestOptions.PayloadFormat = TablePayloadFormat.Json this double xxx.yyyy returned as is xxx.yyyy.

targetFramework="net462"

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
