### ISSUE TITLE
"Object reference not set to an instance of an object." Exception thrown when trying to create a blob

### ISSUE THREAD

**Issue by estenori** [Azure/azure-storage-net#695]
In our project, we were using the 6.0.0 version and we were making use of the UploadTextAsync method to create blobs. After updating to the latest version, the UploadTextAsync function stopped working and now it throws an exception: "Object reference not set to an instance of an object."

I've tried different methods to replace it but all throw the same exception. For example:

```
byte[] fileBytes = Encoding.UTF8.GetBytes(data);
await lockBlob.UploadFromByteArrayAsync(fileBytes, 0, fileBytes.Length);
```

The only way I made it work was to change to the synchronous version: 

```
BlobRequestOptions blobOptions = new BlobRequestOptions
{
         MaximumExecutionTime = TimeSpan.FromSeconds(5),
};
lockBlob.UploadText(data, null, null, blobOptions, null);
```

How can I make the async version work? Is there a workaround or are you planning on fixing this any time soon?

**Comment by seanmcc-msft** [comment]
Please update to version 9.4+.
