### ISSUE TITLE
No method to use TableOperators.Not

### ISSUE THREAD

**Issue by rychuhardy** [Azure/azure-storage-net#696]
I am trying to compose the following query:

`not (LastNotified ge datetime'2018-05-12T10:04:17.978Z')`

The negation allows to return rows which do not have LastNotified column set.

There is a an operator for negating
`TableOperators.Not`
but there is no method that allows to combine it into query.

TableOperators.And and TableOperators.Or can be used in using TableQuery.CombineFilters method
`TableQuery.CombineFilters(query1, TableOperators.And, query2)`

I believe that there should be an overload allowing to use TableOperators.Not
`TableQuery.CombineFilters(TableOperators.Not, query)`

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for support or more information. 

Thanks!
