### ISSUE TITLE
Can't set cloudFile.Properties.ContentMD5

### ISSUE THREAD

**Issue by jkrakov** [Azure/azure-storage-net#698]
Hello
I am setting cloudFile.Properties.ContentMD5 value and uploading file to storage.
After upload i am checking the value in Storage Explorer and the value of ContentMD5 is null.
I tried to set cloudFile.Properties.ContentDisposition in the same way and it works.
Please help

**Comment by seanmcc-msft** [comment]
Please reopen if you are still experiencing this issue.
