### ISSUE TITLE
CloudBlobDirectory properties not marked as virtual

### ISSUE THREAD

**Issue by thomasddn** [Azure/azure-storage-net#709]
I found that the properties of `CloudBlobDirectory` are not marked as virtual (or are not described by an interface) which prevents mocking them. The property I'm particularly interested in is `Prefix`.

In issue #465 @erezvani1529 [indicates](https://github.com/Azure/azure-storage-net/issues/465#issuecomment-307253223) that properties would also be made virtual, but apparently this is not yet the case for `CloudBlobDirectory` in version 9.2 of WindowsAzure.Storage.

Could these properties also be made virtual?

Another option is to make the constructor public. Then we can create `CloudBlobDirectory`'s and mock the virtual methods.

**Comment by seanmcc-msft** [comment]
Fixed in version 10.0.3

Commit: https://github.com/Azure/azure-storage-net/commit/550427e7090ab656f4a8279e7cdd85fba6c6cc98

**Comment by MarcM-PL** [comment]
the Prefix property is still not virtual in 11.2?
