### ISSUE TITLE
Multiple table ExistsAsync() methods take too long to complete

### ISSUE THREAD

**Issue by IlyaBezus** [Azure/azure-storage-net#710]
After upgrading from **v.8.7.0** to **v.9.2.0,** `ExistsAsync()` method used with multiple table references started to use much more time to complete.
Here's test case, created using Azure Web Functions:
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.Storage;

public static async Task Run(string myQueueItem, TraceWriter log)
{
    var storageAccount = CloudStorageAccount.Parse(GetEnvironmentVariable("SAS_ACCOUNT_INFO"));
    var tableClient = storageAccount.CreateCloudTableClient();
    var tableReference = tableClient.GetTableReference(GetEnvironmentVariable("TABLE_NAME"));
    
    var tasks = new List<Task>();
    var count = 100;
            
    var stopwatch = new Stopwatch();
    stopwatch.Start();
            
    for (var i = 0; i < count; i++)
    {
        tasks.Add(tableReference.ExistsAsync());
    }

    await Task.WhenAll(tasks);
    stopwatch.Stop();

    log.Info($"Time elapsed to run {count} tasks: {stopwatch.Elapsed}");
}

public static string GetEnvironmentVariable(string name)
{
    return name + ": " + 
        System.Environment.GetEnvironmentVariable(name, EnvironmentVariableTarget.Process);
}
```

Adiitionally, I should mention, that using automatically suggested version of `WindowsAzure.Storage` package using `#r "Microsoft.WindowsAzure.Storage"` command doesn't provide latest version, and everything works fine. To actually reproduce this issue, one should specify version of package inside `project.json` file: 
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "WindowsAzure.Storage" : "9.2.0"
      }
    }
   }
}
```

Here are some test results, provided by this code with different package versions:
**v.8.7.0**:

> 2018-06-06T13:55:08.110 [Info] Function started (Id=da2ed3c3-ad80-4de9-acdb-515383a2a85b)
> 2018-06-06T13:55:10.567 [Info] Time elapsed to run 100 tasks: 00:00:01.9612244
> 2018-06-06T13:55:10.582 [Info] Function completed (Success, Id=da2ed3c3-ad80-4de9-acdb-515383a2a85b, Duration=2456ms)
> 2018-06-06T13:55:15.217 [Info] Function started (Id=85fa0373-0b8d-44c3-ba39-6e0fd597fff7)
> 2018-06-06T13:55:15.310 [Info] Time elapsed to run 100 tasks: 00:00:00.0865624
> 2018-06-06T13:55:15.310 [Info] Function completed (Success, Id=85fa0373-0b8d-44c3-ba39-6e0fd597fff7, Duration=88ms)
> 2018-06-06T13:55:17.978 [Info] Function started (Id=20c9d5f5-6d81-4410-8e19-49c4658ebd79)
> 2018-06-06T13:55:18.088 [Info] Time elapsed to run 100 tasks: 00:00:00.1035199
> 2018-06-06T13:55:18.088 [Info] Function completed (Success, Id=20c9d5f5-6d81-4410-8e19-49c4658ebd79, Duration=108ms)
> 2018-06-06T13:55:20.885 [Info] Function started (Id=9e8e5605-0a8a-47b0-aa22-8e797f42d58f)
> 2018-06-06T13:55:20.979 [Info] Time elapsed to run 100 tasks: 00:00:00.0908325
> 2018-06-06T13:55:20.979 [Info] Function completed (Success, Id=9e8e5605-0a8a-47b0-aa22-8e797f42d58f, Duration=92ms)

**v.9.0.0** (here's where the problem originally appeared):

> 2018-06-06T13:58:18.532 [Info] Time elapsed to run 100 tasks: 00:00:21.5607551
> 2018-06-06T13:58:18.532 [Info] Function completed (Success, Id=37b3c892-15cf-4416-ac96-c52d72d788ad, Duration=21561ms)
> 2018-06-06T13:58:18.594 [Info] Time elapsed to run 100 tasks: 00:00:01.8750144
> 2018-06-06T13:58:18.594 [Info] Function completed (Success, Id=ec1fa383-8539-43d4-b2a0-06da43aa8548, Duration=1875ms)
> 2018-06-06T13:59:30.491 [Info] Function started (Id=dda75edb-c227-4aef-b175-92cd4c522105)
> 2018-06-06T13:59:51.991 [Info] Time elapsed to run 100 tasks: 00:00:21.4926664
> 2018-06-06T13:59:51.991 [Info] Function completed (Success, Id=dda75edb-c227-4aef-b175-92cd4c522105, Duration=21493ms)
> 

**v 9.2.0** (problem still exists):

> 2018-06-06T14:03:22.366 [Info] Function started (Id=a452cae8-df6a-457d-a276-f661b836ec8f)
> 2018-06-06T14:03:42.265 [Info] Time elapsed to run 100 tasks: 00:00:19.7127538
> 2018-06-06T14:03:42.265 [Info] Function completed (Success, Id=a452cae8-df6a-457d-a276-f661b836ec8f, Duration=19892ms)
> 2018-06-06T14:03:46.712 [Info] Function started (Id=2f48386f-68bc-467b-a3ee-ba2975b03376)
> 2018-06-06T14:03:50.035 [Info] Time elapsed to run 100 tasks: 00:00:03.3171129
> 2018-06-06T14:03:50.035 [Info] Function completed (Success, Id=2f48386f-68bc-467b-a3ee-ba2975b03376, Duration=3318ms)
> 2018-06-06T14:04:27.841 [Info] Function started (Id=82fc060c-8572-4993-80cd-b23e7807dce4)
> 2018-06-06T14:04:50.931 [Info] Time elapsed to run 100 tasks: 00:00:23.0891429
> 2018-06-06T14:04:50.931 [Info] Function completed (Success, Id=82fc060c-8572-4993-80cd-b23e7807dce4, Duration=23090ms)

I should also note that adding line `await Task.Delay(1);` right before `tasks.Add(tableReference.ExistsAsync());` allows code to run almost as fast, as in **v.8.7.0**. Even synchronous method call is faster, than awaiting all tasks.

**v 9.2.0** with additional delay between adding tasks:

> 2018-06-06T14:06:30.342 [Info] Function started (Id=494d5cde-bd70-46f5-808c-dea8c1f5c7eb)
> 2018-06-06T14:06:32.123 [Info] Time elapsed to run 100 tasks: 00:00:01.6025474
> 2018-06-06T14:06:32.123 [Info] Function completed (Success, Id=494d5cde-bd70-46f5-808c-dea8c1f5c7eb, Duration=1783ms)
> 2018-06-06T14:06:41.285 [Info] Function started (Id=c303dcc3-4e0d-4a58-a3a6-de11aae54b94)
> 2018-06-06T14:06:42.863 [Info] Time elapsed to run 100 tasks: 00:00:01.5821680
> 2018-06-06T14:06:42.863 [Info] Function completed (Success, Id=c303dcc3-4e0d-4a58-a3a6-de11aae54b94, Duration=1583ms)
> 2018-06-06T14:06:45.573 [Info] Function started (Id=e9cb18fb-03df-4cb2-8431-ad5f6f36d327)
> 2018-06-06T14:06:47.276 [Info] Time elapsed to run 100 tasks: 00:00:01.7032635
> 2018-06-06T14:06:47.276 [Info] Function completed (Success, Id=e9cb18fb-03df-4cb2-8431-ad5f6f36d327, Duration=1704ms)
> 2018-06-06T14:06:50.409 [Info] Function started (Id=1a7b06e7-65ea-4c3e-98b1-91c6129c9672)
> 2018-06-06T14:06:51.987 [Info] Time elapsed to run 100 tasks: 00:00:01.5910749
> 2018-06-06T14:06:51.987 [Info] Function completed (Success, Id=1a7b06e7-65ea-4c3e-98b1-91c6129c9672, Duration=1591ms)
>

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
