### ISSUE TITLE
Cannot download blob data after upgrading to .net core 2.1 RTM (2.1.300)

### ISSUE THREAD

**Issue by grahamjest** [Azure/azure-storage-net#711]
CloudBlockBlob DownloadTextAsync (WindowsAzure.Storage 9.2.0) no longer connects and downloads the blob contents after upgrading to .NET Core 2.1

The same code works when running under using .NET Core 2.0 and .NET Core 2.1 RC1

Could this issue be linked to the changes that have been made to HttpClientHandler?
Note: I am making the requests on a machine that is behind a ZScalar corporate firewall and proxy server.

I have Wireshark traces and can see that using 2.1 RTM it first does a DNS lookup and then tries to connect directly using **TCP** to XXX.store.core.windows.net on port 443, the request does not go through the proxy server and the connection is not established.
Using a previous version on .NET Core it successfully connects using **HTTP** via the proxy server.

Here's the code:
```
string storageConnectionString = "[SecretDetailsRemoved];EndpointSuffix=core.windows.net";
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageConnectionString);
string blobName = "myblob";
string container = "mycontainer";
Uri uri = new Uri($"{storageAccount.BlobEndpoint}{container}/{blobName}");
CloudBlockBlob blob = new CloudBlockBlob(uri, storageAccount.Credentials);
string content = await blob.DownloadTextAsync();
```
Here's the exception:

> Microsoft.WindowsAzure.Storage.StorageException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by grahamjest** [comment]
If I manually set the proxy on the HttpClient message handler it will use the proxy.

```
HttpMessageHandler handler = new SocketsHttpHandler()
{
	Proxy = new WebProxy()
	{
		Address = new Uri("http://165.225.80.40:80")
	}
};
using (HttpClient client = new HttpClient(handler))
{
	string content = await client.GetStringAsync("http://www.microsoft.com");
	return content;
}
```

This is OK if I am directly using HttpClient, but doesn't help me when using CloudBlockBlob.

Is there a way that I can globally set a proxy?
I see that there is an outstanding request to support specifying proxy settings in Windows using environment variables ([Issue 24574](https://github.com/dotnet/corefx/issues/24574)) this could solve my problem.

**Comment by mirobers** [comment]
The SendingRequest event of OperationContext lets you access the underlying HttpWebRequest, where you can set a proxy. To set a proxy globally, you can use app.config [default proxy settings](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings).

**Comment by grahamjest** [comment]
Thanks for pointing me towards the SendingRequest event of OperationContext.
Unfortunately for .NET Core the Request (HttpWebRequest) property is not available, RequestEventArgs only exposes the properties: RequestInformation and RequestUri.

**Comment by cannn** [comment]
I face the same problem on any HttpClient request. This behavior change breaks existing code when run behind proxy.  AFAIK there is no place to define application wide default proxy and app.config default proxy settings are not used in .net core

**Comment by Windicus** [comment]
I seem to be having issues with Azure Authentication. I had this working with ASP.Net Core 1.x, and 2.0x. It simply used the system wide Windows Proxy setting. On upgrading to 2.1.1, it can no longer access the internet to validate the token presented from login.microsoftonline.com. I went back to my IIS deployment using 2.0.7 and it just works. Given all the authentication code/validation came from MS as part of the original VS Project setup, I'm at a loss as to where to set a proxy.

I added the environment variable, DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER and set it to false, no change.

I added the line, AppContext.SetSwitch("System.Net.Http.useSocketsHttpHandler", false); to the code but no change. I could have missed it but no where does it say where to put this line. Startup.cs, Program.cs, someplace else. It's quite possible I put it in the wrong place.

As mentioned the Windows server itself can get to login.microsoftonline.com, it can pull down the .well-known/openid-configuration json file.

If I run the 2.1.1 version locally where no proxy is required, it works. So the basic code itself appears to be fine. It's the proxy piece that is causing issues from what i can tell.

I'm clearly missing something here. Is there a working example of an ASP.NET Core 2.1.1 Web API with a proxy? I'd rather use the new sockets if possible. Thanks.

**Comment by mirobers** [comment]
@grahamjest In an upcoming release, we will support custom HttpClient handlers so you will be able to manipulate requests even in libraries based on HttpClient.

In the meantime, note that the net45 library does function in .NET Core 2.0 and later, so using the SendingRequest event and manipulating HttpWebRequest works today. NuGet prefers netstandard 1.3 over .NET Framework 4.5, so you would have to explicitly force loading the net45 DLL to do this.

**Comment by mirobers** [comment]
Also, please check to see if the workaround listed in this [corefx issue](https://github.com/dotnet/corefx/issues/30166) is relevant.

**Comment by mrunks** [comment]
I have a similar problem where I have an existing .net app that relies on the DefaultProxy setting inside web.config to get data from Azure Table Storage and calling the documentClient.CreateDocumentQuery.

It depends on the defaultproxy entry in web.config and I cannot find an equivalent work around for .net core.  Is there a way I can work around this problem since I'm not using the HttpClient ?

**Comment by mrunks** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-enable-a-webrequest-to-use-a-proxy-to-communicate-with-the-internet

i found this and it works nicely for what I need so I'm passing it on.

**Comment by alexmg** [comment]
It would be great if an `IWebProxy` implementation could be provided when creating the clients. The `EventProcessorHost` in https://github.com/Azure/azure-event-hubs-dotnet/ allows for this and it works nicely for the `EventHubClient`. Unfortunately, as I described in https://github.com/Azure/azure-event-hubs-dotnet/issues/210#issuecomment-418019549 they are unable to pass the `IWebProxy` further through to the creation of the `CloudBlobClient`. I would love to see consistent support for `IWebProxy` across the Azure libraries as clearly these are regularly used inside corporate environments and .NET Core adoption is only going to continue to grow.

**Comment by rauledo** [comment]
Hi, the following code with WindowsAzure.Storage - Version 9.3.1 package works on Asp Net Core 2.1.

```C#
    public class AzureBlobModel
    {
        public string FileName { get; set; }
        public long? FileSize { get; set; }
        public Stream Stream { get; set; }
        public string ContentType { get; set; }
    }

    public interface IImageStore
    {
        Task<string> SaveDocument(Stream documentStream);
        Task<bool> DeleteDocument(string imageId);
        Task<AzureBlobModel> DownloadDocument(string documentId, string fileName);
        string UriFor(string documentId);
    }

    public class ImageStore : IImageStore
    {
        CloudBlobClient blobClient;
        string baseUri = "https://xxxxx.blob.core.windows.net/";

        public ImageStore()
        {
            var credentials = new StorageCredentials("xxxxx accountName xxxxx", "xxxxx keyValue xxxxx");
            blobClient = new CloudBlobClient(new Uri(baseUri), credentials);
        }

        public async Task<string> SaveDocument(Stream documentStream)
        {
            var documentId = Guid.NewGuid().ToString();
            var container = blobClient.GetContainerReference("xxxxx container xxxxx");
            var blob = container.GetBlockBlobReference(documentId);
            await blob.UploadFromStreamAsync(documentStream);
            return documentId;
        }

        public async Task<bool> DeleteDocument(string documentId)
        {
            var container = blobClient.GetContainerReference("xxxxx container xxxxx");
            var blob = container.GetBlockBlobReference(documentId);
            bool blobExisted = await blob.DeleteIfExistsAsync();
            return blobExisted;
        }

        public async Task<AzureBlobModel> DownloadDocument(string documentId, string fileName)
        {
            var container = blobClient.GetContainerReference("xxxxx container xxxxx");
            var blob = container.GetBlockBlobReference(documentId);

            var doc = new AzureBlobModel()
            {
                FileName = fileName,
                Stream = new MemoryStream(),
            };

            doc.Stream = await blob.OpenReadAsync();
            doc.ContentType = blob.Properties.ContentType;
            doc.FileSize = blob.Properties.Length;

            return doc;
        }

        public string UriFor(string documentId)
        {
            var sasPolicy = new SharedAccessBlobPolicy
            {
                Permissions = SharedAccessBlobPermissions.Read,
                SharedAccessStartTime = DateTime.UtcNow.AddMinutes(-15),
                SharedAccessExpiryTime = DateTime.UtcNow.AddDays(1)
            };

            var container = blobClient.GetContainerReference("xxxxx container xxxxx");
            var blob = container.GetBlockBlobReference(documentId);
            var sas = blob.GetSharedAccessSignature(sasPolicy);
            return $"{baseUri}xxxxx container xxxxx/{documentId}{sas}";
        }
    }

    // On the controller

    [HttpGet("{documentId}", Name = "GetDocument")]
    public async Task<IActionResult> GetDocument(int documentId)
    {
        var doc = await _imageStore.DownloadDocument(documentId, "output filename");

        return File(doc.Stream, doc.ContentType, doc.FileName);
    }

    // On Startup - ConfigureServices

    services.AddSingleton<IImageStore, ImageStore>();
```

**Comment by kfarmer-msft** [comment]
9.4.1 includes the ability to pass in DelegatingHandler chains, which at runtime will have an HttpClientHandler instance assigned to the innermost InnerHandler property.  This can be leveraged to set the Proxy (or any other property supported by HttpClientHandler).  For example, see DelegatingHanlderImpl in TestBase.Common.cs, and the CloudBlobContainerVerifyProxyHit test in CloudBlobContainerTest.cs.
