### ISSUE TITLE
Could not load type 'Microsoft.Azure.Storage.Auth.Protocol.IAuthenticationHandler'

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/azure-storage-net#712]
Hi all

I have following packages in my project:

package id="Microsoft.Azure.CosmosDB.Table" version="**1.1.2**" targetFramework="net462"
  package id="Microsoft.Azure.DocumentDB" version="1.22.0" targetFramework="net462"
  package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net462"
  package id="Microsoft.Azure.Storage.Common" version="**9.4.0.2-preview**" targetFramework="net462"
  package id="Microsoft.Data.Edm" version="5.8.3" targetFramework="net462"
  package id="Microsoft.Data.OData" version="5.8.3" targetFramework="net462"
  package id="Microsoft.Data.Services.Client" version="5.8.3" targetFramework="net462"
  package id="Microsoft.OData.Core" version="7.4.4" targetFramework="net462"
  package id="Microsoft.OData.Edm" version="7.4.4" targetFramework="net462"
  package id="Microsoft.Spatial" version="7.4.4" targetFramework="net462"
  package id="Newtonsoft.Json" version="10.0.2" targetFramework="net462"
  package id="System.ComponentModel.EventBasedAsync" version="4.0.11" targetFramework="net462"
  package id="System.Dynamic.Runtime" version="4.0.0" targetFramework="net462"
  package id="System.Linq.Queryable" version="4.0.0" targetFramework="net462"
  package id="System.Net.Requests" version="4.0.11" targetFramework="net462"
  package id="System.Spatial" version="5.8.3" targetFramework="net462"

Sample code:

```
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(this.storageTableConnectionString);
            // Create the table client.
            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            // Retrieve a reference to the table.
            CloudTable table = tableClient.GetTableReference(tableName);

            // Create the table if it doesn't exist.
            await table.CreateIfNotExistsAsync();
            return table;
```
Method CreateCloudTableClient generate an error: Message: System.TypeLoadException : Could not load type 'Microsoft.Azure.Storage.Auth.Protocol.IAuthenticationHandler' from assembly 'Microsoft.Azure.Storage.Common, Version=9.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

I did check Microsoft.Azure.Storage.Common assembly with reflector and this interface is actually not present any more. How to solve this?

**Comment by mirobers** [comment]
Please use version 9.0.0.1-preview of Microsoft.Azure.Storage.Common for now. The CosmosDB team is working on a new version of Microsoft.Azure.CosmosDB.Table that supports 9.4-preview but it is not available yet.

**Comment by antonGritsenko** [comment]
@mirobers thanks, we already did downgrade. 
Can this issue be open until it actually resolved? Or do you have link to related issue?

**Comment by erezvani1529** [comment]
@antonGritsenko , you may want to email the CosmosDB team as well at : askcosmosdbtableapi@microsoft.com for support.

**Comment by kirankumarkolli** [comment]
@antonGritsenko we will keep this issue open till its addressed fully.

**Comment by shadySirhan** [comment]
Hi,

I am trying to upgrade nuget:
From: **9.0.0.1-preview**
To: **10.0.3**

I am getting:
[error]CA0001 : Could not find type 'Microsoft.Azure.Storage.Auth.Protocol.IAuthenticationHandler' in assembly 'Microsoft.Azure.CosmosDB.Table

Do we still need to use the preview version!?

Thanks,
Shady
