### ISSUE TITLE
when i Upgrading dot net core version 2.0 to 2.1 then blob file uploading function not working well

### ISSUE THREAD

**Issue by ADVikrant** [Azure/azure-storage-net#715]
Hi
when i was working on dot net core version 2.0 then blob file upload function worked properly but now when i upgrade the version 2.1 it is not working properly.

No single file uploaded on azure blob storage 
Please help me out

**Comment by rickle-msft** [comment]
Hello! Thank you for submitting this issue; we have added this issue to our backlog for discussion and will get back to you with an update.

**Comment by mirobers** [comment]
Hi @ADVikrant could you clarify the failure you are seeing? Is there an exception message and stack trace you can share?

**Comment by ADVikrant** [comment]
no any error occurred but url would have been generated but file not upload at particular place.

this is my code for upload file on azure 

CloudBlockBlob blockBlob = container.GetBlockBlobReference(URL + item.Name);
                    using (var fileStream = System.IO.File.OpenRead(item.FilePath))
                    {
                        blockBlob.UploadFromStreamAsync(fileStream);
                        item.URL = blockBlob.Uri.OriginalString;
                    }

another method also i have used but not working still now

CloudBlockBlob blockBlob = container.GetBlockBlobReference(URL + item.Name);
                   blockBlob.UploadFromFileAsync(item.FilePath);
                    item.URL = blockBlob.Uri.OriginalString;


I have got url from item.URL variable to upload URI but
when i show on the azure storage , there is no any files or folder

**Comment by ADVikrant** [comment]
and i am using asp.net core 2.1 

if you are helping me in. it is very thank full to you

**Comment by mirobers** [comment]
GetBlockBlobReference takes a blob name only. Instead of passing a full URL, try passing just the blob name.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
