### ISSUE TITLE
storage emulator not starting after installing core 2.1

### ISSUE THREAD

**Issue by daxu7509** [Azure/azure-storage-net#716]
Hi,
Storage emulator failed to start when .net core 2.1 is installed. I enabled log and it says:
15/06/2018 09:05:24 [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found
15/06/2018 09:05:24 [Error] [ActivityId=00000000-0000-0000-0000-000000000000] Hit Exception while reading Nephos.MaskClientIPAddressesInLogs setting from ACS: System.Exception: Configuration Parameter: Nephos.MaskClientIPAddressesInLogs not found ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Emulator.HttpServiceHost.GetConfigurationParameter(String name)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetConfigSetting[T](IServiceEntrySink serviceEntrySink, String configParam, String configDescription)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.ConfigurationHelper.GetIPAddressMaskSetting(IServiceEntrySink sink)
15/06/2018 09:05:24 [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The process cannot access the file because it is being used by another process
15/06/2018 09:05:24 [Error] [ActivityId=00000000-0000-0000-0000-000000000000] The process cannot access the file because it is being used by another process

I disabled all firewall and disabled IIS (as in an old post, people were suggesting this could be the problem). However, it makes no difference

**Comment by mirobers** [comment]
This can indicate that the emulator ports are in use. (The ports are 10000, 10001, and 10002.) You can experiment by editing AzureStorageEmulator.exe.config and changing these ports to see if you can get it to start. The best resolution in this case is to free up the ports, as most applications assume the standard ports.

**Comment by vovikdrg** [comment]
Same here.... But nothing listening them...
C:\WINDOWS\system32>netstat -bano | findstr "10000"
C:\WINDOWS\system32>netstat -bano | findstr "10001"
C:\WINDOWS\system32>netstat -bano | findstr "10002"

**Comment by kfarmer-msft** [comment]
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite
