### ISSUE TITLE
[8.7 -> 9.2] High memory usage in tests

### ISSUE THREAD

**Issue by bragma** [Azure/azure-storage-net#717]
Hi, pardon if my request is a bit generic, but I am at an early stage in trying to understand what's happening. I have a project involving an asp net core api (.net 4.6), several web jobs, ad a thousand tests for all parts of the app. Lately I have updated the WindowsAzure.Storage package from 8.7 to 9.2 (nothing else changed) and noticed that memory usage skyrocketed when running xunit tests, growing and growing to several GB. Several tests didn't complete due to OOM exceptions. Rolled back to 8.7 and everything was back to normal, memory usage about 500MB.
The problem may be specific to the tests, but obviously I can't afford to put this in production and I'll have to stay with 8.7 till I understand what's happening.
Any suggestions on how to proceed? Is there something I should look at?
Thanks!

**Comment by kfarmer-msft** [comment]
To try to narrow things down, could you please try walking back the version starting at 9.1?

**Comment by bragma** [comment]
@kfarmer-msft I will for sure once I have a minute to try it. I'll let you know.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
