### ISSUE TITLE
Reference documentation unclear on NameValidator.ValidateContainerName behavior

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-storage-net#718]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@marcusvnac commented on [Wed Jun 13 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/682)

How this checks if returns void? It raises some Exception?!? How is that works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947b8ccd-cf8a-89b8-7523-ca3dffaa8a57
* Version Independent ID: fec0672f-ca14-9077-da71-8546ff6b3ce0
* Content: [NameValidator.ValidateContainerName(String) Method (Microsoft.WindowsAzure.Storage)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.namevalidator.validatecontainername?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage/NameValidator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage/NameValidator.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by pemari-msft** [comment]
We reached out to the customer over email. Thanks!
