### ISSUE TITLE
AzCopy Fails to restore a Table which contains Infinity -Infinity or NaN

### ISSUE THREAD

**Issue by Omsaaf** [Azure/azure-storage-net#721]
We have a very large table, which was created with double values. Some of theses values have -Infinity or Infinity
We used AzCopy to backup these tables and create a copy in another storage account for testing purposes.
Unfortunately, azCopy fails and gives this message
[2018/06/21 15:45:48.585+00:00][ERROR] Failed to import Azure table. Detailed error: Format of the data file 20180620190933-XXXXXXX_0_0_468B383E3CD4BA20.json is invalid. Unexpected entity property, type: Edm.Double, value: -Infinity. Error occurred at line number 1, line position 227979565.
This exception seems related to the bug reported here https://github.com/Azure/azure-storage-net/issues/644

**Comment by zezha-msft** [comment]
Hi @Omsaaf, thanks for reaching out!

I've logged this issue for investigation.

**Comment by jiacfan** [comment]
Hi, @Omsaaf 

Thanks for reporting the issue! We can repo this issue with Azcopy locally, and we are planning to provide a fix for it. Will update here for more details.

Thanks,
Jiachen

**Comment by Omsaaf** [comment]
Hey guys
Thanks for the followup. I believe this bug was solved in Azure Storage Library 9.1.0 If I am not mistaken
Best

**Comment by EmmaZhu** [comment]
@Omsaaf  
AzCopy has different story, we can repro the issue with latest XSCL. We should be able to have a fix in later AzCopy.
Thanks
Emma
