### ISSUE TITLE
Pdb files point to local FS of build agent instead of public symbol server

### ISSUE THREAD

**Issue by sergii-sakharov** [Azure/azure-storage-net#726]
Here's a line from included pdb file:
c:\Program Files (x86)\Jenkins\workspace\dotnet-nov17\Lib\Common\Shared\Protocol\StorageErrorCodeStrings.cs

Instead is should be pointing to the public server as mentioned in https://github.com/Azure/azure-storage-net/issues/115

As of now those pdb files just obstruct debugging - without them at least it's possible to use Reflector or dotPeek as a pdb generator (which is still possible if they're removed from nuget cache)

**Comment by zezha-msft** [comment]
Hi @sergii-sakharov, thanks for reaching out!

I've logged this issue for investigation.
