### ISSUE TITLE
Creating a CloudTable immediately after Delete fails with the error - "One or more errors occurred. (Conflict)"

### ISSUE THREAD

**Issue by martinmthomas** [Azure/azure-storage-net#727]
I am learning Azure Table Storage and noticed that when I try to delete an existing table and then recreate immediately, my application throws an error. I tried to delete the table manually using AzurePortal and when I execute my application (after seeing the success message in the portal), it still fails. The issue does not happen if I wait for a couple of seconds after the table is deleted. But this is confusing as the success response (either from Portal or DeleteIfExistsAsync) is not correct and we have to always wait for some time before trying to recreate a table.

#### Version:
- .NET Core 2.0
- WindowsAzure.Storage 9.2.0

#### Breaking Code:
![createissue](https://user-images.githubusercontent.com/2176913/41999463-eab5db06-7aa0-11e8-88e9-1c599dacb883.png)

**Comment by zezha-msft** [comment]
Hi @martinmthomas, thanks for reaching out!

The exception is expected in this case. After the delete request, the service needs a few seconds(the exact duration is unpredictable) to clean out the table, and during that period of time, the same table cannot be re-created. Please consider catching and handling this exception if the delete/re-create operation is needed in your application.

**Comment by martinmthomas** [comment]
I guess it is not a frequent use case in Production apps to drop/create tables at run time. I was doing it since I was creating some sample apps for learning the Table Storage. Thanks @zezha-msft for clarifying the current behaviour!
