### ISSUE TITLE
Writing to table returns "500" statusCode

### ISSUE THREAD

**Issue by shadySirhan** [Azure/azure-storage-net#730]
Hi,

I have a question please regard writing to Azure table.
I have the following code:

```
        var batchOperation = new TableBatchOperation();
	batchOperation.InsertOrReplace(entity);

	tableRequestOptions = new TableRequestOptions
	{
		RetryPolicy = new NoRetry(),
		MaximumExecutionTime = TimeSpan.FromMilliseconds(5000),
		ServerTimeout = TimeSpan.FromMilliseconds(50)
	};
	IEnumerable<TableResult> tableResults = await table.ExecuteBatchAsync(batchOperation, tableRequestOptions, null, cancellationToken).ConfigureAwait(false);
```

From time to time I get “500” errors as below (2 cases):
1) storageException.RequestInformation.ErrorCode = ""
    storageException.RequestInformation.HttpStatusCode = "500"
    storageException.RequestInformation.ExtendedErrorInformation.ErrorMessage = "Operation could not be completed within the specified time"

2) storageException.RequestInformation.ErrorCode = ""
    storageException.RequestInformation.HttpStatusCode = "0"
    storageException.RequestInformation.ExtendedErrorInformation.ErrorMessage = "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server"

As you can see the error code is empty! 

When we run the same code against CosmosDB and the operation times out, we get an ErrorCode = “OperationTimedOut”.
Can you please do the same?

For now I will implement a work around that parses the message instead of looking on the error code but it’s clearly not a clean solution.

Please let me know what do you think.

Thanks,
Shady

(taken from the attached email)

**Comment by mirobers** [comment]
Hi, for the table service please use `RequestInformation.ExtendedErrorInformation.ErrorCode` to access the error code on failure. Note that this is only populated if a response is received form the service, and that response contains an error payload.

**Comment by shadySirhan** [comment]
Hi,

Thanks for the fast response.
Can you please specify the ErrorCode that should be returned in such cases?
In general, is there a formal documentation for all exceptions that can be thrown?

Thanks,
Shady

**Comment by mirobers** [comment]
[Common error codes](https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes);

[Table error codes](https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-error-codes)

**Comment by shadySirhan** [comment]
Thanks.
But seems that `RequestInformation.ExtendedErrorInformation.ErrorCode` is deprecated!
![errorcodedepreceated](https://user-images.githubusercontent.com/5868297/42270266-10d415fe-7f89-11e8-87df-2f2eb933ac8f.png)

I am using this nuget:
Microsoft.Azure.Storage.Common.9.0.0.1-preview

**Comment by shadySirhan** [comment]
Another question please.
Regard the second case described above (with HttpStatusCode = "0"), it's a legal response to return 0 as HttpStatusCode? what that means?

**Comment by shadySirhan** [comment]
Hey,

Did you had the chance to take a look?

Thanks,
Shady

**Comment by shadySirhan** [comment]
Can you please take a look?

**Comment by mirobers** [comment]
Sorry for the delay.

1) It was un-deprecated in later versions for exactly this reason.
2) HttpStatusCode can be set to zero when no response was received from the storage service and therefore there is no status code to report.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
