### ISSUE TITLE
StorageException is not serializable

### ISSUE THREAD

**Issue by Tadimsky** [Azure/azure-storage-net#731]
I'm using `WindowsAzure.Storage` version `9.2.0` and am unable to pass `StorageException`s around Service Fabric Remoting (WCF).
I get an error saying that the exception is not serializable.
This is in .NET Core 2.1

I looked at the code for StorageException and am wondering if it's not `ifdef`ed out?
https://github.com/Azure/azure-storage-net/blob/c1966e1cd64d5eb8e40733ebd6b07b6b8e8fb136/Lib/Common/StorageException.cs

```csharp
#if WINDOWS_DESKTOP && !WINDOWS_PHONE
    [Serializable]
#endif
```

I doubt that .NET Core is marked as `WINDOWS_DESKTOP`?

**Comment by Tadimsky** [comment]
It looks like `NETCORE` is used as an `#if` condition in that file - seems like this is needed as well for the serializable code.

**Comment by rickle-msft** [comment]
Hi, @Tadimsky. Thank you for your question. I have logged this issue for consideration within our team, and we will get back to you as soon as we have more information for you!

**Comment by Tadimsky** [comment]
Hey, any updates on this? It would be great if this was serialized.
We're using this in Service Fabric remoting and we're unable to pass the exceptions through as they are not serializable.

**Comment by rickle-msft** [comment]
@Tadimsky, thank you for your willingness to contribute. We do sometimes accept PRs, and I believe we would welcome your contribution. Please be sure to follow the [guidelines](https://github.com/Azure/azure-storage-net/blob/master/.github/CONTRIBUTING.md). I'll also refer you to @kfarmer-msft who is the gatekeeper for this library.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
