### ISSUE TITLE
ListFilesAndDirectoriesSegmentedAsync does not work in V9.3

### ISSUE THREAD

**Issue by smoro88** [Azure/azure-storage-net#733]
This code works fine in v9.2 
// List all files/directories under the root directory
            Console.WriteLine("4. List Files/Directories in root directory");
            List<IListFileItem> results = new List<IListFileItem>();
            FileContinuationToken token = null;
            do
            {
                FileResultSegment resultSegment = await share.GetRootDirectoryReference().ListFilesAndDirectoriesSegmentedAsync(token);
                results.AddRange(resultSegment.Results);
                token = resultSegment.ContinuationToken;
            }
            while (token != null);

            // Print all files/directories listed above
            foreach (IListFileItem listItem in results)
            {
                // listItem type will be CloudFile or CloudFileDirectory
                Console.WriteLine("- {0} (type: {1})", listItem.Uri, listItem.GetType());
            }
In V9.3 you get the following error.
One or more errors occurred. (The value for one of the HTTP headers is not in the correct format.)

Any ideas?
Steve

**Comment by smoro88** [comment]
On dir.ListFilesAndDirectoriesSegmentedAsync(token).Result; I get the error "The value for one of the HTTP headers is not in the correct format."

I tried to create a new storage account and run the same code on a new Share and it works fine.  I am thinking it has to do with maybe the configuration of the storage account which maybe causing this issue.

Any Ideas?

**Comment by zezha-msft** [comment]
Hi @smoro88, thanks for reaching out! 

I've logged this issue to investigate.

**Comment by smoro88** [comment]
When I try and use latest version of Storage Explorer 1.3.1 it give me the same error when I try and click the storage account.    However if I create a new Storage account everything seems fine.  Thus I have migrated all my folders to the new storage account and all is good.  However would be nice to know what was causing the problem.

**Comment by asorrin-msft** [comment]
Been thinking about this, really no idea what might have happened.  The only possibility I can come up with - and this seems quite unlikely, but I can't think of anything else - is that there was some issue on the service, for your particular storage account at that particular time.  9.3 uses a different service version than 9.2, which could explain why it may have only happened in 9.3 (if there was indeed an issue on the service.)  Wish I had something better to offer - out of curiosity, if you still have the old storage account active & easy to access, does it still repro?

**Comment by smoro88** [comment]
I do not have the repo anymore because I created a new one and copied all the documents over and it works fine.
