### ISSUE TITLE
CloudBlob class is too difficult to mock

### ISSUE THREAD

**Issue by jairov4** [Azure/azure-storage-net#734]
this class has constructors that require other dependencies relying on static methods.
As you can imagine static methods are not able to be mocked and this class would require mock all dep chain up just to call the public constructor.
Im getting here because Im using GetBlobReference() and getting one of those instances.

**Comment by mirobers** [comment]
Could you describe your scenario in some more detail? CloudBlob has public constructors available. A mocking framework can instantiate based on one of these constructors and override the virtual methods to mock the service calls. It isn't immediately clear to me which static methods you would need to mock.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
