### ISSUE TITLE
When will Azure Storage Emulator 5.6 be released with VS2017?

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-storage-net#736]
I'm trying not to leave the rest of the dev team behind by not forcing them to go out of their way to install newer versions of the storage emulator than Visual Studio 2017 provides; and because of this I am not able to upgrade to v9.3.0. It would be nice if you guys coordinated your breaking package changes with VS 2017 releases

**Comment by zezha-msft** [comment]
Hi @onionhammer, thanks for reaching out!

I'll discuss with my team to see what can be done.

**Comment by PureKrome** [comment]
Yep - also found this out, the hard way. If anything, there needs to be some better release notes. Sure, [the release notes exist here](https://github.com/Azure/azure-storage-net/blob/master/changelog.txt) but if there could be some WARNING text in the nuget package, that might make things like this, more visible.

Not hating, just trying to give some feedback from being a soldier caught up in the trenches, in the front line. 👍 👍

**Comment by kfarmer-msft** [comment]
Thanks for the feedback.

Unfortunately, there are three different release vehicles for the emulator:  the standalone download, Web Platform Installer, and VS 2017's new installer.  The timings for each are dramatically different and subject to different constraints.  As you've noticed, VS 2017 will tend to lag the others.
