### ISSUE TITLE
Does (Queue) CreateIfNotExistsAsync slow things down when doing lots of storage calls? e.g. lots of Add/Get/Delete messages?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-storage-net#737]
Hi 👋 

Question: I'm wondering if calling `CreateIfNotExistsAsync` does a single request to Azure Storage **each time** that is called. Leading to: wasted HTTP requests after the first time it's checked.

---

Nearly [all the examples I keep seeing](https://docs.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues#insert-a-message-into-a-queue) generally follow the following pattern:

```
// Retrieve storage account from connection string.
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
    CloudConfigurationManager.GetSetting("StorageConnectionString"));

// Create the queue client.
CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

// Retrieve a reference to a queue.
CloudQueue queue = queueClient.GetQueueReference("myqueue");

// Create the queue if it doesn't already exist.
queue.CreateIfNotExists();

// Now do stuff with the queue, like AddMessage, etc.
```

This is great if it's a single operation (e.g. Add 1x message). But if we need to keep adding a heap of messages, over time (ie. not all via one call to this method, but as people "do stuff" with your website, like buy things, signup, whatever) ... then these calls get called a lot and if feels like it's wasted cycles and can slow things down .. _especially_ if the `CreateIfNotExists()` is doing HTTP (or TCP?) calls to the Storage.

So, it's pretty easy to change things around .. like say ... 

```
// Inject the storage account credentials.
public QueueService(CloudStorageAccount cloudStorageAccount)
{
    _cloudStorageAccount = cloudStorageAccount ?? throw new ArgumentNullException(nameof(cloudStorageAccount));

    // Create a queue ONCE and only when first required...
    _queueClient = new Lazy<CloudQueue>( () =>
    {
        var queueClient = _cloudStorageAccount.CreateCloudQueueClient();

        var queue = queueClient.GetQueueReference("my-queue");
        queue.CreateIfNotExists(); // DOESN'T EXIST ANYMORE. it's CreateIfNotExistsAsync();
        return queue;
    })
}
```

So now we can create the queue ONCE when the queue if first 'requested'. But there are now no sync methods on the CloudQueue. They are all async. which means i need to do an async/await inside a Lazy (urgh, not easy, need 3rd party nuget) and then inside a ctor (urgh. death...).

So I'm stuck. I'm not sure what other people do/are doing.

Sure it's easy for me to just add the `CreateIfNotExistsAsync` just before i do my action (`AddMessageAsync`, etc) but that comes down the crux of my issue -> **If i call `CreateIfNotExistsAsync` each time, that does a single HTTP/TCP request ... which is expensive and-or an overkill _after_ i've checked for the very first time).**

So - any hints?

**Comment by xt0rted** [comment]
I have a method I run on app start that calls this for each of my queues, that way I don't need to call it anywhere else. Would love to know more about this as well.

**Comment by PureKrome** [comment]
@zezha-msft it would be _really nice_ if the client had a secret property that kept track if the `CreateIfNotExistsAsync` was called once - per client _instance_.

Because why bother keep calling it, again and again, if that _client instance_ already knows that the queue/blob/etc already exists?

At the very least, some sample code guidance would be helpful for an _interim_ suggestion/workaround. e.g. Here's some code that uses a slim semaphore or double checked locking (note: "here be dragons" when doing DCL) etc..

No matter what, I just feel that the current guidance is actually pretty poor, with respect to `CreateIfNotExistsAsync`. Would be lovely if the MS devs could just review this little piece of code and make some more perf-suggestions.

cc @guardrex

**Comment by xt0rted** [comment]
The [dotnet-architecture/eShopModernizing ](https://github.com/dotnet-architecture/eShopModernizing) app looks to call this only once on startup (didn't see it used in the other repos).

Key spots in that project:

1. [Global.asax.cs#L64-L68](https://github.com/dotnet-architecture/eShopModernizing/blob/a9ff6d2c826a6f5c1d0795d4da0580cbf2b7ecb3/eShopModernizedMVCSolution/src/eShopModernizedMVC/Global.asax.cs#L64-L68)
2. [ImageAzureStorage.cs#L46](https://github.com/dotnet-architecture/eShopModernizing/blob/a9ff6d2c826a6f5c1d0795d4da0580cbf2b7ecb3/eShopModernizedMVCSolution/src/eShopModernizedMVC/Services/ImageAzureStorage.cs#L46)

**Comment by PureKrome** [comment]
@xt0rted just coming back to this discussion again. If we were using the current Azure storage code, which is `CreateIfNotExistsAsync` ... where would you call this (and how?) in an ASP.NET Core project / webjobs project?

`ConfigureServices` and `Configure` methods (from an ASP.NET Core project) are both `sync` ....

**Comment by xt0rted** [comment]
@PureKrome my project isn't core yet so I'm running the sync versions real early in my owin startup.

To run asynchronous methods synchronously you should call `.GetAwaiter().GetResult()` (this ensures any exceptions that are thrown are not wrapped in an `AggregateException`).

In your webjobs you can call these asynchronously by making your `Main` method `async` like so:

```c#
public static async Task Main(string[] args)
{
   // ...
}
```

**Comment by seanmcc-msft** [comment]
Thank you for the discussion, we are closing the issue.
