### ISSUE TITLE
CloudTable.ExecuteQuery got hang infinitely

### ISSUE THREAD

**Issue by Eva-Xiao** [Azure/azure-storage-net#738]
After upgrade to storage SDK 9.2.0 (and further upgrade to 9.3.0 doesn't help), we frequently got hang when execute query to azure table, below is the hang thread we see in dump:

00000024d003e058 00007ffeaf305b54 [InlinedCallFrame: 00000024d003e058] System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
00000024d003e058 00007ffe9a562de1 [InlinedCallFrame: 00000024d003e058] System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
00000024d003e030 00007ffe9a562de1 DomainBoundILStubClass.IL_STUB_PInvoke(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
00000024d003e0e0 00007ffe9a4c932f System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef) [f:\dd\NDP\fx\src\net\System\Net\Sockets\Socket.cs @ 1778]
00000024d003e170 00007ffe9a4c8f54 System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32) [f:\dd\NDP\fx\src\net\System\Net\Sockets\NetworkStream.cs @ 513]
00000024d003e1e0 00007ffe9a51b850 System.Net.FixedSizeReader.ReadPacket(Byte[], Int32, Int32) [f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_FixedSizeReader.cs @ 52]
00000024d003e230 00007ffe9a4fc42b System.Net.Security._SslStream.StartFrameHeader(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) [f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_SslStream.cs @ 754]
00000024d003e2a0 00007ffe9a4fc098 System.Net.Security._SslStream.StartReading(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) [f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_SslStream.cs @ 723]
00000024d003e300 00007ffe9a4fbe7b System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) [f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_SslStream.cs @ 668]
00000024d003e370 00007ffe9a51b8ca System.Net.TlsStream.Read(Byte[], Int32, Int32) [f:\dd\NDP\fx\src\net\System\Net\_TLSstream.cs @ 118]
00000024d003e3d0 00007ffe9a4c8ea3 System.Net.PooledStream.Read(Byte[], Int32, Int32) [f:\dd\NDP\fx\src\net\System\Net\_PooledStream.cs @ 454]
00000024d003e400 00007ffe9a4c8a62 System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean) [f:\dd\NDP\fx\src\net\System\Net\_Connection.cs @ 3226]
00000024d003e460 00007ffe9a4e2d77 System.Net.ConnectStream.ProcessWriteCallDone(System.Net.ConnectionReturnResult) [f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs @ 450]
00000024d003e4a0 00007ffe9a4e2b87 System.Net.ConnectStream.CallDone(System.Net.ConnectionReturnResult) [f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs @ 423]
00000024d003e4f0 00007ffe9a4e9546 System.Net.ConnectStream.CloseInternal(Boolean, Boolean) [f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs @ 2728]
00000024d003e560 00007ffe9a4e90fa System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(System.Net.CloseExState) [f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs @ 2419]
00000024d003e590 00007ffe9a4e29cf System.Net.HttpWebRequest.EndWriteHeaders_Part2() [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 4619]
00000024d003e5e0 00007ffe9a4e26c7 System.Net.HttpWebRequest.EndWriteHeaders(Boolean) [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 4409]
00000024d003e620 00007ffe9a4e2635 System.Net.HttpWebRequest.WriteHeadersCallback(System.Net.WebExceptionStatus, System.Net.ConnectStream, Boolean) [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 3394]
00000024d003e650 00007ffe9a4e22a1 System.Net.ConnectStream.WriteHeaders(Boolean) [f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs @ 2268]
00000024d003e6e0 00007ffe9a4e11cc System.Net.HttpWebRequest.EndSubmitRequest() [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 4361]
00000024d003e720 00007ffe9a4dcd53 System.Net.Connection.SubmitRequest(System.Net.HttpWebRequest, Boolean) [f:\dd\NDP\fx\src\net\System\Net\_Connection.cs @ 706]
00000024d003e7a0 00007ffe9a4dac8c System.Net.ServicePoint.SubmitRequest(System.Net.HttpWebRequest, System.String) [f:\dd\NDP\fx\src\net\System\Net\ServicePoint.cs @ 406]
00000024d003e800 00007ffe9a4da129 System.Net.HttpWebRequest.SubmitRequest(System.Net.ServicePoint) [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 4161]
00000024d003e860 00007ffe9a4beb07 System.Net.HttpWebRequest.GetResponse() [f:\dd\NDP\fx\src\net\System\Net\HttpWebRequest.cs @ 2226]
00000024d003e900 00007ffe3d8a8b29 Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[[System.__Canon, mscorlib]](Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1, Microsoft.WindowsAzure.Storage.RetryPolicies.IRetryPolicy, Microsoft.WindowsAzure.Storage.OperationContext)
00000024d003ea70 00007ffe3d9fa635 **Microsoft.WindowsAzure.Storage.Table.TableQuery`1+c__DisplayClass7[[System.__Canon, mscorlib]].b__6(Microsoft.WindowsAzure.Storage.IContinuationToken)**
00000024d003ead0 00007ffe3d9fa55a Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility+d__0`1[[System.__Canon, mscorlib]].MoveNext()
00000024d003eb30 00007ffe3da2c944 Microsoft.DataTransfer.ClientLibrary.AzureTableSource+d__19.MoveNext()

**Comment by asorrin-msft** [comment]
9.3.1 was just released and contains a fix that solves a specific class of deadlocks that were possible in parsing responses from the Table service.  Without a consistent repro, I can't be sure whether or not this hang will be solved by this fix, but there's a good chance.  Please upgrade and let us know if the issue is still present.

**Comment by sinaocelot** [comment]
We upgraded our package to 9.3.2 but this problem happened to us as well. When there is many calls to azure table the calls hang indefinitely.

In earlier versions there used to be a deadlock which could cause CRL threads to hang and don't allow them to take any other tasks. But in 9.3.2 version, threads don't hang but query tasks never complete. We have experienced this issue in different services of our product and it has already caused 3 live-sites. We had to revert back to 8.7.0 which does not have this issue.

**Comment by npizzolato** [comment]
We are also still seeing this problem on 9.3.2 (although the rate is much lower than 9.3.0). Is there more information we can give you to help debug this or do you have the info you need from others on the thread? We're running .net framework 4.6.2 in case that matters.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
