### ISSUE TITLE
Need Microsoft.Azure.Storage.Common nupkg RTM release

### ISSUE THREAD

**Issue by Jinhuafei** [Azure/azure-storage-net#740]
When can we expect a RTM version of Microsoft.Azure.Storage.Common.nupkg? The preview release is causing nuget [installation issue](https://github.com/Azure/azure-documentdb-dotnet/issues/385).

**Comment by rickle-msft** [comment]
Thanks for reaching out! We should be releasing a non-preview version within the next month. We are actively working on that new version now.

I'll close this issue as it seems like all parts of your question are addressed, but please feel free to re-open it if you have further concerns.
