### ISSUE TITLE
CloudQueueMessage overloading constructor (byte[]) is missing.

### ISSUE THREAD

**Issue by Elixor** [Azure/azure-storage-net#741]
Hello,
class : Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage is missing 
public CloudQueueMessage(byte[] content); In version 9.3.0.
In older vesion (9.1.0) this construcotr was. 
I cant see any information in changelog.
Regards.

Edit:
sorry my fault - i have two projects where I am using this nuget first is .NET framework 4.6.2 and second is .NET Standard 2.0. This overloaded constructor is missing in nuget for .NET Standard 2.0.

**Comment by rickle-msft** [comment]
Hi, @Elixor. Thank you for raising this issue. I have added it to our backlog for further discussion on our team.

**Comment by Elixor** [comment]
Thank you! I am looking forward

**Comment by jaschrep-msft** [comment]
Hi, @Elixor. The issue you are facing is there are different packages for the two project targets you are running against, and their APIs differ on this. One features the constructor you are attempting to use, the other instead uses a static method:
`public static CloudQueueMessage CreateCloudQueueMessageFromByteArray(byte[] content)`
Please note that this static method is not available in the package that contains the constructor.

An immediate fix would be to switch your code in the failed project to use this static method.

Another solution is to use the queue package which is in preview. This library is set to target .NET Standard 2.0 and will not contain these minor API differences. This preview library has the constructor you are trying to use. You can find the link to the package [here](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/9.4.0-preview). We are planning to make this generally available in the next month.

**Comment by pjt33** [comment]
The workaround which seems to solve this for me is to inline `CreateCloudQueueMessageFromByteArray` as:

    var msg = new CloudQueueMessage(default(string));
    msg.SetMessageContent(myByteArray);

That constructor and method are present in the Net Framework DLL and the Net Standard DLL.

But this is really a genuine issue, and I don't understand why it was closed. The existence of workarounds does not negate the existence of a bug. A Net Framework project is supposed to be able to use a Net Standard project as a dependency, subject to version restrictions, and a Net Standard library which uses `CreateCloudQueueMessageFromByteArray` can be consumed by a Net Framework application without any compile-time errors. Instead a `System.MissingMethodException` is thrown at runtime - and that with a version of the library which claims to be stable.
