### ISSUE TITLE
Release date of 9.4.0 (non-preview)

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-storage-net#743]
I'm working on a number of .NET Core applications, and I'm looking forward to using the BlobEncryptionPolicy to enable encryption. Is there any of idea of when 9.4 will be released? I'd rather not ship with a preview version.

Thanks!
Erick

**Comment by rickle-msft** [comment]
Hi, Erik. Thanks for reaching out! We should be releasing a non-preview version within the next month. We are actively working on that new version now.

I'll close this issue as it seems like all parts of your question are addressed, but please feel free to re-open it if you have futher concerns.
