### ISSUE TITLE
Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.3.0.0

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-storage-net#748]
I developed a .NET Standard 2.0 Nuget package (local) for a class library with a dependency on Microsoft.WindowsAzure.Storage, Version=9.3.0.0. It passed unit tests and ran fine when invoked from a .NET Core 2.0 console app. However, when I added my package to an Azure Function project (.Net Standard 2.0) it caused an exception to be thrown whenever I attempted to run the azure function from the VS2017 debugger.

System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.3.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

I had the same sort of problem with Microsoft.Extensions.Configuration 2.1.1.0 and this was resolved by downgrading to v2.0.0.0  - see [StackOverflow](https://stackoverflow.com/questions/51614750/microsoft-extensions-configuration-version-2-1-1-0-exception-could-not-load-f)

Question 1: What version of Microsoft.WindowsAzure.Storage works with .NET Standard 2.0 Azure Functions?

Question 2: Apart from trial and error, how are people using your package meant to find out what it works with?

**Comment by zezha-msft** [comment]
Hi @ImageQC, this information is available on the [Github README](https://github.com/Azure/azure-storage-net#target-frameworks).
