### ISSUE TITLE
OperationContext.Proxy support for .NET Core 2.0

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-storage-net#750]
### Which service(blob, file, queue, table) does this issue concern?
Common/OperationContext

### Which version of the SDK was used?
v9.3.0

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.1

### What problem was encountered?
Unable to use OperationContext.Proxy.

As a part of fix for issue [#477](https://github.com/Azure/azure-iot-sdk-csharp/issues/477) (Proxy support for Azure IoT Hub and Provisioning SDKs), we are implementing proxy support. Since we are unable to set the Proxy for OperationContext, we are unable to implement proxy support for FileUpload.

On investigating the dll, I can see implementation for net45 which has proxy support, but not in netstandard 1.0 or netstandard 1.3.
Is there proxy support planned for netstandard 2.0?

### How can we reproduce the problem in the simplest way?
1. Create an OperationContext instance
`OperationContext operationContext = new OperationContext();`
2. Set the proxy
`operationContext.Proxy = new WebProxy();`
**'OperationContext' does not contain a definition for 'Proxy'**

### Have you found a mitigation/solution?
No

**Comment by abhipsaMisra** [comment]
@CIPop , @tameraw for reference

**Comment by zezha-msft** [comment]
Communicated offline.

**Comment by CIPop** [comment]
Adding here since the project is OSS: Storage doesn't currently support Proxy in NetStandard 2.0.

**Comment by alexmg** [comment]
@CIPop Is there an intention to support `IWebProxy` in the future?

**Comment by usr4711** [comment]
@zezha-msft Why was this closed?
