### ISSUE TITLE
Cannot start AzureStorageEmulator

### ISSUE THREAD

**Issue by cdowneyM3** [Azure/azure-storage-net#751]
I am on Visual Studio version 15.7.6
AzureStorageEmulator Version 5.6.18177.1124
.NET 4.6.1

When I try to start the storage emulator I'm getting the error

> Unhandled Exception: System.TimeoutException: Unable to open wait handle.
>    at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.InternalWaitForStorageEmulator(Int32 timeoutInMilliseconds)
>    at Microsoft.WindowsAzure.Storage.Emulator.Controller.EmulatorProcessController.EnsureRunning(Int32 timeoutInMilliseconds)
>    at Microsoft.WindowsAzure.Storage.Emulator.Commands.StartCommand.RunCommand()
>    at Microsoft.WindowsAzure.Storage.Emulator.Program.Main(String[] args)

When I try "AzureStorageEmulator start -inprocess"

I'm getting the below error 

> Windows Azure Storage Emulator 5.6.0.0 command line tool
> Service Status: Blob http://127.0.0.1:10000/ False
> Input string was not in a correct format.
> Error: Unable to start the storage emulator.

So I've been though this [issue](https://github.com/Azure/azure-storage-net/issues/370) and didn't have any luck.  I've tried turning off IIS, I've tried changing the service endpoints to localhost, I've tried rebooting, I've tried disabling the firewall, I've tried added 127.0.0.1 via netsh, updating host files. 

I've attached my log file which basically says the same thing as the -inprocess error message.
[Error02-Aug-18-16-08.log](https://github.com/Azure/azure-storage-net/files/2255308/Error02-Aug-18-16-08.log)

Any ideas or suggestions?  

Some additional information, I cant run the init command against my localdb, so i updated the AzureStorageEmulator.5.6.config to point to my local SQL express instance.  Both instances are MS SQL 2017.  I also uninstalled the emulator and reinstalled and I'm running all commands from an admin command prompt.

The error I get when running azurestorage emulator init against LocalDB is

> Windows Azure Storage Emulator 5.6.0.0 command line tool
> Found SQL Instance (localdb)\MSSQLLocalDB.
> Creating database AzureStorageEmulatorDb56 on SQL instance '(localdb)\MSSQLLocalDB'.
> Cannot create database 'AzureStorageEmulatorDb56' : The database 'AzureStorageEmulatorDb56' does not exist. Supply a valid database name. To see available databases, use sys.databases..
> One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
> Error: Cannot create database 'AzureStorageEmulatorDb56' : The database 'AzureStorageEmulatorDb56' does not exist. Supply a valid database name. To see available databases, use sys.databases..
> 

Which doesn't make a lot of sense.  I've even created the AzureStorageEmulatorDb56 database and tried the -forcecreate command to get the database to create against localdb.  I can run it against my SQL express instance and the init command works.

**Comment by zezha-msft** [comment]
Hi @cdowneyM3, thanks for reaching out!

I've logged this issue for investigation.

**Comment by cdowneyM3** [comment]
@zezha-msft  Is the Azure Storage Emulator repo public, I couldn't find it.  I wouldn't mind taking a look at the code,  Doubtful I would be able to help, but I can try.

**Comment by kfarmer-msft** [comment]
Greetings, @cdowneyM3!

The repo is not public.  However, a crashing issue was discovered when starting with logging enabled, and a fix has been released as v5.7.  Could you please download from https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409 and try with that?

**Comment by cdowneyM3** [comment]
Downloaded it and it worked.  Thanks I was hoping it was something like that.
