### ISSUE TITLE
Storage Emulator 5.6 tries to create DB file in 'C:\Users' directory

### ISSUE THREAD

**Issue by gorgi** [Azure/azure-storage-net#752]
I was forced to update to storage emulator 5.6 and now the emulator fails to start. This is the error that I get: CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\GorgiAzureStorageEmulatorDb56.mdf'

As you can see, the path to the .mdf file is wrong.

**Comment by kfarmer-msft** [comment]
Greetings, @gorgi --

We leave it to SQL Server to determine the path.  Do you mind sharing the output of the init command?
