### ISSUE TITLE
Support for synchronous blob copy (x-ms-requires-sync)

### ISSUE THREAD

**Issue by DaRosenberg** [Azure/azure-storage-net#756]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the SDK was used?

9.3.0 

### Which platform are you using? (ex: .NET Core 2.1)

.NET Core 2.1

### What problem was encountered?

The performance of our application could greatly benefit from a synchronous **Copy Blob** operation, i.e. one request to blob storage that can be awaited, rather than having to implement code to wait and poll for the result later.

Using polling, there is a difficult trade-off:
* Poll more often, and we make many unnecessary requests to blob storage
* Poll less often, and our application can end up waiting an unnecessarily long time while the copy operation has in fact completed

Much better if our application can await the copy operation.

I see there is code in the storage client library to do this. It seems to make use of a `x-ms-requires-sync` header in the **Copy Blob** operation, which is exactly what we need. However this code is commented out currently, and there is no mention of this header in the REST API documentation.

First question: What's the status and plan for this functionality?

Second question: Will the `x-ms-requires-sync` header remove the requirement for a lease on the target blob to be infinite? This requirement is causing some design challenges for us, and it would be awesome if we could use a limited-time lease for these operations.

CC @kfarmer-msft

**Comment by mirobers** [comment]
Note that you can already transfer blobs server-side synchronously using the PutBlock overload that takes a Uri. The general support for uploading an entire blob this way is in progress, and it will relax the requirement for leases to be infinite. It is planned to be released in the coming months.

As this is not a client library issue, I'm closing it.

**Comment by DaRosenberg** [comment]
@mirobers Would you be able to give an update on the status/expected arrival of this functionality?

**Comment by scottmcm** [comment]
@mirobers It's now been over a year since this feature was added to the service.  What's the expected lag before a new feature becomes available in the official client library?

**Comment by DaRosenberg** [comment]
@mirobers I'm wondering this too, same as @scottmcm. We still suffer from lack of client library support for this.

> As this is not a client library issue, I'm closing it.

I don't quite understand your reasoning here. There is API support for this as far as I understand. If the support is simply lacking from the official client library, how is this not a client library issue?

**Comment by mirobers** [comment]
The service support was actually released quite recently. See the new [service version docs](https://docs.microsoft.com/en-us/rest/api/storageservices/version-2018-11-09) and the [Copy Blob from URL](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) docs for details.

I think there may be some confusion between "Put Block from URL", which was released last year on the service and client, and "Copy Blob from URL" which was released only a couple weeks ago. If you are looking for Put Block from URL, that support exists today and has been in place for a year.

@kfarmer-msft could you provide an update on the client support for Copy Blob from URL now that the service supports it?

**Comment by DaRosenberg** [comment]
@mirobers Not to split hairs but the doc page for the operation itself states:

> This API is available starting in version 2018-03-28.

That’s a year in my book.. :)

Anyways, we’ll all be grateful when it’s enabled. I noticed the code has been there but commented out for quite a while.

**Comment by mirobers** [comment]
@DaRosenberg Ah, I see! I'll get the documentation clarified. I will let @kfarmer-msft comment further on SDK support.

**Comment by ggirard07** [comment]
Looks like these new service APIs have just been announced publicly...
https://azure.microsoft.com/en-us/updates/new-copy-apis-for-efficient-data-copy/

Any update on the client support?
