### ISSUE TITLE
File Service - Question - Conditions when LastModified is updated

### ISSUE THREAD

**Issue by sujaysarma** [Azure/azure-storage-net#757]
Hello,

***This is not an issue, it is a request for more information.***

Area:
File Storage Service

In an application, we need the LastModified timestamp of CloudFile and CloudFileDirectory objects to be as close to the actual timestamp of the modification as possible. 

I was looking through the code (https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/File/CloudFile.cs @ Line 4985) and I see that it is either fetched afresh from Azure (Line 4983) or updated with whatever is already in Properties.LastModified (Line 4985).

So here is are two scenarios:
1) A new CloudFile is created. 
2) A CloudFile is opened for writing and the contents updated. 

In both cases, what must my code do to ensure LastModified is (a) populated/updated on Azure with a valid DateTimeOffset and (b) matches that value on Azure ?

**Comment by sujayvsarma** [comment]
Ping!

**Comment by seanmcc-msft** [comment]
Hi,

In both cases, the CloudFile's Properties.LastModified time is updated automatically, and will match the service.
