### ISSUE TITLE
Use of 

### ISSUE THREAD

**Issue by djohnsomsft** [Azure/azure-storage-net#758]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
9.3.1

### Which platform are you using? (ex: .NET Core 2.1)
Universal Windows Platform, Unity 2017.9.4f1, .NET 4.6 scripting runtime/compat
DLL version that compats with this for HoloLens is the "win8" build.

### What problem was encountered?
Using the following query results in an exception that "randomguid" key is added multiple times to dictionary.

var tableObjectData =
                    (await this.objectsTable.ExecuteQuerySegmentedAsync(new TableQuery<ObjectDataEntity>().Where(
                        TableQuery.GenerateFilterCondition("EntityId", QueryComparisons.Equal, entityId)).Take(1), null)).FirstOrDefault();

### How can we reproduce the problem in the simplest way?
Use ExecuteQuerySegmentedAsync with a .Where on a TableQuery on "win8" build. 

### Have you found a mitigation/solution?
I was able to rebuild the WindowsPhoneRuntime project with this change commenting out a line in HttpRequestMessageFactory.cs and the error no longer occurred:

#if WINDOWS_RT && !NETCORE
            // Windows Phone does not allow the caller to disable caching, so a random GUID
            // is added to every URI to make it look like a different request.
            // builder.Add("randomguid", Guid.NewGuid().ToString("N"));
#endif

Given that this feature needs to be kept for Windows Phone, presumably just checking or an existing key before the Add call would also mitigate this issue, or modifying UriQueryBuilder.Add to do an indexed assignment instead of IDictionary.Add.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
