### ISSUE TITLE
Blob/Container segmented data structures

### ISSUE THREAD

**Issue by PabloDeCortes** [Azure/azure-storage-net#760]
Hi! There is an issue with abstraction layers for Blob/Container segmented data structures. 
[BlobResultSegment](https://github.com/Azure/azure-storage-net/blob/fdc07726910ead3281b14b2769a92b2fea68bd97/Lib/Common/Blob/BlobResultSegment.cs)
[ContainerResultSegment](https://github.com/Azure/azure-storage-net/blob/fdc07726910ead3281b14b2769a92b2fea68bd97/Lib/Common/Blob/ContainerResultSegment.cs)
There are links above for 2 classes, difference in these files only in one field, that could be generic:
`public IEnumerable<T> Results { get; private set; }`

You can create an abstract class for segments, for example:
`public class AbstractResultSegment<T>`
`{`
`    public AbstractResultSegment(IEnumerable<T> blobs, BlobContinuationToken continuationToken)`
`    {`
`        this.Results = blobs;`
`        this.ContinuationToken = continuationToken;`
`    }`
`    public IEnumerable<T> Results { get; private set; }`
`    public BlobContinuationToken ContinuationToken { get; private set; }`
`}`
Then you can just inherit from that abstract class, for example:
`public class BlobResultSegment : AbstractResultSegment<IListBlobItem>`
`public class ContainerResultSegment : AbstractResultSegment<CloudBlobContainer>`
This approach allow people create more abstraction layers which depends on abstraction and not concrete implementation.

Best Regards.

**Comment by seanmcc-msft** [comment]
Thanks for your suggestion.
