### ISSUE TITLE
Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadTextAsync - unexpected UploadTextAsync Microsoft.WindowsAzure.Storage.StorageException | The remote server returned an error: (412) The append position condition specified was not met.

### ISSUE THREAD

**Issue by pacojones** [Azure/azure-storage-net#761]
### Which service(blob, file, queue, table) does this issue concern?
**blob**

### Which version of the SDK was used?
**7.2.1**

### Which platform are you using? (ex: .NET Core 2.1)
.Net Framework 4.6.1 (Azure Functions, Http trigger)

### What problem was encountered?
I'm using UploadTextAsync inside an HttpTrigger of an AzureFunction, and I'm trying to save each request in a blob. When I do that, I get the error "Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadTextAsync - unexpected UploadTextAsync Microsoft.WindowsAzure.Storage.StorageException | The remote server returned an error: (412) The append position condition specified was not met."

### How can we reproduce the problem in the simplest way?
With the following code:

`Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient client = CloudStorageAccount.Parse("myConnectionString").CreateCloudBlobClient();

            var container = client.GetContainerReference("myContainerName");

            Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blob = container.GetBlockBlobReference(String.Format("{0}/{1}.json", DateTime.Now.ToString("yyyy/MM/dd"), Guid.NewGuid()));

            string obj = JsonConvert.SerializeObject(myInstance, new IsoDateTimeConverter { DateTimeFormat = "yyyy-MM-ddTHH:mm:ss.fZ" });

            blob.UploadTextAsync(obj).Wait();  `

### Have you found a mitigation/solution?
**No**

**Comment by seanmcc-msft** [comment]
Please upgrade to the latest version and let us know if you can still reproduce.
