### ISSUE TITLE
Silent data corruption in CloudBlob.DownloadToFileParallelAsync

### ISSUE THREAD

**Issue by hans-olav** [Azure/azure-storage-net#763]
`CloudBlob.DownloadToFileParallelAsync` under the covers calls `ParallelDownloadToFile.DownloadToStreamWrapperAsync`. That function has logic to abort and retry/resume the download if no data flows for 120 seconds. But it has a bug that corrupts the downloaded file when the abort/retry cycle happens more than once.

Look at line 248 in [ParallelDownloadToFile.cs](https://github.com/Azure/azure-storage-net/blob/master/Lib/ClassLibraryCommon/Blob/ParallelDownloadToFile.cs#L248) and consider what happens to `length` on the second abort/retry. It will be reduced by the _all_ the bytes downloaded since the beginning, not just the bytes downloaded since the last abort/retry.

The result is that not enough data is downloaded to fill the entire chunk/range in the underlying memory mapped file, which are left as zeroes in the resulting file. In other words, the downloaded file is corrupt, but the `DownloadToFileParallelAsync()` call succeeds.

We found this in production with the latest version of the library. The bug is still there in _master_, as you can see above.

**Comment by kfarmer-msft** [comment]
@hans-olav -- Can I confirm that you were using v9.3.x of the library when you wrote this?  I'm seeing differences between that and the current that look like it's been addressed.

**Comment by kfarmer-msft** [comment]
@hans-olav -- Since we're seeing evidence that this was addressed, we're closing the issue for now.  If you're still experiencing it, please re-open.
