### ISSUE TITLE
Missing index in StorageException message while doing TableBatchOperation.

### ISSUE THREAD

**Issue by ozasheetal** [Azure/azure-storage-net#764]
Local Machine Configuration

Storage Emulator: 5.5
.Net Framework: 4.6

When trying to remove entries from TableStorage using TableBatchOperation, I get 404 (HTTPResponseCode) in my storageException, but along with that, **I get index prefixed in the message itself.**

But in production when I am connected to actual Azure, I don't get index in the message. [Screenshot attached]

Has the index been removed from the StorageException message? If yes, is there any other way I could access it. I need the index because I am deleting the entries from TableStorage in batch.

![capture](https://user-images.githubusercontent.com/29248415/45095315-17b9fc00-b11e-11e8-9746-1ca3e4ea929d.JPG)

I found this entry in the change log (v 2.0.5)
**Tables: Exceptions during TableBatchOperation parse the entity index from the server response.**

Any help is much appreciated.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
