### ISSUE TITLE
ReadAsync accepts a CancellationToken but ignores it

### ISSUE THREAD

**Issue by lostllama** [Azure/azure-storage-net#765]
### Which service(blob, file, queue, table) does this issue concern?
Blob, probably others

### Which version of the SDK was used?
9.3.1

### Which platform are you using? (ex: .NET Core 2.1)
NET Core 2.1

### What problem was encountered?
CancellationToken is ignored when reading from a blob read stream. The code below will happily read to the end. For my test file which is 42,397,696 bytes, I get the following output:

    True
    True
    True
    True
    True
    True
    True
    True
    True
    True
    True
    True
    Done

I've had a nose through the code and can see that the problem comes down to the [`ReadAsync`](https://github.com/Azure/azure-storage-net/blob/fdc07726910ead3281b14b2769a92b2fea68bd97/Lib/WindowsRuntime/Blob/BlobReadStream.cs#L98), which takes a `CancellationToken`, but doesn't use it.

### How can we reproduce the problem in the simplest way?

    var cts = new CancellationTokenSource();
    var buffer = new byte[4 * 1024 * 1024];
    var readStream = await blobRef.OpenReadAsync(null, null, null, cts.Token);
    cts.Cancel();
    int bytesRead = 0;
    do
    {
        bytesRead = await readStream.ReadAsync(buffer, 0, buffer.Length, cts.Token);
        Console.WriteLine(cts.Token.IsCancellationRequested);
    }
    while (bytesRead > 0);
    Console.WriteLine("Done");
    Console.ReadLine();

### Have you found a mitigation/solution?

I'm using the following extension method found [here](https://stackoverflow.com/a/26942757/3181933)

    public static Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
    {
        return task.IsCompleted
            ? task
            : task.ContinueWith(
                completedTask => completedTask.GetAwaiter().GetResult(),
                cancellationToken,
                TaskContinuationOptions.ExecuteSynchronously,
                TaskScheduler.Default);
    }

like so:

    bytesRead = await readStream.ReadAsync(buffer, 0, buffer.Length, cts.Token).WithCancellation(cts.Token);

**Comment by SimonGustavsson** [comment]
I've submitted a PR that addresses this issue.

**Comment by kfarmer-msft** [comment]
It's been busy around here. :)

I'm working on accepting the PR

**Comment by lostllama** [comment]
> I'm working on accepting the PR

Thank you :-) and thanks to @SimonGustavsson for creating the PR.

**Comment by kfarmer-msft** [comment]
Tests pass.  I expect this will be in our next release.
