### ISSUE TITLE
Calling CosmosDB table API doesn't retry 429 throttle status code

### ISSUE THREAD

**Issue by damongr-msft** [Azure/azure-storage-net#769]
### Which service(blob, file, queue, table) does this issue concern?
Table (against CosmosDB)

### Which version of the SDK was used?
9.3.0

### Which platform are you using? (ex: .NET Core 2.1)
.Net desktop

### What problem was encountered?
When calling CosmosDB table API and we start to get throttled the expectation is that the table client would using the default ExponentialRetry policy would retry when the CosmosDB table API returns a 429.
But this code (duplicated in LinearRetry policy as well) in ExponentialRetry.ShouldRetry will always return false when statusCode is 429:
``` cs
            // If this method is called after a successful response, it means
            // we failed during the response body download. So, we should not
            // check for success codes here.
            if ((statusCode >= 300 && statusCode < 500 && statusCode != 408)
                  || statusCode == 501 // Not Implemented
                    || statusCode == 505 // Version Not Supported
                || lastException.Message == SR.BlobTypeMismatch)
            {
                return false;
            }
```
Fix would be to change it to:
``` cs
            // If this method is called after a successful response, it means
            // we failed during the response body download. So, we should not
            // check for success codes here.
            if ((statusCode >= 300 && statusCode < 500 && statusCode != 408 && statusCode != 429)
                  || statusCode == 501 // Not Implemented
                    || statusCode == 505 // Version Not Supported
                || lastException.Message == SR.BlobTypeMismatch)
            {
                return false;
            }
```

### How can we reproduce the problem in the simplest way?
Any throttling from the CosmosDB table API that returns 429

### Have you found a mitigation/solution?
Only writing our own ExponentialRetry policy implementation will fix this issue.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
