### ISSUE TITLE
FilterString confusing behavior on TableQuery depending on creation path

### ISSUE THREAD

**Issue by kellypleahy** [Azure/azure-storage-net#77]
If you create a `TableQuery<T>` using the factory method (for LINQ) of `CloudTable.CreateQuery<T>()`, and then set a `FilterString` on the resulting object, the `FilterString` is ignored by `ExecuteQuery` on the `TableQuery<T>`.  However, if you set the `FilterString` on a `TableQuery<T>` that is created via the default constructor of the `TableQuery<T>` object, it works as expected.

It seems like there are some strange behavior differences based on whether the `queryProvider` private field is set in the `TableQuery<T>` object.  While I'd have personally preferred that the LINQ stuff wasn't comingled with the `FilterString`, at the very least it seems like `FilterString` should throw if the `queryProvider` is set, or `TableQuery.Execute`, etc. should throw if the `FilterString` is set and the `queryProvider` is also set.

**Comment by nukefusion** [comment]
Just came across this issue ourselves. We started off using the factory methods to generate a query which was then filtered via LINQ but moved to use FilterString when we needed to apply more complex filtering than was supported via LINQ. I second the notion that the API should be more predictable here. If the FilterString itself doesn't apply in this scenario then ideally it would be hidden completely, however raising an error would certainly be better than silent failure.

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information. 

Thanks!

**Comment by Porges** [comment]
This is absolutely bizarre.
