### ISSUE TITLE
Which version of this storage library is supported on the Azure Functions platform?

### ISSUE THREAD

**Issue by ryancole** [Azure/azure-storage-net#773]
Hi all,

I've been working on some code that I intend to deploy to the Azure Functions platform. I've got my Functions project template created with several different Functions written. I moved and consolidated some repeated code. relating to Azure Storage operations, into a separate library project. On that new library, with my Storage code, I installed this `azure-storage-net` library via the nuget package `WindowsAzure.Storage`.

When I add my library, using `WindowsAzure.Storage`, to the Functions project, I get an error about conflicting `WindowsAzure.Storage` versions. The version that the Functions project seems to demand is 7.2.1. That version is several years old at this point.

Is it possible to use these more recent library versions, of `WindowsAzure.Storage`, on the Azure Functions platform?

**Comment by seanmcc-msft** [comment]
Please follow up with the Azure Function team.
