### ISSUE TITLE
The Table API no longer exist, but why?

### ISSUE THREAD

**Issue by rmja** [Azure/azure-storage-net#779]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the SDK was used?
latest

### Which platform are you using? (ex: .NET Core 2.1)
any

### What problem was encountered?
The Table api does no longer exist

### How can we reproduce the problem in the simplest way?
Checkout the latest source

### Have you found a mitigation/solution?
Nope, what is the recommended way to use the Table service going forward?

**Comment by rickle-msft** [comment]
Hi, @rmja. Thank you for your interest in using Azure Tables. Ownership of this service has transferred over to Azure CosmosDB. Docs, etc. now live here https://docs.microsoft.com/en-us/azure/cosmos-db/table-sdk-dotnet

**Comment by rmja** [comment]
@rickle-msft but that API is neither .NET Standard compatible nor open source. What a major setback! :(

**Comment by seniorquico** [comment]
@pemari-msft The existing Table SDKs (pre-9.4) you reference appear to have production issues (#744). And... _shortly_ now being 1.5 months later... the preview version of the Cosmos DB SDK still doesn't support Azure Table endpoints:

https://docs.microsoft.com/en-us/azure/cosmos-db/table-sdk-dotnet-standard#0.9.1-preview

So... why the haste to remove the Table SDKs from this project before an alternative was made available? Anything that can be done at this point? Or are we just stuck waiting? re: https://github.com/Azure/azure-storage-net/pull/774#issuecomment-426652496

**Comment by rmja** [comment]
@rickle-msft I am tuned, but I guess we have very different definitions of "shortly"! My PR for fixing a production issue (#774) that we are facing _all the time_ was rejected.

Please realize that a lot of libraries have a dependency on this one, and the time it takes for them to refactor into the new "upcoming" one takes a while - in the meantime we are all simply stuck. Not to mention that you removed the API in a MINOR verison.

What a mess.
