### ISSUE TITLE
Any plans om making a PCL version?

### ISSUE THREAD

**Issue by Cheesebaron** [Azure/azure-storage-net#78]
Is a version of WindowsAzure.Storage for PCL projects (not just universal apps) on the roadmap? This way it would be super easy to use in a MVVM context where you have a PCL for all model code which could be shared with Universal apps, Xamarin.Android, Xamarin.iOS and other platforms.

**Comment by pemari-msft** [comment]
We've released a PCL that supports Xamarin.Android & Xamarin.iOS as version 4.4.0-preview. Please try it out and let us know if you have any feedback!

**Comment by Cheesebaron** [comment]
Sweet baby Jesus. Will try this immediately! Thanks a bunch @pemari-msft! :+1: :+1: :+1:
