### ISSUE TITLE
Provide docs in a more friendly format

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-storage-net#785]
Please consider providing docs in HTML format like many other Azure SDKs

**Comment by kfarmer-msft** [comment]
@stewartadam -- Our HTML docs are at https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet, or is there another set of documentation you're thinking of?

**Comment by stewartadam** [comment]
Thanks - the 'Documentation' folder contains (what I think is an outdated) CHM file and the README doesn't link to the above - we should include that instead of a link to the .NET developer homepage.

**Comment by seanmcc-msft** [comment]
We are moving to online documentation and removing the documentation folder.
