### ISSUE TITLE
Storage Emulator converts old DateTimes to DateTime.MinValue

### ISSUE THREAD

**Issue by crnd** [Azure/azure-storage-net#787]
### Which service(blob, file, queue, table) does this issue concern?
Table storage

### Which version of the SDK was used?
Storage Emulator 5.8.0.0 and WindowsAzure.Storage 9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.1

### What problem was encountered?
[Table storage limits](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model#property-types) the minimum accepted value of ```DateTime``` to 1st of January 1601 UTC. However storing that ```DateTime``` to Storage Emulator ends up getting converted to ```DateTime.MinValue```. This seems to happen to all the years between 1600 and 1754. Starting from 1754 the conversion does not happen anymore.

### How can we reproduce the problem in the simplest way?
I made a project where the problem can be reproduced. https://github.com/crnd/storage-emulator-datetime

**Comment by kfarmer-msft** [comment]
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite
