### ISSUE TITLE
SetStandardBlobTierAsync invalid URI parameter

### ISSUE THREAD

**Issue by luisve1427** [Azure/azure-storage-net#788]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.NET core 2.1

### What problem was encountered?
Error when trying to set tier using storage emulator

            //Upload
            await blobReference.UploadFromByteArrayAsync(content, 0, content.Length);
            //Set blob tier
            **await blobReference.SetStandardBlobTierAsync(StandardBlobTier.Cool);**

Error: Value for one of the query parameters specified in the request URI is invalid. Trace:   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

### How can we reproduce the problem in the simplest way?

create blob then try to set the blob tier

### Have you found a mitigation/solution?

No

**Comment by kfarmer-msft** [comment]
It seems likely that blob tier support was never added to the emulator (there are a number of server features that were not readily implementable for that environment).  With that in mind, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite
