### ISSUE TITLE
Question: Is any way to check that container was actually removed

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/azure-storage-net#793]
We're using CloudBlobClient to manipulate containers inside blob storage. One of the common operation is to remove container:

```
CloudBlobClient blobClient = GetBlobClient();
 CloudBlobContainer container = blobClient.GetContainerReference(this.BuildPropertyStorageName(input1, input2));
await container.DeleteAsync();
```
This works fine, but the blob storage has a known behavior: container is not removed right after command completed, but just marked as deleted and then Azure need about 1-2 minutes to actually remove it. If you will try to create container with same name  in this period of time, then you will get (409) Conflict error (container with name 'name' already exist).

So my question is: how can we check that container was actually removed from Azure blob storage?

**Comment by jonimec** [comment]
Joining the question,
I have a problem where i run some tests and delete the container, and afterwards try to add it again and it return 409 conflict 
it passes the not exist check, and fails in the Create
i assume that this issue is related 

`if (!blobContainer.Exists())
                {
                    blobContainer.Create();
                }
                else
                {
                    blobContainer.SetMetadata();
                }`

**Comment by seanmcc-msft** [comment]
Hi,

Unfortunately, it is not possible to determine when a container is actually deleted, but it will occur within 30 seconds.  For more information, see [https://docs.microsoft.com/en-us/rest/api/storageservices/delete-container#remarks](url).

-Sean
