### ISSUE TITLE
Hi! I am wondering if you support .NET Standard 2.0

### ISSUE THREAD

**Issue by learnersm** [Azure/azure-storage-net#795]

**Comment by erezvani1529** [comment]
For NetStandard2.0 support, please try our split per service packages([Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/9.4.0), [File](https://www.nuget.org/packages/Microsoft.Azure.Storage.File/9.4.0), [Queue](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/9.4.0)).

Note: Table support via CosmosDB table package is being worked on.

**Comment by learnersm** [comment]
Thanks !

**Comment by srini1978** [comment]
Hi @erezvani1529  is the package v9.3.2. not a .net standard 2.0 compliant package.
