### ISSUE TITLE
Is TableQuery<DynamicTableEntity> projectionQuery = new TableQuery<DynamicTableEntity>().Select(new string[] { "RowKey" }); honoring select statements ?

### ISSUE THREAD

**Issue by kemura** [Azure/azure-storage-net#798]
### Which service(blob, file, queue, table) does this issue concern?
Azure Storage Table 

### Which version of the SDK was used?
WindowsAzure.Storage.8.7.0 but latest version was same.

### Which platform are you using? (ex: .NET Core 2.1)
.NETFramework,Version=v4.6.1

### What problem was encountered?
I wanted to project only RowKey but the actual API threw $select=PartitionKey,RowKey,Timestamp

### How can we reproduce the problem in the simplest way?
following the document and makin requests then capture by Fiddler.

https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#query-a-subset-of-entity-properties

### Have you found a mitigation/solution?
Not yet. would like to know if it is by design.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
