### ISSUE TITLE
Compliance with .net standard 2.0

### ISSUE THREAD

**Issue by srini1978** [Azure/azure-storage-net#799]
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the SDK was used?
v9.3.2

### What problem was encountered?
is this version of the package a .net standard 2.0 compliant package ?

**Comment by deckertron9000** [comment]
@pemari-msft is there any hope of a Table nuget that is .net standard 2.0 compliant being released soon?

**Comment by ManfredLange** [comment]
> 9.4 is the compliant version. Please upgrade to that version.

@pemari-msft Upgrading to version 9.4 is not really an option for anyone already using Table storage that contains a large amount of data that you can't afford to loose.

Upgrading to 9.4.x would require people to move their data from Azure Table Storage to CosmosDB. This could potentially very time-consuming and incur substantial costs (out-going data). Furthermore, entries in tables have timestamps. You may want to keep those which may not be an option.

This whole story around Azure Table storage seems to be very badly managed in terms of transition, feature pipeline, etc. It's been very frustrating so far to find the right nuget packages. Example code is outdated in a lot of cases.

**Comment by kfarmer-msft** [comment]
I'd suggest not updating your 3rd party dependency in that case, until CosmosDB releases their package.
