### ISSUE TITLE
Azure Table Serialization Error: Not marked as Serializable

### ISSUE THREAD

**Issue by abhishekkant** [Azure/azure-storage-net#800]
### Which service(blob, file, queue, table) does this issue concern?
Azure Table queried from Azure Bot Framework v3.

### Which version of the SDK was used?
9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.NET 4.7.1

### What problem was encountered?
I have shared the problem on [Stackoverflow](https://stackoverflow.com/questions/53046358/windows-azure-table-storage-serialization-error-in-bot-framework-v3).

### Have you found a mitigation/solution?
Nope. I tried even with v9.3.1

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
