### ISSUE TITLE
Unable to upload large files from stream (upper than 100MB)

### ISSUE THREAD

**Issue by nemrism** [Azure/azure-storage-net#803]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
9.4 / Emulator 5.8

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.7

### What problem was encountered?
Failure when uploading a large file using async stream in the Azure Storage emulator

### How can we reproduce the problem in the simplest way?
1. Upload stream async (larger than 100Mb)
2. Wait for the unhandled exception to raise (NullReference inner exception)

### Have you found a mitigation/solution?
Nope, unfortunately.
But we did notice that the problem does not happen on a real Azure storage!

### Storage Emulator logs
[Verbose01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539735/Verbose01-Nov-18-15-11.log)
[Verbose_debug01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539736/Verbose_debug01-Nov-18-15-11.log)
[UnhandledException01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539737/UnhandledException01-Nov-18-15-11.log)
[Perf01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539738/Perf01-Nov-18-15-11.log)
[LinqToSQL01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539739/LinqToSQL01-Nov-18-15-11.log)
[Info01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539740/Info01-Nov-18-15-11.log)
[Info_debug01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539741/Info_debug01-Nov-18-15-11.log)
[Error01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539742/Error01-Nov-18-15-11.log)
[Error_debug01-Nov-18-15-11.log](https://github.com/Azure/azure-storage-net/files/2539743/Error_debug01-Nov-18-15-11.log)

**Comment by kfarmer-msft** [comment]
Please try v5.9 of the emulator.

**Comment by nemrism** [comment]
Just confirmed it works with the new emulator. Thanks!
