### ISSUE TITLE
how to enable Storage Client Library logging with a .net core console app

### ISSUE THREAD

**Issue by imeya** [Azure/azure-storage-net#805]
I tried to follow this [link](https://docs.microsoft.com/en-us/rest/api/storageservices/client-side-logging-with-the-.net-storage-client-library), but there is no information about how to enable Storage Client Library logging when use the .net core console application. As you know, in .net core console application, there is no app.config file, it is used the .json file in .net core console.(I also tried add app.config for this project, but no effect)

**Comment by kfarmer-msft** [comment]
Unfortunately, the listener support we depend on does not appear to be supported, and I haven't found any specific workarounds at this time.

**Comment by johnib** [comment]
hey @kfarmer-msft, are you considering using ILogger/ILoggerFactory interfaces as a means to emit logs from the SDK?
(that would give the users the ability to control/listen to your logs easily)
