### ISSUE TITLE
CloudBlockBlob.UploadFromStreamAsync fails with NullReferenceException

### ISSUE THREAD

**Issue by aemil1** [Azure/azure-storage-net#806]
### Which version of the SDK was used?
9.4.0.0.

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.6.2

### What problem was encountered?
UploadFromStreamAsync(Stream source, long length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
fails with NullReferenceException  at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<UploadFromStreamAsyncHelper>d__31.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-blob\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 833

### How can we reproduce the problem in the simplest way?
According to the source code, progressIncrementer is null.

### Have you found a mitigation/solution?
Used UploadFromStreamAsync's overload that takes an IProgress<StorageProgress> reference.

**Comment by kfarmer-msft** [comment]
Well, darn!

Thanks, @aemil1!  I'll schedule a hotfix out for this soon, and verify the other APIs where IProgress needs to be wrapped.

**Comment by kfarmer-msft** [comment]
This should be fixed in v9.4.1.
