### ISSUE TITLE
Azure emulator 5.8 crashes and returns 500 on putblob 

### ISSUE THREAD

**Issue by javier-alvarez** [Azure/azure-storage-net#810]
07/11/2018 14:08:20 [UnhandledException] [ActivityId=059990ee-6fbc-4a67-82ae-0cef244c8f94] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:08:21 [UnhandledException] [ActivityId=c4a5ac08-809c-4fed-8175-5a4b5bd90d34] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:08:22 [UnhandledException] [ActivityId=b5f3da61-9ea3-4d15-a66a-831921d5455a] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:08:23 [UnhandledException] [ActivityId=b53b66fb-f63c-48bc-91aa-72ed321ea195] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:11:38 [UnhandledException] [ActivityId=036dbf25-91ed-405d-8b69-a0ad7c77d2de] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:11:39 [UnhandledException] [ActivityId=ebcc45ad-1ee1-46de-80ba-2457ec765f33] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:11:40 [UnhandledException] [ActivityId=51691ea9-890a-4e2f-bc21-f8f1f0069cb9] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
07/11/2018 14:11:41 [UnhandledException] [ActivityId=1b1417bd-cda4-49bf-a20c-fa62c68ca27a] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)

**Comment by dfbaskin** [comment]
I'm seeing this same error.

**Comment by dfbaskin** [comment]
Changing the configuration from:

```
  <SQLInstance>.</SQLInstance>
```

to

```
  <SQLInstance>(localdb)\MSSQLLocalDB</SQLInstance>
```

made no difference.

**Comment by dfbaskin** [comment]
The error is:

```
EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException:
The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request.
---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object.
---> System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by dfbaskin** [comment]
This is the entire log for the activity Id:

```
11/30/2018 9:38:33 AM [Error] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] [FEUnhandledException] Process crashed due to fatal exception: AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11/30/2018 9:38:33 AM [Error_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Exception raised during processing of request. Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11/30/2018 9:38:33 AM [Info] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Request content length is 133.
11/30/2018 9:38:33 AM [Info] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Processing exception: AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11/30/2018 9:38:33 AM [Info] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] ProcessException is throwing fatal exception Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11/30/2018 9:38:33 AM [Info_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Setting status description as "Server encountered an internal error. Please try again after some time."
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] SELECT TOP (1) [t0].[Name], [t0].[SecretKey], [t0].[QueueServiceSettings], [t0].[BlobServiceSettings], [t0].[TableServiceSettings], [t0].[SecondaryKey], [t0].[SecondaryReadEnabled]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] FROM [dbo].[Account] AS [t0]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] WHERE [t0].[Name] = @p0
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] -- @p0: Input VarChar (Size = 8000; Prec = 0; Scale = 0) [devstoreaccount1]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] -- Context: SqlProvider(Sql2008) Model: AttributedMetaModel Build: 4.7.3056.0
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] SELECT GETUTCDATE() AS [value]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] -- Context: SqlProvider(Sql2008) Model: AttributedMetaModel Build: 4.7.3056.0
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] SELECT GETUTCDATE() AS [value]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] -- Context: SqlProvider(Sql2008) Model: AttributedMetaModel Build: 4.7.3056.0
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] SELECT GETUTCDATE() AS [value]
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] -- Context: SqlProvider(Sql2008) Model: AttributedMetaModel Build: 4.7.3056.0
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [LinqToSQL] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] 
11/30/2018 9:38:33 AM [Perf] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] PerfCounters: Account=devstoreaccount1 Operation=PutBlockList on Container=imported-documents with Status=InternalError RequestHeaderSize=451 RequestSize=133 ResponseHeaderSize=173 ResponseSize=253 ErrorResponseByte=253 TimeInMs=7 ProcessingTimeInMs=7 UserTimeoutInMs=922337203685477 OperationTimeoutInMs=60000 MaxAllowedTimeoutInMs=60000 SlaUsedInMs=0 ReadLatencyInMs=0 WriteLatencyInMs=0 ClientIP=127.0.0.1:64450 UserAgent='Azure-Storage/9.3.2 (.NET Core)' RequestVersion='2018-03-28' ProcessorVersionUsed='2018-03-28' RequestUrl='http://127.0.0.1:10000/devstoreaccount1/imported-documents/ca67b650-4927-4c8c-bbe9-5069b7ceb2c1/original.json?comp=blocklist' ClientRequestId='cf1b523f-b24f-4f02-8e5b-035f161d8433' MeasurementStatus=UnknownFailure HttpStatusCode=500 TotalFeTimeInMs=7 TotalTableServerTimeInMs=0 TotalTableServerRoundTripCount=0 TotalPartitionWaitTimeInMs=0 TotalXStreamTimeInMs=0 TotalXStreamRoundTripCount=0 SmbOpLockBreakLatency=0 LastTableServerInstanceName= LastTableServerErrorCode=0 TotalAccountCacheWaitTimeInMs=0 TotalContainerCacheWaitTimeInMs=0 InternalStatus= RequestContentType='' ResponseContentType='application/xml' PartitionKey='ca67b650-4927-4c8c-bbe9-5069b7ceb2c1/original.json' ItemsReturned='0' BatchOperationCount='0' LastXStreamErrorCode=0 AuthenticationType='NA' AccountConcurrentReq='' OverallConcurrentReq='0' Range='' EntityType='BlockBlob'  LastTSPartition= TotalXCacheTimeInMs=0 TotalXCacheRoundTripCount=0 TotalTableServerOnlyTimeInMicroSeconds=0 TotalAuthTimeInMs=0.234 AuthenticationTimeInMs=0.234 AuthorizationTimeInMs=0 GetAuthenticationDataTimeInMs=0, GetAuthorizationDataTimeInMs=0
11/30/2018 9:38:33 AM [UnhandledException] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] ActivityBegin, ActivityName=RDStorageRequest CorrelationInfo=
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Limiting operation timeout '922337203685477'ms to Max allowed  timeout '60000ms'.
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] No snapshot; this request is for the root blob.
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] CORS: Start processing actual CORS request
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] CORS: Origin request header doesn't exist and request method is not GET/HEAD so no CORS headers needed
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Closing HttpListenerResponse of this request...
11/30/2018 9:38:33 AM [Verbose] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] The HttpListenerResponse of this request has been closed successfully
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Accepting request
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Got request PUT http://127.0.0.1:10000/devstoreaccount1/imported-documents/ca67b650-4927-4c8c-bbe9-5069b7ceb2c1/original.json?comp=blocklist 2018-03-28
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Host-style URI resolution failed. Allowing path-style for uri http://127.0.0.1:10000/devstoreaccount1/imported-documents/ca67b650-4927-4c8c-bbe9-5069b7ceb2c1/original.json?comp=blocklist
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] StorageAccount.GetPropertiesImpl(PropertyNames=0x0020, ServiceMetadataPropertyNames=0x000000007807C000,,00:00:30)
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Returning from AcceptRequest method.
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Setting status code to 500
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] In the process end callback
11/30/2018 9:38:33 AM [Verbose_debug] [ActivityId=84c2fe6a-4717-42f9-8a54-146fd5a4c592] Entering BasicHttpRestProcessor.EndProcess
```

**Comment by dfbaskin** [comment]
Changing from the shortcut connection string to the full connection string (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-a-shortcut) made no difference.

The application I'm running works fine with real Azure Storage.

I did also notice that the file that I was writing appears to have been successfully written to the emulator's `AppData\Local\AzureStorageEmulator\BlockBlobRoot` directory.

**Comment by kfarmer-msft** [comment]
Sorry for the delay, folks.  I've managed to clear out time away from the client to look into this one.  It takes a while to spin up this project.

Re 5.8:  It was intended to be a release that just allowed to emulator to accept clients advertising newer server API versions (without implementing new APIs, though).

In the meantime, we are pointing people to the Azurite emulator.  If it solves your needs and unblocks you, please make use of it.

**Comment by rmja** [comment]
@kfarmer-msft The azurite emulator does not work with Orleans. Do you have a link where we can download version 5.7. I can only find installers for 5.8.

**Comment by javier-alvarez** [comment]
@kfarmer-msft  Any updates on a link to get 5.7? I am also blocked. I cannot use Azurite as it crashes with a PANIC on tables.

**Comment by kfarmer-msft** [comment]
I think I found the issue:  Uploading a blob via Cloud Explorer works again.  I'll start the work to publish v5.9.

Because of the different paths these bits can take to arrive on user installations, this will be available first via the standalone link at https://azure.microsoft.com/en-us/downloads/, perhaps as early as today.  Web Platform Installer and Visual Studio each refer to the download location, and release on their own schedules.

Apologies again for the error, and for the delay.

**Comment by kfarmer-msft** [comment]
v5.9 is live

**Comment by dfbaskin** [comment]
That fixed the issue.  Thanks!

**Comment by riverar** [comment]
@kfarmer-msft Wow, just wasted days on this. What's the servicing plan for this? This breaks Azure Functions v2 out of the box with non-descript errors.

cc: @cgillum
