### ISSUE TITLE
Silent crash when asynchronously updating/quering Table Storage. WindowsAzure.Storage 9.3.2

### ISSUE THREAD

**Issue by oorobets** [Azure/azure-storage-net#811]
### Which service(blob, file, queue, table) does this issue concern?
Table storage

### Which version of the SDK was used?
WindowsAzure.Storage 9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.NetFramework 4.6,  .NET Core 2.1

### What problem was encountered?
execution of `await table.ExecuteAsync(operation);` causes silent crash

### How can we reproduce the problem in the simplest way?
Was following example from [Microsoft Docs](https://docs.microsoft.com/en-us/azure/visual-studio/vs-storage-aspnet5-getting-started-tables)
Create new Console project (.NetFramework 4.6 or .NET Core 2.1)

            CloudStorageAccount storageAccount = new CloudStorageAccount(new 
             Microsoft.WindowsAzure.Storage.Auth.StorageCredentials(
            "storageaccname", "key"), true);

            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            CloudTable table = tableClient.GetTableReference("test");
            table.CreateIfNotExists();
            CustomerEntity customer1 = new CustomerEntity("Harp", "Walter");
            customer1.Email = "Walter@contoso.com";
            customer1.PhoneNumber = "425-555-0101";

            // Create the TableOperation that inserts the customer entity.
            TableOperation insertOperation = TableOperation.Insert(customer1);

            // Execute the insert operation.
            await table.ExecuteAsync(insertOperation);

            System.Console.WriteLine("Done");
            System.Console.ReadKey();

Synchronous `Execute` method (which exists only for .NetFramework) works properly

**Comment by kfarmer-msft** [comment]
@oorobets : Are you using the emulator for this?

**Comment by oorobets** [comment]
@kfarmer-msft Nope. I was running this code against actual Table storage in Azure

**Comment by kilianovski** [comment]
@kfarmer-msft I am using emulator for similar thing, and it causes the same crash

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
