### ISSUE TITLE
Supported Client Side Encryption Before Upload

### ISSUE THREAD

**Issue by tsharp** [Azure/azure-storage-net#812]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.3.0 Storage + 3.0 KeyVault

### Which platform are you using? (ex: .NET Core 2.1)
.Net 4.6.2

### What problem was encountered?
BlobEncryptionData is not public which means I need to copy the EncryptionData & BlobEncryptionData classes into my project.

I would like to see these public, or just part of the blob object directly for cases when data is encrypted outside the AzureStorage client library but I would like to use the KeyVaylt + AzureStorage client library to decrypt the data when downloading.

The story looks like this:
1. Client side application retrieves public rsa key
2. Client side application creates key for file encryption
3. Nonce is generated per file
4. File is encrypted with generated key and nonce (using AES-256-CBC)
5. File is uploaded with wrapped key to api
6. Api uploads to Azure Storage (with encryption metadata)
7. Backend processing downloads decrypted blob using the supported AzureStorage client decryption.

### How can we reproduce the problem in the simplest way?
Look at the relevant classes.

### Have you found a mitigation/solution?
Yes, copying the classes and setting the encryptiondata metadata directly.

**Comment by seanmcc-msft** [comment]
Thanks for the suggestion, we will consider it for a future release.
