### ISSUE TITLE
Newtonsoft.Json v11.0.2

### ISSUE THREAD

**Issue by chrisparkeronline** [Azure/azure-storage-net#813]
Story: As a function user, I would like WindowsAzure.Storage nuget to use Newtonsoft.Json v11.0.2 so that it is inline with other used packages such as Microsoft.NET.Sdk.Functions, Microsoft.Azure.DocumentDB.Core, etc.

### Which service(blob, file, queue, table) does this issue concern?
All.

### Which version of the SDK was used?
9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.NET 4.6, want to upgrade my function to version 2.0 which uses .net core.

### What problem was encountered?
Can not upgrade all components of function from 1.0+ to 2.0 as new packages use Json v11.0.2 and latest package of WindowsAzure.Storage continues to use 9.0.1 which was released June 22, 2016.

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
Yes, continue to use older packages to ensure I can download document into a stream and pass to a parsing component. Extracted data is saved to Cosmos Db using older package version (1.9.1) to ensure it doesn't generate the dreaded Partition Key extract from document error.

**Comment by chrisparkeronline** [comment]
I do realize that I may be in a unique position with using WindowsAzure.Storage package in conjunction with Microsoft.Azure.DocumentDB.Core package inside an Azure Function. If there is a development reason this package is still using 2 year old Json.Net package, I totally understand.

**Comment by kfarmer-msft** [comment]
So there's been discussion on the question of taking higher dependences -- for various reasons related to coordinating with other projects that take dependencies on us, and the transitive dependencies arising from that, we cannot.

The dependencies on Newtonsoft.Json for WindowsAzure.Storage v 9.3.2 are for versions greater or equal to 10.0.2:  you should be able to take a dependency on v11.x, and things should resolve and build appropriately.  NuGet also includes platform fall-back if it cannot find a platform-specific version (as you'd note, NET Standard 2.x-specific versions for Newtonsoft.Json start at 11.x).
