### ISSUE TITLE
Continuation Token is returned for Table Query even after returning the requested number of rows

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-storage-net#814]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
NET Core 2.1

### What problem was encountered?
I have a table that has many rows. I create a Query which contains the Take() predicate. Even though the first result returns the required number of rows, the segmented result contains a continuation token, which suggests that there are more rows. I would not expect to get a continuation token once the requested number of rows have been returned.

### How can we reproduce the problem in the simplest way?
1. Create a table with more than 1 row in it.
2. Create a basic Table Query with Take set to 1.
3. Execute the query.
4. Observe that 1 row is correctly returned with the result set.
5. However, also observe that a continuation token is supplied.
6. If you execute the query with the continuation token, the same row is returned.
7. This pattern will repeat, forever.

Sample below is in F# but should be easy to understand and translate to C# if required.

```fsharp
open Microsoft.WindowsAzure.Storage.Table
open System

// assume you already have a handle to a cloud table 'table'
let query = TableQuery<DynamicTableEntity>().Take(Nullable 1)
let segment = table.ExecuteQuerySegmentedAsync(query, token) |> Async.AwaitTask |> Async.RunSynchronously
segment.Results.Count // returns 1
segment.ContinuationToken // not null!
```
### Have you found a mitigation/solution?
Manually track how many rows have been read. However, this is a suboptimal solution:
* The current behaviour of the SDK is not expected and can lead to confusion on the developer's part.
* It is now difficult to generically write around all the "segment" methods across queue / table / blobs (which all follow the same pattern).

**Comment by isaacabraham** [comment]
Ping

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
