### ISSUE TITLE
Azure Storage Emulator v5.8.0.0 doesn't support Stream upload without seek/length 

### ISSUE THREAD

**Issue by seweso** [Azure/azure-storage-net#816]
### Which service(blob, file, queue, table) does this issue concern?

Azure Storage Emulator v5.8.0.0

### Which version of the SDK was used?

WindowsAzure.Storage 9.3.2

### Which platform are you using? (ex: .NET Core 2.1)

NetCoreApp2.1

### What problem was encountered?

When using UploadFromStreamAsync with a stream which doesn't support seeking (and doesn't have a length) the following error is given by the simulator:

Microsoft.WindowsAzure.Storage.StorageException : Server encountered an internal error. Please try again after some time.

( I would solve it myself if the simulator was open sourced, which makes sense for a simulator btw ).

### How can we reproduce the problem in the simplest way?

    var blockBlob = container.GetBlockBlobReference(path);            
    stream = new WrappedReadonlyStream(new MemoryStream(some2kbFile));                
    await blockBlob.UploadFromStreamAsync(stream);

Where WrappedReadonlyStream looks like: 

    public class WrappedReadonlyStream : Stream
    {
        private readonly Stream _stream;

        public WrappedReadonlyStream(Stream stream)
        {
            _stream = stream;
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            return _stream.Read(buffer, offset, count);
        }
        
        public override void Flush()
        {
            throw new NotImplementedException();
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new NotImplementedException();
        }

        public override void SetLength(long value)
        {
            throw new NotImplementedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new NotImplementedException();
        }

        public override bool CanRead { get; } = true;
        public override bool CanSeek { get; } = false;
        public override bool CanWrite => throw new NotImplementedException();
        public override long Length => throw new NotImplementedException();

        public override long Position
        {
            get => throw new NotImplementedException();
            set => throw new NotImplementedException();
        }
    }

### Have you found a mitigation/solution?

Use a real azure blob storage. Then the same code just works. But means we can't use the simulator.

**Comment by seweso** [comment]
Just debugged the AzureStorageEmulator, it crashes with a:

AzureStorageEmulator.exe: 0xC0000005: Access violation reading location 0x0000000000000008.

Hmm...

**Comment by seweso** [comment]
> We recommend trying out Azurite.

Thanks, but that runs into  **PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state! TypeError: Cannot read property 'tableName' of undefined

Probably this issue: https://github.com/Azure/Azurite/issues/20

**Comment by ryancole** [comment]
> We recommend trying out Azurite.

@kfarmer-msft Wait. Microsoft recommends Azurite instead of their own Azure Storage Emulator? Is this true?

**Comment by pemari-msft** [comment]
We have been actively collaborating with Azurite and are making investments there. It was merely a suggestion for an alternative for the active issue.

**Comment by ryancole** [comment]
> We have been actively collaborating with Azurite and are making investments there. It was merely a suggestion for an alternative for the active issue.

@kfarmer-msft I see. I had never heard of Azurite before. Do you see Azurite becoming the recommended tool the job, or does the Storage Emulator have a future still?

**Comment by seweso** [comment]
I'd rather have one functioning simulator than two half functioning ones. Maybe that's just me.

**Comment by ryancole** [comment]
Azurite working great for me so far.

**Comment by kfarmer-msft** [comment]
The null ref in Emulator v5.8 should be corrected in v5.9, released yesterday.
