### ISSUE TITLE
when support .net standard and .net core for client side encryption (focus on BlobEncryptionPolicy) and use table without encryption

### ISSUE THREAD

**Issue by FrankPan1990** [Azure/azure-storage-net#817]
### Which service(blob, file, queue, table) does this issue concern?
Blob, Table

### Which version of the SDK was used?
9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
.Net core 2.0, .Net Standard 2.0

### What problem was encountered?
Hi team, 

I review all the package 9.3.2 and find only .net framework 4.5 and windows phone 8.0 can work with **BlobEncryptionPolicy**. For the others(.net standard 1.0, .net standard 1.3, .net core and window phone app 8.1), I cannot find it. I would like to create the .net core and .net standard on my project so would like to know when it can work with BlobEncryptionPolicy. 

Hence, could you let us know when the .net core and .net standard can work with client side encryption.

I know it is still in work and will appreciate if you can provide an ETA for that feature. 

Frank Pan v-frpan@microsoft.com

**Comment by FrankPan1990** [comment]
Hi Team,

I just find the package Microsoft.Azure.Storage.Blob 9.4 and believe the package contain the BlobEncryptionPolicy for the client side encryption working for the .net core and .net standard. Also, will check with other 9.4 package.

Frank Pan

**Comment by FrankPan1990** [comment]
Hi Team,

Find another problem that if we use the blob encryption policy in new package which only work for blob storage Microsoft.Azure.Storage.Blob 9.4 but it looks like we don't have a Microsoft.Azure.Storage.Table so cannot support at the same time. do you have any idea on it?

Frank Pan

**Comment by kfarmer-msft** [comment]
we no longer offer Table as of v9.4.0.  CosmosDB will be taking over Table support, but have not yet updated their library.

**Comment by kfarmer-msft** [comment]
I haven't heard any information about their release schedule in the meantime.  I'd recommend contacting them.
