### ISSUE TITLE
Please provide some examples of TableEntityAdapter

### ISSUE THREAD

**Issue by imeya** [Azure/azure-storage-net#819]
I don't know how to use the TableEntityAdapter, could you please provide some examples? like read, write etc. Thank you.

**Comment by ryanoshag** [comment]
I struggled with the lack of examples here as well, but was able to recently build out a basic Table Storage integration using `TableEntityAdapter`. Take a look [here](https://github.com/halforbit/data-stores/blob/master/TableStores/AzureTables/Halforbit.DataStores.TableStores.AzureTables/Implementation/AzureTableStore.cs) to see the implementation.

As a note, the `TableEntityAdapter` will only write out properties on your class if those properties have a setter - it can be either public or private, but caused me some initial headaches when trying to store some immutable POCOs.

Hopefully the Azure team will provide some usage examples for `TableEntityAdapter` soon, but I hope that this helps out a little in the meantime.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
