### ISSUE TITLE
Async Blob Copy : Failure Details

### ISSUE THREAD

**Issue by mayoatbm** [Azure/azure-storage-net#820]
### Which service(blob, file, queue, table) does this issue concern?
Blobs

### Which version of the SDK was used?
9.3.1

### Which platform are you using? (ex: .NET Core 2.1)
.Net Standard

### What problem was encountered?
One of our high volume use cases involves moving millions of blobs from one storage account to another. We do that using the StartCopyAsync method passing a SAS uri. 

Sometimes these blob copies fail in Azure. The destination blob is left at 0 bytes and the copy status is "failed". How do we troubleshoot the cause of the failure? We don't see any more information in the blob properties (progress was 0/size). 

Btw: Are there plans to improve the current reporting for blob copies? It's all well and good to poll for progress when copying a few blobs but it's not feasible to do that for millions of blobs. The storage service should at least be able to show some high level numbers (pending, success, failed etc) in the portal or explorer. I'm happy to send across our storage account name if that helps.

### How can we reproduce the problem in the simplest way?
Not sure since we don't know why the copies failed. 

### Have you found a mitigation/solution?
No. The copy status in the portal is blank (-). The copy status in the storage explorer says "failed" but there's no description .

**Comment by mayoatbm** [comment]
Some progress. Using the SDK to get the blob reference from the server does return the status description (not sure why the explorer and portal don't show this). The description on the ones i've checked has been: 412 PreconditionFailed "Copy failed when reading the source." 

The source blob appears to be there so we're back to the original question: what caused the copy to fail?Is there any other way to figure out what caused the error?

**Comment by kfarmer-msft** [comment]
Greetings, @mayoatbm --

Sorry for the delay.

I passed this by one of our server leads, and in their opinion the issue is almost certainly that the data is being edited during the time of the copy.  Stopping all writes to the source, or taking a snapshot of the source first and copying the snapshot would be approaches to removing that as a potential problem.

If you wanted more specific insight, you can email your account name to ascl@microsoft.com, and reference this issue.
