### ISSUE TITLE
Azure Storage Emulator needs multi-arch Docker Images

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-storage-net#822]
The [Azure Emulator Docker Image](https://hub.docker.com/r/microsoft/azure-storage-emulator/) only works under Windows Containers.

Would be _really really really really really really really really_ helpful if this could run under linux containers also. 

I understand that the Emulator repo isn't this/it's private/etc ... so hopefully this issue can get copied over to that repo please or some public information about this, posted in here.

![](https://media.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

**Comment by kfarmer-msft** [comment]
Forwarded internally.  The docker images aren't produced by this team, and it's not a public repo.

Good choice of GIF :)

**Comment by Ashtonian** [comment]
https://github.com/Azure/Azurite

**Comment by onionhammer** [comment]
@Ashtonian doesn't support tables (except in its legacy version)
