### ISSUE TITLE
Azure storage emulator container with persistent volumes

### ISSUE THREAD

**Issue by GersonDias** [Azure/azure-storage-net#823]
Is that possible to configure the container to use a volume so I'll not lose my data if I stop the container?

I've tried to run something like 
```
docker run -d -p 10000-10002:10000-10002 -v storageemulator:C:\Users\ContainerAdministrator\AppData\Local\ microsoft/azure-storage-emulator
```
but I can't because some permission related issue and then I changed the azurestorageemulator config file to point to another folder that I was able to mount, something like

```
docker run -p 10000-10002:10000-10002 -d -v storageemulator:C:\storageemulator_data
```

which works (I was able to see the folder structure on host machine) but my data (blobs) was not persisted after I stop and run the container again. Of course should be related to the sql data... so my question is, there is a way to do that?

**Comment by kfarmer-msft** [comment]
I'd love to be able to help you, but our team doesn't produce or support Docker containers.

You might find answers at the [MSDN forums](https://social.msdn.microsoft.com/Forums/azure/en-US/home?category=windowsazureplatform&forum=windowsazuredevelopment%2Cwindowsazuredata%2Cssdsgetstarted%2Cwindowsazuremanagement%2Cwindowsazurepurchasing%2Cservbus%2CWindowsAzureAD%2Cwindowsazureactiveauthentication%2CMediaServices%2CWAVirtualMachinesVirtualNetwork%2CWAVirtualMachinesforWindows%2Cwindowsazurepack%2Cwindowsazurewebsitespreview%2Cazuremobile%2Chypervrecovmgr%2Cwindowsazureonlinebackup%2Chdinsight%2Cazureautomation%2Cazuresearch%2CDataMarket%2Cazurecache%2Cazurescheduler%2Cazureapimgmt%2Cazurescripting%2Cnotificationhubs%2Cazurecdn%2CAzureDataFactory%2CAzureKeyVault%2CAzureStreamAnalytics%2Cazurebatch%2Copinsights%2CMachineLearning%2CStorSimple%2CAzureAPIApps%2Cazurelogicapps%2CAzureServiceFabric%2CLUIS%2CAzureSQLDataWarehouse%2Cazuredatacatalog%2CAzureSecurityCenter%2CAzureDevTestLabs%2Cazureiothub%2CAzureDiskEncryption%2CAzureStack%2CAzureFunctions%2CAzureDataLake%2CAzureAnalysisServices%2Cazureblockchain%2CAzureLogIntegration%2CAzureDatabaseforPostgreSQL%2CAzureDatabaseforMySQL%2CAzureTimeSeriesInsights%2CCloudyn%2Cazureddosprotection%2CAzureAvailabilityZones%2CAzureMigrate%2Ciotedge%2Cazurelbs%2Cazurecosmosdb%2CMoveTest%2CApplicationInsights%2Cazuresphere%2CAzureKusto%2CAzureDatabaseforMariaDB%2CAzureCognitiveService%2CAzureCostManagement%2Cazuredigitaltwins%2CAzureMachineLearningService%2CAzureContainerServices&filter=alltypes&sort=relevancedesc&brandIgnore=True&filter=alltypes&searchTerm=docker):

**Comment by tonypolik** [comment]
Sorry if I post here after so much time.
@GersonDias did you find a way to run the container without losing data?
