### ISSUE TITLE
Azure Storage - Slows down as parallel requests increase

### ISSUE THREAD

**Issue by grik001** [Azure/azure-storage-net#824]
Hi,

I have an implementation where I am querying across different partitions on multiple threads. So each thread is targeting as single partition and querying all the data by PartitionKey.

What I do not understand is why it sometimes takes seconds to complete a single retrieve. I have tried using either a single StorageClient or have 5-10 static clients and selecting them in round-robin, but both methods did not improve performance.

Thanks!

**Comment by seanmcc-msft** [comment]
Which Storage Service are you using?

**Comment by grik001** [comment]
Thanks for your reply @seanmcc-msft 

I am querying **Tables** on Azure Web Storage from **Azure Functions V1**. Using Assembly **Microsoft.WindowsAzure.Storage, Version=9.1.1.0**

Account kind: StorageV2
Performance: Standard
Access tier: Hot

Thanks!

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

**Comment by grik001** [comment]
@seanmcc-msft Hi Sean can you pls explain further, do I need to open this ticket on another GIT?
