### ISSUE TITLE
Tables support

### ISSUE THREAD

**Issue by michaelkruglos** [Azure/azure-storage-net#825]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
9.4.0

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.1

### What problem was encountered?
The readme says "As of 9.4.0, Tables are not supported by this library.", it doesn't mention where I can find support for tables.

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
NO

**Comment by kfarmer-msft** [comment]
We recommend staying on 9.3.x for Table support at the present.
