### ISSUE TITLE
9.3.x sourcecode

### ISSUE THREAD

**Issue by Vhab** [Azure/azure-storage-net#826]
Is there any way to obtain the latest 9.3.x source code?
In particular there's a recent new release (9.3.3) without change log and to my knowledge no public source code available.

I understand the deprecation path, but the complete removal of the older version's source code is rather impractical for us who still depend on table support.

**Comment by kfarmer-msft** [comment]
9.3.3 was purely a NuGet docs change.  The binaries weren't changed.

**Comment by ManfredLange** [comment]
> 9.3.3 was purely a NuGet docs change. The binaries weren't changed.

Still should have received a proper tag in this repo.
