### ISSUE TITLE
Nuget spec files reference .net 4.5 instead of .net 4.5.2

### ISSUE THREAD

**Issue by mj1856** [Azure/azure-storage-net#829]
Though the project readme now states that 4.5.2 is the minimum .NET Framework version supported, the nuspec files reference .NET Framework 4.5.  This is problematic for a few reasons:

- On Nuget.org, and in Visual Studio's Nuget window, .NET 4.5 looks like a valid target.

![image](https://user-images.githubusercontent.com/1396388/49465646-f3b89600-f7b2-11e8-8ea3-039585e1261c.png)

- Visual studio will allow the package to be installed in a .NET 4.5 project, though it should reject it as no valid targets.

- Since there are no binaries for net45 or net451 in the package, then no assemblies are referenced when installed.  However, tools like ReSharper will still suggest referencing the ones in the net452 folder, which could create a problem at runtime.

Please update the nuspec files from `<group targetFramework=".NETFramework4.5">` to ` <group targetFramework=".NETFramework4.5.2">`

Thanks.

**Comment by seanmcc-msft** [comment]
Fixed in version 10.0.3.

Commit: https://github.com/Azure/azure-storage-net/commit/42ef139953c13da74dee8329d932cde3d035c79a
