### ISSUE TITLE
Azure Storage Emulator 5.8 is failing on PutBlockList/PutBlockListAsync

### ISSUE THREAD

**Issue by plillevold** [Azure/azure-storage-net#831]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Azure Storage .NET Client (Microsoft.Azure.Storage.Blob) 9.4.1

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.6.2

### What problem was encountered?
PutBlockList/PutBlockListAsync calls are failing consistently with "internal server error" and NullReferenceExceptions in the logs.

### How can we reproduce the problem in the simplest way?
The following code demonstrate uploading two blocks to a block blob, and then committing the blob using PutBlockList. Run it and observe that PutBlockList fails with Emulator 5.8. The exact same code running towards Azurite or real storage accounts works as expected.

            var client = CloudStorageAccount.DevelopmentStorageAccount.CreateCloudBlobClient();

            const int BlockSize = 64;
            var blockIds = new [] {"MDAwMDAx", "MDAwMDAy"};

            var data = blockIds
                .Select(blockId => new { blockId, data = Enumerable.Range(0, BlockSize).Select(i => (byte)i).ToArray() })
                .ToList();

            var container = _client.GetContainerReference("storageclienttest");
            await container.CreateIfNotExistsAsync();
            var blob = container.GetBlockBlobReference("PutBlockListAsyncTest.bin");
            await blob.DeleteIfExistsAsync();

            foreach (var d in data)
            {
                using (var stream = new MemoryStream(d.data))
                {
                    await blob.PutBlockAsync(d.blockId, stream, null);
                }
            }

            await blob.PutBlockListAsync(blockIds);

### Have you found a mitigation/solution?
Revert to older version of Azure Storage Emulator or use Azurite.

**Comment by plillevold** [comment]
Actually, falling back to Azurite was not an optimal mitigation since it currently (v2.7.0) does not support some operations involving SAS keys and read/write permission checks. For example, given a SAS url granting "write" permission to a specific blob will, in Azure Storage Emulator and production accounts, cause an exception if the SAS is used to list the contents of a container. Azurite 2.7.0 does not conform to this behavior.

**Comment by kfarmer-msft** [comment]
Greetings, @plillevold --

v5.9 was released yesterday, which should address the issue you report.
