### ISSUE TITLE
Support new Span<T> and Memory<T> types

### ISSUE THREAD

**Issue by alastairs** [Azure/azure-storage-net#836]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.4.2

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.2, but I believe this will affect more target platforms than just this most recent one.

### What problem was encountered?
I'd like to be able to use `Span<T>` and/or `Memory<T>` in my calls to the Azure blob storage client, but currently the APIs still only support `byte[]` and `Stream`. This is more of a problem in the upload scenario, where a `Memory<byte>` needs to be converted to a `byte[]` before upload, resulting in an unwanted heap allocation.

### How can we reproduce the problem in the simplest way?
N/A? This is an API issue, rather than a runtime functionality issue.

### Have you found a mitigation/solution?
There is a workaround possible via the `Stream`-based methods, e.g.:

```csharp
await blob.FetchAttributesAsync();
var buffer = new Memory<byte>(new byte[blob.Properties.Length]);
using (var memoryStream = new MemoryStream())
{
    await blob.DownloadToStreamAsync(memoryStream);
    await memoryStream.ReadAsync(buffer);
    return new Blob(buffer);
}
```

but this feels quite roundabout.

**Comment by kfarmer-msft** [comment]
It should be possible to get convert Memory<T> to T[] without an allocation, using MemoryMarshal.TryGetArray.  This is, of course, a Try* method, so there's a failure-to-get scenario that would need to be understood.

See Figure 1 here, following the chain Memory<T> -> ArraySegment<T> -> T[]: https://msdn.microsoft.com/en-us/magazine/mt814808.aspx.

We won't be introducing more interesting use of Memory and Span until later (eg, I'm experimenting with, for example, using ReadOnlyMemoryContent in our HttpClient requests).  It's high on my personal list of Interesting Platform Features, but we're constrained to NET Standard 2.0.
