### ISSUE TITLE
Please follow SemVer and solve Issue #834

### ISSUE THREAD

**Issue by WernerMairl** [Azure/azure-storage-net#837]
Assuming that Microsoft/Azure/NuGet is following the basic principles of SemVer 2.0 i must suggest to solve #834 ASAP in some way (rollback, improve...)

It should not be acceptable that a patch (9.4.1 => 9.4.2) is causing new and unexpected compiler warnings.

In a (professional) build pipeline a warning is causing a full stop and some workarounds must be implemented......
 
>The warning should be ignorable:  It was opened to maximize the range of other SDKs that depend on >us to be able to take more interesting dependencies on KeyVault than we do (we only care about IKey >and IKeyResolver).

_Originally posted by @kfarmer-msft in https://github.com/Azure/azure-storage-net/issues/834#issuecomment-448353443_

SemVer 2.0:
>Given a version number MAJOR.MINOR.PATCH, increment the:
>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards-compatible manner, and
>PATCH version when you make **backwards-compatible bug fixes**.

regards
Werner

**Comment by karoberts** [comment]
I also have this issue.  I got around the warning my installing Microsoft.Azure.KeyVault.Core 3.0.1 in my project.  

While this does clear the warning, it isn't ideal because now I am somewhat responsible for a dependency of a dependency.

**Comment by kfarmer-msft** [comment]
The hyperbole is unnecessary.

Various projects around Azure have been re-aligning each others' dependencies -- the solution for this project was to relax our dependency on KeyVault, to allow other teams more leeway.

**Comment by Leon99** [comment]
@kfarmer-msft Any comments on possibilities to make that re-aligning trouble-free for your users, as per suggestions in https://github.com/Azure/azure-storage-net/issues/834?
