### ISSUE TITLE
Deletion problem : This request is not authorized to perform this operation using this permission

### ISSUE THREAD

**Issue by axninfo** [Azure/azure-storage-net#838]
### Which service(blob, file, queue, table) does this issue concern?
Blob containers via SAS

### Which version of the SDK was used?
1.6.0

### Which platform are you using? (ex: .NET Core 2.1)
Platform: Windows
Architecture: ia32
Build Number: 20181204.3
Commit: 6ae5640a
Support Id: fab874d9-87dc-7996-ec13-8ac189556852

### What problem was encountered?
When I delete a PST file uploded via SAS key, I obtain a permission denied error : 

{
  "name": "StorageError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:0f17cf22-b01e-005c-3085-a2c584000000\nTime:2019-01-02T10:27:40.8241916Z",
  "stack": "StorageError: This request is not authorized to perform this operation using this permission.\nRequestId:0f17cf22-b01e-005c-3085-a2c584000000\nTime:2019-01-02T10:27:40.8241916Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "requestId": "0f17cf22-b01e-005c-3085-a2c584000000"
}

### How can we reproduce the problem in the simplest way?
Simply delete a PST file via Azure Storage Explorer

### Have you found a mitigation/solution?
No

**Comment by kfarmer-msft** [comment]
Azure Storage Explorer is another team altogether.  I believe you'll find their repo at https://github.com/Microsoft/AzureStorageExplorer/issues.
