### ISSUE TITLE
Cannot reference block blobs with blank space in filename

### ISSUE THREAD

**Issue by VladimirSorokoumov** [Azure/azure-storage-net#839]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
9.3.1

### Which platform are you using? (ex: .NET Core 2.1)
.NET-Standard 2.0

### What problem was encountered?
I am using Azure SDK for .Net for working with Azure Blob storage, and having troubles with referencing block blobs which have blank space in the blob name.

I have uploaded a block blob JSON Test.json into a private container via Azure Storage Explorer 1.6.1.
Here are the blob properties as per Azure Storage Explorer:

```
Name: JSON Test.json
URI: https://<myaccountname>/<mycontainername>/JSON%20Test.json
```

So far so good, blob name shown correctly, blank space in the URI is encoded.

Now, I am trying to check whether that Blob exists with ExistsAsync(), passing to GetBlockBlobReference non-encoded filename JSON Test.json

```
public async Task<bool> CheckExistsAsync(string connectionString,
string containerName, 
string fileName)

{
var blockBlob = GetBlockBlobReference(connectionString, containerName, fileName);
return await blockBlob.ExistsAsync();
}
```

```
private static CloudBlockBlob GetBlockBlobReference(string connectionString,
string containerName, 
string fileName)

{
return CloudStorageAccount
.Parse(connectionString)
.CreateCloudBlobClient()
.GetContainerReference(containerName)
.GetBlockBlobReference(fileName);
}
```

And getting FALSE as result.

Now, I am creating a blob programatically in a different container, passing the same filename non-encoded JSON Test.json, using the same GetBlockBlobReference and getting created a blob with encoded filename.

```
Name: JSON%20Test.json 

URI: https://<myaccountname>/<mycontainername2>/JSON%20Test.json
```

What I am doing wrong? Why my block blob with blank space in its name created via Azure Storage Explorer is not found while referencing it with non-encoded filename? When creating a block blob programatically a passing non-encoded filename, why the filename gets encoded via the wire?

Please help.

Thanks a lot in advance!

**Comment by seanmcc-msft** [comment]
Hi,

I attempted to reproduce using your provided code sample, and am getting true as a result.  The Blob name is being url and decoded correctly.

-Sean
