### ISSUE TITLE
Properties property is still not virtual on CloudFile

### ISSUE THREAD

**Issue by LevioConseils** [Azure/azure-storage-net#841]
Hello team!

I saw on https://github.com/Azure/azure-storage-net/issues/465 that it was planned to make the Properties property on the CloudFile class virtual so that we could mock it (the same as for Name property).  But in the latest version of the project (now Microsoft.Azure.Storage.File version 9.4.2), it's not done yet.  Do you still have plans regarding this issue?

We're using .NET Standard 2.0

Thanks!

**Comment by seanmcc-msft** [comment]
Fixed in version 10.0.3.

Commit: https://github.com/Azure/azure-storage-net/commit/eff40aa0ea1ba69c80ce0dc30539586a44b44731
