### ISSUE TITLE
'CloudTable' does not contain a definition for 'CreateQuery' and no accessible extension method 'CreateQuery' accepting a first argument of type 'CloudTable' could be found 

### ISSUE THREAD

**Issue by alexgman** [Azure/azure-storage-net#846]
### Which service(blob, file, queue, table) does this issue concern?
Table Storage using Storage V2.

### Which platform are you using? (ex: .NET Core 2.1)
![image](https://user-images.githubusercontent.com/4227695/51698185-320e4c80-1fcf-11e9-8c75-8ac0e170cca3.png)

### What problem was encountered?

![image](https://user-images.githubusercontent.com/4227695/51698451-dc866f80-1fcf-11e9-95c8-1e708e081e0d.png)

### How can we reproduce the problem in the simplest way?

1. Create a new azure function app project, core 2.1
2. Try to query table storage using the method below:
```

    public static class TableService
    {
        public static IEnumerable<DocumentMetaDataEntity> Get(string connectionString, string cacheName, DeconstructedFileName deconstructedFileName, FileMetaDataFilters filters)
        {
            var acc = CloudStorageAccount.Parse(connectionString);
            var tableClient = acc.CreateCloudTableClient();
            var table = tableClient.GetTableReference(cacheName);

            var translations = from entity in table.CreateQuery<DocumentMetaDataEntity>()
                               where (entity.sourceParty == sourceParty.ToLowerTrim()
                                           && entity.destinationParty == destinationParty.ToLowerTrim())
                                     || (entity.sourceParty == wildcardSourceParty
                                           && entity.destinationParty == destinationParty.ToLowerTrim())
                               select entity;

            return translations.Where(x => x.expireAt > DateTime.Now)
                               .Where(x => x.effectiveAt < DateTime.Now);
        }
    }
```
You will get a dev-time exception:

> 
'CloudTable' does not contain a definition for 'CreateQuery' and no accessible extension method 'CreateQuery' accepting a first argument of type 'CloudTable' could be found (are you missing a using directive or an assembly reference?)

**Comment by kfarmer-msft** [comment]
Hi, @alexgman --

This project isn't part of Azure Functions.  I've sent an email internally to determine who can assist you.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
