### ISSUE TITLE
TokenCredential doesn't allow for token expiry

### ISSUE THREAD

**Issue by pramin** [Azure/azure-storage-net#848]
### Which service(blob, file, queue, table) does this issue concern?
ALL

### Which version of the SDK was used?
ALL

### Which platform are you using? (ex: .NET Core 2.1)
ALL

### What problem was encountered?
Invalid token after token expires, but before the refresh timer.

### How can we reproduce the problem in the simplest way?
- Get an AAD token
- Let it expire
- Try to use a storage account API via AAD. It will fail

### Have you found a mitigation/solution?
No mitigation. Solution, add the below code to TokenCredential (removing scope if you will never use it), and replace references to TokenCredential.Token with calls to GetTokenAsync(). NOTE: The only non-async references are in tests.

```
namespace Microsoft.WindowsAzure.Storage.Auth
{
    partial class TokenCredential
    {
        private readonly AuthenticationCallbackAsync authenticationCallbackAsync;

        /// <summary>
        /// Create an instance of <see cref="TokenCredential"/>.
        /// </summary>
        /// <param name="authenticationCallbackAsync">Delegate responsible for retrieving the current token credential.</param>
        public TokenCredential(AuthenticationCallbackAsync authenticationCallbackAsync)
        {
            this.authenticationCallbackAsync = authenticationCallbackAsync;
        }

        /// <summary>
        /// Asynchronously gets the current authentication credential.
        /// </summary>
        /// <returns> access token </returns>
        public Task<string> GetTokenAsync()
        {
            // Return the set token if there is no callback function
            if (this.authenticationCallbackAsync == null)
            {
                return Task.FromResult(this.Token);
            }

            // TODO: This should probably not be a constant
            return this.authenticationCallbackAsync("https://storage.azure.com/", null);
        }
    }
}
```

**Comment by seanmcc-msft** [comment]
Was the initial TimeSpan you passed in when creating your TokenCredential less than the expiry of your token?
