### ISSUE TITLE
Potential Thread Pool starvation of entire app during ListBlobs() (sync) method

### ISSUE THREAD

**Issue by Plasma** [Azure/azure-storage-net#852]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.3.1

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.5.1

### What problem was encountered?
We noticed that when we had a few tasks running on a machine that called ```container.ListBlobs(flatten: true)```, and when that container had millions of blobs, other Task callbacks (eg being processed by the thread pool), unrelated to storage SDK, can deadlock/freeze for up to 20 minutes.

We then replaced the ListBlobs() method with a loop using the async ListBlobSegmentsAsync() method and the problem vanished.

It seems as if the Azure Storage SDK, when processing at least the ListBlobs method for a large result set, can cause the entire app thread pool to come to a stall, preventing unrelated Task callbacks from firing or thread pool threads from processing work.

### How can we reproduce the problem in the simplest way?
Try calling ```container.ListBlobs(flatten: true)``` a few times on a container that has millions of blobs (so that it takes several min at least to return a result), and have a few other Tasks's running in a loop (eg await Task.Delay with console logs, or something).

I suspect you will see the console logs stop working until potentially ListBlobs() returns after 20 minutes.

### Have you found a mitigation/solution?
Yes, use the async ListBlobSegmentsAsync method, but, this issue is wanting to expose a potential issue with the implementation of tasks/threading in the storage SDK.

**Comment by kfarmer-msft** [comment]
The segmented APIs are the recommendation, not merely a mitigation.  Porting it to use the segmented forms is a non-trivial exercise I've had to look into elsewhere.  I'll add this class of APIs to our backlog for porting to a streaming result making multiple segmented calls, but ultimately uisng the segmented API is absolutely the way to go, and a recommendation I recently made to other teams.

**Comment by seanmcc-msft** [comment]
We've added this issue to our backlog.

**Comment by Plasma** [comment]
Hi team,

Agree 100% the async APIs are best, we happily moved to them. I wanted to bring it to your attention because I've seen a few other issues on GitHub here about weird stalls / performance drops and noticed this was a root cause for something of ours.

Not sure if it is relevant, but our default operation timeout was also very high (30 minutes) that may have contributed to this problem too.

Thank you
