### ISSUE TITLE
Access is denied - Error: Unable to start the storage emulator.

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-storage-net#854]
### Which service(blob, file, queue, table) does this issue concern?
The Azure Storage Emulator

### Which version of the SDK was used?
5.7

### Which platform are you using? (ex: .NET Core 2.1)
.net 472

### What problem was encountered?

Upon starting the debugging for a new Azure Function (no code added, just selected as startup project and F5)
![image](https://user-images.githubusercontent.com/15381181/52654682-83b84180-2ec0-11e9-9061-3d5e43e7c291.png)

When I tried to set the program shortcut to run as administrator, I could not. 
![image](https://user-images.githubusercontent.com/15381181/52654726-a0ed1000-2ec0-11e9-86e5-2ce6c70134c2.png)

When I try running the program from cmd.exe I get the error in the issue title. 
![image](https://user-images.githubusercontent.com/15381181/52654630-65524600-2ec0-11e9-8846-599224a013d2.png)

If i start cmd.exe as administrator and `cd` to that path (again) and run the command, it appears to start
![image](https://user-images.githubusercontent.com/15381181/52654976-296bb080-2ec1-11e9-8558-60ce4eea86e3.png)

I'm not interested in having to do a rain dance just to F5 debug a function. Can the storage emulator either run and install as a service, or be able to run as a non-admin user for the purposes of debugging in VS?

**Comment by kfarmer-msft** [comment]
The emulator has not been tested on 4.7.2.  That aside, historically, there have been a few hard-to-reproduce, idiosyncratic install issues related to accounts and how they impact being able to connect to the MS SQL Local DB instance.  With that in mind, I would suggest checking to see if Azurite will satisfy your needs: https://github.com/azure/azurite.

**Comment by StingyJack** [comment]
@kfarmer-msft  - Thanks, Do you know if azurite can be managed by VS for a debug session, or installed as a service?  I haven't had much luck in the past trying to run nodejs programs as windows services.

**Comment by kfarmer-msft** [comment]
I haven't tried -- my focus on client SDKs means I target the servers, not an emulator.  However, the NuGet package apparently provides a standalone executable, which should improve the situation over the old emulator.

**Comment by StingyJack** [comment]
It works pretty good, definitely less greif giving than the full emu. Thanks f
