### ISSUE TITLE
Hight CPU Usage on Downloading Blob

### ISSUE THREAD

**Issue by binkum** [Azure/azure-storage-net#857]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
8.6.0

### Which platform are you using? (ex: .NET Core 2.1)
.Net Core 1.0

### What problem was encountered?
Stimulate High CPU usage on downloading the files from blob using CloudBlockBlob.DownloadRangeToByteArray method under high concurrent requests.

### How can we reproduce the problem in the simplest way?
application stimulating downloads from the blob using the method DownloadRangeToByteArray with high concurrency.

### Have you found a mitigation/solution?
No

**Comment by seanmcc-msft** [comment]
Please try to reproduce on the latest version (9.4.2).
