### ISSUE TITLE
Issues with Cross-Framework Compatibility

### ISSUE THREAD

**Issue by robertmclaws** [Azure/azure-storage-net#863]
I'm getting the following error from running the Azure WebJobs 3.0 SDK in a .NET Framework console app:
```
      Warning: Only got partial types from assembly: Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
      The following loader failures occured when trying to load the assembly:
         - Method 'Commit' in type 'Microsoft.Azure.WebJobs.Host.Blobs.Bindings.DelegatingCloudBlobStream' from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
         - Method 'Commit' in type 'Microsoft.Azure.WebJobs.Host.Blobs.Bindings.DelegatingCloudBlobStream' from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
         - Method 'Commit' in type 'Microsoft.Azure.WebJobs.Host.Blobs.Bindings.DelegatingCloudBlobStream' from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
         - Method 'Commit' in type 'Microsoft.Azure.WebJobs.Host.Blobs.Bindings.DelegatingCloudBlobStream' from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
         - Could not load type 'Microsoft.WindowsAzure.Storage.Table.TableQuerySegment' from assembly 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
      This can occur if the assemblies listed above are missing, outdated or mismatched.
      Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
         at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
         at System.Reflection.Assembly.GetTypes()
         at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 115
```
I believe this is happening because of the method used to ensure support for older versions of .NET. The easiest way to do it is to leverage a single SDK-style project per Library, specify multiple TargetFrameworks for the project, and then use Conditional Compilation Constants to change the behavior based on the TargetFramework. But that is not how this SDK has been implemented, and it is causing issues with how the packages are built.

I would suggest modernizing the project setup to make managing the codebase as simple as possible, and utilizing the .NET Core CLI for build and NuGet packaging.

**Comment by kfarmer-msft** [comment]
I agree (and I've played around with this feature for my own projects at home -- I really like the new project style).  But the changes go too deep and depend on subtly different execution engines to make a confident release.  I think a different approach would be needed.

**Comment by robertmclaws** [comment]
I know very little about this particular library's engine architecture... but I have been doing a bunch of work with the WebJobs SDK lately, and was pretty amazed that the same project and binary can execute on both .NET Core and the .NET Framework.

So the question is, if you could upgrade the engine to ONLY support .NET Standard 2.0... would the engines REALLY _need_ to be that different? I feel like there would be a way to get it done for a Version 10 release that would satisfy all the requirements... and people would still have Version 9 of the library available if they needed older support.

**Comment by kfarmer-msft** [comment]
This library has a mandate (currently) to support NS 2.0, desktop 4.6.1, and NS 1.x.  That NS 1.x support is the source of differences.  Unfortunately, some things aren't actually in both platforms, and that's lead to divergence in implementation.

I would sincerely like to drop NS 1.x (and, further, I'd really like to go pure NS 2.1+, with all the really nice goodies coming in NET Core 3) but our ability to do that is highly dependent on buy-in from the customers, and coordination with various other projects that depend on us.

**Comment by nicholastic** [comment]
I'm also getting this error, I asked a question about it here: https://stackoverflow.com/questions/57281474/warning-only-got-partial-types-from-assembly-microsoft-azure-webjobs-extension

1) Is there a fix?

2) More importantly, will it cause anything to malfunction? Does it affect functionality in any way? Someone said no, but it would be good to have this confirmed.
