### ISSUE TITLE
CloudBlob.UploadText/UploadTextAsync loads for ever.

### ISSUE THREAD

**Issue by v-ishnmu** [Azure/azure-storage-net#864]
### Issues is with ?
> Issue is with Blobs. 

### Dot Net SDK used 

> Version=9.4.2.0

### Which platform are you using? (ex: .NET Core 2.1)
> .NET Standard 4.6.1

### What problem was encountered?
> I tried to upload a json file to blobs. On my local machine it works without any issues. But on deployment, it works who ever access it first and it keeps working for them without any issues. But if the other user trues to invoke that service it keeps loading for ever and crashes.

### How can we reproduce the problem in the simplest way?
>  invoke a service with a method **CloudBlob.UploadText(string)** and tries to access the service from multiple machines /  users

### Have you found a mitigation/solution?
> Nope :(

### My Code Snippet

```
using Newtonsoft.Json;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

public static void UploadFileToBlob(object value)
{
  CloudStorageAccount storageAccount = CloudStorageAccount.Parse(blobConnectionString);
  var client = storageAccount.CreateCloudBlobClient();
  CloudBlobContainer container = client.GetContainerReference(BlobContainer);
  CloudBlockBlob cblob = container.GetBlockBlobReference(fileName);
  cblob.UploadText(JsonConvert.SerializeObject(value))
}
```

**Comment by imshanmusanjay** [comment]
Hi @EmmaZhu , 

Could you please help me on this issue ?

**Comment by kfarmer-msft** [comment]
There is nothing in the code you show that would obviously lead to the behavior you're seeing, particularly since you say it works and continues to work for the first person to call it in your production deployment.  That's not a behavior I'd expect in any class of bug the SDK could exhibit -- async deadlocks would not care about the caller, for example.  I suspect the issue is at a higher level than this method.

Can you please describe what environment you're in?  Is this ASP.NET, or a console app, or something else?

Do you have a stack trace?  Fiddler logs?

**Comment by v-ishnmu** [comment]
Hi @kfarmer-msft ,

Thanks for the response, the environment is .Net Web API (REST Service). 

> I suspect the issue is at a higher level than this method.
But on Commenting this snippets and if I try I works Perfect. Anyway will get you a trace or somehting so that you can dig this deeper.


Thanks,
Shanmu

**Comment by v-ishnmu** [comment]
Hey @kfarmer-msft ,

I have got you a Fiddler Archive for that particular request that i make. Even this request hangs and crashes. 
Please find the below attached archive for more.
[BlobHangIssue.zip](https://github.com/Azure/azure-storage-net/files/2991886/BlobHangIssue.zip)

Please help me fix this ASAP, I'm blocked
Thanks in advance.

**Comment by kfarmer-msft** [comment]
Sorry, but there's nothing in that archive that shows any activity beyond the existance of an encrypted connection.

You say the process crashes in your production environment.  Have you attempted to debug into the production process?  Have you any stack traces?  Exception messages that might be getting swallowed?  Without this, I'm not going to be able to help you track down where the issue actually is.

Your code snippet isn't really anything that is going to help narrow things down here -- it's no different from any test method we already have.  What is going to be different is how it's called (eg, how you use it via DMLib), and different environments can do different things that neither you nor I nor DMLib would necessarily think about:  that's the sort of thing that leads to being unable to reproduce it locally.
