### ISSUE TITLE
Filtering in TableQuery is not worked as expected

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-storage-net#869]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
"WindowsAzure.Storage" Version="9.3.3"

### Which platform are you using? (ex: .NET Core 2.1)
WPF

### What problem was encountered?
Filter is not working

### How can we reproduce the problem in the simplest way?
I do like this:
``` cs
await _table.CreateIfNotExistsAsync();
var filter = TableQuery.CombineFilters(
                TableQuery.GenerateFilterConditionForDate(nameof(DynamicTableEntity.Timestamp), QueryComparisons.GreaterThanOrEqual, start),
                TableOperators.And,
                TableQuery.GenerateFilterConditionForDate(nameof(DynamicTableEntity.Timestamp), QueryComparisons.LessThanOrEqual, end)
            );

var q = table.CreateQuery<DynamicTableEntity>();
q.FilterString = filter;
q.TakeCount = 100;
segment = await q.ExecuteSegmentedAsync(segment?.ContinuationToken);
```
but as a result I get 1000 entries. and so all the data from the table comes.
It turns out that the parameters 
"q.FilterString = filter" and "q.TakeCount = 100;" ignored.

**Comment by KSemenenko** [comment]
And I get cyclical. the data goes in a circle.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)

**Comment by KSemenenko** [comment]
What a twist. Thanks for this information.
