### ISSUE TITLE
No messages written to TraceListener in .NET Core 2.x app

### ISSUE THREAD

**Issue by alastairs** [Azure/azure-storage-net#870]
### Which service(blob, file, queue, table) does this issue concern?
Blob.

### Which version of the SDK was used?
9.4.2.

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.2

### What problem was encountered?
I am trying to write the internal SDK operations to Serilog, using the System.Diagnostics.Trace support in the SDK and the [Serilog TraceListener library](https://github.com/serilog-trace-listener/SerilogTraceListener). I have verified that the TraceListener is working correctly, but no messages are written to it from the SDK. [This comment](https://github.com/Azure/azure-storage-net/blob/8c426573fda5c0caa6704a2d0f9af0acef0e7b9f/Test/ClassLibraryCommon/Core/LoggingTests.cs#L44) suggests that the app.config configuration approach of the trace switch and listener are not supported in .NET Core 2.0, although this is the [only documented approach](https://docs.microsoft.com/en-us/rest/api/storageservices/Client-side-Logging-with-the-.NET-Storage-Client-Library). I have tried fudging this with API calls as follows:

```csharp
public static IServiceCollection AddBlobStorageTracing(this IServiceCollection services, ILogger logger)
{
    // Add SerilogTraceListener to write Storage Client logs to Serilog
    var listener = new SerilogTraceListener.SerilogTraceListener(logger.ForContext<AzureBlobStore>());
    Trace.AutoFlush = true;

    var source = new TraceSource("Microsoft.Azure.Storage");
    source.Switch.Level = SourceLevels.Verbose;
    source.Listeners.Add(listener);
    source.Listeners.Add(new TextWriterTraceListener(Console.Out));

    services.AddSingleton(source);

    return services;
}
```

I call this from my `Startup` class. Nothing is written to either `TraceListener` instance by the Storage SDK, although I have verified that things _are_ written to these `TraceListener`s by including a `Trace.Write()` call after the listeners have been configured. 

### How can we reproduce the problem in the simplest way?
See the above code sample.

### Have you found a mitigation/solution?
None.

**Comment by seanmcc-msft** [comment]
This is a known issue with .NET Core, we are unable to address it.

**Comment by alastairs** [comment]
Thanks @seanmcc-msft, I found after a couple more days faffing around that it worked in .NET Framework but not .NET Core. 

.Net Standard defines a new API, `DiagnosticSource`. Could this be targeted instead of the Trace API?

**Comment by HengzheLi** [comment]
Hi @alastairs , I got the same issue as yours. So does DiagnosticSource help?
