### ISSUE TITLE
Cannot create database - missing slash when attempting to save mdf file

### ISSUE THREAD

**Issue by danabdn** [Azure/azure-storage-net#871]
### Which service(blob, file, queue, table) does this issue concern?
Local development with the emulator. 
I want to init the storage emulator, start it, use Azure Storage Explorer and open my local blob files.
I am familiar with the tools - had it working before my recent PC rebuild - a few months ago.

### Which version of the SDK was used?
Windows Azure Storage Emulator 5.7.0.0 command line tool
Microsoft Azure Storage Explorer 1.7

### Which platform are you using? (ex: .NET Core 2.1)
Windows 10 64 bit running with .NET core 2.1/2.2

### What problem was encountered?

Cannot create local emulator database.

> Found SQL Instance (localdb)\MSSQLLocalDB.
> Creating database AzureStorageEmulatorDb57 on SQL instance '(localdb)\MSSQLLocalDB'.
> Cannot create database 'AzureStorageEmulatorDb57' : The database 'AzureStorageEmulatorDb57' does not exist. Supply a valid database name. To see available databases, use sys.databases..
> One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
> Error: Cannot create database 'AzureStorageEmulatorDb57' : The database 'AzureStorageEmulatorDb57' does not exist. Supply a valid database name. To see available databases, use sys.databases..

### How can we reproduce the problem in the simplest way?

When attempting to run **AzureStorageEmulator.exe init**
Can manually create the database but then I think there is a saved setting somewhere with a bad path (see below) which then results in "unable to retrieve child resources" in Azure Storage Explorer when trying to expand nodes.

### Have you found a mitigation/solution?
I may have found the cause which may have knock-on effects Storage Explorer

When examining the error logs, I found one line which may be of interest:

> 2019-04-01 10:21:22.09 spid51 CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\danieAzureStorageEmulatorDb57.mdf'.

**Notice how the username danie - shouldn't there be an additional slash here?**
I.e. it's trying to create a file in a folder that doesn't exist / have permission to.
Perhaps there is some logic which is resulting in a missing slash?

I have also tried:
Deleting the local instance i.e. sqllocaldb stop/delete/start MSSQLLocalDB
Deleting the C:\Users\danie\AppData\Roaming\StorageExplorer folder
I launch the emulator before Azure Storage Emulator. I have had it working before in the past.
But given the logs this would appear to be a bug.

Also, logged issue with the AzureStorageExplorer team (see below link) as I believe this issue could to both platforms in how the database path is created, used and stored as a settings (which then results in unable to retrieve child resources error)
[AzureStorageExplorer - GitHub Issue - 1265](https://github.com/Microsoft/AzureStorageExplorer/issues/1265)

**Comment by seanmcc-msft** [comment]
We recommend using Azurite instead of the emulator.

[https://github.com/Azure/Azurite](url)

**Comment by chrisrichards** [comment]
Just had this issue after upgrading to Visual Studio v16.3 (which installed Azure Storage Emulator v5.10). Copying or moving the old storage emulator localDb database files to the new filename allowed me to start the emulator i.e. in your home folder, copy or rename AzureStorageEmulatorDb59.mdf to AzureStorageEmulatorDb510.mdf and AzureStorageEmulatorDb59_log.ldf to AzureStorageEmulatorDb510_log.ldf
