### ISSUE TITLE
CloudTable.ExecuteQuerySegmentedAsync returns only a fraction of max 1k entities

### ISSUE THREAD

**Issue by jouendag** [Azure/azure-storage-net#873]
As we have an event sourced system working with projections, we often have to query our event store for a large number of entities to (re)build our state. This is done by:
- Querying entities on PartitionKey, RowKey and occasionally extra filtering
- Processing the result segment
- Repeating this untill continuationtoken== null

Run by an Azure Function (V2), Windows.Azure.Storage 9.3.1.

The issue we are running into is the fact that the segments returned by ExecuteQuerySegmentedAsync vary in size from around 200~ to 700~ entities. I was able to reproduce this with a simple query on only PartitionKey, with no additional filtering. See below.

![querysegmented issue](https://user-images.githubusercontent.com/49230954/55467681-18f2cf00-5602-11e9-90ad-70c324eb7d3c.JPG)

Documentation states ExecuteQuerySegmentedAsync could return up to 1k of entities. Any ideas as to why we are not hitting that number? It would (expectantly) dramatically increase performance.

Thanks!

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)
