### ISSUE TITLE
.Storage.File has no CopyStatus

### ISSUE THREAD

**Issue by thedavegray** [Azure/azure-storage-net#875]
### Which service(blob, file, queue, table) does this issue concern?
Microsoft.WindowsAzure.Storage;

### Which version of the SDK was used?
Version 9.3.2.0 
Runtime Version 4.0.30319 

### Which platform are you using? (ex: .NET Core 2.1)
.net framework 4.6.1 

### What problem was encountered?
I cannot get VS2019 to download a copy of this .dll that contains CopyStatus, ILSpy, dotPeek and Visual Studio's own built in assembly browser say this class/folder does not exist.  

However LINQPad5 installs Microsoft.Azure.Storage.File from NuGet which contains this definition. 

### How can we reproduce the problem in the simplest way?
Create a .net console application and install Microsoft.WindowsAzure.Storage then attempt to use this 

var junk = Microsoft.WindowsAzure.Storage.File.

### Have you found a mitigation/solution?
No.  I appreciate this might not be a bug but my C# scratchpad LINQPad5 can use this no problem but VS2019 (or 2017) can't seem to use this definition. 

VS2019
![Image 012](https://user-images.githubusercontent.com/4395873/55754950-b5bfcd00-5a45-11e9-9eb9-0caa1e381434.png)

LINQPad5
![Image 129](https://user-images.githubusercontent.com/4395873/55754980-c708d980-5a45-11e9-9dc1-47422814a6c1.png)

**Comment by thedavegray** [comment]
A simple one-liner with the DataMovement library. 
![Image 013](https://user-images.githubusercontent.com/4395873/55755650-814d1080-5a47-11e9-820a-d2ed445c1797.png)

**Comment by seanmcc-msft** [comment]
We've checked the most recent version of the codebase, Microsoft.Azure.Storage.File.CopyStatus is present and public.  We recommend you update to the latest version (v10.0.1).
