### ISSUE TITLE
Dead links in package descriptions on NuGet.org

### ISSUE THREAD

**Issue by natemcmaster** [Azure/azure-storage-net#879]
There are several dead links in package descriptions on NuGet.org.

* https://github.com/Azure/azure-storage-net/blob/master/Blob/changelog.txt -> 404
* https://blogs.msdn.com/b/windowsazurestorage/ -> HTTP 404

Recommendation: consider using aka.ms so you can update links later since you can't update a package description once it has been published.

Example: https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/10.0.1 links to https://blogs.msdn.com/b/windowsazurestorage/, but  https://blogs.msdn.com/b/windowsazurestorage/ results in a 404.

<img width="450" src="https://user-images.githubusercontent.com/2696087/56173466-8dceed00-5fa2-11e9-9083-0a6874a694af.png" >
<img width="450" alt="Untitled" src="https://user-images.githubusercontent.com/2696087/56173471-91627400-5fa2-11e9-8e9f-349e0a8fc060.png">

**Comment by seanmcc-msft** [comment]
Fixed in version 10.0.3.

Commit: https://github.com/Azure/azure-storage-net/commit/1c736cebbbf37a96c0be9e9f36f5c297796e063d
