### ISSUE TITLE
RequestResult class is missing IngressBytes and EgressBytes proerties in NS2 version. 

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#880]
### Which service(blob, file, queue, table) does this issue concern?
RequestResult class is not specific to service. 

### Which version of the SDK was used?

9.3.3

### Which platform are you using? (ex: .NET Core 2.1)

.NET Framework 4.6.1

### What problem was encountered?

Unable to migrate to NS2 version of library.

### How can we reproduce the problem in the simplest way?

Try to create "var r =new RequestResult()" and access "var bytes = r.IngressBytes + r.EgressBytes;"

### Have you found a mitigation/solution?

I was not able to find solution or workaround.

**Comment by seanmcc-msft** [comment]
Hi,

Unfortunately, I'm not able to reproduce, RequestResult appears to have IngressBytes and EgressBytes for .NET Standard 2.0 and 2.1 as of version 10.0.2.

-Sean
