### ISSUE TITLE
Regarding the UpdateMessage() method of queue

### ISSUE THREAD

**Issue by imeya** [Azure/azure-storage-net#881]
I use this nuget package **Microsoft.Azure.Storage.Queue -Version 10.0.1** , and when I want to update the Visibility timeout for an queue message, there is something I don't understand.

the code like below:

```
CloudQueueMessage queueMessage = queue.GetMessage();
            queueMessage.SetMessageContent("updated contents...");
            queue.UpdateMessage(queueMessage, TimeSpan.FromSeconds(120), MessageUpdateFields.Content | MessageUpdateFields.Visibility);
```

I can see the message content can be updated successfully after 120s in azure portal -> queue.

And then I thought the Visibility timeout should also be updated to 120s. Then I write the following code to test it.

            ```
CloudQueueMessage queueMessage = queue.GetMessage();
            Console.WriteLine(queueMessage.AsString + ",," + queueMessage.Id + ",," + queueMessage.NextVisibleTime);
```

But as per my test, I see that the visibility timeout is still 30s.

Could you please let me know if this is the expected behavior? only when I used the updateMessage() method, I can see the message after 120s(I check it in azure portal).  But after the 120s, when the message is visible, I check the message's visibility timeout using GetMessage(), I can see the visibility timeout is 30s. why not 120s?

**Comment by seanmcc-msft** [comment]
Hi,

I've double checked with the service team, and this is the expected behavior.  After a message has become visible, it's TimeNextVisible defaults back to 30 seconds.

For more information, see [https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages#remarks](url)

-Sean

**Comment by imeya** [comment]
@seanmcc-msft , hi Sean, in the link you provided, I just see this sentence "the TimeNextVisible element of the response, which is calculated based on the value of the visibilitytimeout parameter", and it will always back to 30s or other values?
