### ISSUE TITLE
The Blob encryption download a empty stream

### ISSUE THREAD

**Issue by TuanDMT-FPT** [Azure/azure-storage-net#886]
### Which service(blob, file, queue, table) does this issue concern?
This is Blob

### Which version of the SDK was used?
Last version: 10.0.1

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.2

### What problem was encountered?
I implement "Client-Side Encryption and Azure Key Vault for Microsoft Azure Storage" by follow the post:
> https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption
and
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-encrypt-decrypt-blobs-key-vault

After upload the stream, it work as well. But i cannot download the that file.

### How can we reproduce the problem in the simplest way?
1. Init:
```csharp
var cloudResolver = new KeyVaultKeyResolver(keyVaultOptions.VaultName, GetAccessToken);
var aggregateResolver = new AggregateKeyResolver().Add(cloudResolver);

_keyResolver = new CachingKeyResolver(1, aggregateResolver);
_key = _keyResolver.ResolveKeyAsync(keyVaultOptions.KeyIdentifier, CancellationToken.None)
    .GetAwaiter().GetResult();
```
2. Upload:
```csharp
var options = new BlobRequestOptions()
{
    EncryptionPolicy = new BlobEncryptionPolicy(_key, null)
};
await blob.UploadFromStreamAsync(stream, null, options, null);
```
![image](https://user-images.githubusercontent.com/37429094/56853335-4bb58c00-6950-11e9-8d0a-94e3d1bddee9.png)

3. Download:
```csharp
var options = new BlobRequestOptions()
{
    EncryptionPolicy = new BlobEncryptionPolicy(null, _keyResolver)
};
await blob.DownloadToStreamAsync(stream, null, options, null);
```
The stream is empty when i use BlobRequestOptions with BlobEncryptionPolicy.
If i use DownloadToStreamAsync without BlobRequestOptions, it's work.
```csharp
await blob.DownloadToStreamAsync(stream);
```
![image](https://user-images.githubusercontent.com/37429094/56853385-0cd40600-6951-11e9-8f3c-3664810f3e11.png)

### Have you found a mitigation/solution?
No. :(

Can you help me to resolve this issue, please?

**Comment by TuanDMT-FPT** [comment]
I was resolve this issue. The cause is Stream have been uploaded wrong.
Thanks.

**Comment by rmed1na** [comment]
> I was resolve this issue. The cause is Stream have been uploaded wrong.
> Thanks.

Hey can you provide the wrong and right upload cases? I'm having the exact same issue with DownloadToStreamAsync

**Comment by rmed1na** [comment]
> > I was resolve this issue. The cause is Stream have been uploaded wrong.
> > Thanks.
> 
> Hey can you provide the wrong and right upload cases? I'm having the exact same issue with DownloadToStreamAsync

Nvm, in my case, the stream position was at the end when uploading. Set it to zero and works fine.
