### ISSUE TITLE
Implement TableBatchOperation.set_Item

### ISSUE THREAD

**Issue by pjt33** [Azure/azure-storage-net#888]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the SDK was used?

9.3.2, but the problem is clearly visible in the latest `dev` source code:

https://github.com/Azure/azure-storage-net/blob/dev/Lib/Common/Table/TableBatchOperation.Common.cs#L226

### Which platform are you using? (ex: .NET Core 2.1)

.Net Framework 4.7.1.

### What problem was encountered?

    System.NotSupportedException:
       at Microsoft.WindowsAzure.Storage.Table.TableBatchOperation.set_Item (Microsoft.WindowsAzure.Storage, Version=9.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

### How can we reproduce the problem in the simplest way?

    var batch = new Microsoft.WindowsAzure.Storage.Table.TableBatchOperation();
    batch.Insert(new Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity("foo", "bar"));
    batch[0] = batch[0];

### Have you found a mitigation/solution?

The workaround is to replace

    batch[idx] = op;

with

    batch.RemoveAt(idx);
    batch.Insert(idx, op);

I assume that the reason that `set_Item` isn't implemented was a fear that a "slow" implementation would violate the principle of least surprise, but I would argue that throwing `NotSupportedException` from a list which returns `false` for `IsReadOnly` is more surprising than taking non-constant time to implement an operation whose complexity is not guaranteed by the spec.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)

**Comment by pjt33** [comment]
If you're no longer supporting the code, why is it still in your source tree?

**Comment by IlyaGrebnov** [comment]
@seanmcc-msft, I notice on various your replies that link for CosmosDB NuGet is pointing to nowhere. You probably want to correct it.

**Comment by seanmcc-msft** [comment]
Thanks, updated.
