### ISSUE TITLE
[BUG] [Azure Table storage] Query filter containing exclamation mark not working correctly.

### ISSUE THREAD

**Issue by Dethras** [Azure/azure-storage-net#893]
While testing I have noticed an issue with filters containing the '!' character, when you include it in the query, the sdk will automatically convert it to 'not'.

Example:

PartitionKey eq 't!est' = PartitionKey eq 'tnotest'

I tried to search for an escape character of something of that sort but it was fruitless.
I also don't know if there are other characters with the same issue.

**Comment by gmantri** [comment]
BTW, this happens with Node SDK as well.  Here's an issue there: https://github.com/Azure/azure-storage-node/issues/588.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
