### ISSUE TITLE
Question: When a download from Azure blob storage takes a long time (50 MB in 2 hours) to complete, how do we determine if the issue is with the storage client library or network or proxy? This is intermittent in our customer environment.

### ISSUE THREAD

**Issue by akomandooru** [Azure/azure-storage-net#896]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.1

### Which platform are you using? (ex: .NET Core 2.1)
.net framework 4.6

### What problem was encountered?
Blob (around 50 MB size) takes around 2 hours to finish downloading intermittently; sometimes, it downloads in 2 sec; our service using Azure Storage client is behind a proxy. 

### How can we reproduce the problem in the simplest way?
We do not know how to reproduce; this issue shows at our client environment.

### Have you found a mitigation/solution?
Changing to a different proxy server at our client seems to have fixed the issue.

**Comment by seanmcc-msft** [comment]
The issue is almost certainly caused by something with your proxy server, because switching proxies appears to resolve your issue.
