### ISSUE TITLE
Custom metadata/message attribute for CloudQueueMessage

### ISSUE THREAD

**Issue by explorer14** [Azure/azure-storage-net#898]
Hi, 

Is there a way in the storage queue APIs for .NET, to specify custom metadata/attribute (basically a bunch of `KeyValuePair<string, object>` or similar), per message? Something along the lines of [SQS queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html)

These custom attributes are really useful to pass along custom application specific pieces of information such as correlation id etc or whatever is needed, without having to add that data to the message itself and then decoding it on the consumer side.

If not, then do you have any plans to put it in?

Thanks
Aman

**Comment by kfarmer-msft** [comment]
We have no plans within the foreseeable (eg, upcoming year) term to add such a feature.
