### ISSUE TITLE
Add lifecycle management functionality

### ISSUE THREAD

**Issue by iamandymcinnes** [Azure/azure-storage-net#901]
### Which service(blob, file, queue, table) does this issue concern?
Blob storage

### Which version of the SDK was used?
Latest

### Which platform are you using? (ex: .NET Core 2.1)
Core 2.2

### What problem was encountered?
No lifecycle management functionality available: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts

### How can we reproduce the problem in the simplest way?
Try set a delete rule on a container for 7 days

### Have you found a mitigation/solution?
Other than running a powershell command no, especially problematic when blob containers are created programatically

**Comment by amnguye** [comment]
Hi Andy,

Support for Lifecycle management is currently not on the roadmap for the storage .NET sdk. We are open to feedback and looking into it if the interest in this becomes larger.

**Comment by amnguye** [comment]
This feature is a management plane feature and is already supported there. It can’t be supported on the storage sdk.
