### ISSUE TITLE
XML documentation missing in NuGet package

### ISSUE THREAD

**Issue by josefblaha** [Azure/azure-storage-net#905]
### Which version of the SDK was used?
Microsoft.Azure.Storage.Blob 10.0.3

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.2
Visual Studio 16.1.3

### What problem was encountered?
The NuGet package does not contain the XML doc file. Therefore no IntelliSense documentation is shown for the Blob API.

I'm not sure if it is related, but the [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.icloudblob.uploadfromstreamasync?view=azure-dotnet) lacks any description of the API as well.

### How can we reproduce the problem in the simplest way?
Create a console app project, install the package and reference any type from the package.

**Comment by seanmcc-msft** [comment]
Hi,

I can repo, we will address this issue in an upcoming release.

-Sean

**Comment by seanmcc-msft** [comment]
Fixed in v11.0.0.
