### ISSUE TITLE
unable to view image from blob storage

### ISSUE THREAD

**Issue by sathishTkumar** [Azure/azure-storage-net#907]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Microsoft.Azure.Storage.Blob 10.0.3

### Which platform are you using? (ex: .NET Core 2.1)
.Net Core 2.2

### What problem was encountered?
am uploading image programmatically to azure blob storage and trying to view the same from browser. 
If i set ContentType =application/octet-stream then i able to download the file from browser. But i would to like to view in browser instead of download. So i set ContentType=image/jpeg which is throwing 304 error.
https://travelfotos.blob.core.windows.net/post/19/6c20a9a8-db8d-4f79-955f-88bdc6a5f8bb.jpg 

### How can we reproduce the problem in the simplest way?
 CloudStorageAccount storageAccount = null;
                if (CloudStorageAccount.TryParse(_configuration.GetConnectionString("StorageAccount"), out storageAccount))
                {
                    var client = storageAccount.CreateCloudBlobClient();
                    CloudBlobContainer container = client.GetContainerReference(_configuration.GetValue<string>("imageContainerName"));                    
                   var blob = container.GetBlockBlobReference(request.fileName);
                    blob.Properties.ContentType = GetContentType(request.fileName);
                    await blob.UploadFromStreamAsync(request.fileStream);

                    return blob.Uri.AbsoluteUri;
                }

### Have you found a mitigation/solution?
Nope. Please help me to resolve this issue.

**Comment by seanmcc-msft** [comment]
Hi,

Would you mind using Fiddler to grab the HTTP request you send on the upload and posting it here?

-Sean

**Comment by kfarmer-msft** [comment]
Be sure to hide any credentials, of course.
