### ISSUE TITLE
MultiBufferMemoryStream objects passed as arguments are disposed by the library

### ISSUE THREAD

**Issue by Chelaris182** [Azure/azure-storage-net#91]
The library executor automatically disposes MultiBufferMemoryStream instance passed to any blob API call, for example CloudBlockBlob.UploadFromStreamAsync. This logic causes UB if the stream instance is reused after the library call end.

Call chain that leads to the stream disposal:
----
               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.Dispose(bool disposing) 
               mscorlib.dll!System.IO.Stream.Close()                     Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.Executor.ExecutionState<Microsoft.WindowsAzure.Storage.Core.NullType>.CheckDisposeSendStream()               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.Executor.ExecutionState<Microsoft.WindowsAzure.Storage.Core.NullType>.Dispose(bool disposing)
               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.Util.StorageCommandAsyncResult.Dispose()
               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.Util.StorageCommandAsyncResult.End()               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync<Microsoft.WindowsAzure.Storage.Core.NullType>(System.IAsyncResult result)>               Microsoft.WindowsAzure.Storage.dll!Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamHandler.AnonymousMethod__14(System.IAsyncResult ar)

**Comment by veena-udayabhanu** [comment]
Thank you for reporting this. This is because we recently exposed MultiBufferMemoryStream so users can use it. We will fix this in an upcoming release.

**Comment by pemari-msft** [comment]
Hi -- this was fixed in version 5.0.0 of our library. Thanks for reporting it! Please let us know if you have any further issues.
