### ISSUE TITLE
Azure table returns null value randomly

### ISSUE THREAD

**Issue by erYasar** [Azure/azure-storage-net#919]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
WindowsAzure.Storage.Table (8.6.0)

### Which platform are you using? (ex: .NET Core 2.1)
.Net Core 2.2

### What problem was encountered?
Azure table returns null value randomly

### How can we reproduce the problem in the simplest way?
```csharp
var continuationToken = default(TableContinuationToken);
CloudTable cloudTable = _cloudTableClient.GetTableReference(_tableName);
var filter = TableQuery.CombineFilters(
                    TableQuery.GenerateFilterCondition(PartitionKey, QueryComparisons.Equal, userName),
                    TableOperators.And,
                    TableQuery.GenerateFilterCondition(RowKey, QueryComparisons.Equal, instanceId)
                );
var query = new TableQuery<Container>().Where(filter);
do
{
var retrievedResult = await cloudTable.ExecuteQuerySegmentedAsync(query, continuationToken).ConfigureAwait(false);
var result= retrievedResult.Results.SingleOrDefault();
continuationToken = retrievedResult.ContinuationToken;
retryCounter++;
}
while (continuationToken != null && retryCounter < 15);
```
Here result is null randomly, also tried with continuation token but not working so far.

### Have you found a mitigation/solution?
No

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
