### ISSUE TITLE
Memory Leak in CloudQueue.AddMessageAsync

### ISSUE THREAD

**Issue by pwninstein** [Azure/azure-storage-net#92]
We've found that over a long period of time (on the order of days), `CloudQueue.AddMessageAsync` will leak. Below is a small program that reproduces the problem. Note that in the application that we're seeing this behavior, we have code that limits the number of concurrent async operations to 40, so the reproduction code below will show the problem greatly exaggerated. SDK Version: 2.2.

```c#
public static void Main()
{
	const string ConnectionString = "DefaultEndpointsProtocol=https;AccountName=REMOVED;AccountKey=REMOVED";
	var storageAccount = CloudStorageAccount.Parse(ConnectionString);
	var client = storageAccount.CreateCloudQueueClient();
	var queue = client.GetQueueReference("things");

	queue.CreateIfNotExists();

	while (true)
	{
		var content = DateTime.UtcNow.Ticks.ToString(CultureInfo.InvariantCulture);
		var message = new CloudQueueMessage(content);
		queue.AddMessageAsync(message);
	}

	Console.WriteLine("Press any key");
	Console.ReadKey();
}
```

Please let me know if you need more information - I'll be happy to provide it. Thanks!

**Comment by phstur** [comment]
I have found this to be true as well. I have code that loops and sends messages async and I quickly run out of memory. Simply changing the code to use the non async method fixes the problem but is too slow.

**Comment by mirobers** [comment]
Sorry for the late response. The repro code provided appears to create tasks as quickly as possible, faster than they can complete. So this code will consume unbounded resources. I experimented with adding pauses that wait for the pending requests to complete, and the memory usage falls to expected levels. Running the code this way for an hour (resulting in millions of requests), I don’t see any upward trend in memory usage. Could you explain the usage pattern that leads to increasing memory usage? Simple repro code would be great, but be sure that the number of pending tasks is limited or else you will exhaust your machine’s resources simply by creating tasks.

**Comment by pemari-msft** [comment]
Closing this as it seems to have been resolved. Please reopen if you have any other comments.
