### ISSUE TITLE
StackOverflow exception from Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.WriteBlobAsync

### ISSUE THREAD

**Issue by HengzheLi** [Azure/azure-storage-net#920]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
9.4.0

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.6.2

### What problem was encountered?
IIS encounter a StackOverflowException from the code then IIS crashed

### How can we reproduce the problem in the simplest way?
Can't reproduce for now. But got a dump file and have the  call stack:
![image](https://user-images.githubusercontent.com/491759/62617166-da6c7880-b943-11e9-8b8d-b21a138d7faf.png)
And below is the related screenshot from Paralled Stacks from dump file:
![image](https://user-images.githubusercontent.com/491759/62617226-fcfe9180-b943-11e9-9dab-70b244fdffed.png)

### Have you found a mitigation/solution?
No.

The issue may be not related to the blob's sdk code. But as the CallStack seems that it indicates the exception from BlobWriteStream.WriteBlobAsync and you are so familiar with the SDK. Could you give me some advices?

**Comment by relf218** [comment]
I have a similar issue when uploading data of larger than 6GB.
I am using 11.0.0, my .net framework 4.7.1 project is doing nothing but uploading data using UploadFromStreamAsync, and it will crash toward the end of the upload with a Stackoverflow exception.

**Comment by HengzheLi** [comment]
@relf218  I think maybe we need to vote this issue to involve the team for investigation

**Comment by botinko** [comment]
We have the same error! 
We use Version 9.4.2.0 and Net framework 4.6.1

**Comment by austvik** [comment]
We have the same error.
Framework 4.6.1

**Comment by botinko** [comment]
This bug in https://github.com/Azure/azure-storage-net/issues/894

**Comment by CooperRon** [comment]
I am still getting the StackOverflow exception when trying to upload large blobs (i.e. more than 2GB) with ParallelOperationThreadCount=1. When using ParallelOperationThreadCount > 1 the operation is successful.

I am using Microsoft.Azure.Storage.Blob nuget version 11.0.0 but it also happens with the latest version (11.2.2).
Running with .NET framework 4.7.2.
