### ISSUE TITLE
Latest version of Microsoft.Azure.Storage.* does not work with Azure Storage Emulator v5.9 (latest)

### ISSUE THREAD

**Issue by skykick-cm** [Azure/azure-storage-net#921]
### Which service(blob, file, queue, table) does this issue concern?

Am using 'blob', but this is systemic and probably affects all of the `Microsoft.Azure.Storage.*` libraries

### Which version of the SDK was used?

I am using the Nuget package listed [here](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/)

v11.0.0

### Which platform are you using? (ex: .NET Core 2.1)

.NET Core 2.1

### What problem was encountered?

The latest (updated 3 days ago) stable build of this Nuget Package does not work with the latest Azure Storage Emulator v5.9

### How can we reproduce the problem in the simplest way?

Run the ASE v5.9 and attempt to perform any operation against the emulator using the SDK.

E.g.

```
var account = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
var client = account.CreateCloudBlobClient();
var container = client.GetContainerReference("foo");
await container.ExistsAsync(CancellationToken.None);
```

### Have you found a mitigation/solution?

I had to downgrade my Nuget Package back to v10.0.3 and then it worked again

**Comment by BrianVallelunga** [comment]
Just writing to confirm that I'm seeing the same issue.

**Comment by Plasma** [comment]
Can confirm this also.

**Comment by Plasma** [comment]
Referencing https://github.com/Azure/azure-sdk-for-net/issues/7208 also

**Comment by skykick-cm** [comment]
@Plasma thanks for the find. So I'm going to assume that this can be closed as Azure Storage Emulator is being deprecated in favor for Azurite?  Must have missed the memo :)

**Comment by nlysaght** [comment]
Azurite just supports blob storage only, so we still need the Storage Emulator for Table and Queue storage. 
So is it only the Blob portion of Azure Storage Emulator that is being retired or the whole emulator? Is there an official announcement that you folks in MS are going to be making around this issue, because this is going to cause a lot of trouble for a lot of people.

I posted this in #7208 also, apologies if I was incorrect doing this.

**Comment by pemari-msft** [comment]
Hi all, thanks for your feedback. We are still supporting the older, Windows-only Storage Emulator, but new features won't be able to be added to it. We'll release a new version in the coming days that will fix the latest api-versions to ensure you are unblocked ASAP and we apologize for the confusion.

The Azurite emulator is an open-source, cross-platform emulator that we've chosen to invest in in response to customer feedback. Azurite will support Blobs and Queues, and the CosmosDB emulator is the way forward for Table emulation. Azurite is our officially recommended solution, and as such, all new Storage Service releases will also have a corresponding Azurite release on day 1.

Please let me know if you have any questions regarding the above -- we are working on some official documentation that outlines the above and we'll be posting it shortly.
