### ISSUE TITLE
C# - Setting legal hold on blob container

### ISSUE THREAD

**Issue by ssjaronx4** [Azure/azure-storage-net#922]
### Which service(blob, file, queue, table) does this issue concern?

Blob container

### Which version of the SDK was used?

Latest (13.0.0 storage, 11.0.0 blob). 

### Which platform are you using? (ex: .NET Core 2.1)

 .Net Framework 4.7.2

### What problem was encountered?

I need an example of how to set legal hold on a container using C# and the latest version of the SDK. CloudBlobContainer does not seem to provide a set method for legal hold / immutable policies. Based on how permissions / metadata is set, I would expect to be able to do something like:

`BlobContainerProperties props = new BlobContainerProperties{
	.....
}
container.SetProperties(props);`

But this doesn't exist. I've tried crawling through the SDK for the answer but am struggling to find a workable method. The Azure Docs team said I should raise the request here as they don't currently have any examples available.

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
No

**Comment by pemari-msft** [comment]
Hi, this operation is only available on the control plane, so it requires the Azure Storage Management SDK. Here is the documentation for that method: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.blobcontainersoperationsextensions.setlegalhold?view=azure-dotnet
