### ISSUE TITLE
Table storage- get unavailable or Table Not found exception

### ISSUE THREAD

**Issue by test123114** [Azure/azure-storage-net#926]
I use Microsoft Azure Storage SDK for table to dele some data for my table in my console application My code is :
string connectionString = ConfigurationManager.ConnectionStrings["StorageAccountConnectionString"].ConnectionString;
	CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(connectionString);
	CloudTableClient cloudTableClient = cloudStorageAccount.CreateCloudTableClient();
	CloudTable cloudTable = cloudTableClient.GetTableReference(""); 

	string number= "10000"

	TableQuery<TableEntity> query = new TableQuery<TableEntity>().
		Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.LessThanOrEqual, number)); //my PartitionKey is Interger 

	TableContinuationToken token = null;

	try
	{
		do
		{
			Console.WriteLine("Fetching Records");
			TableQuerySegment<TableEntity> resultSegment = await cloudTable.ExecuteQuerySegmentedAsync(query, token);
			token = resultSegment.ContinuationToken;

			Console.WriteLine("Fetched all records to be deleted, count: " + resultSegment.Results.Count);

			foreach (TableEntity entity in resultSegment.Results)
			{
				Console.WriteLine("Deleting entry with TimeStamp: " + entity.Timestamp.ToString());
				TableOperation deleteOperation = TableOperation.Delete(entity);
				await cloudTable.ExecuteAsync(deleteOperation);
			}
		} while (token != null);

		Console.WriteLine("Entities Deleted from " + cloudTable.Name);
	}
	catch (Exception ex)
	{
		Console.WriteLine("Exception occured while deleting data from table " + cloudTable.Name + " " + ex.Message);
	}
It spends some time to run and it throws intermittent Service Unavailable or Not Found exception. Could someone help me fix it?

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
