### ISSUE TITLE
CloudBlobClient.GetRootContainerReference XmlDoc is not correctly formatted

### ISSUE THREAD

**Issue by Chris-Johnston** [Azure/azure-storage-net#928]
https://github.com/Azure/azure-storage-net/blob/bbb7da62bc49ee79e07cf607d2202c9778b83d56/Lib/Common/Blob/CloudBlobClient.Common.cs#L190-L191

[The formatting of the Remarks field for this method appears to be incorrectly formatted, as seen in the docs.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient.getrootcontainerreference?view=azure-dotnet#remarks) Maybe the xmldoc comments don't like the newline? I haven't seen this issue before myself.

**Comment by seanmcc-msft** [comment]
We'll fix this in a future release.
