### ISSUE TITLE
Download Different Versions of Storage Emulator?

### ISSUE THREAD

**Issue by spottedmahn** [Azure/azure-storage-net#934]
Where can I download different stand-alone versions of the azure storage emulator?

Here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#get-the-storage-emulator and here: https://azure.microsoft.com/en-us/downloads/ direct me to the current version v5.10.

And I don't see them in the [repo/releases](https://github.com/Azure/azure-storage-net/releases).

**Comment by spottedmahn** [comment]
I ask b/c v5.10 won't start for me, reference #933

**Comment by seanmcc-msft** [comment]
Unfortunately, I don't think it's possible to download an older version of the emulator.

I'd recommend switching to [Azurite](https://github.com/Azure/Azurite)

**Comment by spottedmahn** [comment]
I'm looking to use it for table storage and it seems Azurite isn't the tool for that:

![image](https://user-images.githubusercontent.com/14079228/68703976-8cc26600-0559-11ea-9229-1be62e3420ab.png)

I'm guessing it moved to another tool?

And does that mean the storage emulator is going away?  Where I can read more about the direction of these tools?

**Comment by spottedmahn** [comment]
>please use V2 for Table service for the time being.  [source](https://github.com/Azure/Azurite#azurite-v3)

oops, missed that part, guess it is the work for v3.

**Comment by spottedmahn** [comment]
>Regarding Azurite, yes, we recommend migrating to it if possible. Visual Studio support is on its roadmap.

[source](https://github.com/Azure/azure-storage-net/issues/704#issuecomment-394835505)

**Comment by spottedmahn** [comment]
>Azurite supersedes the Azure Storage Emulator

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite

Why doesn't the readme have this in bold on-top?  "This product has pretty much been sunsetted and all efforts is being made in Azurite."

**Comment by amnguye** [comment]
Hi,

Any questions regarding Azurite, please direct it to the [Azurite Repository](https://github.com/Azure/Azurite).

**Comment by wislon** [comment]
> 
> 
> Unfortunately, I don't think it's possible to download an older version of the emulator.
> 
> I'd recommend switching to [Azurite](https://github.com/Azure/Azurite)

It's nearly a year later, and Azurite V3 still can't do table storage. This isn't an option for a lot of people.
