### ISSUE TITLE
Metadata exists in Azure storage but is empty when read in programatically using CloudBlockBlob.Metadata

### ISSUE THREAD

**Issue by Cj-muse** [Azure/azure-storage-net#937]
Hi, having the same issue as #603 but not using TransferManager.

I set my metadata as follows.
`
cloudBlockBlob.Metadata.Add("Key1",value1);
cloudBlockBlob.Metadata.Add("Key2", value2);
cloudBlockBlob.SetMetadata();
`

I attempt to read the metadata from azure storage as follows.
`
blob.Metadata.TryGetValue("Key1", out outputVariable)
`

however the blob object read has no metadata but other properties are populated correctly, such as name, content, and time created. 

![image](https://user-images.githubusercontent.com/5886515/65362639-fe66df00-dbbc-11e9-825a-1ed10cad2c28.png)

The blob has all properties and correct metadata in the properties pane of Azure storage explorer but when read programmatically there is no metadata.

Any ideas?

Thank you,
Conner

_Originally posted by @Cj-muse in https://github.com/Azure/azure-storage-net/issues/603#issuecomment-533733725_

**Comment by nmaarse** [comment]
I have Exactly the same problem. Writing to metadata works fine. But when retrieving the metadata of the cloudblockblob it is empty.
Retrieving the blob data with DownloadTextAsync() does work. 
 the code is use:
        private string description RetrieveMetaData(CloudBlockBlob blob)
        {
            var description = blob.Metadata["description"];
            return description;
        }

**Comment by Cj-muse** [comment]
Thank you for the feedback. I just found that calling `blob.FetchAttributes();` before attempting to gather metadata via `blob.Metadata.TryGetValue()` also solves the problem.

Closing issue.
Thank you.
