### ISSUE TITLE
Async Methods for CloudTable.ExecuteQuery

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/azure-storage-net#94]
On the CloudTable class, is there a reason why there isn't an async counterpart for ExecuteQuery? All of the rest of the Execute methods have an async counterpart apart from that one

**Comment by pemari-msft** [comment]
This is not considered best practice. Essentially to execute an entire query asynchronously would mean to follow all subsequent continuation tokens and store all resulting data in memory. In Azure Tables this could potentially mean 200 TB of data which is not practical. Once could conceivably create a helper method that simply executes N segmented operations until a given number of entities are returned, and such a method is simple enough do (i.e. an extension method ExecuteQueryForN). .NET does not at the moment include built-in support for async lazy iteration; we will consider this feature when the framework supports it. We will investigate other possible alternatives in upcoming releases of the storage client library.

**Comment by MatthewSteeples** [comment]
@pemari-msft Thanks for that response. I assumed it would execute as an async lazy iteration but if the framework doesn't support it that makes sense.

**Comment by GuardRex** [comment]
@pemari-msft Why don't we have a non-async `ExecuteQuery` that we can call to return a small number of entities?

**Comment by pemari-msft** [comment]
You can use ``ExecuteQuerySegmented`` to return a segment of entities. This will return a lazy enumerator for a smaller number of entities. Is this what you are looking for?

**Comment by GuardRex** [comment]
@pemari-msft Perhaps ... I found myself ending up with this to get a `List` of company entities ...
```c#
public async static Task<IEnumerable<Company>> FetchAll(string accountName, string accountKey)
{
    List<Company> allEntities = new List<Company>();
    StorageCredentials storageCredentials = new StorageCredentials(accountName, accountKey);
    CloudStorageAccount storageAccount = new CloudStorageAccount(storageCredentials, true);
    CloudTableClient tableClient = storageAccount.CreateCloudTableClient();
    tableClient.DefaultRequestOptions.RetryPolicy = new ExponentialRetry(TimeSpan.FromSeconds(1), 10);
    CloudTable table = tableClient.GetTableReference("Company");
    TableContinuationToken tableContinuationToken = null;
    do 
    {
        var queryResponse = await table.ExecuteQuerySegmentedAsync<Company>(null, tableContinuationToken, null, null);
        tableContinuationToken = queryResponse.ContinuationToken;
        allEntities.AddRange(queryResponse.Results);
    } 
    while(tableContinuationToken != null);
    return allEntities;
}
```
... and calling it like this elsewhere for use ...
```c#
IEnumerable<Company> companies = await Company.FetchAll(accountName, accountKey);
```
This is a VB.NET WCF .NET 4.5.2 app setup as a managed Windows service and it's going to become a C# .NET 5 CoreCLR Web API app. I'm still in the middle of porting a lot of code, so I haven't tested this method yet to see if that's going to work. If you see something troubling there, please let me know. Certainly, if there is a simpler way to do it, I'm all :ear:'s.

**Comment by Cheesebaron** [comment]
Looks OK to me. Notice that the method might run a long time. In cases of needing to present data as they are fetched page for page, you could consider using Reactive Extensions to populate an `IObservable` or populate an `ObservableCollection`.

**Comment by GuardRex** [comment]
@Cheesebaron Cool. This is merely to return a list of entities that are kept in a local var for quick lookups when inserting other entities into other tables. This particular one isn't for paging and it wouldn't be returning thousands of entities.

My question for @pemari-msft is: I understand that `.ExecuteQuerySegmentedAsync` can return up to 1K entities, but there is no guarantee that if a table has less than 1K that they would all be returned? I seem to recall reading somewhere that if a table crosses a partition boundary that it may stop there and return a segment up to that point ... then start a new segment on the next boundary, thus `.ExecuteQuerySegmentedAsync` could return anywhere from 0 to 1K entities; and for tables crossing partitions, you really do need to keep asking for segments until the continuation token comes back null.

If that is true, my next question is: If we can guarantee to the service that all entities of a given table have the same `PartitionKey`, then could we be guaranteed that `.ExecuteQuerySegmentedAsync` will return them all in one segment? In that case, can I drop the loop and just hit `.ExecuteQuerySegmentedAsync` once and be sure to get all of the entities in one hit on the service?

**Comment by arangas** [comment]
Sorry, I must be missing something... From what I understand we don't have `ExecuteQueryAsync()` because it could consume all memory with a badly written query. But isn't that true with the existing `ExecuteQuery()`?

Also, is the memory concern on the Microsoft infrastructure side, or the client side? If it's the latter then surely that's an issue for the developer to resolve?

**Comment by pemari-msft** [comment]
No, the existing `ExecuteQuery` in the sync paradigm is a `Lazy` method, only making a new service call when necessary and managing memory correctly. This concept does not exist in an async paradigm, and to do so would require a greedy method that did not return until all results were returned from the service. This may be millions of entities taking tens of minutes. If you are sure in your scenario that your queries cannot return 200TB of data from this call, you are free to implement it as you wish, via the  `ExecuteQuerySegmentedAsync` methods that already exist.

**Comment by kitsu** [comment]
I don't know about others, but my use case is grabbing a chunk of 10 to 50 entities using a `take`.

Because of the `segment on partition` behavior it would be really nice to have a helper method that manages collecting segments.
Effectively a method like `ExecuteQueryAsyncTaking(query, max = 50)` or some such.

Again, this is purely because of the virtual *promise* that the first segment will *NOT* contain an entire `take`'s worth of entities.

For others who end up here - I did find [a nice extension method](https://github.com/vivienchevallier/Article-AzureTableStorage.TableQueryAsync) for this purpose.
