### ISSUE TITLE
Overly complex and too many dependencies

### ISSUE THREAD

**Issue by ejsmith** [Azure/azure-storage-net#97]
I know this is just picky, but I don't understand why this library has to be so complex and have so many dependencies. Azure storage is a fairly simple REST API. It seems like it would be nice to have a simple base Azure Storage client that didn't have dependencies on odata, configuration manager and data services client. It seems like a lot of things in Azure are becoming simpler and cleaner, but this client doesn't appear to be one of them. Thoughts?

**Comment by dsevastianov** [comment]
+1

**Comment by felipeleusin** [comment]
+1

Bugs every single time I update my packages

**Comment by Scooletz** [comment]
+1
Not to mention that targeting given API can bring performance improvements.

**Comment by benabbon** [comment]
+1

**Comment by AlanParr** [comment]
+1

**Comment by Dorokhov** [comment]
+1

**Comment by jehine-MSFT** [comment]
Hello everyone,

We want to address your concerns about the usability of our library to provide the best user experience possible. Could you list some specific issues you have with the library?

Thanks!

**Comment by Scooletz** [comment]
That package list would be one: https://github.com/jehine-MSFT/azure-storage-net/blob/master/Lib/WindowsDesktop/packages.config
You're using JSON.Net which is not the fastest library in the world, there are much faster like JIL (https://github.com/kevin-montrose/Jil).
There is plenty of allocations. Even calculation of Sha256 which is used for signing could be done in place (you need just 4kb to store the block).
A library for accessing Azure should be a library on its own, if you want to consume some other dependencies, just ilmerge them and liberate others from having deps on JSON.Net or sth.

**Comment by niemyjski** [comment]
@jehine-MSFT Just read the root issue, why should I have to take a dependency on any of those? I don't want anything OData in my app or executables being added to the project esp when were working towards cross plat..

**Comment by felipeleusin** [comment]
I think the main point is probably splitting this nuget into separate ones with minimal dependencies. OData always comes to mind and the KeyVault one should probably be used separately.

For instance, I only use BlobStorage and there's no need for me to use OData or anything like that. So going forward I think it would be interesting to have a WindowsAzure.Storage.Blob, WindowsAzure.Storage.Table (this one I think requires OData), WindowsAzure.Storage.XXXX and create a WindowsAzure.Storage.Configuration that has the shared configurations parts.

**Comment by ejsmith** [comment]
Yes, what he said.

**Comment by mirobers** [comment]
So there are several different requests here:

* performance improvements
* cross-platform support
* use a single dll with no dependencies
* split the dll into multiple dlls with a common dependency

It will be difficult to track and respond to all of these in a single GitHub issue. For everyone's sanity, if you have observed a performance or cross-plat issue then please open a new GitHub issue and we will investigate.

For the requests relating to removing dependencies or splitting the assembly, are there specific problems you have encountered with the current package or is this request more based on principles? I find that having a single package with dependencies managed by NuGet is simple and works well but I'd be interested in hearing arguments against. Splitting the package into packages for blob/table/queue/file/etc itself feels like an overcomplication to me.

**Comment by GuardRex** [comment]
> Azure storage is a fairly simple REST API

And maybe ... way, way down the road: a "lite" version of the assembly that doesn't provide the vast functionality (or have the enormous dependency tree and footprint) of the current assembly but just has the basics for Table, Blob, and Queue CRUD operations.

**Comment by AlanParr** [comment]
I'll add my 2 cents.
For me, it is more a matter of having the large dependency tree containing lots of packages for features that, to my knowledge, I don't use, such as KeyVault, System.Spatial, OData, etc.
If I use features of the library that require that functionality, I've no issue having the dependency, but managing Nuget dependencies in a large project is difficult enough as it is without having lots of packages which I technically do not need.

I agree that splitting it out to separate Table, Blob,Queue packages is unnecessary.

I think the suggestion from @GuardRex is a good solution. You have a package for "Basic" use of the Azure storage (including the *Client classes), and then if you want to use KeyVault, this comes in as a separate package with the KeyVault dependency, same with OData, Spatial, etc.

**Comment by markrendle** [comment]
What the ASP.NET 5 guys did with MVC might be worth considering; around beta6 or 7 they broke things down into smaller packages. There's a `Microsoft.AspNet.Mvc.Core` which is the minimum, basic functionality, then things like `Microsoft.AspNet.Mvc.Razor` and so on can be installed independently. Then `Microsoft.AspNet.Mvc` became a meta-package that installed the whole kaboodle.

On a side note, a refactoring like this would make it simpler to do some house-keeping on the smaller packages, like migrating to `HttpClient` instead of `HttpWebRequest`, as well as being able to create Core or Portable libraries more easily when there are fewer dependencies.

**Comment by jdrake3** [comment]
+1

**Comment by mirobers** [comment]
Thanks for the suggestions. While I agree with the design principle of minimal dependencies, we have no current plans to make changes to existing dependencies for the following reasons:

* NuGet does a good job managing the dependencies in our experience.
* There is no major problem with the current design and there are few benefits to changing it. We have ourselves seen no problems with maintenance or portability due to dependencies.
* The proposed changes are large breaking changes and it is not clear that they would increase the simplicity of the library compared to the current state.

That being said, we also don't plan to take unnecessary dependencies. For example, we have not taken a dependency on any of Key Vault's client libraries. Our support for Key Vault is completely abstracted behind interfaces. The interfaces themselves have been factored out into a small "core" DLL that both we and Key Vault depend on. This is far superior to taking a dependency on Key Vault (or vice versa).

I'm not ruling out the possibility of some refactors in the future to existing dependencies, but it does not align with our current priorities.

**Comment by niemyjski** [comment]
You've got to be kidding me... Just what I want in my project a crap ton of nuget dependencies to things I'll never use like the pile we call  odata.. There's many +1s take the time and do what's right, not the easy road which is do nothing. Your first bullet point is a con not a pro..

**Comment by phillip-haydon** [comment]
This is one of the reasons I moved to AWS.

**Comment by GuardRex** [comment]
> There is no major problem with the current design and there are few benefits to changing it.

I'm feel'in a :-1: coming on.

I want to take a look at the size and number of dependencies in `WindowsAzure.Storage`. It's not reported openly AFAIK. @ejsmith and @mirobers ... don't close this issue yet please.

My basic idea (hope) was for a more modular system for the main services ... e.g., if your app only needs Table Storage, you add something like `WindowsAzure.Storage.Tables` and that's it ... it only gets the bare minimum for that service ... no Queue bits ... no Blob bits ... unless it wouldn't matter that much to the number of dependencies and size of the overall payload that has to be loaded and compiled.

**Comment by ejsmith** [comment]
Ugh. Blob storage is probably one of the more popular libraries that people use on azure and their first experience is installing this beast and seeing it modify their config files and install like 10 additional nuget packages. Not to mention the API itself could be a lot cleaner and simpler as well. IMO this is leaving a horrible impression and it's just plain silly to have to have all those dependencies for things the majority of people aren't using. This crap is like the same old Enterprise Library bloat ware that MS used to do with everything they touched, but they have been getting better and building simpler more loosely coupled and composable things. Take a look at where .net is going with vnext. The focus is on simplicity and composability. You opt into only what you need. Please stop making excuses and listen to your customers. If this many people have found and replied to this issue, imagine how many people have the same opinion. Or worse yet, tried Azure and saw this mess and ran away. Simplicity and composability are important features.

**Comment by jdrake3** [comment]
+1 the above.

**Comment by AlanParr** [comment]
thanks @mirobers for the honest reply, while it's not what we would want to hear, I understand that the dev team have got other priorities. Would you be open to pull requests that made these changes or even that made small changes slowly working towards this end?
On the plus side, with the new dependency system in asp.net 5 only showing the installed package and not all of it's dependencies, this will become a less visible issue.

**Comment by ejsmith** [comment]
Yes, it will become less in your face visible when nuget packages are the point of reference instead of assemblies, but the biggest problem is that the library is opinionated and coupled in that it is expecting you to use app/web.config for settings and muddying up your config file. What we are asking for is simple, loosely coupled, non-opinionated libraries to work with Azure Storage. It should be simple and then other things can be built on top of that package that add additional features like OData and key vault. Sure we can ignore that those things are in the library but the point is that they should not be there. Make simple building blocks and people (including MS) can compose those blocks in opinionated ways. It also makes it easier for people to contribute to the libraries.

**Comment by mirobers** [comment]
I think there's some misunderstanding about the new role of NuGet packages in the .NET platform. Take a look at the dependencies [here](https://www.nuget.org/packages/WindowsAzure.Storage/6.2.2-preview). As you can see, the trend in .NET is for each assembly to have its own NuGet package, but they are not dividing assemblies into smaller assemblies. See the [.Net Core blog post](http://blogs.msdn.com/b/dotnet/archive/2014/12/04/introducing-net-core.aspx) for more details.

So the number of assemblies is staying the same but the number of dependencies is going up. This is one reason why removing dependencies for its own sake isn't on the roadmap. The future of .NET is a large number of dependencies, managed by NuGet.

@AlanParr Thanks for the offer! If we conclude that a change is desirable here then we'll let you know what you can do to help.

@ejsmith I don't understand what you mean about the library being opinionated. It isn't opinionated and it doesn't require you to use a config file. You don't have to use Key Vault; you can use whatever key management system you want (or none at all). You need not use WCF/OData either. We use OData (the protocol) for communicating with the service, and this is largely abstracted from the user.

**Comment by niemyjski** [comment]
You're missing the point...  If we don't have to use it then why is it a dependency we have take...

**Comment by mirobers** [comment]
It isn't a dependency you have to take. We do the right thing. To use Key Vault, you would add a reference to [this](http://www.nuget.org/packages/Microsoft.Azure.KeyVault.Extensions/).

**Comment by tarwn** [comment]
I have half of blob/queue/table written with only a single nuget dependency required: https://github.com/tarwn/BasicAzureStorageSDK

Granted I didn't write for multiple .Net frameworks, but the basic structure is there (and half of that was written in my spare time, half contributed by another dev, not a full time team). 

Buck the trend. I should be able to use a nuget package to interact with KeyVault without it also dragging along all of the storage assemblies, but I don't mind if it is using a couple other dependencies that are the best possible X thing you can find. It's when I have Spatial pulled into my assembly list for no apparent reason that it's annoying.

**Comment by GuardRex** [comment]
@tarwn :+1: ... I've gone the .NET 5-way and will never look back. I look forward to when you get the table service entity ops in there and have it for Core CLR. btw -- This was a good phrase, too, "object-ification of a REST service" :smile:

**Comment by niemyjski** [comment]
Are there any updates to this? This should really be split out? I don't want to have to have any extra code / headaches then I have to. And by bringing down the kitchen sink of dependencies I'm adding things I don't need or will use.

**Comment by GuardRex** [comment]
@niemyjski By all accounts, the short answer seems to be "no" from the team. However, you do have the REST API at your disposal. You can craft up a very small, lightweight set of methods that use the REST API, which will radically reduce the number of deps and the size of the codebase needed to interact with Azure Storage. I haven't done it in .NET yet, but I did go that route for some Raspberry Pi+Python work, and it went well.

https://msdn.microsoft.com/en-us/library/azure/dd179355.aspx

**Comment by phillip-haydon** [comment]
AWS SDK > Azure SDK

**Comment by pemari-msft** [comment]
We do appreciate the feedback given here and have had multiple conversations about its content. We are currently investigating removing dependencies such as OData as per your suggestion. However, we do not plan to split up the different services into separate packages as this does not decrease the complexity. We do value real constructive criticism, are working to include suggestions in our upcoming releases, and will continue to do so. Thanks in advance!
