### ISSUE TITLE
What purpose does connection string serve when using SAS

### ISSUE THREAD

**Issue by mtaylorfsmb** [Azure/azure-storage-net#980]
### Which service(blob, file, queue, table) does this issue concern?
BlobServiceClient

### Which version of the SDK was used?
v12.0

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.1

### What problem was encountered?
Not a problem but a question on the API surface.  We use a SAS to connect from one of our apps. We previously used the legacy Azure Storage library and we had code similar to the following.

```csharp
_account = new CloudStorageAccount(new StorageCredentials(storagAccountName, storageAccounKey), true);

var blobClient = _account.CreateCloudBlobClient();
```

Now we have to do something like this.
```csharp
_credentials = new StorageSharedKeyCredentials(storageAccountName, storageAccountKey);

var blobClient = new BlobServiceClient(connectionString, _credentials);
```

Why is the connection string now required when using SAS credentials? Looking at the connection string that is generated it contains some default options (e.g. HTTPS) and embeds the account name/key already. So it seems that the constructor could infer the connection string from the credentials like it used to do. It seems redundant to need to specify a connection string (with embedded credentials) in addition to creating a separate credentials object.

### How can we reproduce the problem in the simplest way?
Just review the above code.

### Have you found a mitigation/solution?

I see 2 possible options here right now.
1. Store both the connection string and storage account name/key and set all this up even though it is somewhat redundant.
2. Forget the SAS credentials altogether and just use the connection string. But I'm not sure what impact that has, if any.

**Comment by amnguye** [comment]
Hi,

Could you post this issue in the v12 library. All issues got moved to this repo.
https://github.com/Azure/azure-sdk-for-net/issues/
That way your issue gets seen in the right place with the right support.

Thanks

**Comment by mtaylorfsmb** [comment]
Sure, done.
