### ISSUE TITLE
QueueRequestOptions.ApplyDefaults does not apply default NetworkTimeout

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-storage-net#999]
If you look here -- there's no default NetworkTimeout applied: https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Queue/QueueRequestOptions.cs#L82, so if you pass null options in you don't get any timeout behavior and can result in a deadlock (fixed by #985).

Other requestOptions apply the default:
- https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Blob/BlobRequestOptions.cs#L167-L170
- https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/File/FileRequestOptions.cs#L144-L147

FYI @kasobol-msft

**Comment by kasobol-msft** [comment]
Fix released in https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/11.1.7
